aws-amplify/docs

cli/codegen.md, cli/concept.md, cli/hosting.md, cli/index.md, js/index.md
- update navigation for CLI
- update CLI docs
- fix various JS issues and redirects
=> Update nav and CLI docs

404.md, _config.yml, cli/init.md, js/start.md, theme/_includes/docs-header.html, theme/_layouts/default.html, theme/assets/css/style.scss
Various cleanup on links and styles
=> Fixes and Updates

.spelling, js/graphql.md
This fixes the typos found during npm test from the graphql file.
=> Correcting typos

js/react.md
Updating the yarn create syntax.
Information Source: https://yarnpkg.com/docs/cli/create/
=> Updating yarn create syntax

js/react.md
Issue #, if available: N/A
Description of changes: Typo in CLI command to invalidate cache automatically when publishing
=> fix(docs/media): typo in command to invalidate cache 

js/hub.md
=> Typo fix in hub.md

js/analytics.md
See aws-amplify/amplify-js#1880
=> Fix typo in docs/media/analytics_guide

cli/init.md
I've made a number of small edits to the init.md file to improve the grammar and punctuation used in the hopes of making it read more clearly.
=> Simple grammar/punctuation edits for clarity

js/authentication.md
add first Parentheses at Verify phone_number or email address
=> add first Parentheses

js/vue.md
Updated the import statements from the beta version to the stable version 0.1.4 
Removed file alteration in `App.vue` since its not needed
Add version tag in npm
=> fix outdated vue doc

.spelling, _config.yml, ios/manualsetup.md, ios/start.md, package-lock.json
Updated flow for Getting Started with iOS, also includes Manual SDK setup.
=> Getting started iOS update

js/xr.md
Remove note that says unauthenticated access is not supported because it is now currently supported.
=> Update XR unauth note

js/authentication.md
Related to:
https://github.com/aws-amplify/amplify-js/pull/1854
=> Fix typo in auth docs

.spelling, android/analytics.md
Add the following sections to Analytics:
1) reporting events
2) different event types
3) session management and app lifecycle
4) endpoint profile update
=> [Analytics] [Pinpoint] Add event types and endpoint profile update

js/authentication.md
=> Edit wrong document verifyCurrentUserAttribute

.spelling, android/analytics.md, android/how-to-pinpoint-notifications-adm.md, android/how-to-pinpoint-notifications-baidu.md, android/how-to-pinpoint-notifications-fcm.md, android/how-to-setup-pinpoint-notifications-fcm.md, android/push-notifications.md, android/storage.md
1. Removed iOS and Kotlin references 
2. Synced up with latest content available
3. Fixed headers and spacing in push notifications and analytics
=> [Storage] Remove iOS and Kotlin references; Sync up with latest content

android/api.md
API documentation for GraphQL and REST with Android that matches iOS using new AWSMobileClient.
=> Initial Android API documentation to match iOS

android/authentication.md, ios/authentication.md
=> Fix broken image links

android/analytics.md, android/push-notifications.md, android/storage.md
Update the following docs to use the new AWSMobileClient APIs to initialize and retrieve the credentials.
1. Analytics
2. Storage
3. Push Notifications
=> Update the Android docs to use the new AWSMobileClient flow

_config.yml, cli/graphql.md
=> Moving js/graphql to cli/graphql and enabling redirect

android/storage.md
Changing text in Download a File section from 'upload a file' to 'download a file'
=> Update storage.md doc

js/api.md
=> Revert "Update api.md fix broken image"

android/api.md, cli/codegen.md
See: https://developer.android.com/studio/build/dependencies?utm_source=android-studio#dependency_configurations
=>  Replace deprecated use of Gradle compile with implementation 

.spelling, js/angular.md, js/ionic.md
Previously updated the angular doc... however, it appears that the ionic doc is actually the one displayed on site.
=> fixes(#1870)

android/authentication.md
Fixes android side of things for #242
=> [Android] Add instructions for Forgot Password

android/authentication.md
=> [Android] Add instructions for force change password

js/cache.md
I was able to set and get arrays from the cache as well.
=> add array to list of cache types

js/authentication.md
Fix the link to /js/cognito-hosted-ui-federated-identity
=> Fix broken link

js/storage.md
Addressing confusion in https://github.com/aws-amplify/amplify-js/issues/2203
=> Updates to clarify implicit usage with Auth

js/storage.md
Clean Storage configure instructions
=> fix(docs): Clean Storage configure instructions

js/api.md
=> Typo correction

android/analytics.md, android/api.md, android/authentication.md, android/how-to-cognito-integrate-an-existing-identity-pool-android.md, android/interactions.md, android/manualsetup.md, android/pubsub.md, android/push-notifications.md, android/start.md, android/storage.md
To be merged after 2.11 Android release
=> Bump SDK version references to 2.11

.spelling, ios/pubsub.md
Adding the code snippets and documentation for the following connection mechanism:
- SigV4 credentials based authentication
- Custom authentication
=> [iOS][IoT] Add custom authentication

js/api.md
Replaced AWSMobileClient with Auth category
=> Fixed inaccurate client reference

android/analytics.md, android/api.md, android/authentication.md, android/how-to-cognito-integrate-an-existing-identity-pool-android.md, android/interactions.md, android/manualsetup.md, android/pubsub.md, android/push-notifications.md, android/start.md, android/storage.md
=> Update Android docs to 2.12.0

js/authentication.md
=> Fix typo in authentication.md

js/pubsub.md
Had some issues finding the `aws_pubsub_endpoint`.
=> where to find your wss endpoint in AWS console

cli/codegen.md
- Clarified async behavior
- Clarified need to retain the subscription watcher
- Added note about subscription watcher retaining result handler block
- Removed unnecessary `didReceiveMemoryWarning`
- Replaced deprecated `databaseURL` with `cacheConfiguration`
=> iOS sample clarifications

js/api.md
=> fixup: typo

cli/init.md
=> Spelling mistake.

cli/migrate.md
N/A
Fixing a misspelled word under Storage (DynamoDB) # amplify/backend/storage//-cloudformation-template.json instructions
=> Fixing minor Typo

cli/multienv.md
=> Fix link to Amplify console docs

cli/multienv.md
=> Fix brokem image links in multinev page

cli/concept.md
=> Fix broken image link in cli architecture page

cli/migrate.md
=> Update outdated Migration docs 

ios/api.md
=> Minor clarification on subscription inputs

js/authentication.md
Fix the typo error in Authentication -> Creating a CAPTCHA
=> fix issue 502

js/angular.md
=> Single command for installation

ios/pubsub.md
=> Fix a typo in ios pubsub documentation

android/storage.md
=> [Android][S3] Fix a syntax error in downloadWithTransferUtility

android/analytics.md
There are a few imports that need to be added to the code snippet
in Analytics section for it to work out of the box.
=> Add missing imports to Analytics code snippet

cli/graphql.md
Hi,
just a quick fix of a typo i found while reading the docs..
=> GraphQL Documentation typo

cli/graphql.md
Remove TODO in graphql cli docs
=> Remove TODO

js/authentication.md
=> Add more description about currentSession method

js/authentication.md
We need to do a clean up for the UI part in the Auth Doc.
=> Auth Doc UI Part Improvement

ios/authentication.md
=> Fixing image in developer authenticated identities section

js/authentication.md
=> [JS] Fix complete new password docs

cli/graphql.md
fixes https://github.com/aws-amplify/amplify-cli/issues/1046
=> Fix typo in DataSourceName

cli/init.md
Rectified command args in AWS Cli usage docs
=> Rectified command args

js/cognito-hosted-ui-federated-identity.md
Fixing for the proper jekyll image path.
=> fix (Cognito Federated Identity Setup): Images not displaying

js/hub.md
Docs for PR: https://github.com/aws-amplify/amplify-js/pull/2850
cc @jordanranz @elorzafe @haverchuck @manueliglesias @powerful23
- Documentation for https://github.com/aws-amplify/amplify-js/pull/2850
=> Docs for new Hub refactor

android/authentication.md, ios/authentication.md, js/authentication.md
=> Update base path images

android/authentication.md, ios/authentication.md, js/authentication.md
=> Fix google post push images

js/xr.md
- Show required version to use XR CLI integration
=> Add XR CLI version requirement

android/analytics.md, android/api.md, android/authentication.md, android/how-to-cognito-integrate-an-existing-identity-pool-android.md, android/interactions.md, android/manualsetup.md, android/pubsub.md, android/push-notifications.md, android/start.md, android/storage.md
=> Update Android docs to 2.13.0

ios/authentication.md
Fixes https://github.com/aws-amplify/aws-sdk-ios/issues/1400
=> Fix issue pointed out by customer in Auth iOS

ios/authentication.md
=> Removed extraneous closing bracket

js/vue.md
Added JavaScript syntax highlighting for Vue code examples
=> Javascript Syntax highlighting

android/authentication.md
Modify the part where JSON highlighting syntax is not properly applied
=> Fixed md format typo

cli/graphql.md
Fixing images in new docs. The paths work in local dev env but are not working in prod. This should fix.
=> Fixing images in new docs.

android/api.md, android/start.md
=> Update version to the latest

cli/lambda-node-version-update.md, js/analytics.md, js/authentication.md, js/interactions.md, theme/assets/js/scripts.js
https://github.com/aws-amplify/amplify-cli/issues/1105
add docs for aws lambda node.js runtime version update
=> add doc for aws lambda node version update

cli/lambda-node-version-update.md
=> correct inaccuracy

android/start.md, ios/start.md
https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/152
=> Clarify the getting started instruction

js/start.md
Fix last step as React Native doesn't require website hosting
=> Correct web vs React Native

js/start.md
chaging data-group in step 5 of getting started guide to not break other tabs
=> fix(docs): resolves missing tab content

android/analytics.md, ios/analytics.md
Fixes https://github.com/aws-amplify/aws-sdk-ios/issues/1244
Update the required IAM policy in the analytics docs for iOS and Android.
=> [iOS][Android] Update Pinpoint Analytics docs to include the required IAM policy

ios/storage.md
Remove any references to `:code:` which is RST syntax.
=> [iOS] Fix formatting in graphql complex objects

js/authentication.md
=> Add instructions for deep linking in RN

js/start.md
=> Fix grammar in start.md

js/pubsub.md
=> Fix pubsub doc

js/api.md
There have been a few times when I needed to refer to these docs to find out
=> Show how to access body parameter

js/storage.md
*Issue #, if available:* No issue number.
*Description of changes:* Fixed a typo.
=> Fix assignment in Storage documentation example code

js/cache.md
=> fix the description of cache priority

js/api.md
=> Multi-client support in aws-appsync sdk

cli/graphql.md
Addresses missed comments in previous @key PR.
=> Address previous @key PR comments

android/api.md
=> Fix typo in Android API documentation

ios/api.md
Fixes https://github.com/aws-amplify/docs/issues/702
#702 
=> [iOS][API] Fix Multi-Auth sample code snippet

android/messaging.md
Added information about spending limits, and how to request a spending limit increase. 
=> Update SMS section of messaging.md

js/authentication.md
Took me about one hour to find this, might as well link to it in the docs 😊
=> Add link to attributes list for cognito user pools

theme/_includes/sign-up-attributes.html
Updating default value of the header attribute.
`s/Sign Up/Create a new account/`
See related: https://github.com/aws-amplify/amplify-js/blob/6d34cbd865d813bb6b542bcd90d9ce05eaac40a0/packages/aws-amplify-vue/src/components/authenticator/SignUp.vue#L98
None.
See above.
=> Document outdated, updating with the actual value

js/api.md
#290 
Removes dead link to mobile hub documentation.
=> removes mobilehub link

ios/start.md
iOS versions are not correct and produce a SQLite.swift issue ( ":" invalid character) and fixes a button label from 'Next' to 'Finish'
=> Update getting started for iOS

js/react.md
Fixes #664
Adds a note on using custom storage for JWT tokens on react native
=> Add note about JWT storage

.spelling, ios/api.md
This was asked for by @undefobj in aws-amplify/amplify-cli#1593
Added a call out for SwiftUI. To try this out I have a working test implementation found here:
https://github.com/wizage/SwiftUI-AWS
=> Added a SwiftUI callout

.spelling, cli/graphql.md
[1627](https://github.com/aws-amplify/amplify-cli/issues/1627)
Adding adding note on changing graphql connections
=> Added note on changing graphql connections

android/api.md
=> [API] Update build.gradle to highlight dependencies

.spelling, android/api.md, android/authentication.md, android/storage.md, cli-toolchain/cognito-triggers.md, cli-toolchain/quickstart.md, ios/api.md, ios/authentication.md, ios/storage.md, js/api.md, js/authentication.md, js/storage.md
=> Auth + Storage Triggers docs

cli-toolchain/cognito-triggers.md
Removing a button that is not necessary from angular trigger code sample.  Updating React sample code to use getDerivedStateFromProps.
=> removing unnecessary button and use react lifecycle properly

cli-toolchain/quickstart.md
Example Lambda function of calling an AppSync endpoint using AWS IAM from a Lambda with Sigv4 signing
=> Update with GraphQL from Lambda sample

cli-toolchain/graphql.md
Formatting changed to get rid of weird numbered list.
=> Formatting update for subscription authorization docs.

js/api.md
update access token API reference to use `.getAccessToken().getJwtToken()`
=> documentation: update api.md accessToken api references

ios/analytics.md, ios/api.md, ios/authentication.md, ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md, ios/pubsub.md, ios/push-notifications.md, ios/start.md, ios/storage.md
=> Update iOS docs to 2.10.0

js/start.md
Fixes #790 
Fixes 404 with Ionic documentation link.
=> fixes 404 with ionic link

android/analytics.md, android/api.md, android/authentication.md, android/how-to-cognito-integrate-an-existing-identity-pool-android.md, android/interactions.md, android/manualsetup.md, android/pubsub.md, android/push-notifications.md, android/start.md, android/storage.md
=> Update Android docs to 2.14.0

js/start.md
=> fixes for pubsub imports

js/authentication.md
- Change content in "Social Provider Federation" section in last sentence of paragraph to read, `and build out your own UI`. Please clarify if this was what was originally intended.
- Make small grammar change and add missing `'` apostrophe in final paragraph of same section.
=> Make small content and grammar change to Auth docs

js/authentication.md
There was one div too many.
When copy pasting the code to test, they where an error with the following snippet
Remove  a div so the code work on real application
=> Snipped of code incorrect in social proof exemple

js/authentication.md
Instructions for adding the library to a project and performing React Native linking. Several customers have missed this step.
=> Library installation

js/predictions.md
Fix file name to not be hardcoded
=> Fix file name

js/predictions.md
=> Grammar fix

js/predictions.md
=> Fix case and sentence end.

js/angular.md
JS Repo Issue 3762
Notes that we do not support Ivy and adds process polyfill.
=> Angular PolyFill and Ivy Support

js/predictions.md
Add sample code for ionic/angular
=> add ionic sample

js/authentication.md
Adding documentation in order to resolve issues with linking in React Native. 
[#3612](https://github.com/aws-amplify/amplify-js/issues/3612) in JS repo
[#3682](https://github.com/aws-amplify/amplify-js/issues/3682) in JS repo
=> Updating authentication docs for RN 0.60.0+

ios/storage.md
=> Fix optional

cli-toolchain/graphql.md
=> Revert "Adds docs for @connection limits."

.spelling, android/api.md, android/storage.md, cli-toolchain/quickstart.md, cli-toolchain/usage.md, ios/api.md, ios/storage.md, js/api.md, js/storage.md
Local mocking and testing documentation 🥰
=> Local mocking and testing

ios/api.md
=> Bump AppSync version

cli-toolchain/graphql.md
=> Add @model to schema examples under @connections

cli-toolchain/usage.md
=> Link to launch blog

js/push-notifications.md
Push notifications URL for android was not correct so I updated to be pointing to the right location.
=> Fix push notifications url

ios/analytics.md
=> Fix auth integration code snippet formatting

.spelling, cli-toolchain/usage.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/pull/1951
Added docs for the function build hooks as described in https://github.com/aws-amplify/amplify-cli/pull/1951.
=> Added docs for build script hooks.

ios/start.md
=> Add intro for GraphQL, schema, and make iOS getting started consistent with JS.

android/analytics.md, android/api.md, android/authentication.md, android/how-to-cognito-integrate-an-existing-identity-pool-android.md, android/interactions.md, android/manualsetup.md, android/pubsub.md, android/push-notifications.md, android/start.md, android/storage.md
=> Update Android docs to 2.15.0

android/api.md
Replaces proposed changes in #802.
=> Clarify usages for 'amplify codegen' in Android

js/api.md
Amplify Connect Component property is 'errors' not error.
Errors is an array. Not singular. 
```
<Connect query={graphqlOperation(gql)}>
{({ data: { object }, loading, errors }) => {
if (errors.length > 0) {
return (
<>
<h3>Error: Unable to fetch data.</h3>
<p>See errors below:</p>
{errors.map(error => {
return <p>{error.message}</p>;
})}
</>
);
}
if (loading || !object) return <Spinner />;
return object.id;
}}
</Connect>
```
=> Update API Docs React Component

js/authentication.md
A section of code was misaligned. This change will re-indent the demo with 4 spaces.
Reformatted a section of demo code which was misaligned.
=> fix indenting inconsistencies in demonstration

js/api.md
Add explicit warnings on direct Lambda invocation from clients
=> Warnings on direct Lambda invocation

ios/start.md
=> Updated the AppSync version to latest

js/start.md
Clarifies there are two separate options for creating the react native app and provides guidance on which to choose and also fixes missing style object in code snippet.
=> Updates React Native documentation

android/storage.md
The image URL was wrong once the pull request was published to the site - fixes it following the example in docs/js/predictions.md
=> Fixed image path

ios/analytics.md, ios/api.md, ios/authentication.md, ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md, ios/pubsub.md, ios/push-notifications.md, ios/start.md, ios/storage.md
=> Update iOS docs to 2.11.0

ios/api.md, ios/start.md, ios/storage.md
=> Update AppSync version

.spelling, cli-toolchain/graphql.md
=> Add more clarification around @auth and permitted operations behavior

cli-toolchain/graphql.md
Updated general usage and added a fifth workflow.
=> Added documentation tied to codegen without init

js/authentication.md
I feel this more clearly communicates the intended message for the "forcing email uniqueness section"
=> Clearer language

android/authentication.md
=> Update custom auth documentation for android

js/react.md, theme/_includes/sign-up-attributes.html
- Adding couple of links for clarification around auth.
- Code change to make this tutorial run without any errors.
=> update react tutorial docs minor

cli-toolchain/quickstart.md, cli-toolchain/usage.md
Added samples workflow and more information in the usage section.
=> Updating docs for sample apps option in init

cli-toolchain/graphql.md
=> Revert "Revert "Adds docs for @connection limits.""

android/start.md, ios/start.md
1. Include more high level concepts and links
2. Remove information not needed for getting started
3. Add CLI flow and output for "add api"
4. Formatting and language updates
=> Update Getting started guides

ios/analytics.md, ios/api.md, ios/authentication.md, ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md, ios/pubsub.md, ios/push-notifications.md, ios/start.md, ios/storage.md
=> Bump iOS SDK version to 2.12.0

js/service-workers.md
Update code sample that enables push notification
*Issue #, if available:* aws-amplify/amplify-js#4222
*Description of changes:* update sample code to enable push notification
=> fixes aws-amplify/amplify-js#4222 update sample to enable push notification

.spelling, ios/start.md
=> Update Getting Started guide for iOS

android/start.md, ios/start.md
=> Update Getting Started guides for iOS and Android

.spelling, ios/manualsetup.md
- Removed all Auth SDKs/Pods in favor of referring to ./authentication.md for setup instructions
- Added missing SDKs/Pods
#987
=> Clean up SDK list

js/start.md
- Missed one double quote in full sample
=> chore:(Getting Started - React) fix typo in full sample

js/start.md
- Fixes: #962
Customer found a bug in our documentation. This resolves this issue.
=> chore: (Fixing typo in Pure JS example)

js/authentication.md
Changing "Amazon" to "LoginWithAmazon"
=> fix typo in Authentication OAuth and HostedUI

cli-toolchain/graphql.md
=> @predictions directive docs

cli-toolchain/graphql.md
=> fixed formatting for predictions

js/datastore.md
Update the title of datastore page
=> Update the title of datastore page

js/datastore.md
CRA doesn't like uppercase letters in the project name
Error message would be: name can no longer contain capital letters
=> docs(datastore): fixes CRA create command

android/start.md
Per our Chime call @nikhil-dabhade 
=> Fixes Android Start Doc

ios/start.md
=> FIx Task+Schema.swift filename

android/api.md
- Changes syntax for bulleting since on the website it was showing each bullet as 1 instead of increasing the numbering
- Added missing step to Amplify Init phase
- Clarified a couple sections by adding/removing notes
- Added necessary compileOptions section
- Updated gradle tools plugin to correct version
- Updated gradle tools section
- Added section about imports since one import is ambiguous.
=> Few corrections/updates to Android API

js/datastore.md
=> Add `@latest` to `npx` command

cli-toolchain/usage.md
- Add a section for the headless parameters of the pull command
- Add `"amplify:*"` to the required IAM policies 
=> add pull headless doc

.spelling, cli/lambda-node-version-update.md
=> nodejs version update to 10.x

cli-toolchain/quickstart.md
=> fix dependsOn block location

cli-toolchain/quickstart.md
=> fix broken nodejs download link

js/vue.md
Small grammatical and  typographical fixes.
Changed "it's" to "its" and removed a couple of extra spaces in the copy.
=> Removing improper apostrophe and extra spaces.

.spelling, android/authentication.md, sdk/ios/authentication.md
=> Updated custom auth challenge

js/datastore.md
=> Fix query with limit sample

.spelling, ios/authentication.md, ios/manualsetup.md, sdk/android/authentication.md, sdk/ios/manualsetup.md
- Update custom auth documentation for the new Amplify auth
- Update iOS configuration setup 
=> Update authentication doc

ios/authentication.md, ios/predictions.md
*Description of changes:* Note to reflect aws mobile client not returning guest state on initialize with a fresh app.
=> Note add to Guest Access for MobileClient

ios/predictions.md
*Description of changes:* adding transcribe functionality to docs to reflect it being added to Amplify
=> adding predictions transcribe to docs

Readme.md
This PR adds download links to make it easier for contributors to find the software required to contribute. 
=> 👌 IMPROVE: Docs with links

cli-toolchain/plugins.md
There were several Markdown formatting issues throughout the document that cause rendering issues as shown below. This PR fixes all of them and removes extra white-space characters.
|               **BEFORE**                |               **AFTER**                |
| :-------------------------------------: | -------------------------------------- |
| ![before](https://on.ahmda.ws/22876e/c) | ![after](https://on.ahmda.ws/c39177/c) |
| ![before](https://on.ahmda.ws/e6b9f6/c) | ![after](https://on.ahmda.ws/a784cd/c) |
=> 👌 IMPROVE: Markdown formatting

js/angular.md
=> Pointing out that angular 9 is not supported yet

ios/predictions.md
Docs were not working - now they will. Hooray.
=> Fixing the problems

cli-toolchain/quickstart.md
=> change amplify update api to amplify update function in quickstart

ios/api.md
=> Fix typo in api.md

sdk/ios/analytics.md
Fixes https://github.com/aws-amplify/aws-sdk-ios/issues/2066
=> Add region restriction on auth event integration

ios/storage.md
Remove's progress handler for `Storage.list`, `Storage.remove`, and `Storage.getURL` since those return Void and do not report progress
=> Update Amplify iOS Storage

cli-toolchain/graphql.md
=> DataStore with versioned directive

cli-toolchain/graphql.md
=> Maybe wrong function name

.spelling, js/datastore.md
Update DataStore documentation with React Native instructions
=> Update DataStore documentation with React Native instructions

android/authentication.md
=> Updates version and adds dependency for hosted UI

ios/analytics.md, ios/authentication.md, ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md, ios/pubsub.md, ios/push-notifications.md, ios/storage.md
=> Update iOS docs to 2.13.0

docs/start/getting-started/fragments/reactnative/setup.md
- this content fix is required for the react-native app to launch without errors
=> Fixes V2 docs' React Native's first-run experience

docs/start/getting-started/fragments/reactnative/auth.md, docs/start/getting-started/fragments/reactnative/data-model.md, docs/start/getting-started/fragments/reactnative/setup.md
- fixing 3 nitpick content issues to make the React Native guide more descriptive
=> Fixing nitpick V2 doc content

cli-toolchain/quickstart.md
=> Amplify @model triggers + kinesis streams docs

.spelling, cli-toolchain/quickstart.md
=> Amplify console hosting docs

cli-toolchain/quickstart.md
=> fix graphql hyper-link

android/analytics.md, android/api.md, android/authentication.md, android/datastore.md, android/start.md, android/storage.md, ios/analytics.md, ios/api.md, ios/authentication.md, ios/datastore.md, ios/predictions.md, ios/start.md, ios/storage.md, sdk/android/analytics.md, sdk/android/api.md, sdk/android/start.md, sdk/android/storage.md, sdk/ios/analytics.md, sdk/ios/api.md, sdk/ios/start.md, sdk/ios/storage.md, theme/_includes/docs-header.html
=> Update default landing section and note for Amplify iOS/Android and SDKs

client/src/index.html
* ogp image references
* added 'nofollow' to robots, just incase
=> Fixing meta

client/src/components.d.ts, client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap, client/src/docs-ui/secondary-nav/secondary-nav.style.ts, client/src/docs-ui/secondary-nav/secondary-nav.tsx
Depending on selected filter state, a different reference link gets rendered.
=> feat: update secondary nav with filter-specific api reference links

client/src/docs-ui/menu/menu.style.ts, client/src/docs-ui/menu/menu.tsx
* added `(preview)` and `(stable)` subheadings to switcher tabs
* improved styles (hover state, for instance)
=> sdk lib switcher description & style

sdk/ios/start.md, theme/_layouts/index.html
=> Update links from Getting Started page

sdk/android/authentication.md
=> Added missing auth dependency + raised sdk version

cli-toolchain/usage.md
=> add section for upgrading the CLI

sdk/android/start.md, sdk/ios/start.md
=> Fix links to CLI installation

client/src/amplify-ui/styles/elements.ts, client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap, client/src/docs-ui/secondary-nav/secondary-nav.style.ts, client/src/index.html
* iframe widths (video players)
* border radius on webkit devices
=> More mobile tweaks

docs/sdk/auth/fragments/ios/hosted-ui.md
Applying changes from https://github.com/aws-amplify/docs/pull/1220 to v2-preview
=> [v2-preview] Reference Apple Sign In blog and hostedUI options

docs/fragments/reactnative.md
=> removed deployment reference from ReactNative

sdk/ios/authentication.md
*Issue #, if available:* fixed a typo in docs
=> Fixed typo

docs/start/getting-started/installation.md
=> Making the video / read options for `install amplify CLI` section clearer

docs/start/getting-started/fragments/react/api.md, docs/start/getting-started/fragments/reactnative/api.md
=> Added (Optional) tag to `Test your API`

docs/start/getting-started/fragments/android/setup.md, docs/start/getting-started/fragments/angular/data-model.md, docs/start/getting-started/fragments/ionic/data-model.md, docs/start/getting-started/fragments/ios/setup.md, docs/start/getting-started/fragments/react/api.md, docs/start/getting-started/fragments/reactnative/api.md, docs/start/getting-started/fragments/vanillajs/data-model.md, docs/start/getting-started/fragments/vue/data-model.md
Made all selections highlighted with "#"
=> Made command defaults highlighted

docs/start/getting-started/fragments/reactnative/setup.md
Added more context to install instructions to be consistent with Expo.
=> Small update to setup step in React Native getting started guide

client/src/docs-ui/feedback-callout/feedback-callout.tsx, client/src/docs-ui/repo-actions/repo-actions.tsx, docs/cli/cli.md
=> New feedback button text and CLI description

docs/start/start.md
=> Adjusted the copy on the getting started page

docs/fragments/lib/android-sdk.md, docs/fragments/lib/android.md, docs/fragments/lib/ios-sdk.md, docs/fragments/lib/ios.md, docs/lib/getting-started/fragments/android/setup.md, docs/lib/getting-started/fragments/ios/setup.md
=> Updates to SDK and Lib landing pages

client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap, client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap, client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap
=> Fix snapshots

docs/start/getting-started/fragments/android/prereq.md, docs/start/getting-started/fragments/ios/prereq.md, docs/start/getting-started/installation.md
=> Udpate Node version and Android getting started guide

docs/lib/getting-started/fragments/android/setup.md
=> Update Amplify Android getting started guide 

client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap, client/src/docs-ui/secondary-nav/secondary-nav.tsx
The behavior for which @nikhil-dabhade requested.
=> chore: set sdk to lib root when in android or ios

cli-toolchain/graphql.md
=> fix broken link in migration script

client/src/robots.txt
Enables us to run broken-link checkers on the v2-preview site
=> Added LinkChecker to robots.txt exclusion

docs/start/start.md
=> Change Amplify Console link

capi/src/visitors/links.ts, client/src/docs-ui/internal-link/internal-link.tsx
`[cli](/cli)` is now as valid as `[cli/cli.md]`. No hash support.
=> Fix link bug

docs/fragments/features-grid.md
=> adjusted language for landing page features

theme/_includes/site-footer.html, theme/_layouts/index.html
- Move Google Analytics to `<head>`
=> Move Google Analytics script to head

client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap, client/src/docs-ui/universal-nav/universal-nav.style.ts
=> Adjusted NEW label alignment

client/src/docs-ui/secondary-nav/secondary-nav.tsx
Added the new algolia docsearch keys
=> fix: add new algolia keys

docs/start/getting-started/fragments/ios/setup.md
- fix podfile deps
- move `awsconfiguration.json` explanation to note
=> Getting Started Fixes

android/analytics.md, android/datastore.md, android/storage.md
*Description of changes:* Rene is updating URLs for consistency, so these redirects must also be updated.
=> Update redirects for URL changes

android/api.md, android/datastore.md
*Description of changes:* We've restructured the sections to always start with Getting Started, so redirect to that page for each category.
=> Redirect to Getting Started pages

docs/fragments/features-grid.md
=> Fixed broken links on Landing Page

docs/lib/auth/fragments/js/getting-started.md
=> [Auth - JS] Added a note in case people have an existing auth resource

docs/lib/storage/fragments/js/autotrack.md, docs/lib/storage/fragments/js/configureaccess.md, docs/lib/storage/fragments/js/download.md, docs/lib/storage/fragments/js/getting-started.md, docs/lib/storage/fragments/js/list.md, docs/lib/storage/fragments/js/remove.md, docs/lib/storage/fragments/js/upload.md, docs/lib/storage/triggers.md
Updating broken links and missing content from Storage JS docs
=> chore:(storage-docs) Update broken links and missing content

docs/start/getting-started/fragments/ios/data-model.md, docs/start/getting-started/fragments/ios/prereq.md, docs/start/getting-started/fragments/ios/setup.md
=> Addressed iOS Getting Started feedback after user study

docs/lib/predictions/fragments/ios/getting-started.md
- update pod to use latest version
- add cli link for getting started
=> chore: Update iOS Predictions

docs/start/getting-started/fragments/reactnative/setup.md
Updates to Expo installation instructions.
- Removed Amazon Cognito Identity dependency (already included in Expo SDK)
- Removed React Native Vector Icons dependency (already included in Expo SDK)
=> Fixed installation instructions for expo

docs/lib/getting-started/fragments/android/integrate.md, docs/lib/getting-started/fragments/ios/integrate.md
*Description of changes:* Fixed broken links to category pages at end of overall get started
=> Fix broken links

docs/sdk/auth/drop-in-auth.md, docs/sdk/auth/fragments/android/custom-auth-flow.md, docs/sdk/auth/fragments/android/federated-identities.md, docs/sdk/auth/fragments/android/getting-started.md, docs/sdk/auth/fragments/android/guest-access.md, docs/sdk/auth/fragments/android/how-it-works.md, docs/sdk/auth/guest-access.md, docs/sdk/auth/menu.json, docs/sdk/auth/working-with-api.md
*Description of changes:* Addresses issues with SDK authentication documentation.
*Preview:* https://pr-1373.d39agkzf0cwtdz.amplifyapp.com/sdk/auth/getting-started?platform=android
=> Fixes for Android Auth SDK Overview

docs/start/getting-started/fragments/vanillajs/data-model.md
Just a tiny typo that made the line read improperly.
=> fixed typo in GraphQL amplify push instructions

docs/sdk/api/fragments/android/graphql.md, docs/sdk/api/fragments/android/rest.md
*Description of changes:* As before, mostly fixing broken links but also some Markdown syntax issues.
=> Fixes for Android API SDK documentation

theme/_includes/site-head.html, theme/_layouts/index.html
=> fixes google analytics issues

client/src/sitemap.xml, client/stencil.config.ts
=> Add sitemap.xml

docs/lib/push-notifications/fragments/js/getting-started.md, docs/sdk/push-notifications/fragments/android/getting-started.md
=> Fixed remaining links

docs/cli/start/install.md
=> Update CLI installation steps to match getting started

docs/lib/auth/fragments/js/emailpassword.md, docs/lib/graphqlapi/fragments/js/getting-started.md
Fixed code formatting for Auth methods. Fixed misspelling in API GraphQL getting started guide.
=> a few small fixes: code formatting, mispelling

docs/lib/predictions/fragments/ios/translate.md
Minor changes, which (i think) improve readability/follow-on ability
=> Translate text: Update CLI options & minor changes

docs/docs.md, docs/lib/predictions/sample.md
=> Adjusted landing page link and removed empty predictions page

client/src/amplify-ui/code-block/__snapshots__/code-block.spec.ts.snap, client/src/amplify-ui/code-block/code-block.style.tsx, client/src/amplify-ui/code-block/code-block.tsx, docs/start/getting-started/fragments/reactnative/api.md
=> Removed code block shadow and moved copy button slightly

docs/lib/datastore/fragments/js/data-access/observe-snippet.md
=> by ID example of JS DataStore Observe, re issue #1545

docs/lib/analytics/fragments/android/getting-started.md, docs/lib/analytics/fragments/android/identifyuser.md, docs/lib/analytics/fragments/android/record.md, docs/lib/analytics/getting-started.md
*Description of changes:* Some general fixes to Android syntax and overall flow for the section.
- Removed links to the legacy API reference
- Reordered links so viewing the console is at the bottom
- Simplified code examples and verified them
=> Fixes for Analytics library section

docs/lib/analytics/getting-started.md, docs/sdk/analytics/fragments/android/endpoints.md, docs/sdk/analytics/fragments/android/kinesis.md
*Description of changes:* Minor fixes, including:
- Fix broken links and random Markdown errors
- Fix references to Amazon Kinesis services
=> Minor fixes for the SDK Analytics section

docs/sdk/pubsub/fragments/android/getting-started.md, docs/sdk/pubsub/fragments/android/working-api.md, docs/sdk/pubsub/getting-started.md, docs/sdk/pubsub/working-api.md
*Description of changes:* Fixed an image, added an article, all in a day's work.
=> Minor fixes for the SDK PubSub section

docs/sdk/push-notifications/getting-started.md, docs/sdk/push-notifications/messaging-campaign.md, docs/sdk/push-notifications/setup-push-service.md
*Description of changes:* Making the headers consistent with other sections.
=> Fix title casing of Push Notifications section headers

docs/lib/analytics/fragments/android/record.md
*Description of changes:* Some small things:
- Our guidance around autoFlushEventsInterval was incorrect
- Some Markdown badness (oops)
=> Some more Analytics library fixes

docs/lib/graphqlapi/getting-started.md, docs/lib/interactions/getting-started.md, docs/lib/predictions/getting-started.md, docs/lib/pubsub/getting-started.md, docs/lib/push-notifications/getting-started.md, docs/lib/restapi/getting-started.md, docs/lib/storage/getting-started.md, docs/lib/xr/getting-started.md
*Description of changes:* We started moving to 'Getting started' but didn't do this globally, this change commits the change across the Libraries section.
=> Make titlecase consistent

docs/ui-legacy/xr/fragments/react/sumerian-scene.md
Removing dead links in UI Legacy code
=> fix:(xr) Remove Jekyll link from XR UI Legacy docs

ios/predictions.md, sdk/ios/analytics.md, sdk/ios/api.md, sdk/ios/authentication.md, sdk/ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md, sdk/ios/pubsub.md, sdk/ios/push-notifications.md, sdk/ios/storage.md
Searched all for "2.12.0" and replaced with "2.13.0"
=> iOS - Bump all to 2.13.0

docs/lib/analytics/fragments/autotrack.md, docs/lib/analytics/fragments/ios/getting-started.md, docs/lib/analytics/fragments/ios/identifyuser.md, docs/lib/analytics/fragments/ios/record.md, docs/lib/analytics/fragments/js/autotrack.md, docs/lib/analytics/fragments/js/getting-started.md, docs/lib/analytics/getting-started.md
**Notes:** review of the Amplify.Analytics for iOS. Minor fixes and removed inaccurate/redundant content.
=> Amplify Analytics iOS docs review

docs/lib/restapi/delete.md, docs/lib/restapi/fetch.md, docs/lib/restapi/fragments/js/authz.md, docs/lib/restapi/fragments/js/delete.md, docs/lib/restapi/fragments/js/fetch.md, docs/lib/restapi/fragments/js/getting-started.md, docs/lib/restapi/fragments/js/update.md, docs/lib/restapi/menu.json, docs/lib/restapi/update.md
Updating the API Rest docs and splitting out CRUD operations into their own sections
=> V2 preview rest

docs/lib/restapi/fragments/js/getting-started.md
=> Fix link on REST API getting started

docs/lib/datastore/fragments/android/sync.md, docs/lib/datastore/fragments/js/sync.md, docs/lib/datastore/sync.md
**Notes:**
- remove duplicated sections from fragments
=> adjust datastore sync content

docs/lib/push-notifications/fragments/js/getting-started.md, docs/lib/push-notifications/fragments/js/overview.md, docs/lib/push-notifications/fragments/js/working-with-api.md, docs/lib/push-notifications/getting-started.md, docs/lib/push-notifications/overview.md, docs/lib/push-notifications/testing.md, docs/lib/push-notifications/working-with-api.md
Update the Push Notifications section within the new docs site.
=> Add, remove and rework push notifications section

docs/sdk/pubsub/fragments/android/getting-started.md, docs/sdk/pubsub/fragments/ios/getting-started.md, docs/ui-legacy/auth/fragments/react/tutorial.md
=> Removing jekyll reference and fixing image links

docs/start/getting-started/fragments/vanillajs/data-model.md, docs/start/getting-started/fragments/vue/data-model.md
=> fixed typos in data modeling instructions, addresses #1413

docs/lib/storage/fragments/ios/configureaccess.md, docs/lib/storage/fragments/ios/download.md, docs/lib/storage/fragments/ios/escapehatch.md, docs/lib/storage/fragments/ios/getting-started.md, docs/lib/storage/fragments/ios/list.md, docs/lib/storage/fragments/ios/remove.md, docs/lib/storage/fragments/ios/upload.md
**Notes:**
- moved content to the right pages
- reformatted code snippets
- reviewed faulty snippets
=> review and fix Amplify iOS Storage

docs/sdk/push-notifications/fragments/android/getting-started.md, docs/sdk/push-notifications/fragments/android/handle-adm.md, docs/sdk/push-notifications/fragments/android/handle-baidu.md, docs/sdk/push-notifications/fragments/android/handle-fcm.md, docs/sdk/push-notifications/fragments/android/messaging-campaign.md
**Notes:**
- minor formatting improvements
- verified that content matches v1
=> review Android Push Notification content

client/src/index.html
=> Add meta description

docs/sdk/auth/fragments/android/working-with-api.md
We had no documentation on how to set up MFA - we should have.
=> Adds a section on setting up MFA

docs/sdk/auth/fragments/android/working-with-api.md
Wrong size header for confirm sign in
=> Slight formatting fix

docs/lib/predictions/fragments/js/identify-text.md
=> fixes prediction's JS code sample

docs/sdk/auth/fragments/android/federated-identities.md
- Fix code typos
- Update instruction to require service ID rather than bundle ID
=> Update SIWA directions

docs/ui/auth/fragments/react/authenticator.md
Switch the documentation to reference the component that is exported by the js library
=> switch Contract to say Contact

docs/cli/graphql-transformer/directives.md
=> Fix content misaligned of @versioned directive with v1

capi/src/inject/menu.ts, capi/src/types/page.ts, client/src/docs-ui/page/__snapshots__/page.spec.ts.snap, client/src/docs-ui/page/page.style.ts, client/src/docs-ui/page/page.tsx, client/src/utils/update-document-head.ts
- Show section header on content pages
=> Add section header

theme/_includes/docs-header.html, theme/_sass/components/_redesign.scss
=> Adding move-banner

client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap, client/src/docs-ui/feedback-callout/feedback-callout.style.ts, client/src/docs-ui/feedback-callout/feedback-callout.tsx, client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap, client/src/docs-ui/repo-actions/repo-actions.tsx
=> Refactor callout style

client/src/docs-ui/page/__snapshots__/page.spec.ts.snap, client/src/docs-ui/page/page.style.ts
=> Adjust section header style to be more consistent with overall UI

docs/docs.md
=> Docs Episode 6 - The Return of "Explore Features"

docs/lib/graphqlapi/fragments/js/authz.md
=> Swapped out swift content with JS content of API Authz

docs/start/getting-started/fragments/react/api.md, docs/start/getting-started/fragments/vanillajs/data-model.md, docs/start/getting-started/fragments/vanillajs/hosting.md
Updates re: issues tagged by @brene
=> Nader/minor updates from GitHub

docs/lib/getting-started/fragments/android/integrate.md, docs/lib/getting-started/fragments/ios/integrate.md, docs/start/getting-started/fragments/angular/data-model.md, docs/start/getting-started/fragments/ionic/data-model.md, docs/start/getting-started/fragments/ios/data-model.md, docs/start/getting-started/fragments/vanillajs/data-model.md
Fixing you -> your typo at a bunch of places. 
=> Fixing typo you -> your at a bunch of places

client/src/sitemap.xml
=> updated sitemap.xml with new URL scheme

docs/lib/auth/fragments/js/getting-started.md
=> updated JS auth getting-started to make right-hand nav look cleaner

docs/start/getting-started/fragments/react/auth.md
=> Correct withAuthenticator React package name

client/src/docs-ui/feedback-callout/__snapshots__/feedback-callout.spec.ts.snap, client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap, client/src/utils/issue-link.ts
=> Add more descriptive feedback button link and make it work with # links

client/src/sitemap.xml, docs/cli/usage/menu.json, docs/cli/usage/upgrade.md
=> added "upgrade the cli" section

theme/_layouts/default.html
=> Redirecting "upgrade the cli" section to v2

Readme.md, client/src/sitemap.xml, docs/lib/auth/fragments/js/getting-started.md, docs/lib/auth/fragments/js/social.md, docs/sdk/auth/fragments/android/hosted-ui.md, docs/sdk/auth/fragments/ios/hosted-ui.md, docs/start/getting-started/fragments/reactnative/api.md, docs/start/getting-started/fragments/reactnative/auth.md, docs/start/getting-started/fragments/reactnative/getting-started-steps.md, docs/start/getting-started/fragments/reactnative/setup.md, docs/ui/auth/fragments/react/authenticator.md, docs/ui/auth/fragments/react/withauthenticator.md
=> Leveraging "tabs" for RN Getting Started guide, Auth Hosted UI, Auth JS getting started

docs/lib/datastore/fragments/js/sync.md
=> Typo fix for DataStore - syncing with cloud

docs/lib/datastore/fragments/android/getting-started/configuration.md
Update sample code to reflect new config interface introduced in: https://github.com/aws-amplify/amplify-android/pull/401
=> Update sample code to reflect new config interface

theme/_layouts/default.html
=> Adding redirect logic for fragment links

docs/lib/graphqlapi/fragments/android/subscribe-data.md
N/A
Fixes minor typo for GraphQL subscriptions in Android docs.
=> Fix minor android api typo

docs/lib/auth/overview.md
=> Removed extraneous 'a'

docs/lib/auth/fragments/js/mfa.md, docs/lib/auth/overview.md, docs/lib/datastore/fragments/js/sync.md, docs/lib/datastore/how-it-works.md, docs/lib/datastore/relational.md, docs/lib/getting-started/fragments/android/generate-model.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/start/getting-started/fragments/ios/setup.md, docs/ui-legacy/auth/fragments/react-native/authenticator.md, docs/ui-legacy/auth/fragments/react/authenticator.md, docs/ui-legacy/auth/fragments/react/tutorial.md, docs/ui/auth/fragments/angular/authenticator.md, docs/ui/auth/fragments/ionic/authenticator.md, docs/ui/auth/fragments/react-native/authenticator.md, docs/ui/auth/fragments/react/authenticator.md, docs/ui/auth/fragments/vue/authenticator.md
=> Removed all v1 link references

docs/lib/datastore/fragments/js/sync.md
#1723 
Resolving the issue with code snippet missing the import statement
=> fix:(datastore-docs) add missing code snippet for datastore

docs/cli/graphql-transformer/config-params.md
Fixed casing of ElasticSearch parameter
=> Update Searchable directive configurations

docs/sdk/analytics/fragments/ios/events.md
=> Update reference from Android SDK to iOS SDK

Readme.md
- Update amplify-block-switcher docs
=> Update block switcher readme

docs/cli/graphql-transformer/directives.md
Removed extraneous apostrophe.
=> Remove extraneous apostrophe

docs/cli/graphql-transformer/examples.md
Added GraphQL syntax highlighting.
=> Add GraphQL syntax highlighting

Readme.md
Hi @brene - thoughts on adding a Discord badge here?
=> Add Discord badge

docs/ui/auth/fragments/react/authenticator.md
- Fix typo in `AmplifyTOTPSetup` customization docs
=> Update customization AmplifyTOTPSetup component

client/src/utils/update-document-head.ts
- Dynamic meta description tag
=> Use dynamic meta description

docs/cli/usage/files.md
Added section on .gitignore updates when an Amplify init is run from the cli. Change is based on customer feedback.
=> Added section on .gitignore updates when an Amplify init is run from the cli.

docs/lib/datastore/fragments/js/relational/delete-snippet.md, docs/lib/datastore/fragments/js/relational/query-snippet.md, docs/lib/datastore/fragments/js/relational/save-many-snippet.md, docs/lib/datastore/fragments/js/relational/save-snippet.md, docs/lib/datastore/relational.md
=> feat(datastore): update js datastore relational docs

docs/lib/datastore/relational.md
=> fix(datastore): clarify @key caveat

docs/lib/getting-started/fragments/android/add-api.md, docs/lib/getting-started/fragments/android/integrate.md
*Description of changes:* Changing the guide to accommodate some issues with DataStore running without an API pushed.
=> Getting Started Changes

docs/start/getting-started/fragments/android/native_add-api.md, docs/start/getting-started/fragments/android/native_integrate.md
*Description of changes:* Fixes the Kotlin samples.
=> Remove specious new keyword from Kotlin examples

docs/lib/storage/escapehatch.md, docs/lib/storage/fragments/android/getting-started/10_preReq.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/30_initStorage.md, docs/lib/storage/fragments/android/getting-started/40_upload.md, docs/lib/storage/fragments/ios/getting-started/10_preReq.md, docs/lib/storage/fragments/ios/getting-started/20_installLib.md, docs/lib/storage/fragments/ios/getting-started/30_initStorage.md, docs/lib/storage/fragments/ios/getting-started/40_upload.md, docs/lib/storage/fragments/native_common/getting-started/common.md, docs/lib/storage/getting-started.md
=> Getting started storage for iOS and (in progress for) Android

docs/lib/graphqlapi/cancel-request.md, docs/lib/graphqlapi/fragments/js/cancel-request.md, docs/lib/graphqlapi/menu.json, docs/lib/restapi/cancel.md, docs/lib/restapi/fragments/js/cancel.md, docs/lib/restapi/menu.json
*Issue #, if available:* aws-amplify/amplify-js#5753
Add docs for cancel API request . See aws-amplify/amplify-js#5753 for more details
=>  Add docs for cancel API request 

client/src/docs-ui/menu/menu.tsx, docs/fragments/lib/android-sdk.md, docs/fragments/lib/android.md, docs/fragments/lib/ios-sdk.md, docs/fragments/lib/ios.md, docs/lib/lib.md, docs/sdk/fragments/android/library-callout.md, docs/sdk/fragments/ios/library-callout.md, docs/sdk/fragments/library-callout.md, docs/start/getting-started/fragments/android/native_setup.md, docs/start/getting-started/fragments/ios/native_setup.md
*Description of changes:* Changes from the latest round of feedback
By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.
=> Changes from the latest round of feedback

docs/start/getting-started/fragments/android/native_add-api.md, docs/start/getting-started/fragments/android/native_setup.md, docs/start/getting-started/native_add-api.md
*Description of changes:* Fixes for tutorial based upon feedback
- Add a Next Steps section to the tutorial
- Be prescriptive about the version of Android SDK to use
- Add priority to graphql query for completeness
=> Fixes for tutorial based upon feedback

docs/lib/predictions/fragments/android/getting-started/40_init.md, docs/lib/predictions/fragments/android/getting-started/50_translate.md, docs/lib/predictions/fragments/android/identify-entity.md, docs/lib/predictions/fragments/android/identify-text.md, docs/lib/predictions/fragments/android/interpret.md, docs/lib/predictions/fragments/android/label-image.md, docs/lib/predictions/fragments/android/text-speech.md, docs/lib/predictions/fragments/android/translate.md, docs/lib/project-setup/fragments/android/create-application/40_verifyAmplifyLibraries.md
*Description of changes:* Instead of MyAmplifyApplication, use MyAmplifyApp to save some characters.
=> Abbreviate Application to App

docs/start/getting-started/fragments/android/native_generate-model.md, docs/start/getting-started/fragments/android/native_integrate.md, docs/start/getting-started/fragments/android/native_setup.md
=> Fix typos in Android tutorial

docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/30_initStorage.md, docs/lib/storage/fragments/ios/getting-started/30_initStorage.md
=> [Native][Storage] Remove Predications word from Storage

docs/start/getting-started/fragments/android/native_integrate.md
=> Fix compile error in Java code sample

docs/start/getting-started/fragments/android/native_add-api.md
=> Replace model with getModel to fix error and specify type args to fix warning

docs/lib/storage/fragments/ios/download.md, docs/lib/storage/fragments/ios/escapehatch.md, docs/lib/storage/fragments/ios/list.md, docs/lib/storage/fragments/ios/remove.md, docs/lib/storage/fragments/ios/upload.md
=> Fix the code sample in storage download

docs/lib/datastore/fragments/android/sync.md
`syncMode` is no longer a valid config key and will crash the app
=> Update outdated config

docs/lib/graphqlapi/fragments/ios/getting-started/20_installLib.md, docs/lib/graphqlapi/fragments/ios/mutate-data.md, docs/lib/graphqlapi/fragments/ios/query-data.md, docs/lib/graphqlapi/fragments/ios/subscribe-data.md, docs/lib/graphqlapi/graphql-from-nodejs.md
I think the concepts page needs to be re-worked for iOS... also, did not dogfood configure auth modes yet.
=> Updates from dogfooding graphql api

client/src/docs-ui/page/page.style.ts
- Improve breakpoint for TOC hiding on smaller laptop screens
=> Make TOC breakpoint wider

client/src/components.d.ts, client/src/docs-ui/page/page.tsx
Uses RAF, as there are no event-listening capabilities for certain URL change events, oddly. This solution is light enough IMO. & most importantly, it works consistently!
=> Fix navigation issues

client/src/docs-ui/footer/__snapshots__/footer.spec.ts.snap, client/src/docs-ui/footer/footer.tsx
*Description of changes:* It's 2020.
=> Update copyright year

docs/lib/interactions/fragments/js/chatbot.md, docs/lib/restapi/delete.md, docs/lib/restapi/fetch.md, docs/lib/restapi/fragments/android/delete.md, docs/lib/restapi/fragments/android/fetch.md, docs/lib/restapi/fragments/android/getting-started/10_preReq.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/restapi/fragments/android/getting-started/30_initapi.md, docs/lib/restapi/fragments/android/getting-started/40_postTodo.md, docs/lib/restapi/fragments/android/update.md, docs/lib/restapi/fragments/ios/delete.md, docs/lib/restapi/fragments/ios/fetch.md, docs/lib/restapi/fragments/ios/getting-started/10_preReq.md, docs/lib/restapi/fragments/ios/getting-started/20_installLib.md, docs/lib/restapi/fragments/ios/getting-started/30_initapi.md, docs/lib/restapi/fragments/ios/getting-started/40_postTodo.md, docs/lib/restapi/fragments/ios/update.md, docs/lib/restapi/fragments/js/fetch.md, docs/lib/restapi/fragments/native_common/getting-started/common.md, docs/lib/restapi/getting-started.md, docs/lib/restapi/update.md, docs/lib/xr/fragments/sceneapi.md, docs/ui-legacy/api/fragments/react/connect.md
- migrate structure to Storage doc's getting started
- mostly follows the JS's API Rest structure
- added Android code snippets
=> [Native][AmplifyAPIRest] doc updates

docs/lib/auth/fragments/android/signin/40_multi_factor_signup.md, docs/lib/auth/fragments/android/signin/50_multi_factor_confirm_signin.md
=> Kotlin samples for MFA section in Auth

docs/lib/analytics/fragments/ios/getting-started/40_record.md, docs/lib/analytics/fragments/ios/record.md, docs/lib/storage/fragments/ios/escapehatch.md
Update some incorrect code snippets
=> [iOS][AmplifyAnalytics] code snippets update

docs/lib/predictions/fragments/android/identify-entity.md, docs/lib/predictions/fragments/android/identify-text.md, docs/lib/predictions/fragments/android/interpret.md, docs/lib/predictions/fragments/android/label-image.md, docs/lib/predictions/fragments/android/text-speech.md, docs/lib/predictions/fragments/ios/identify-entity.md, docs/lib/predictions/fragments/ios/identify-text.md
=> Android Predictions (minor fixes)

docs/start/getting-started/fragments/ios/native_setup.md
- remove unnecessary plugins like AWSPluginsCore
=> [iOS] [Tutorial] run through updates

docs/lib/auth/fragments/android/signin_web_ui/10_cli_setup.md, docs/lib/auth/fragments/android/social_signin_web_ui/10_cli_setup.md, docs/lib/auth/fragments/ios/signin_web_ui/10_cli_setup.md, docs/lib/auth/fragments/ios/social_signin_web_ui/10_cli_setup.md, docs/lib/auth/fragments/native_common/signin/common.md
=> Refactored terminal code to increase readability

docs/lib/restapi/delete.md, docs/lib/restapi/fetch.md, docs/lib/restapi/fragments/android/authz.md, docs/lib/restapi/fragments/android/delete.md, docs/lib/restapi/fragments/android/fetch.md, docs/lib/restapi/fragments/android/getting-started/10_preReq.md, docs/lib/restapi/fragments/android/getting-started/11_amplifyInit.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/restapi/fragments/android/getting-started/30_initapi.md, docs/lib/restapi/fragments/android/getting-started/40_postTodo.md, docs/lib/restapi/fragments/android/update.md, docs/lib/restapi/fragments/ios/getting-started/11_amplifyInit.md, docs/lib/restapi/fragments/native_common/getting-started/common.md, docs/lib/restapi/update.md
=> Fixes for the Android REST API section

docs/start/getting-started/fragments/android/native_add-api.md, docs/start/getting-started/fragments/ios/native_add-api.md, docs/start/getting-started/fragments/ios/native_integrate.md
- update sample logging
- preference for "amplify console api" instead of "amplify api console". i think it's more similar to "amplify add api" and "amplify update api"
=> [iOS] [Tutorial] run through updates 2

docs/lib/datastore/fragments/ios/getting-started/configuration.md
=> fix(datastore): getting started code snippet fix

docs/lib/graphqlapi/fragments/native_common/getting-started/common.md
More dogfooding this morning lead me to a couple nits on the getting-started guide
=> Updating minor nits on API GraphQL

docs/lib/auth/fragments/native_common/signout/common.md
=> Added content related to global signout

client/src/amplify-ui/container/__snapshots__/container.spec.ts.snap, client/src/amplify-ui/container/container.spec.ts, client/src/amplify-ui/container/container.tsx, client/src/components.d.ts, client/src/docs-ui/footer/__snapshots__/footer.spec.ts.snap, client/src/docs-ui/footer/footer.tsx, client/src/docs-ui/links-banner/__snapshots__/link-banner.spec.ts.snap, client/src/docs-ui/links-banner/link-banner.tsx, client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap, client/src/docs-ui/secondary-nav/secondary-nav.tsx, client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap, client/src/docs-ui/universal-nav/universal-nav.tsx, docs/docs.md, package.json, yarn.lock
- Bump UI component module version to latest
- Rename docs container to get rid of naming conflict
=> Update container to not conflict, bump ui module version

docs/cli/start/menu.json, docs/cli/start/workflows.md
=> renamed page to workflows

docs/lib/auth/fragments/ios/device_features/10_rememberDevice.md
=> fix: Remember device misspelling

docs/lib/auth/fragments/ios/access_credentials/10_fetchAuthSession.md, docs/lib/auth/fragments/ios/device_features/10_rememberDevice.md, docs/lib/auth/fragments/ios/device_features/20_forgetDevice.md, docs/lib/auth/fragments/ios/device_features/30_fetchDevice.md, docs/lib/auth/fragments/ios/getting_started/40_fetchSession.md, docs/lib/auth/fragments/ios/password_management/10_reset_password.md, docs/lib/auth/fragments/ios/password_management/20_confirm_reset_password.md, docs/lib/auth/fragments/ios/signout/10_local_signout.md, docs/lib/auth/fragments/ios/signout/20_global_signout.md, docs/lib/auth/fragments/ios/user_attributes/10_fetch_attributes.md, docs/lib/auth/fragments/ios/user_attributes/20_update_user_attribute.md, docs/lib/auth/fragments/ios/user_attributes/30_confirm_attribute.md, docs/lib/auth/fragments/ios/user_attributes/40_resend_code.md
=> chore: Remove parens around result closure params

docs/cli/graphql-transformer/directives.md
=> Fixed error in data modeling example

docs/sdk/fragments/library-callout.md
Make it clear that you are on the SDK docs and change the link to land on the Amplify Libs landing page.
=> Tweak the language of the callout

client/src/styles/font-faces.scss
[lighthouse recommendation](https://web.dev/avoid-invisible-text/)
=> chore: add font-swap prop to fontface declarations

docs/ui/auth/fragments/react/auth-state-management.md
- Fix React `user` usage inside of app
=> Update user usage in app

docs/cli/teams/overview.md, docs/cli/usage/lambda-triggers.md
=> Updated all copy to use "allow & deny" list and "prod" instead of master #BLM

docs/lib/graphqlapi/fragments/js/offline.md
=> (fix) fix table formatting in offline.md

theme/_layouts/default.html
=> redirect remaining v1 docs pages to v2

client/src/index.html, client/src/styles/algolia.scss, client/src/styles/styles.scss
[lighthouse recommendation](https://web.dev/render-blocking-resources/?utm_source=lighthouse&utm_medium=devtools)
=> perf: inline algolia styles in main css bundle

client/src/docs-ui/page/page.tsx, client/src/utils/track.ts
Does not capture sites urls redirecting to docs. Captures internal docs page referral urls.
=> feat: track referrer

docs/lib/storage/fragments/js/list.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-js/discussions/6135#discussioncomment-29191
this is a followup for user feedback in https://github.com/aws-amplify/amplify-js/discussions/6135#discussioncomment-29191 where we had the functionality he needed, but he wasnt aware of it bc our docs weren't descriptive enough. In fact, ideally, we would be able to add a sample API response for all of these APIs, or expose the typescript signatures.
@mtakac feel free to chime in with any other ideas for making documentation better. i'll make a separate issue for the HEAD api thing
=> [docs] note that lastmodified is returned in Storage.list

docs/lib/analytics/fragments/android/getting-started/30_initAnalytics.md
*Issue #, if available:* #1971
*Description of changes:* `AWSPinpointAnalyticsPlugin` expects the application to be passed in during initialization.
=> Fix analytics add documentation

docs/cli/graphql-transformer/resolvers.md
=> Addressing #1647

docs/cli/teams/shared.md, docs/cli/usage/files.md
=> Addresses #1713

package.json, yarn.lock
- Bump UI module version
- Gain new prop docs for the authenticator
=> Bump ui version for updated prop docs

docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md, docs/lib/datastore/fragments/android/getting-started/40_codegen.md
=> feat: android snippets for next datastore guide

docs/lib/auth/fragments/js/overview.md
=> Addresses #2602

client/src/docs-ui/landing-hero-cta/landing-hero-cta.tsx
=> Add "for free" label to "getting started"

docs/sdk/api/fragments/ios/rest.md
=> refactor: Remove pod version from api doc

docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/datastore/fragments/android/sync/20-savePredicate.md, docs/lib/datastore/fragments/android/sync/30-savePredicateComparison.md, docs/lib/datastore/fragments/android/sync/40-clear.md
=> feat: next datastore sync android fragments

docs/lib/auth/fragments/js/social.md
https://github.com/aws-amplify/docs/issues/2079
Fix typo from the issue.
=> Fix typo on social federation

docs/start/getting-started/fragments/vanillajs/setup.md
Resolves: https://github.com/aws-amplify/docs/issues/2078
=> Remove a stray comment in JS Getting Started

package.json, yarn.lock
=> Bump and pin ui version

docs/cli/graphql-transformer/directives.md
Added a new, clearer example to introduce customers to the `@key` directive. Cleaned up some syntax.
=> Added additional example in @key, cleaned up some syntax

docs/start/getting-started/fragments/vanillajs/data-model.md
Fixes #2060 
*Description of changes:* Update an incorrect path from `myapp` to `amplifyjsapp`
=> fix(getting-started/data-model): Update incorrect path

docs/guides/api-rest/fragments/js/form-api-with-dynamodb-and-lambda.md
*Description of changes:* added missing fields which are hard to add later due to related bug https://github.com/aws-amplify/amplify-cli/issues/4840
cc @dabit3
=> add missing fields to Creating a Form API with DynamoDB and Lambda guide

client/src/docs-ui/page/page.tsx, client/src/utils/track.ts
=> Adding Referrer info to Pinpoint

docs/cli/usage/iam.md
=> Addresses #2121

docs/sdk/push-notifications/fragments/android/getting-started.md
*Issue #, if available:* #1747
*Description of changes:* Remove unnecessary line which causes sync errors.
=> Remove unnecessary firebase-core dependency

docs/lib/graphqlapi/fragments/js/getting-started.md
add missing prompt in GraphQL API Getting Started doccs
=> [minor docfix] add missing prompt in GraphQL API Getting Started docs

docs/lib/storage/existing-resources.md, docs/lib/storage/fragments/existing-resources.md, docs/lib/storage/menu.json
*Description of changes:* Adds a page showing iOS and Android developers how to use an existing Amazon S3 bucket.
=> Docs for existing Amazon S3 buckets

docs/lib/restapi/existing-resources.md, docs/lib/restapi/fragments/existing-resources.md, docs/lib/restapi/menu.json
*Description of changes:* Adds a page showing iOS and Android developers how to use an existing API Gateway API.
=> Docs for existing REST API resources

cspell.json, docs/lib/auth/existing-resources.md, docs/lib/auth/fragments/existing-resources.md, docs/lib/auth/menu.json
*Description of changes:* Adds a page showing iOS and Android developers how to use existing Amazon Cognito resources.
=> Docs for existing Amazon Cognito resources

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
*Description of changes:* Update Android version to 1.1.1
For posterity, I ran:
```sh
find docs -path '**/android/**' -name '*.md' -exec sed -i -e 's/1\.0\.0/1.1.1/g' {} \;
```
=> Update Android version to 1.1.1

docs/cli/graphql-transformer/directives.md
=> Addressing #1910

docs/ui/auth/authenticator.md, docs/ui/auth/fragments/react/authenticator.md
This shows how to hide the phone number field as it is often requested by customers.
=> Added section to show how to hide the phone number field

docs/ui/auth/fragments/react/authenticator.md, docs/ui/customization/fragments/web/theming.md
Added section showing how to control component state and layout.
Added section showing how to use css to control layout of AmplifyAuthenticator
=> Updates to AmpllifyAuthenticator docs

.gitignore, docs/cli/usage/files.md
N/A
Document `amplify.json` file.
=> fix: add amplify.json file documentation

docs/start/getting-started/fragments/react/api.md
=> Addresses #2157

docs/cli/graphql-transformer/dataaccess.md
=> backticks instead of front ticks for code

docs/cli/graphql-transformer/dataaccess.md
=> removed duplicate "product" from list

docs/cli/graphql-transformer/dataaccess.md
fix https://github.com/aws-amplify/docs/issues/2180
=> fix https://github.com/aws-amplify/docs/issues/2180

docs/cli/teams/commands.md
Current version is missing some flags and the checkout command.
Reviewed content and improved formatting to match latest CLI commands.
=> Added commands table and improved formatting

docs/lib/datastore/fragments/js/examples.md
NA
Add Angular and Vue examples to DataStore section.
=> Add Angular and Vue examples

cspell.json
helps address https://github.com/aws-amplify/docs/pull/2188#pullrequestreview-460823733
=> (fix) add USERTABLE to spellcheck list

docs/lib/datastore/fragments/js/sync/20-savePredicate.md
=> Remove Swift example from DataStore JS docs

docs/lib/datastore/datastore-events.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/ios/getting-started/20_installLib.md, docs/lib/datastore/fragments/js/data-access/delete-snippet.md, docs/lib/datastore/fragments/js/datastore-events.md, docs/lib/datastore/fragments/js/other-methods.md, docs/lib/datastore/getting-started.md, docs/lib/datastore/menu.json, docs/lib/datastore/other-methods.md, docs/lib/utilities/fragments/hub.md
Documented DataStore events and methods that were previously not documented.
A couple of other minor fixes.
closes https://github.com/aws-amplify/docs/issues/2220
=> Documented datastore events and methods

docs/guides/authentication/email-only-authentication.md, docs/guides/authentication/fragments/js/email-only-authentication.md, docs/guides/authentication/menu.json, docs/lib/datastore/fragments/js/datastore-events.md
This is something that comes up a lot and I think it would be helpful to provide an end to end guide showing how to authenticate using email.
I also added a fix for some code I pushed for DataStore.
=> Auth with email guide

docs/cli/graphql-transformer/directives.md
=> Added limitations section for @searchable directive

docs/start/getting-started/fragments/ios/setup.md
*Issue #, if available:* #2230 
*Description of changes:* Adjust markdown formatting to fix broken code snippet rendering.
=> fix(ios): get started code snippet broken fixes #2230

docs/guides/functions/menu.json
New guide is not available in the menu.
Added new guide to the menu.
=> Add guide to menu

docs/lib/predictions/fragments/ios/transcribe.md
- Simply update several outdated lines in `transcribe.md`
=> fix(predictions): Minor mistake in iOS Predictions Transcribe docs

docs/start/getting-started/fragments/flutter/nextsteps.md
=> update flutter example link/text

docs/lib/datastore/fragments/native_common/getting-started.md
*Issue #, if available:* closes https://github.com/aws-amplify/docs/issues/2265
=> make xcode reference conditional in getting started

docs/lib/project-setup/fragments/flutter/prereq/prereq.md, docs/start/getting-started/fragments/flutter/setup.md
=> fix(amplify-flutter): clarifying platform prereqs

docs/lib/auth/fragments/android/signin_web_ui/20_platform_specific_setup.md, docs/sdk/auth/fragments/android/hosted-ui.md
Extending new HostedUI functionality to Amplify.
=> Adds updated HostedUI documentation to Amplify Auth

docs/lib/datastore/fragments/android/data-access/query-sort-multiple-snippet.md, docs/lib/datastore/fragments/android/data-access/query-sort-snippet.md
=> Revert "Datastore/android sort"

docs/start/getting-started/fragments/flutter/setup.md
create a new project using flutter cli
=> create a new project using flutter cli

docs/ui/storage/fragments/web/s3-album.md, docs/ui/storage/fragments/web/s3-image-picker.md, docs/ui/storage/fragments/web/s3-image.md, docs/ui/storage/fragments/web/s3-text-picker.md, docs/ui/storage/fragments/web/s3-text.md, docs/ui/storage/s3-album.md, docs/ui/storage/s3-image-picker.md, docs/ui/storage/s3-image.md, docs/ui/storage/s3-text-picker.md, docs/ui/storage/s3-text.md
=> Move common Storage component installation to common web file

docs/lib/project-setup/fragments/flutter/create-application/10_createProject.md, docs/lib/project-setup/fragments/flutter/create-application/30_provisionBackend.md, docs/lib/project-setup/fragments/flutter/create-application/40_verifyAmplifyLibraries.md, docs/lib/storage/fragments/flutter/getting-started/10_preReq.md, docs/lib/storage/fragments/flutter/getting-started/20_installLib.md, docs/lib/storage/fragments/flutter/upload.md, docs/lib/storage/fragments/native_common/getting-started/common.md
*Description of changes:* 
1. when I follow the flutter instructions to the letter (i dont have cocoapods installed), i dont have a podfile generated. it's unclear whether it is required or if it is optional. could you please clarify?
2. added amplify cli version prompt
3. fixed `AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();` bug
4. added install prompt `import 'package:amplify_storage_s3/amplify_storage_s3.dart';`
5. amplify auth seems to be a prerequisite in order to use storage seamlessly so i added in some nags
6. `Amplify.Storage.uploadFile()` args are totally undocumented
7. added link to https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_storage_s3/example
=> [Feedback] Flutter docs improvements

docs/ui/storage/fragments/web/s3-album.md, docs/ui/storage/fragments/web/s3-image-picker.md, docs/ui/storage/fragments/web/s3-image.md, docs/ui/storage/fragments/web/s3-text-picker.md, docs/ui/storage/fragments/web/s3-text.md, docs/ui/storage/fragments/web/tracking-events.md
Fixes #2289
Fix self closing elements for both Angular and Ionic.
=> Fix self closing elements for Angular and Ionic

docs/lib/project-setup/fragments/ios/combine/combine.md
=> fix: typo in iOS Combine docs

docs/cli/restapi/restapi.md
Some recent changes were not available in the docs.
Added new intro and create api.
=> Update overview with latest CLI

docs/lib/storage/fragments/js/configureaccess.md
Fixes: #2325 
Adding Custom Prefix documentation for Storage category
=> Adding custom prefix docs for Storage

client/src/docs-ui/universal-nav/__snapshots__/universal-nav.spec.ts.snap, client/src/docs-ui/universal-nav/universal-nav.tsx
=> Removed NEW label

docs/ui/interactions/fragments/web/chatbot/customization.md
*Description of changes:* This PR fixes typo in css variables and adds new variables.
=> Fix typo in css variables

docs/cli/usage/tags.md
=> Update tags to new design

docs/lib/auth/fragments/android/device_features/10_rememberDevice.md, docs/lib/auth/fragments/android/device_features/20_forgetDevice.md, docs/lib/auth/fragments/android/device_features/30_fetchDevice.md
*Description of changes:* Add Android samples for device management
=> Add Android samples for device management

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
=> Amplify Android 1.3.1 release

docs/cli/usage/tags.md
Added docs on how to use tags for existing projects
https://github.com/aws-amplify/amplify-cli/issues/5230
=> feat: existing project tags

docs/cli/restapi/menu.json, docs/cli/restapi/testing.md
Add new section for testing REST APIs
=> Add test section

docs/lib/datastore/fragments/native_common/data-access.md, docs/lib/datastore/fragments/native_common/sort.md
=> Remove Sort DS Section from JS

docs/cli/reference/feature-flags.md, docs/cli/reference/files.md
Update feature flag documentation to mirror the changes in the CLI's behavior.
=> fix: update feature flags documentation

cspell.json, docs/lib/graphqlapi/fragments/android/advanced-workflows/20_custom.md, docs/lib/graphqlapi/fragments/android/advanced-workflows/30_nested.md, docs/lib/graphqlapi/fragments/android/advanced-workflows/40_multiple.md
=> [Android] AWSAPIPlugin GraphQL Advanced workflow docs with custom GraphQL requests

docs/start/getting-started/fragments/vanillajs/data-model.md
=> Update VanillaJS tutorial to be more explicit

docs/cli/auth/overview.md
=> update social provider section in the CLI docs

docs/lib/datastore/fragments/native_common/getting-started.md
=> Fixes datastore CLI guide to accommodate new CLI flow.

docs/lib/datastore/fragments/js/data-access/query-sort-multiple-snippet.md, docs/lib/datastore/fragments/js/data-access/query-sort-snippet.md, docs/lib/datastore/fragments/native_common/data-access.md, docs/lib/datastore/fragments/native_common/sort.md
=> feat(datastore): add query sort docs

client/src/styles/color-effect-utils.scss, client/src/styles/elements.scss, docs/cli/start/install.md, docs/docs.md, docs/fragments/features-grid.md, docs/guides/hosting/fragments/custom-domains.md, docs/guides/hosting/fragments/local-deployments.md, docs/guides/hosting/fragments/password-protected-deployments.md, docs/guides/hosting/fragments/pull-request-previews.md, docs/lib/datastore/fragments/js/getting-started/30_platformIntegration.md, docs/lib/datastore/fragments/native_common/how-it-works.md, docs/lib/project-setup/fragments/native_common/prereq/common_body.md, docs/start/getting-started/fragments/common/prereq.md, docs/start/getting-started/fragments/next/hosting.md
- New landing page with 90s explanation video
- Updated youtube links
- minor styling fixes
=> Updated landing page & video links

docs/cli/cli.md
=> Added a CLI GIF

docs/cli/menu.json, docs/cli/restapi/menu.json, docs/cli/storage/menu.json, docs/cli/storage/overview.md, docs/cli/usage/lambda-triggers.md
=> Adding CLI storage docs

docs/start/getting-started/fragments/reactnative/getting-started-steps.md
=> Revert "Remove react-native-vector-icons from getting started"

docs/cli/plugins/plugins.md
=> Addresses #2402

docs/lib/storage/fragments/js/download.md
(fix) improve storage.get docs
*Issue #, if available:* closes https://github.com/aws-amplify/amplify-js/issues/847
helps address valid concerns raised by @donnrri
=> (fix) improve storage.get docs

docs/start/getting-started/fragments/next/setup.md
fixes https://github.com/aws-amplify/docs/issues/2418
Fix typo 
=> Create React App -> Create Next App

docs/guides/api-rest/fragments/js/form-api-with-dynamodb-and-lambda.md
flesh out the sample function code for maximum copy and paste
=> [Form API Guide] flesh out the sample code for maximum copy and paste

docs/start/getting-started/fragments/android/setup.md
https://github.com/aws-amplify/amplify-android/issues/844
Update version in the getting started guide for android
=> chore(android): update version in getting started

docs/lib/auth/fragments/android/user_attributes/10_fetch_attributes.md, docs/lib/auth/fragments/android/user_attributes/20_update_user_attribute.md, docs/lib/auth/fragments/android/user_attributes/30_confirm_attribute.md, docs/lib/auth/fragments/android/user_attributes/40_resend_code.md, docs/lib/auth/fragments/native_common/user_attributes/common.md
=> Add user attribute documentation

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
=> chore: advertise 1.4.0 of Amplify Android

docs/lib/auth/fragments/native_common/guest_access/common.md, docs/lib/auth/guest_access.md, docs/lib/auth/menu.json
Describes what it does and how to set it up via CLI
=> Adds Guest Access Documentation

docs/start/getting-started/auth.md, docs/start/getting-started/fragments/angular/auth.md, docs/start/getting-started/fragments/angular/data-model.md, docs/start/getting-started/fragments/angular/setup.md
Adding missing forms module and other improvements.
Fixes to getting started after doing another full review.
=> Fix issues with getting started

docs/start/getting-started/fragments/reactnative/getting-started-steps.md
=> Remove react-native-vector-icons from getting started

docs/start/getting-started/fragments/angular/data-model.md, docs/start/getting-started/fragments/angular/setup.md
Fixes / updates to add clarity and copy-paste examples to the Angular getting started guides.
=> Updates to angular getting started guide

docs/start/getting-started/nextsteps.md
Regression from #2381
The React fragment was intended to be shared for both React & Next.js
---
=> Add "Next Steps" to React

docs/guides/api-graphql/fragments/js/graphql-pagination.md, docs/guides/api-graphql/graphql-pagination.md
Updates to pagination docs, addresses comments in #2354
=> Addresses #2354, updates to pagination docs

docs/start/getting-started/fragments/ios/generate-model.md
=> iOS tutorial replace "then" with "them"

docs/guides/api-graphql/fragments/android/subscriptions-by-id.md
=> Android documentation for subscription by id

docs/cli/graphql-transformer/directives.md
=> remove field level IAM example

docs/ui/customization/customizing-css.md
- include top level components available for customization now.
- update custom usage code.
=> Update custom css docs.

docs/start/getting-started/fragments/reactnative/api.md
Closes: #2447
Resolving issues and fixing typo of `addTodo` instead of `createTodo`
Screenshot of change:
=> fix:(react-native-getting-started) fix typo

docs/guides/functions/menu.json
add 'appsync-operations-to-lambda-layer' to menu.json
=> add 'appsync-operations-to-lambda-layer' to menu.json

docs/lib/auth/fragments/js/manageusers.md
=> Fixed missing await

docs/lib/xr/fragments/getting-started.md
=> Update Tutorial URL

.github/CODEOWNERS
*Description of changes:* The CLI team must review any change to files in docs/cli. The previous pattern did not match this directory.
=> Fix CLI ownership path

docs/cli/start/workflows.md
=> fix(workflows.md): root stack template shows up after push

docs/lib/pubsub/fragments/js/getting-started.md
https://github.com/aws-amplify/docs/issues/2550
=> Feedback from #2550

docs/cli/teams/shared.md
https://github.com/aws-amplify/docs/issues/2507
=> Clarification on reusing existing envs

docs/start/getting-started/fragments/ios/integrate.md
Resolves: https://github.com/aws-amplify/docs/issues/2601
=> fix: add closing parens where missing in ios query docs

docs/cli/auth/admin.md
=> Updated Admin queries with latest listGroups feature

client/src/components.d.ts, docs/lib/datastore/fragments/js/sync/50-selectiveSync.md, docs/lib/datastore/fragments/native_common/sync.md
=> feat(datastore): js - add selective sync docs

client/src/docs-ui/landing-hero-cta/landing-hero-cta.style.ts, client/src/docs-ui/landing-hero-cta/landing-hero-cta.tsx
=> Adding React + Vue to the main landing page

docs/lib/client-configuration/fragments/js/js-configuration.md
Updated to add "aws_appsync_apiKey" to configuration for AppSync API.
=> Added api key config to "Configuring Amplify Categories" docs

docs/lib/datastore/fragments/ios/setup-auth-rules/owner_based_auth_oidc.md, docs/lib/datastore/fragments/native_common/setup-auth-rules.md
Added iOS specific section for OIDC Auth provider
=> Added iOS specific section for OIDC Auth provider

docs/lib/project-setup/fragments/flutter/create-application/40_verifyAmplifyLibraries.md
=> fix flutter syntax in docs

client/src/constants/links.ts, client/src/docs-ui/footer/__snapshots__/footer.spec.ts.snap, client/src/docs-ui/links-banner/__snapshots__/link-banner.spec.ts.snap
=> Update discord link to https://discord.gg/amplify

cspell.json, docs/lib/auth/fragments/ios/signin_with_custom_flow/10_cli_setup.md, docs/lib/auth/fragments/ios/signin_with_custom_flow/20_signup.md, docs/lib/auth/fragments/ios/signin_with_custom_flow/30_confirmSignup.md, docs/lib/auth/fragments/ios/signin_with_custom_flow/40_signin.md, docs/lib/auth/fragments/ios/signin_with_custom_flow/50_custom_challenge.md, docs/lib/auth/fragments/native_common/signin_with_custom_flow/common.md, docs/lib/auth/menu.json, docs/lib/auth/signin_with_custom_flow.md
*Issue #, if available:* https://github.com/aws-amplify/docs/issues/2306
*Description of changes:* Add custom authentication flow for iOS.
=> feat(auth): Added implementation for custom auth

docs/ui/auth/fragments/react-native/authenticator.md
=> fix grammar error

docs/lib/graphqlapi/fragments/ios/getting-started.md, docs/lib/project-setup/fragments/ios/create-application/31_provisionBackend.md, docs/lib/project-setup/fragments/ios/create-application/40_verifyAmplifyLibraries.md
=> fix(doc): removed references of xcode-build-error.png

docs/lib/datastore/fragments/android/datastore-events.md
=> [Android] Fix bug in DataStore hub event code sample

docs/lib/datastore/datastore-events.md
=> fix(DataStore): Add one empty line

client/src/amplify-ui/sidebar-layout/sidebar-close-button/__snapshots__/sidebar-close-button.spec.ts.snap, client/src/amplify-ui/sidebar-layout/sidebar-close-button/sidebar-close-button.style.ts, client/src/amplify-ui/sidebar-layout/sidebar-open-button/__snapshots__/sidebar-open-button.spec.ts.snap, client/src/amplify-ui/sidebar-layout/sidebar-open-button/sidebar-open-button.style.ts
=> Fixed sidebar menu alignment

docs/lib/utilities/fragments/hub.md
Added description of hub `tokenRefresh` and `tokenRefresh_failure` events. Also fixed accidental `error` instead of `info` for certain cases.
=> added to hub readme

docs/cli/plugins/plugins.md
=> Updating docs with more descriptive information for 3rd party plugins

docs/lib/graphqlapi/fragments/js/query-data.md
=> removed one extra bracket

docs/ui/auth/fragments/web/authenticator.md
Fixes https://github.com/aws-amplify/docs/issues/2659
@harrysolovay , can you review?
=> Fix component to use ConfirmSignUp

docs/lib/datastore/fragments/js/sync/50-selectiveSync.md
Some edits and clarification based on feedback from @renebrandel 
=> fix(datastore): selective sync edit

docs/lib/analytics/fragments/js/getting-started.md
*Description of changes:* Remove note in Analytics guide
=> Remove note in Analytics guide

client/src/components.d.ts, docs/lib/datastore/fragments/android/sync/50-selectiveSync.md, docs/lib/datastore/fragments/native_common/sync.md
=> Add documentation for selective sync on Android

docs/lib/datastore/fragments/android/other-methods.md, docs/lib/datastore/other-methods.md
=> Add documentation for clear, start and stop on Android

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
*Description of changes:* `find docs -path '**/android/**' -name '*.md' -exec sed -i -e 's/1\.4\.1/1.6.2/g' {} \;`
=> Bump Android to 1.6.2

docs/lib/client-configuration/fragments/js/js-configuration.md
Fixes REST API config documentation.
=> Updated rest api config docs

docs/lib/datastore/fragments/android/other-methods.md
=> Removed superfluous "("

docs/guides/hosting/fragments/nextjs.md
=> Correct typo

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
=> Advertise Amplify Android 1.6.3

docs/guides/authentication/fragments/js/custom-auth-flow.md
*Description of changes:* Fixed a couple of typos in the Creating a custom authentication flow guide.
=> fixed typos

docs/cli/auth/import.md, docs/cli/storage/import.md, docs/cli/storage/menu.json
=> Added import storage docs

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
=> Advertise 1.6.4 of Amplify Android

docs/lib/analytics/fragments/flutter/getting-started/10_preReq.md, docs/lib/auth/fragments/flutter/getting_started/10_preReq.md, docs/lib/datastore/fragments/flutter/data-access/delete-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-basic-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-pagination-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-predicate-multiple-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-predicate-or-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-predicate-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-sort-multiple-snippet.md, docs/lib/datastore/fragments/flutter/data-access/query-sort-snippet.md, docs/lib/datastore/fragments/flutter/data-access/save-snippet.md, docs/lib/datastore/fragments/flutter/data-access/update-snippet.md, docs/lib/datastore/fragments/flutter/getting-started/10_preReq.md, docs/lib/datastore/fragments/flutter/getting-started/20_installLib.md, docs/lib/datastore/fragments/flutter/getting-started/50_initDataStore.md, docs/lib/datastore/fragments/flutter/getting-started/60_saveSnippet.md, docs/lib/datastore/fragments/flutter/getting-started/70_querySnippet.md, docs/lib/datastore/fragments/flutter/real-time/observe-snippet.md, docs/lib/storage/fragments/flutter/getting-started/10_preReq.md
This PR doesn't add all the snippets, still TBDs are
* Relational data access
* Sync
* Events
* Auth rules
* Conflict resolution
=> Add datastore flutter code snippets

docs/lib/datastore/fragments/android/relational/save-many-snippet.md, docs/lib/datastore/fragments/android/relational/save-snippet.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md
As discovered while walking through docs with @renebrandel, @jpignata, @raphkim.
=> fix: bad usage of rxjava merge operator

docs/lib/storage/fragments/js/download.md
closes https://github.com/aws-amplify/amplify-js/issues/7311
=> fix Storage.get inaccuracy

docs/console/adminui/intro.md, docs/console/adminui/start.md, docs/console/auth/user-management.md, docs/console/console.md, docs/console/data/content-management.md
=> quickfixes for console

docs/console/data/data-model.md
=> fix sandbox link

docs/lib/datastore/fragments/flutter/getting-started/30_platformIntegration.md, docs/lib/datastore/fragments/flutter/getting-started/40_codegen.md
Change from TBD to say coming soon.
=> Update platform integration section for flutter datastore

docs/start/start.md
=> update link to admin UI

cspell.json, docs/lib/info/fragments/native_common/data-information/common.md, docs/lib/info/menu.json, docs/lib/info/overview.md, docs/lib/menu.json
=> Added data policy for the ios library

docs/lib/graphqlapi/fragments/js/subscribe-data.md
https://github.com/aws-amplify/amplify-js/issues/7324
- Adding more details about the data that is received from GraphQL subscriptions.
Code reference: 
https://github.com/aws-amplify/amplify-js/blob/daca2ab654159dfdb43527b42703497c105c2bf6/packages/pubsub/src/PubSub.ts#L175
---
=> Be explicit about GraphQL subscription data

docs/lib/datastore/fragments/ios/other-methods.md, docs/lib/datastore/other-methods.md
Added start/stop:
https://github.com/aws-amplify/amplify-ios/pull/919/files
Planned to be released as part of our next release 1.5.0
Here is the accompanying documentation (largely lifted from Android documentation).
**Feel free to review, but please do not merge in until we have released 1.5.0**
=> Adding iOS documentation for start/stop/clear

docs/cli/start/install.md
=> Corrected formatting

docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md, docs/start/getting-started/fragments/android/setup.md
Update docs to reflect new version of amplify-tools
=> chore(amplify-tools) Update amplify-tools version

docs/lib/datastore/fragments/native_common/relational.md
Resolves: https://github.com/aws-amplify/docs/issues/2746
=> fix: confusing grammar for many to many relationships

docs/lib/auth/fragments/android/getting_started/30_initAuth.md
*Description of changes:* The parser expects these to be files followed by a fragment uri.
=> Fix broken reference

docs/cli/usage/containers.md
=> Region note

docs/cli/usage/containers.md
=> Troubleshooting note

docs/cli/function/layers.md
https://github.com/aws-amplify/amplify-cli/issues/5779
=> fix lambda layer update docs

docs/lib/auth/fragments/js/advanced.md
Refactoring components on `advanced` auth workflows to use Functional Components, so it's easier to use it with new projects.
=> Refactoring components on advanced auth workflows for FCs

Readme.md
Making it more clear how to contribute to docs and test changes.
=> Update readme to explain branch structure

docs/guides/location-service/setting-up-your-app.md, docs/guides/location-service/tracking-device-location.md
=> add awslocation ios guides

docs/guides/location-service/fragments/setting-up-your-app-ios.md
=> fix location links in the ios guide

client/src/amplify-ui/cli-feature-flag/feature-flags.json
=> chore: added new FeatureFlags

docs/lib/storage/fragments/flutter/getting-started/40_upload.md
The type of argument "local" in uploadFile is File, not String.
=> fix: flutter getting-started uploading data to your bucket

docs/ui/auth/fragments/react/handleauthstatechange.md, docs/ui/auth/fragments/web/authenticator.md
Documents `handleauthstatechange` in React, should address concerns in #2549 & #2513
=> Documented handleauthstatechange for React

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap, client/src/docs-ui/choose-integration-anchor/__snapshots__/choose-integration-anchor.spec.ts.snap, client/src/utils/filter-data.ts, docs/fragments/lib/flutter.md, docs/lib/project-setup/fragments/flutter/create-application/30_provisionBackend.md, docs/start/getting-started/fragments/flutter/add-api.md
Remove preview language from Flutter docs
=> Remove preview language from Flutter docs

docs/lib/datastore/fragments/ios/sync/50-selectiveSync.md, docs/lib/datastore/fragments/native_common/sync.md
Currently self-reviewing, feel free to add comments.
=> fix: add DataStore selective sync section for iOS

docs/cli/graphql-transformer/key.md
Fixes link to @connection in docs.
=> Fixed broken link

docs/lib/graphqlapi/fragments/flutter/getting-started/20_installLib.md, docs/lib/graphqlapi/fragments/flutter/subscribe-data.md, docs/lib/restapi/fragments/flutter/getting-started/20_installLib.md, docs/lib/restapi/fragments/flutter/update.md
Originating PR https://github.com/aws-amplify/docs/pull/2818
=> Update package name for flutter api docs

docs/lib/analytics/fragments/android/getting-started/20_installLib.md, docs/lib/auth/fragments/android/getting_started/20_installLib.md, docs/lib/datastore/fragments/android/getting-started/20_installLib.md, docs/lib/datastore/fragments/android/sync/10-installPlugin.md, docs/lib/graphqlapi/fragments/android/authz/21_oidc.md, docs/lib/graphqlapi/fragments/android/getting-started.md, docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md, docs/lib/predictions/fragments/android/getting-started/30_installLib.md, docs/lib/project-setup/fragments/android/create-application/20_gradle.md, docs/lib/project-setup/fragments/android/rxjava/rxjava.md, docs/lib/restapi/fragments/android/getting-started/20_installLib.md, docs/lib/storage/fragments/android/getting-started/20_installLib.md, docs/start/getting-started/fragments/android/setup.md
=> chore: update Amplify Android to 1.6.10
