aws-amplify/docs

docs/lib/storage/fragments/android/upload.md

Add Storage upload inputStream doc

---

cspell.json
docs/cli/function/build-options.md

*Issue #, if available:* #2478
*Description of changes:* Adds barebones documentation of build & package steps for Python functions, specifically around packaging dependencies.

first pass at adding build/packaging details for Python functions

---

docs/start/getting-started/fragments/reactnative/api.md

#2453
- Update wording to be clearer about what customers should do

Update wording for React Native getting started

---

docs/cli/usage/monorepo.md
docs/guides/api-graphql/building-a-form-api.md
docs/guides/api-graphql/fragments/js/image-and-file-uploads.md
docs/guides/api-graphql/lambda-resolvers.md
docs/guides/functions/cognito-trigger-lambda-dynamodb.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/ios/getting-started.md
docs/lib/graphqlapi/fragments/js/getting-started.md
docs/lib/graphqlapi/fragments/native_common/getting-started/common.md
docs/start/getting-started/fragments/react/api.md
docs/start/getting-started/fragments/vanillajs/data-model.md
docs/start/getting-started/fragments/vue/data-model.md

#2444 
- Update to reflect the current prompts presented when adding an API with the CLI
- removes `Do you want a guided schema creation?` and `What best describes your project:` questions
While going through this, it did become apparent that we use many different formats for how the console output is shown in the docs. Fixing this is likely out of scope for this PR, but just something to consider going forward.
---

Update `add api` prompts

---

docs/cli/graphql-transformer/predictions.md
docs/cli/usage/lambda-triggers.md
docs/lib/analytics/fragments/js/getting-started.md
docs/lib/auth/fragments/js/advanced.md
docs/lib/datastore/fragments/js/data-access/importing-datastore-snippet.md
docs/lib/datastore/fragments/js/examples.md
docs/lib/datastore/fragments/js/other-methods.md
docs/lib/pubsub/fragments/js/getting-started.md
docs/lib/restapi/fragments/js/getting-started.md
docs/lib/utilities/fragments/cache.md
docs/lib/utilities/fragments/hub.md
docs/lib/utilities/fragments/i18n.md
docs/lib/utilities/fragments/serviceworker.md
docs/start/getting-started/fragments/angular/data-model.md
docs/start/getting-started/fragments/vanillajs/data-model.md
docs/start/getting-started/fragments/vue/data-model.md
docs/ui-legacy/fragments/angular/overview.md

#2885 
- Remove sections about installing modular imports
- Remove references to modular packages in code snippets
---

Remove references to modular imports

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md

Advertise Android version 1.6.11 in the docs.

---

yarn.lock

Updating the `yarn.lock` file to update dependencies.

fix: Update yarn.lock file

---

docs/sdk/analytics/fragments/ios/kinesis.md

https://github.com/aws-amplify/docs/issues/2860

iOS - Update kinesis.md broken links

---

client/src/utils/track.ts

Resolving search query issue

---

docs/sdk/api/fragments/ios/graphql.md

https://github.com/aws-amplify/docs/issues/2853

fix(ios-sdk): appsync client architecture table formatting

---

docs/lib/analytics/fragments/ios/getting-started/30_initAnalytics.md
docs/lib/auth/fragments/ios/getting_started/30_initAuth.md
docs/lib/datastore/fragments/ios/getting-started/50_initDataStore.md
docs/lib/graphqlapi/fragments/ios/getting-started/30_initapi.md
docs/lib/predictions/fragments/ios/getting-started/40_init.md
docs/lib/restapi/fragments/ios/getting-started/30_initapi.md
docs/lib/storage/fragments/ios/getting-started/30_initStorage.md

This adds a switcher for SwiftUI Apps verse Appdelegate. Depending on the outcome of this PR, we can apply the same content across other places

[iOS] Update switcher for AppDelegate

---

docs/lib/auth/fragments/ios/signin_web_ui/40_private_session.md
docs/lib/auth/fragments/native_common/signin_web_ui/common.md

*Issue #, if available:* https://github.com/aws-amplify/docs/issues/2922
Documentation for the changes introduced in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0

chore: Updated auth documentation to reflect changes regarding private session

---

docs/lib/analytics/fragments/flutter/getting-started/30_initAnalytics.md
docs/lib/analytics/fragments/flutter/getting-started/40_record.md
docs/lib/analytics/fragments/flutter/identifyuser.md
docs/lib/analytics/fragments/flutter/record.md
docs/lib/datastore/fragments/flutter/data-access/delete-snippet.md
docs/lib/datastore/fragments/flutter/data-access/query-basic-snippet.md
docs/lib/datastore/fragments/flutter/data-access/update-snippet.md
docs/lib/datastore/fragments/flutter/datastore-events.md
docs/lib/datastore/fragments/flutter/getting-started/70_querySnippet.md
docs/lib/datastore/fragments/flutter/real-time/observe-snippet.md
docs/lib/datastore/fragments/flutter/relational/delete-snippet.md
docs/lib/datastore/fragments/flutter/relational/save-many-snippet.md
docs/lib/datastore/fragments/flutter/relational/save-snippet.md
docs/lib/datastore/fragments/flutter/sync/40-clear.md
docs/lib/datastore/fragments/native_common/getting-started.md
docs/lib/graphqlapi/fragments/flutter/getting-started/30_initapi.md
docs/lib/graphqlapi/fragments/flutter/getting-started/50_createtodo.md
docs/lib/graphqlapi/fragments/flutter/mutate-data.md
docs/lib/graphqlapi/fragments/flutter/query-data.md
docs/lib/project-setup/fragments/flutter/create-application/40_verifyAmplifyLibraries.md
docs/lib/restapi/fragments/flutter/delete.md
docs/lib/restapi/fragments/flutter/fetch.md
docs/lib/restapi/fragments/flutter/getting-started/40_postTodo.md
docs/lib/restapi/fragments/flutter/update.md
docs/start/getting-started/fragments/flutter/integrate.md

Update Flutter Docs Error Handling + Single Quotes

---

docs/lib/auth/fragments/flutter/access_credentials/10_fetchAuthSession.md
docs/lib/auth/fragments/flutter/signin/10_signUp.md
docs/lib/auth/fragments/flutter/signin/20_confirmSignUp.md
docs/lib/auth/fragments/flutter/signin/30_signIn.md
docs/lib/auth/fragments/flutter/signin/40_multi_factor_signup.md
docs/lib/auth/fragments/flutter/signin/50_multi_factor_confirm_signin.md
docs/lib/auth/fragments/flutter/signin_web_ui/30_signin.md
docs/lib/auth/fragments/flutter/signout/10_local_signout.md
docs/lib/auth/fragments/flutter/signout/20_global_signout.md
docs/lib/auth/fragments/flutter/user_attributes/10_fetch_attributes.md
docs/lib/storage/fragments/flutter/download.md
docs/lib/storage/fragments/flutter/list.md
docs/lib/storage/fragments/flutter/remove.md
docs/lib/storage/fragments/flutter/upload.md

Adds single quote style for Flutter Auth docs, new Exception types for Auth/Storage, and Flutter fetchUserAttributes API docs.

chore: single quote style, new exception types, fetchUserAttributes

---

docs/lib/project-setup/fragments/flutter/create-application/40_verifyAmplifyLibraries.md
docs/lib/project-setup/fragments/flutter/create-application/50_nextSteps.md
docs/start/getting-started/fragments/flutter/integrate.md
docs/start/getting-started/fragments/flutter/nextsteps.md

*Description of changes:*chore: Update getting started guide to reflect 'AmplifyAlreadyConfiguredException'

chore: Update getting started guide to reflect 'AmplifyAlreadyConfiguredException'

---

docs/start/getting-started/fragments/ios/add-api.md

chore: Updated getting started for iOS

---

docs/cli/graphql-transformer/resolvers.md

Update the geo location search schema with  @connection directive
fix #2487

fix: Update geolocation schmea to include @connection directive

---

docs/lib/auth/fragments/flutter/signin/10_signUp.md

```
E/flutter (30435): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'
E/flutter (30435): #0      new CognitoSignUpOptions (package:amplify_auth_cognito/src/CognitoSignUp/CognitoSignUpOptions.dart:20:87)
E/flutter (30435): #1      SignUpState._signUp (package:AwsAmplifySample/components/signUp.dart:29:20)
E/flutter (30435): #2      SignUpState.build.<anonymous closure> (package:AwsAmplifySample/components/signUp.dart:190:35)
E/flutter (30435): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (30435): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (30435): #5 …
```

fix: type error on register

---

docs/lib/datastore/fragments/flutter/sync/40-clear.md

corrects DataStore.clear documentation for flutter

fix: corrects DataStore.clear documentation for flutter

---

docs/lib/auth/fragments/flutter/social_signin_web_ui/10_cli_setup.md
docs/lib/auth/fragments/flutter/social_signin_web_ui/20_signin.md
docs/lib/auth/fragments/native_common/social_signin_web_ui/common.md
docs/lib/auth/social_signin_web_ui.md

Adds social sign in with web ui page for Flutter.

chore: Social sign in with web ui page for flutter

---

docs/cli/usage/customcf.md

ref #2676
update auth resource format for custom cf

Fix Auth Resource Format in CustomCF

---

docs/cli/plugins/fragments/custom-transformer.md

ref #2813
add back how to add custom transformers and fix broken link for transformer context

Fix Custom Transformer Plugin Info

---

client/src/components.d.ts
docs/guides/api-graphql/query-with-sorting.md

Issue #2883
Updates to GraphQL sorting guide

Updated graphql sort example, addresses #2883

---

client/stencil.config.ts

This + redeploy should do it, hopefully

Don't fingerprint js files.  The goal is for this to fix the white page error

---

client/stencil.config.ts

The white-screen issue was a hosting issue anyway.

Turn fingerprinting back on, because it didn't seem to do anything

---

cspell.json
docs/sdk/api/fragments/android/graphql.md

Update Android AppSync getting started to latest versions

---

docs/lib/auth/fragments/flutter/signin_web_ui/10_cli_setup.md

Aligns signin_web_ui CLI setup with social_signin_web_ui

fix(flutter): aligns signin_web_ui CLI setup with social_signin_web_ui

---

docs/lib/auth/fragments/flutter/signin_web_ui/30_signin.md

Adds apple to list of supported providers

fix(flutter): adds apple to list of supported providers

---

docs/lib/debugging/fragments/android/dev-menu/setup.md
docs/lib/debugging/fragments/android/dev-menu/usage.md

Update Android dev menu docs to since it is no longer enabled by default

---

docs/lib/analytics/fragments/android/escapehatch.md
docs/lib/analytics/fragments/android/getting-started/30_initAnalytics.md
docs/lib/analytics/fragments/android/getting-started/40_record.md
docs/lib/analytics/fragments/android/identifyuser.md
docs/lib/analytics/fragments/android/record.md

For convenience, the Rx Bindings were recently updated to pass Analytics calls through to the regular Java methods. For completeness, show how these calls work when using the Rx facade.

Add RxJava snippets for Android Analytics

---

docs/lib/storage/fragments/js/download.md
docs/lib/storage/fragments/js/remove.md
docs/lib/storage/fragments/js/upload.md

Updated JavaScript storage docs to be more consistent across pages, using async await vs regular promise.

Updated storage docs to use async await

---

docs/lib/storage/fragments/js/upload.md

Updated function to be async

---

docs/lib/graphqlapi/fragments/ios/query-data.md

feat(ios-graphql): add pagination support in API

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md

chore: update android version to 1.16.15

---

Readme.md

fix typo in readme

---

docs/lib/auth/fragments/existing-resources.md

https://github.com/aws-amplify/amplify-ios/issues/1040#issuecomment-786949951

fix(native): note that auth can be used without identity pool

---

docs/lib/project-setup/fragments/android/coroutines/coroutines.md

Coroutines project setup tweaks

---

docs/lib/project-setup/fragments/ios/create-application/20_cocoaPods.md

fixing repeated word in a sentence

---

docs/start/getting-started/fragments/android/add-api.md
docs/start/getting-started/fragments/android/integrate.md

Also fixes one snippet that shows Coroutines API instead of Callbacks.
The Getting Started guide will continue to show the traditional callback
APIs for the time-being.

Cleanup formatting Android Getting Started snippets

---

docs/lib/datastore/fragments/android/data-access/delete-snippet.md
docs/lib/datastore/fragments/android/data-access/query-basic-snippet.md
docs/lib/datastore/fragments/android/data-access/query-pagination-snippet.md
docs/lib/datastore/fragments/android/data-access/query-predicate-multiple-snippet.md
docs/lib/datastore/fragments/android/data-access/query-predicate-or-snippet.md
docs/lib/datastore/fragments/android/data-access/query-predicate-snippet.md
docs/lib/datastore/fragments/android/data-access/query-sort-multiple-snippet.md
docs/lib/datastore/fragments/android/data-access/query-sort-snippet.md
docs/lib/datastore/fragments/android/data-access/save-snippet.md
docs/lib/datastore/fragments/android/data-access/update-snippet.md
docs/lib/datastore/fragments/android/datastore-events.md
docs/lib/datastore/fragments/android/getting-started/60_saveSnippet.md
docs/lib/datastore/fragments/android/getting-started/70_querySnippet.md
docs/lib/datastore/fragments/android/other-methods/10_clear.md
docs/lib/datastore/fragments/android/other-methods/20_start.md
docs/lib/datastore/fragments/android/other-methods/30_stop.md
docs/lib/datastore/fragments/android/real-time/observe-snippet.md
docs/lib/datastore/fragments/android/relational/delete-snippet.md
docs/lib/datastore/fragments/android/relational/query-snippet.md
docs/lib/datastore/fragments/android/relational/save-many-snippet.md
docs/lib/datastore/fragments/android/relational/save-snippet.md
docs/lib/datastore/fragments/android/sync/20-savePredicate.md
docs/lib/datastore/fragments/android/sync/30-savePredicateComparison.md
docs/lib/datastore/fragments/android/sync/40-clear.md
docs/lib/datastore/fragments/android/sync/50-selectiveSync.md

**Updates the Android DataStore code snippets.**
While we are incubating the 0.1.1 release of Core Kotlin, we will keep
the traditional callback-based Kotlin snippets in the documentation.

Android DataStore: Re-introduce callbacks alongside Kotlin Coroutine snippets

---

docs/lib/storage/fragments/android/configureaccess.md
docs/lib/storage/fragments/android/download.md
docs/lib/storage/fragments/android/getting-started/40_upload.md
docs/lib/storage/fragments/android/list.md
docs/lib/storage/fragments/android/remove.md
docs/lib/storage/fragments/android/upload.md

**This updates the Android Storage code snippets.**
While the Core Kotlin module is incubating in Beta, we will *keep* the
Kotlin callback documentation.

Android Storage: Re-introduce Callbacks alongside Kotlin Coroutines

---

docs/lib/predictions/fragments/android/getting-started/50_translate.md
docs/lib/predictions/fragments/android/identify-entity.md
docs/lib/predictions/fragments/android/identify-text.md
docs/lib/predictions/fragments/android/interpret.md
docs/lib/predictions/fragments/android/label-image.md
docs/lib/predictions/fragments/android/text-speech.md
docs/lib/predictions/fragments/android/translate.md

**This updates the Android Predictions code snippets.**
The Core Kotlin library is in 0.1.1. Until it becomes stable, we will
*keep* the callback style code snippets for Kotlin in the documentation.
The Android Predictions content now show a "Kotlin - Callbacks" tab as
well as a "Kotlin - Coroutines (Beta)" tab.

Android Predictions: callback and coroutines snippets together

---

docs/cli/graphql-transformer/directives.md

Minor grammatical correction in cli graphql transformer docs

fix: minor grammatical correction in cli docs

---

docs/lib/graphqlapi/fragments/android/advanced-workflows/10_example.md
docs/lib/graphqlapi/fragments/android/advanced-workflows/20_custom.md
docs/lib/graphqlapi/fragments/android/advanced-workflows/30_nested.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/authz/30_multi.md
docs/lib/graphqlapi/fragments/android/getting-started/50_createtodo.md
docs/lib/graphqlapi/fragments/android/mutate-data.md
docs/lib/graphqlapi/fragments/android/query-data.md
docs/lib/graphqlapi/fragments/android/subscribe-data.md
docs/lib/restapi/fragments/android/delete.md
docs/lib/restapi/fragments/android/fetch.md
docs/lib/restapi/fragments/android/getting-started.md
docs/lib/restapi/fragments/android/getting-started/40_postTodo.md
docs/lib/restapi/fragments/android/update.md

**This update the Android API code snippets.**
While the Core Kotlin 0.1.1 library is incubating in beta, we will keep
the "vanilla" callback code snippets for Kotlin, too.

Android API: Kotlin callbacks alongside coroutines

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md

Amplify Android 1.17.0
Android Gradle Plugin 4.1.2
Core Desugaring Library 1.1.5

Bump Android Dependency Versions

---

docs/lib/graphqlapi/fragments/ios/advanced-workflows/50_interceptor.md

fix: apiPlugin assignment in iOS interceptor

---

docs/lib/auth/fragments/android/hub_events/10_listen_events.md

fix Auth hub events doc

---

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
client/src/amplify-ui/cli-feature-flag/feature-flags.json
docs/lib/graphqlapi/fragments/android/getting-started/40_codegen.md
docs/lib/graphqlapi/fragments/ios/getting-started/40_codegen.md

Added Feature Flags for some of the enhancements made to `amplify-codegen` in the migrated packages. 
This PR needs to be merged after:
- https://github.com/aws-amplify/amplify-cli/pull/6732

Add documentation for supported Feature Flags in Amplify CLI related to codegen

---

docs/guides/functions/dynamodb-from-python-lambda.md

Adds documentation for pipenv to the boto3/dynamodb CRUD example

add pipenv info for installing boto3

---

docs/sdk/api/fragments/ios/graphql.md

*Issue #, if available:* https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/390

chore: Appsync fix the offline optimistic update code fix

---

cspell.json
docs/cli/start/workflows.md

https://github.com/aws-amplify/docs/issues/2503

fix: add missing text for amplify logout

---

docs/cli/start/workflows.md

Describe the option to accept defaults shown

Update workflows.md with init dx change

---

docs/lib/restapi/fragments/ios/getting-started/40_postTodo.md
docs/lib/restapi/fragments/ios/update.md

*Description of changes:* Following getting started guide in iOS API category gives you the following error:
```
Failed APIError: The HTTP response status code is [400].
```
Looks like the error is occurs when the internal code tries to parse the request body [here](https://github.com/expressjs/body-parser/blob/480b1cfe29af19c070f4ae96e0d598c099f42a12/lib/read.js#L121).
The error occurs because the parser is expecting a JSON body. 

chore: Fix API getting started guide for iOS

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/coroutines/coroutines.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md

Amplify Android 1.17.1
Core-kotlin 0.1.2

Bump Android version

---

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
client/src/amplify-ui/cli-feature-flag/feature-flags.json

Add ff docs for secondaryKeyAsGSI

---

docs/guides/functions/configuring-lambda.md

Fixed link function guide and removed "overview" header

---

docs/lib/storage/fragments/js/autotrack.md

*Issue #, if available:* fixes #3031 
*Description of changes:* Updates url and link label. 

fix(lib/storage): Update link to UI Components

---

docs/ui/customization/fragments/react-native/theming.md

*Issue #, if available:* closes #2787
*Description of changes:* Update broken link

fix(ui/reactnative): Update broken link re: custom theming

---

docs/lib/graphqlapi/fragments/js/mutate-data.md

*Issue #, if available:* https://github.com/aws-amplify/docs/issues/3118

fix: Remove extraneous parenthesis in code sample

---

docs/lib/restapi/fragments/ios/fetch.md

(fix:ios): Correct heading and standardize capitalization

---

docs/cli/usage/iam.md

This is required for cleaning up notifications.

Add iam:ListAttachedRolePolicies requirement for CLI

---

docs/lib/analytics/fragments/android/getting-started/12_amplifyConfig.md
docs/lib/analytics/fragments/flutter/getting-started/12_amplifyConfig.md
docs/lib/analytics/fragments/flutter/record.md
docs/lib/analytics/fragments/ios/getting-started/12_amplifyConfig.md
docs/lib/analytics/fragments/native_common/getting-started/common.md
docs/lib/auth/fragments/android/getting_started/12_amplifyConfig.md
docs/lib/auth/fragments/flutter/getting_started/12_amplifyConfig.md
docs/lib/auth/fragments/ios/getting_started/12_amplifyConfig.md
docs/lib/auth/fragments/native_common/getting_started/common.md
docs/lib/storage/fragments/android/getting-started/12_amplifyConfig.md
docs/lib/storage/fragments/flutter/getting-started/12_amplifyConfig.md
docs/lib/storage/fragments/ios/getting-started/12_amplifyConfig.md
docs/lib/storage/fragments/native_common/getting-started/common.md

- update `amplifyconfiguration.json` reference to `amplifyconfiguration.dart` for auth & analytics getting started tutorials
- update reference to `amplifyconfiguration.json`/`amplifyconfiguration.dart` in storage getting started tutorial to be targeted to flutter, ios, and android
- update `amplifyconfiguration.json` reference in analytics "record events" tutorial to `amplifyconfiguration.dart`

fix(flutter): update amplifyconfiguration.json to amplifyconfiguration.dart for flutter

---

cspell.json
docs/lib/menu.json
docs/lib/troubleshooting/fragments/js/upgrading.md
docs/lib/troubleshooting/menu.json
docs/lib/troubleshooting/upgrading.md

N/A
Added a page with upgrade instructions and troubleshooting

docs: Add page to troubleshoot multiple versions of a package

---

docs/lib/graphqlapi/fragments/js/getting-started.md

*Description of changes:* Add missing `graphqlOperation` in import statements

Add missing graphqlOperation

---

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
client/src/amplify-ui/cli-feature-flag/feature-flags.json

add ff for appsync gql permissions

---

.github/workflows/spellcheck.yml
.github/workflows/test.yml
Readme.md
client/src/docs-ui/repo-actions/__snapshots__/repo-actions.spec.ts.snap
client/src/docs-ui/repo-actions/repo-actions.tsx
docs/cli/teams/sandbox.md
docs/cli/teams/shared.md
docs/guides/hosting/fragments/gatsby.md
docs/guides/hosting/fragments/git-based-deployments.md
docs/guides/hosting/fragments/gridsome.md
docs/guides/hosting/fragments/nextjs.md
docs/guides/hosting/fragments/nuxt.md

Courtesy of @oieduardorabelo -- thank you!  We plan on performing this migration tomorrow 😄 

fix(2985): Migrate Use of “Master” to “Main” in Docs

---

docs/lib/auth/fragments/js/customui.md
docs/ui/customization/fragments/react-native/theming.md

Also, React Native documentation doesn't randomly include React docs
Fixes #3126!

(update): Auth documentation now refers to current version of UI components

---

docs/lib/restapi/fragments/flutter/authz.md
docs/start/getting-started/fragments/flutter/integrate.md
docs/start/getting-started/fragments/flutter/setup.md

Describes hot reload and hot start and isConfigured getter for Amplify-Flutter. Also fixes incorrect key for apiKey param in amplifyconfiguration.dart example.

fix(flutter): Describes hot reload and hot start and isConfigured getter

---

docs/cli/graphql-transformer/key.md

Added multiple GSI updates documentation & troubleshooting guide

---

.github/workflows/build.yml
.github/workflows/test.yml

🚨  **ACHTUNG**🚨 This may require some repo settings fiddling after merge.
*Description of changes:* To ensure the docs site has parseable content, run the build on every check-in after spellcheck.

Run build on any docs change

---

capi/src/init-node/index.ts

This change ensures that the build process exits upon error.
This is accomplished by wrapping a promise used in an async function that throws an error in a try/catch statement.

Wrap async build function in try/catch

---

.github/workflows/build.yml
.github/workflows/test.yml

This PR bumps the version of Node.js used in our build process to the current Node.js LTS version (14.x).

Update Node version to 14.x

---

docs/lib/datastore/fragments/android/sync/40-clear.md

fix: kotlin coroutine code snippet for datastore clear local data

---

docs/lib/graphqlapi/fragments/graphql-from-node.md

Added details on how to add GraphQL API permission

---

docs/lib/project-setup/fragments/native_common/prereq/common_header.md
docs/start/getting-started/fragments/common/prereq.md
docs/start/getting-started/fragments/ios/setup.md

https://github.com/aws-amplify/amplify-cli/pull/7214
Readme update:
https://github.com/aws-amplify/amplify-cli/pull/7263
- Update required Node.js minimum version references to coincide with recent CLI updates. (10.x -> 12.x)

update(node version): update min. required Node.js version references

---

docs/lib/auth/fragments/js/getting-started-steps-basic-auth.md
docs/lib/datastore/fragments/js/getting-started/30_platformIntegration.md
docs/start/getting-started/fragments/reactnative/getting-started-steps-ui.md

- Adding additional dependency needed for React Native
Do not merge until related PR has been released: https://github.com/aws-amplify/amplify-js/pull/8250

add @react-native-async-storage/async-storage as dependency

---

docs/lib/auth/fragments/flutter/user_attributes/10_fetch_attributes.md
docs/lib/auth/fragments/flutter/user_attributes/20_update_user_attribute.md
docs/lib/auth/fragments/flutter/user_attributes/30_confirm_attribute.md
docs/lib/auth/fragments/flutter/user_attributes/40_resend_code.md

**NOTE: This should not be merged until amplify-flutter 1.0.5 is released**
- Add documentation for [newly added](https://github.com/aws-amplify/amplify-flutter/pull/533) user attributes for Flutter Auth

Add docs for flutter auth user attributes

---

docs/start/getting-started/fragments/next/hosting.md

[Hotfix] Update next.js hosting instructions to remove the upvote SSR on Amplify console language

---

docs/lib/auth/fragments/js/emailpassword.md

#2448
Adding clarification for the customer to know what exactly Cognito returns upon authenticating a user.

docs(improving dx): in response to an issue, updated documentation to inform customers of a return field

---

docs/console/data/content-management.md

N/A
Content management feature is already GA.
https://aws.amazon.com/blogs/mobile/introducing-aws-amplify-content-management-a-visual-way-to-browse-app-data/

Remove Preview Warning re: Admin UI Content Management

---

docs/cli/graphql-transformer/resolvers.md

docs: add doc about custom resources and parameters

---

docs/cli/reference/files.md

Closes #2437
added documentation for `amplify/backend/backend-config.json` on https://docs.amplify.aws/cli/reference/files

docs(files): document backend-config.json

---

docs/cli/auth/groups.md

Minor grammatical fix for CLI User groups language

[Amplify CLI] Changed whom to who for groups.md

---

docs/lib/analytics/fragments/flutter/getting-started/10_preReq.md
docs/lib/auth/fragments/flutter/getting_started/10_preReq.md
docs/lib/graphqlapi/fragments/flutter/getting-started/10_preReq.md
docs/lib/project-setup/fragments/flutter/create-application/10_createProject.md
docs/lib/restapi/fragments/flutter/getting-started/10_preReq.md
docs/lib/storage/fragments/flutter/getting-started/10_preReq.md

*Issue #, if available:* [Instructions for Flutter 2.2.0 compatibility with Amplify](https://github.com/aws-amplify/docs/issues/3258)
*Description of changes:* Add instructions to disable sound null safety

Flutter 2.2.0 Instructions

---

docs/lib/storage/fragments/js/download.md

https://github.com/aws-amplify/amplify-js/issues/4734
Adding a section for add download progress tracking. 

adding page for download progress monitoring

---

.github/PULL_REQUEST_TEMPLATE.md

- update PR template with correct license reference.

chore(repo): update PR template with correct license

---

docs/lib/storage/fragments/android/download.md

PM-Update download.md

---

docs/lib/datastore/fragments/native_common/setup-auth-rules.md

*Issue #, if available:* The name of a link is wrong
*Description of changes:* Just replaced the name of the link with the correct one

fixing link name

---

docs/start/getting-started/fragments/angular/setup.md

Fix typo
Fix minor typo in IE 11 section

Fix Typo in IE 11 Support Section

---

docs/cli/usage/menu.json
docs/cli/usage/uninstall.md
docs/cli/usage/upgrade.md

closes #3178, #2892
Adding documentation for upgrading the pkg cli as well as uninstall instructions for both the pkg cli and npm cli

upgrade and uninstall docs for pkg cli

---

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
client/src/amplify-ui/cli-feature-flag/feature-flags.json
docs/cli/reference/feature-flags.md

Added a FF : breakcirculardependency 
PR: https://github.com/aws-amplify/amplify-cli/pull/6968

fix: adds circular dependency FF

---

docs/lib/restapi/fragments/existing-resources.md

These are valid for both iOS and Android.
*Issue #, if available:* no open issue identified
*Description of changes:*. add all currently implemented authentication modes to the list of REST authorization types.  (As an aside, these are actually authentication types.)

Include all implemented authorization types

---

docs/sdk/auth/fragments/ios/how-it-works.md

chore: Add user state information for AWSMobileClient

---

docs/lib/project-setup/fragments/android/create-application/40_verifyAmplifyLibraries.md

add clear directions to extend the class from `Application` class for java and kotlin

chore: update new class config steps

---

docs/cli/reference/files.md

Fixed typo added in PR #3254 
The document has the random ``` MarkDown symbol in the end of the line.

Removed typo

---

client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
client/src/amplify-ui/cli-feature-flag/feature-flags.json

Add docs for FF of timestamp fields. Related PR: https://github.com/aws-amplify/amplify-cli/pull/7273

docs: add docs for FF of timestamp fields

---

docs/lib/auth/fragments/js/emailpassword.md

Adding description on Sign-out documentation

SignOut token revocation description

---

docs/lib/auth/fragments/js/emailpassword.md

Making clear the fact is with Cognito UserPools

Small change on SignOut

---

docs/lib/troubleshooting/fragments/flutter/upgrading.md
docs/lib/troubleshooting/upgrading.md

- Add a troubleshooting section for flutter to explain common upgrade issues
The new troubleshooting info will be needed with this PR (https://github.com/aws-amplify/amplify-flutter/pull/589) to specify an amplify iOS version.

Add flutter troubleshooting/upgrades section

---

client/src/docs-ui/footer/__snapshots__/footer.spec.ts.snap
client/src/docs-ui/footer/footer.tsx

Updates the year in the footer to be dynamic and always match the current year.

Dynamically update the year in the footer

---

docs/cli/teams/commands.md
docs/cli/usage/permissions-boundary.md

fix: nits from perm bound changes

---

docs/lib/analytics/fragments/ios/getting-started/20_installLib.md
docs/lib/auth/fragments/ios/getting_started/20_installLib.md
docs/lib/datastore/fragments/ios/getting-started/20_installLib.md
docs/lib/graphqlapi/fragments/android/mutate-data.md
docs/lib/graphqlapi/fragments/flutter/mutate-data.md
docs/lib/graphqlapi/fragments/ios/getting-started/20_installLib.md
docs/lib/graphqlapi/fragments/ios/getting-started/30_initapi.md
docs/lib/graphqlapi/fragments/ios/getting-started/50_createtodo.md
docs/lib/graphqlapi/fragments/ios/mutate-data.md
docs/lib/graphqlapi/mutate-data.md
docs/lib/restapi/fragments/ios/getting-started/20_installLib.md
docs/lib/storage/fragments/ios/getting-started/20_installLib.md

- Adds SPM steps under API category
- Adds reference to create and delete mutation in the section "create, update, delete data" (renamed from "create, update")
1. iOS Changes
2. Android
3. Flutter

fix(API): iOS SPM and mutations

---

docs/cli/storage/overview.md

https://github.com/aws-amplify/amplify-cli/issues/7567
Updated storage s3 docs to reflect the current CLI walkthrough. Also provided more detail on exactly what resources are accessible under different configurations

update s3 docs to reflect current walkthrough and give more detail on expected behavior

---

docs/cli/storage/overview.md

fix formatting issue

---

docs/lib/datastore/fragments/flutter/data-access/query-pagination-snippet.md

Add 
```
import 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart';
```
to the Pagination code

clarify datastore doc on pagination

---

docs/lib/auth/fragments/existing-resources.md

Document how to include Hosted UI configuration in config file

---

docs/lib/auth/fragments/existing-resources.md
docs/lib/storage/fragments/existing-resources.md

fix: use import command instead of editing config files

---

docs/lib/auth/fragments/flutter/user_attributes/20_update_user_attribute.md

Adds batch update method docs for attribute management.

fix(flutter): adds batch update method docs for attribute management

---

docs/cli/auth/admin.md

https://github.com/aws-amplify/amplify-ios/issues/1103
This PR updates the Admin Queries API example to include platform specific examples using Amplify. It mostly replicates the existing JS code snippet in the different platform languages

fix(CLI): admin queries API with updated code snippets

---

docs/lib/auth/fragments/flutter/access_credentials/10_fetchAuthSession.md
docs/lib/auth/fragments/flutter/password_management/10_reset_password.md
docs/lib/auth/fragments/flutter/password_management/20_confirm_reset_password.md
docs/lib/auth/fragments/flutter/password_management/30_change_password.md
docs/lib/auth/fragments/flutter/signout/10_local_signout.md
docs/lib/auth/fragments/flutter/user_attributes/20_update_user_attribute.md

_Issue #, if available:_ n/a
- update flutter authentication docs for null safety
- update other issues in code snippets that were found during the updates for null safety

chore(flutter/auth): update flutter auth docs for null safety

---

docs/start/getting-started/fragments/flutter/integrate.md

Update Flutter tutorial snippets for null safety

chore(flutter): update tutorial snippets for null safety

---

docs/cli/function/env-vars.md
docs/cli/function/menu.json
docs/cli/function/secrets.md

https://github.com/aws-amplify/amplify-cli/pull/7529
Adds docs for upcoming release of Function secrets and environment variables. Draft because these changes shouldn't be merged until the release.

feat: func env vars and secrets docs

---

cspell.json
docs/lib/datastore/fragments/android/setup-auth-rules/10_multiauth-snippet.md
docs/lib/datastore/fragments/ios/setup-auth-rules/10_multiauth-snippet.md
docs/lib/datastore/fragments/native_common/setup-auth-rules.md

Multiauth documentation for native. Needs code snippet from iOS.

feat(native):adding multiauth docs for native

---

.github/stale.yml

- chore(stale.yml): update exemptLabels and *only* act on issues, not PRs

chore(stale.yml): update exemptLabels and *only* act on issues, not PRs

---

docs/lib/analytics/fragments/android/identifyuser.md

Adding information about how to provide user attributes when invoking identifyUser in Android.

chore(android): update identifyUser documentation

---

docs/guides/functions/configuring-lambda.md

Code Snippets incorrectly showed that the memory size should be nested in LambdaFunction.
Changed snippet so that the properties changed are nested in the `"Properties"` object.

Updated Code snippets for Lambda Functions

---

docs/ui/auth/fragments/web/authenticator.md

Remove closing tag with no corresponding opening tag (detected during Next.js migration process)

---

docs/guides/hosting/fragments/nextjs.md

Issue #, if available:
closes #3395 
Add expression to avoid eslint error

Update hosting/nextjs document to pass eslint

---

docs/cli/usage/iam.md

To publish Amplify CLI requires amplify:GetBranch to publish

Added policy action for Amplify

---

client/src/docs-ui/page/redirects.ts
cspell.json
docs/cli/cli.md
docs/cli/graphql-transformer/config-params.md
docs/cli/graphql-transformer/directives.md
docs/cli/graphql-transformer/model.md
docs/cli/graphql-transformer/resolvers.md
docs/cli/graphql-transformer/searchable.md
docs/lib/graphqlapi/fragments/js/getting-started.md
docs/ui-legacy/auth/fragments/react/tutorial.md

_Notes:_
changes made in `docs/`
cc @jakeburden @tjleing  @mauerbac 

chore(main): rename ES to OpenSearch

---

docs/guides/functions/configuring-lambda.md

Fixing wrong links for function guides

---

docs/lib/datastore/fragments/flutter/sync/50-selectiveSync.md
docs/lib/datastore/fragments/native_common/sync.md

https://github.com/aws-amplify/amplify-flutter/issues/298
This PR adds documentation for Flutter selective sync

feat(flutter): Add docs for selective sync

---

cspell.json
docs/cli/graphql-transformer/directives.md

Updated with community contribution of @algolia directive plugin

---

docs/cli/function/env-vars.md
docs/cli/function/secrets.md

Added CLI recovery information when customers use environment variables & secrets for git based workflows

---

docs/lib/datastore/fragments/js/setup-auth-rules/20_function-auth-snippet.md
docs/lib/datastore/fragments/native_common/setup-auth-rules.md
docs/lib/graphqlapi/fragments/android/authz/22_lambda.md
docs/lib/graphqlapi/fragments/ios/authz/22_lambda.md
docs/lib/graphqlapi/fragments/js/authz.md
docs/lib/graphqlapi/fragments/native_common/authz/common.md

[WIP] feat: add lambda auth docs

---

cspell.json
docs/lib/geo/fragments/js/maps.md

Add docs for adding maps to javascript html website

feat(@aws-amplify/geo): Add docs for adding maps to html website

---

docs/lib/auth/fragments/native_common/signin_web_ui/common.md

Specifies OAuth Flow for native

fix: Specifies OAuth Flow for native

---

client/src/amplify-ui/cli-feature-flag/feature-flags.json

For useExperimentalPipelinedTransformer: remove deprecationDate and change defaultNewProject to false.

fix useExperimentalPipelinedTransformer feature flag

---

docs/lib/geo/fragments/js/maps.md

- Remove unnecessary import in display map code sample

fix: remove unnecessary import in display map section

---

docs/lib/geo/fragments/js/getting-started.md

_Description of changes:_ adding blurb for Amplify Geo

add blurb for Geo category in getting started page

---

docs/lib/geo/fragments/js/getting-started.md
docs/lib/geo/fragments/js/maps.md
docs/lib/geo/fragments/js/search.md

_Description of changes:_ Added details on where to find region information and added placeholder for region to avoid confusion

Add region instruction

---

docs/lib/geo/fragments/js/maps.md

_Description of changes:_ add missing instructions on adding import statements

Add missing import instructions

---

docs/lib/graphqlapi/fragments/android/advanced-workflows/20_custom.md
docs/lib/graphqlapi/fragments/android/advanced-workflows/30_nested.md
docs/lib/graphqlapi/fragments/android/advanced-workflows/40_multiple.md

Fixes several critical errors in current documentation.

fix Android graphQL advanced flow documentation

---

docs/lib/auth/device_features.md
docs/lib/auth/fragments/common/device_features/common.md
docs/lib/auth/fragments/flutter/device_features/10_rememberDevice.md
docs/lib/auth/fragments/flutter/device_features/20_forgetDevice.md
docs/lib/auth/fragments/flutter/device_features/30_fetchDevice.md

- Adds documentation for the device features API for Flutter

feat(auth): Device Features for Flutter

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md

Update docs to use the latest version of Amplify library.

[Android] update android docs to use v1.24.0

---

docs/lib/geo/fragments/js/maps.md
docs/lib/geo/fragments/js/search.md

fix: remove unnecessary map import, add AmplifyGeocoderAPI documentation

---

docs/lib/auth/fragments/flutter/signin_web_ui/20_platform_specific_setup.md

- https://github.com/aws-amplify/amplify-flutter/issues/677
- Update instructions for `AndroidManifest.xml`

Update AndroidManifest instructions

---

docs/lib/auth/fragments/android/getting_started/10_preReq.md
docs/lib/datastore/fragments/android/getting-started/10_preReq.md
docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md
docs/lib/datastore/fragments/android/getting-started/40_codegen.md
docs/lib/datastore/fragments/native_common/setup-auth-rules.md
docs/lib/graphqlapi/fragments/android/getting-started/10_preReq.md
docs/lib/graphqlapi/fragments/native_common/advanced-workflows/common.md
docs/lib/predictions/fragments/android/getting-started/20_preReq.md
docs/lib/predictions/fragments/android/getting-started/50_translate.md
docs/lib/predictions/fragments/android/translate.md
docs/lib/project-setup/fragments/android/create-application/10_createProject.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/10_preReq.md
docs/lib/restapi/fragments/native_common/authz/common.md
docs/lib/storage/overview.md
docs/start/getting-started/fragments/android/integrate.md
docs/start/getting-started/fragments/android/setup.md

_Description of changes:_ Fixed various typos in the Android Getting Started and Libraries docs.

Fixed typos in android docs

---

docs/lib/auth/fragments/android/signin_web_ui/20_platform_specific_setup.md
docs/lib/auth/fragments/android/user_attributes/20_update_user_attribute.md
docs/lib/datastore/fragments/android/data-access/save-snippet.md
docs/lib/datastore/fragments/android/getting-started/60_saveSnippet.md
docs/lib/graphqlapi/fragments/android/advanced-workflows/40_multiple.md
docs/lib/graphqlapi/fragments/android/query-data.md
docs/lib/storage/fragments/android/upload.md
docs/start/getting-started/fragments/android/integrate.md

_Description of changes:_ Fix errors in the code displayed in the Android Getting Started and Libraries docs.

Fix errors in Android docs code blocks

---

docs/cli/reference/files.md

- https://github.com/aws-amplify/amplify-cli/issues/7591 adds dart file to code block
- https://github.com/aws-amplify/docs/pull/3330 updates pragma
Adds a couple files that are currently added to gitignore from the CLI, also updates pragma from gitignore adjustments made. 
This PR should not be merged before #3330

chore(cli): update gitignore contents

---

docs/lib/geo/fragments/js/maps.md

_Description of changes:_chore(geo): update new script tags for geo

chore(geo): update new script tags for geo

---

docs/cli/start/install.md

update min node version for cli

---

next.config.js
src/components/Menu/FilterSelect/index.tsx

Fix `a` vs `an` grammar, more terse text; thank you @renebrandel!

---

src/components/Layout/index.tsx
src/pages/index.tsx

Adds `<meta name="description" content="..." />` tags to the home page and Layout component.

Add meta description tags

---

src/components/Menu/index.tsx
src/components/Page/index.tsx
src/components/Page/styles.tsx
src/pages/ChooseFilterPage.tsx

This reverts commit 56aa3f3728c4bce243c08532720ecf25bd395ed6.
Reverts a PR causing a broken build.

Revert "Use menuIsOpen state to determine the width of content (#3498)"

---

src/directory/directory.js

Fixes the issue with the SSR link

Fix SSR route

---

docs/lib/geo/fragments/js/maps.md
docs/lib/geo/fragments/js/search.md
src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/geo/js/search.mdx

- Updated search docs to use `createAmplifyGeocoder`

chore: updated search to use createAmplifyGeocoder

---

src/components/Menu/index.tsx
src/components/Page/index.tsx
src/components/Page/styles.tsx
src/pages/ChooseFilterPage.tsx

Will allow us to revert #3502!
Probably not merging until tomorrow for my sanity's sake

Fix sidebar hooks on CFP pages

---

src/fragments/lib/auth/android/signin_web_ui/20_platform_specific_setup.mdx
src/fragments/sdk/auth/android/hosted-ui.mdx

Add queries section for ACTION_VIEW to manifest for API 30+

---

src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/geo/js/search.mdx

- Add documentation on importing css files for maps and search
- Add note about package bundlers needing to correctly handle css files

chore: add css imports to maps/search documentation

---

package.json
yarn.lock

Bump package versions

---

docs/lib/pubsub/fragments/js/getting-started.md
src/fragments/lib/pubsub/js/getting-started.mdx

https://github.com/aws-amplify/amplify-js/issues/7103
Documenting [a recent update](https://github.com/aws-amplify/amplify-js/pull/7256) made by one of our open source contributors. Their PR addresses the following Amplify JS issue: https://github.com/aws-amplify/amplify-js/issues/7103
**NOTE: This PR should _NOT_ be merged until we have successfully shipped our next release (scheduled for 9/8/21)**

feat: add PubSub provider removal doc

---

src/directory/directory.js
src/fragments/lib/datastore/flutter/other-methods/10_clear.mdx
src/fragments/lib/datastore/flutter/other-methods/15_start.mdx
src/fragments/lib/datastore/flutter/other-methods/20_start.mdx
src/fragments/lib/datastore/flutter/other-methods/30_stop.mdx
src/fragments/lib/datastore/native_common/other-methods.mdx
src/pages/lib/datastore/other-methods/q/platform/[platform].mdx

Add "Other methods" section to amplify-flutter DataStore documentation.
----

chore: Add docs of Flutter DataStore start and stop APIs

---

docs/cli/geo/maps.md
docs/cli/geo/search.md
src/pages/cli/geo/maps.mdx
src/pages/cli/geo/search.mdx

- Pricing plan service link moved before the code snippets
- Modified the pricing plan walkthrough based on feedback
- Update `HERE` data provider naming

fix(cli-docs): update geo pricing plan and HERE data provider

---

src/fragments/lib/graphqlapi/flutter/advanced-workflows/50_interceptor.mdx
src/fragments/lib/graphqlapi/flutter/authz/10_userpool.mdx
src/fragments/lib/graphqlapi/flutter/authz/20_oidc.mdx
src/fragments/lib/graphqlapi/flutter/authz/21_oidc.mdx
src/fragments/lib/graphqlapi/flutter/authz/22_lambda.mdx
src/fragments/lib/graphqlapi/flutter/authz/2X_add_plugin.mdx
src/fragments/lib/graphqlapi/flutter/authz/30_multi.mdx
src/fragments/lib/graphqlapi/native_common/authz/common.mdx
src/pages/lib/graphqlapi/authz/q/platform/[platform].mdx

- Updates the OIDC/Lambda docs to the latest format

chore(flutter): Update OIDC/Lambda docs to new format

---

src/directory/directory.js
src/pages/cli/migration/cli-auth-signup-changes.mdx

Create CLI Auth Signup Changes page

---

.github/workflows/build.yml

Update node options to be in string

Update node options memory in GitHub workflow

---

.github/workflows/build.yml

Moves the NODE_OPTIONS env variable to it's own line

Update node options fix in GitHub workflow

---

src/pages/cli/graphql-transformer/searchable.mdx

- added documentation for configuring different open search instance types in a multi environment setup

documentation for opensearch multi env configuration

---

docs/lib/analytics/fragments/android/getting-started/20_installLib.md
docs/lib/auth/fragments/android/getting_started/20_installLib.md
docs/lib/datastore/fragments/android/getting-started/20_installLib.md
docs/lib/datastore/fragments/android/sync/10-installPlugin.md
docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
docs/lib/graphqlapi/fragments/android/getting-started.md
docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
docs/lib/predictions/fragments/android/getting-started/30_installLib.md
docs/lib/project-setup/fragments/android/coroutines/coroutines.md
docs/lib/project-setup/fragments/android/create-application/20_gradle.md
docs/lib/project-setup/fragments/android/rxjava/rxjava.md
docs/lib/restapi/fragments/android/getting-started/20_installLib.md
docs/lib/storage/fragments/android/getting-started/20_installLib.md
docs/start/getting-started/fragments/android/setup.md
src/fragments/lib/analytics/android/getting-started/20_installLib.mdx
src/fragments/lib/auth/android/getting_started/20_installLib.mdx
src/fragments/lib/datastore/android/getting-started/20_installLib.mdx
src/fragments/lib/datastore/android/sync/10-installPlugin.mdx
src/fragments/lib/graphqlapi/android/authz/21_oidc.mdx
src/fragments/lib/graphqlapi/android/getting-started.mdx
src/fragments/lib/graphqlapi/android/getting-started/20_installLib.mdx
src/fragments/lib/predictions/android/getting-started/30_installLib.mdx
src/fragments/lib/project-setup/android/coroutines/coroutines.mdx
src/fragments/lib/project-setup/android/create-application/20_gradle.mdx
src/fragments/lib/project-setup/android/rxjava/rxjava.mdx
src/fragments/lib/restapi/android/getting-started/20_installLib.mdx
src/fragments/lib/storage/android/getting-started/20_installLib.mdx
src/fragments/start/getting-started/android/setup.mdx

Bump Amplify Android version to 1.27.0 and Core Kotlin version to 0.11.0.

 chore(Android): bump Amplify Android version

---

src/fragments/lib/geo/js/maps.mdx

- Removed unnecessary import from display map docs

chore: remove unnecessary import AmplifyMaplibreRequest

---

.github/workflows/build.yml

The GitHub Build workflow had invalid indentation

Fix indentation in Build workflow

---

src/fragments/lib/datastore/flutter/getting-started/50_codegenCli.mdx
src/fragments/lib/geo/js/search.mdx
src/fragments/lib/project-setup/native_common/prereq/flutter_null_safety.mdx
src/fragments/start/getting-started/flutter/integrate.mdx
src/fragments/ui-legacy/angular/overview.mdx
src/fragments/ui-legacy/auth/react-native/authenticator.mdx
src/fragments/ui-legacy/auth/react/authenticator.mdx
src/fragments/ui-legacy/auth/react/tutorial.mdx
src/fragments/ui/auth/react-native/authenticator.mdx
src/pages/cli/graphql-transformer/auth.mdx
src/pages/cli/storage/import.mdx

Fixes some links by using absolute paths and removing `.md`

Updates to fix a few links

---

src/fragments/lib/geo/js/existing-resources.mdx
src/fragments/lib/geo/js/maps.mdx

- `AmazonLocationServices` => `AmazonLocationService`

chore(geo): update AmazonLocationService to singular

---

src/fragments/lib/geo/js/maps.mdx

- Update all the Geo Maps CDN resources with the newest versions

chore(geo): update CDN resources to latest versions for GA

---

src/fragments/lib/geo/js/maps.mdx

Add note about having a div with id of map or else the rendering will fail.

docs(geo): add note about having <div id="map"> in the DOM

---

src/fragments/lib/geo/js/maps.mdx

fix: update maplibreAmplify reference to AmplifyMapLibre

---

src/fragments/lib/predictions/ios/identify-text.mdx

_Issue #, if available:_ https://github.com/aws-amplify/amplify-ios/issues/1098

chore: Change the prediciton code with simpler logic

---

src/pages/console/data/content-management.mdx

To be published Oct 29, 2021
Updated documentation with new features - AWS Amplify Admin UI now allows generating seed data with Faker (https://faker.readthedocs.io/en/master/), and downloading data to a CSV file. This makes creating and managing your data in Amplify easier, and allows for more realistic demo data that is easily shareable. 

[Do not merge] Updated docs with further Admin UI data features

---

src/fragments/start/getting-started/vanillajs/hosting.mdx

_Issue#:_  #3237 
_Description of changes:_ Added a brief information about why the error occurs and  linked `DistributionDir` with its specification

Adding a note on DistributionDir

---

src/fragments/start/getting-started/flutter/integrate.mdx
src/fragments/start/getting-started/flutter/setup.mdx

- Update flutter getting started guide to use example app

chore: update flutter getting started guide with observeQuery

---

src/fragments/sdk/storage/ios/transfer-utility.mdx

_Description of changes:_ Fixed the force unwrapping code in the S3 Transfer Utility code.

chore: Fix the force unwrap inside iOS Storage

---

src/components/FeatureFlags/feature-flags.json

_Issue #, if available:_ https://github.com/aws-amplify/amplify-cli/pull/7024
_Description of changes:_ This commit documents a new set of feature flags related to region mapping.

Add region mapping feature flags

---

src/fragments/lib/client-configuration/js/js-configuration.mdx
src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/geo/js/search.mdx

- docs(geo): add info about map.remove
- docs(geo): add import in snippets
- docs(geo): all long, lat comments to reinforce order
- docs(geo): add geo to js configuration page
- docs(geo): add link to CLI search index provisioning

docs(geo): updates from DA feedback

---

src/fragments/start/getting-started/ios/add-api.mdx

Fix: iOS Getting Started Formatting Typo

---

src/pages/cli/graphql-transformer/overview.mdx
src/pages/cli/usage/headless.mdx

https://github.com/aws-amplify/amplify-cli/pull/8144
Adds documentation for upcoming CLI feature to allow destructive schema changes.
Ready for review, but marked as a draft to prevent merging before the feature is released.

feat: docs for destructive schema updates

---

src/fragments/guides/api-graphql/js/image-and-file-uploads.mdx
src/fragments/lib/datastore/native_common/conflict.mdx
src/fragments/lib/datastore/native_common/setup-env-cli.mdx
src/fragments/lib/graphqlapi/js/getting-started.mdx
src/fragments/lib/graphqlapi/native_common/authz/common.mdx
src/fragments/lib/graphqlapi/native_common/getting-started/common.mdx
src/fragments/ui-legacy/auth/react/tutorial.mdx
src/pages/cli/usage/monorepo.mdx
src/pages/guides/api-graphql/building-a-form-api/q/platform/[platform].mdx
src/pages/guides/api-graphql/lambda-resolvers/q/platform/[platform].mdx
src/pages/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/[platform].mdx

Update docs to reflect the new improved graphql add and update api workflow.

improved graphql add and update api workflow (MERGE ONLY when new api workflow goes live)

---

src/fragments/lib/storage/flutter/getting-started/20_installLib.mdx

_Issue #, if available:_ N/A
Import request for amplify was incorrect.

fixed incorrect import statement for storage/flutter

---

src/directory/directory.js

removed superfluous nav items

---

src/fragments/lib/auth/ios/access_credentials/10_fetchAuthSession.mdx

_Issue #, if available:_ https://github.com/aws-amplify/amplify-ios/issues/1447
_Description of changes:_ Added extra session to show how to get guest credentials

chore: Chage the documentation to show guest fetchauthsession

---

src/fragments/lib/auth/common/social_signin_web_ui/configure_auth_category.mdx
src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx

Added updates to flutter quickstart guide for social sign in to clarify the direcotry of the info.plist file, and provide steps for retrieving the web sign in URL using the CLI

Social sign in - flutter quickstart changes

---

src/directory/directory.js

Remove /console/storage/develop from navigation

---

src/fragments/ui/vue/installation.mdx

Updated install information for Vue 2

Update Vue 2 Install Information

---

src/directory/directory.js
src/fragments/lib/geo/existing-resources.mdx
src/fragments/lib/geo/ios/dev-preview-callout.mdx
src/fragments/lib/geo/ios/existing-resources.mdx
src/fragments/lib/geo/ios/getting_started/10_pre_req.mdx
src/fragments/lib/geo/ios/getting_started/20_cli_resources.mdx
src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
src/fragments/lib/geo/ios/getting_started/40_init_geo.mdx
src/fragments/lib/geo/ios/maps/10_install_adapter.mdx
src/fragments/lib/geo/ios/maps/20_display_map.mdx
src/fragments/lib/geo/ios/maps/30_styles.mdx
src/fragments/lib/geo/ios/search/10_search_by_text.mdx
src/fragments/lib/geo/ios/search/20_search_by_coordinates.mdx
src/fragments/lib/geo/native_common/getting_started/common.mdx
src/fragments/lib/geo/native_common/maps/common.mdx
src/fragments/lib/geo/native_common/search/common.mdx
src/pages/lib/geo/existing-resources/q/platform/[platform].mdx
src/pages/lib/geo/getting-started/q/platform/[platform].mdx
src/pages/lib/geo/maps/q/platform/[platform].mdx
src/pages/lib/geo/search/q/platform/[platform].mdx

Add iOS Geo Category Maps and Search Developer Preview

feat(iOS): Add iOS Geo Category Maps and Search Developer Preview

---

src/pages/cli/usage/export-to-cdk.mdx

Docs for multi-account and multi-region export deployments

---

src/fragments/lib/in-app-messaging/js/prerequisites.mdx

ensured all changes are carried over to the In-app-messaging branch

all changes applied to pre-requisites page

---

src/fragments/lib/in-app-messaging/js/prerequisites.mdx

NA
reformat manual `aws-exports` snippet

reformat aws-exports snippet to match expectation

---

src/pages/cli/graphql/authorization-rules.mdx

fix: missing "]"

---

cspell.json
src/pages/cli/restapi/restapi.mdx

1. REST API : Description of these user types below - Added User Groups
2. REST API :  Added example "Create REST API and restrict specific routes to specific user groups"

Rest API User Groups

---

src/directory/directory.js
src/fragments/lib/geo/android/escapehatch.mdx
src/pages/lib/geo/escapehatch/q/platform/[platform].mdx

Added instructions for accessing escape hatch for Geo plugin.

[Android] add geo escape hatch instructions

---

src/fragments/lib/geo/js/maps.mdx

chore(geo): add note about how to create a map with a classname

---

src/pages/cli/graphql/data-modeling.mdx

added docs for missing queryField in GQL Transformer v2

---

src/fragments/lib/datastore/native_common/sync.mdx

Added a clarification on datastore starting after any operation runs. Trying to resolve this doc issue https://github.com/aws-amplify/docs/issues/3445

Added clarification on when DS starts sync

---

src/directory/directory.js
src/fragments/lib/geo/ios/escapehatch.mdx
src/pages/lib/geo/escapehatch/q/platform/[platform].mdx

N/A
Added documentation for iOS Geo escape hatch.

feat(iOS): Add escape hatch documentation for Geo

---

cspell.json
src/fragments/lib/geo/android/getting_started/20_cli_resources.mdx
src/fragments/lib/geo/android/getting_started/30_install_lib.mdx
src/fragments/lib/geo/android/getting_started/40_init_geo.mdx

Addressed issues that caused minor friction while following the documentation for geo setup guide.

[Android] Add CLI steps for geo

---

cspell.json
src/fragments/cli/gqlv2callout.mdx
src/pages/cli/graphql/data-modeling.mdx
src/pages/console/data/relationships.mdx
src/pages/lib/datastore/relational/q/platform/[platform].mdx

GQL v2 hasOne-hasMany update

---

src/fragments/lib/graphqlapi/existing-resources.mdx
src/fragments/lib/graphqlapi/js/create-or-re-use-existing-backend.mdx

feat: add docs for Custom Domains for all platforms

---

src/pages/cli/usage/export-to-cdk.mdx

The install command had a typo in it

Typo in install command

---

src/fragments/lib/auth/js/getting-started.mdx
src/fragments/ui/auth/react/withauthenticator.mdx

_Issue #, if available:_ https://github.com/aws-amplify/amplify-ui/issues/913

Update Authentication Getting Started to use new UI components

---

src/fragments/lib/auth/js/react-native-withoauth.mdx
src/fragments/lib/auth/js/start.mdx
src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
src/fragments/start/getting-started/reactnative/getting-started-steps-ui.mdx
src/fragments/ui-legacy/auth/react-native/overview.mdx
src/fragments/ui-legacy/auth/react/tutorial.mdx
src/fragments/ui-legacy/react-native/overview.mdx
src/fragments/ui/react-native/installation.mdx

https://github.com/aws-amplify/amplify-js/issues/6845
https://github.com/aws-amplify/amplify-js/pull/9158

add @react-native-picker/picker to aws-amplify-react-native install steps

---

src/components/InternalLink/index.tsx

_Issue #, if available:_ #3858
- update logic to form the url to always put anchor links at the end

fix: broken named anchor links

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx

Added link to UI components. Fixed link for the example app.

---

src/pages/cli/geo/geofencing.mdx

Add documentation for `amplify geo populate` (still in developer preview). Related feature PR: https://github.com/aws-amplify/amplify-cli/pull/8822

docs: documentation for geo populate

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx

Fixes Flutter authenticator link from getting started page.

fix(flutter): fixes authenticator link

---

src/fragments/lib/geo/existing-resources.mdx
src/fragments/start/getting-started/android/add-api.mdx
src/fragments/start/getting-started/android/generate-model.mdx
src/fragments/start/getting-started/flutter/add-api.mdx
src/fragments/start/getting-started/flutter/generate-model.mdx
src/pages/cli-legacy/graphql-transformer/connection.mdx
src/pages/cli/project/command-hooks.mdx
src/pages/cli/q/integration/[integration].mdx
src/pages/cli/start/workflows.mdx
src/pages/console/adminui/start.mdx
src/pages/console/auth/authentication.mdx
src/pages/console/auth/import.mdx
src/pages/console/authz/authorization.mdx
src/pages/console/data/data-model.mdx
src/pages/console/storage/file-browser.mdx
src/pages/console/storage/file-storage.mdx
src/pages/index.tsx
src/pages/start/q/integration/[integration].mdx

With the launch of Amplify Studio, removed all remaining instances of Admin UI and replaced with Amplify Studio. 

Update Admin UI references to Amplify Studio

---

src/fragments/lib/datastore/js/examples.mdx

_Issue #, if available:_ 3891
After merging this update, the customer can copy / paste this and will have a working sample.

fix(datastore): fix DS example typo (#3891)

---

src/pages/cli/start/workflows.mdx

docs(workflows): update the description of pull to reflect that changes made in a push

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx
src/fragments/ui/auth/flutter/authenticator.mdx

- Updates docs with changes from https://github.com/aws-amplify/amplify-flutter/pull/1241

chore(flutter/authenticator): Updates for better navigation support

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx
src/fragments/ui/flutter/installation.mdx

Bump authenticator flutter version

---

src/pages/cli/start/workflows.mdx

update typo on cfn

---

src/fragments/lib/geo/js/geofences.mdx

- Fix geo tagged install on geofences
- add noted about using authenticator

Geo: Fix geo tags

---

src/fragments/lib/geo/js/geofences.mdx
src/fragments/lib/geo/js/search.mdx

fix: remove -s flag from install commands

---

src/fragments/lib/geo/js/geofences.mdx

Geo signout button

---

src/pages/cli/geo/geofencing.mdx

Remove the pricing plan walkthrough for Geofencing. 

fix(geo-cli): remove pricing plan from goefencing

---

src/pages/start/q/integration/[integration].mdx

Update broken getting started link to Studio

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx
src/fragments/ui/flutter/installation.mdx

Flutter authenticator bug fix version bump

---

src/pages/cli/geo/maps.mdx
src/pages/cli/geo/search.mdx

Removes the pricing plan walkthrough for Maps and Search.
Add instructions to update existing Geo resources with Asset based pricing plans.
**Screenshots:**

[Do not merge] Add callout for pricing plan changes

---

src/fragments/lib/analytics/flutter/getting-started/20_installLib.mdx
src/fragments/lib/analytics/flutter/getting-started/30_initAnalytics.mdx
src/fragments/lib/auth/flutter/getting_started/20_installLib.mdx
src/fragments/lib/datastore/flutter/getting-started/10_preReq.mdx
src/fragments/lib/datastore/flutter/getting-started/20_installLib.mdx
src/fragments/lib/datastore/flutter/getting-started/50_initDataStore.mdx
src/fragments/lib/datastore/flutter/getting-started/60_initDataStore.mdx
src/fragments/lib/datastore/flutter/sync/10-installPlugin.mdx
src/fragments/lib/flutter.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/30_initapi.mdx
src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
src/fragments/lib/project-setup/flutter/create-application/20_pubspec.mdx
src/fragments/lib/project-setup/flutter/create-application/40_verifyAmplifyLibraries.mdx
src/fragments/lib/restapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/restapi/flutter/getting-started/30_initapi.mdx
src/fragments/lib/storage/flutter/getting-started/20_installLib.mdx
src/fragments/start/getting-started/flutter/add-api.mdx
src/fragments/start/getting-started/flutter/integrate.mdx
src/fragments/start/getting-started/flutter/setup.mdx

- Bump version to 0.3.0
- Update API Stream docs
- Add DataStore callout

chore(flutter): Updates for 0.3.0

---

src/fragments/lib/datastore/native_common/setup-auth-rules.mdx

- Fix links to CLI documenation
- Align wording with CLI documentation
- Update example following deny-by-default principle

fix: native libraries auth rules documentation

---

src/fragments/lib/auth/js/social.mdx

N/A
Use React FC + React hooks over old class based components to keep code snippets consistent.

Use React hooks in JS Auth social signin snippet

---

src/fragments/start/getting-started/vue/auth.mdx
src/fragments/start/getting-started/vue/setup.mdx

#3964 
Added better documentation for get Getting Started with Vue

Getting started with Vue update

---

src/fragments/lib/auth/js/delete_user.mdx

Update callout for delete user on JS

---

src/fragments/lib/storage/ios/configureaccess/50_customization.mdx
src/fragments/lib/storage/native_common/configureaccess/common.mdx

iOS - https://github.com/aws-amplify/amplify-ios/pull/1277
Add docs for storage prefix resolver

feat(Storage): AWSS3PluginPrefixResolver

---

src/fragments/start/getting-started/ios/integrate.mdx

I believe the latest xcode/swift ui filename is `ContentView.swift`

chore(getting started docs): update to accurate filename

---

src/fragments/ui/auth/developer-preview-callout-js.mdx

#3982 
Update developer preview banner to show correct information

Updated developer preview banner

---

src/components/Footer/index.tsx
src/components/UniversalNav/index.tsx
src/constants/links.ts

Lower left of page, Change Support  to Community Chat (pointing to same link discord)
Upper right of page, change Community to Contribute -> pointing to https://contributetoamplify.com/

Update community links on the home page

---

src/pages/cli/migration/transformer-migration.mdx

docs(cli): update cli.json path

---

cspell.json
src/fragments/lib/geo/js/geofences.mdx
src/fragments/lib/geo/js/maps.mdx

- update maps example to use `amplify-map.css`
- update geofence api links

chore(geo): update geofence API links, update map display docs to use vended css file

---

src/fragments/start/getting-started/angular/auth.mdx
src/fragments/start/getting-started/angular/data-model.mdx
src/fragments/start/getting-started/angular/setup.mdx

_Description of changes:_ Updates angular getting started to use latest `@aws-amplify/ui-angular`, as well as some callouts specific to Angular 12+.

Angular Getting Started Updates

---

src/fragments/lib/auth/js/social.mdx
src/fragments/lib/auth/js/start.mdx

Adding a section that will explain in more detail the required parameters for using Amplify with Cognito Hosted UI

Adding note for OAuth configuration

---

src/fragments/start/getting-started/flutter/prereq.mdx

This PR specifies the Kotlin version that a customer App must define in order to update to Flutter 2.10+.

fix(flutter): specifies kotlin version requirement

---

src/fragments/lib/project-setup/flutter/prereq/prereq.mdx

Adds requirement for kotlin version to library doc section.

fix(flutter) add kotlin version to library section

---

src/fragments/ui/auth/web/authenticator.mdx

_Issue #, if available:_  Resolves #4005

Fix link to React authenticator properities

---

src/fragments/lib/auth/flutter/getting_started/40_authenticator.mdx
src/fragments/ui/flutter/installation.mdx

updated Authenticator version number

updated Authenticator version number

---

src/components/FeatureFlags/feature-flags.json

Brings the feature flags documentation up to date on missing feature flags

Update: bring feature flags documentation up to date

---

src/fragments/lib/datastore/flutter/conflict.mdx

Update the [document](https://docs.amplify.aws/lib/datastore/conflict/q/platform/flutter/#custom-configuration) regarding DataStore custom configurations to align with other libraries documents.
**Preview**
----

fix(amplify-flutter): Update DataStore custom config related docs

---

src/pages/cli/graphql/data-modeling.mdx

Add an example of how to specify having multiple connections between the same two models

Update: Add example of multiple connections between models

---

src/pages/cli/start/workflows.mdx

add workflow for pulling an existing project to a new machine to src/pages/cli/start/workflows.mdx
https://github.com/aws-amplify/amplify-cli/issues/3643
https://github.com/aws-amplify/amplify-cli/issues/9711
https://github.com/aws-amplify/amplify-js/discussions/7503

add workflow for pulling an existing project to a new machine to src/pages/cli/start/workflows.mdx

---

src/fragments/lib/auth/android/device_features/10_rememberDevice.mdx
src/fragments/lib/auth/android/device_features/20_forgetDevice.mdx
src/fragments/lib/auth/android/device_features/30_fetchDevice.mdx

_Description of changes:_ Fix RxJava sample code for remembering, forgetting, and fetching devices.

fix(Android): Correct RxJava code for device tracking

---

src/fragments/lib/datastore/flutter/sync/50-selectiveSync.mdx

https://github.com/aws-amplify/amplify-flutter/issues/1315
Add reevaluate selective sync expression document for amplify-flutter.
Preview:

fix(flutter): add reevaluate syncExpression section

---

src/fragments/lib/auth/flutter/access_credentials/10_fetchAuthSession.mdx

Added `timeout` function to `fetchAuthSession` for Flutter

Timeout fetch auth session flutter

---

src/pages/console/uibuilder/figmatocode.mdx

Update figma to react page based on usability feedback

---

src/fragments/sdk/library-callout.mdx

fix: sdk callout

---

src/fragments/lib/auth/flutter/getting_started/20_installLib.mdx
src/fragments/lib/datastore/flutter/getting-started/20_installLib.mdx
src/fragments/lib/storage/flutter/getting-started/20_installLib.mdx

small tweak to add amplify core package as a dependency

small tweak to add amplify core package as a dependency

---

src/fragments/lib/pubsub/js/subunsub.mdx

n/a
The earlier formatting did not produce a table,
but a garbled paragraph with some of the intended markup visible.
Old:
New:

PubSub: Fix table formatting

---

cspell.json
src/fragments/lib/auth/ios/password_management/10_reset_password.mdx

https://github.com/aws-amplify/amplify-ios/issues/1473

chore(Auth): iOS Cognito Errors returned on ForgotPassword API

---

src/fragments/lib/geo/js/getting-started.mdx

- Add link to escape hatch on geo getting started per request from @hdworld11 

chore(geo): add escape hatch link to geo getting started

---

src/fragments/guides/hosting/nextjs.mdx

add double quotes for terminal commands
https://github.com/aws-amplify/docs/issues/4095

Update nextjs.mdx git formatting

---

src/fragments/lib/geo/js/geofences.mdx

chore(geo): add note about nextjs with geo

---

src/fragments/lib/restapi/native_common/authz/common.mdx

_Description of changes:_ The key used in API plugin was wrong.

fix(api): Configuration for apikey authorization in API category

---

src/fragments/lib/analytics/ios/identifyuser.mdx

_Issue #3922 https://github.com/aws-amplify/docs/issues/3922

Fix for Typo on the ANALYTICS Docs for iOS

---

src/pages/cli-legacy/graphql-transformer/codegen.mdx

_Issue #, if available:_ #3943, #3931
_Description of changes:_ Change Codegen link

update broken link

---

src/fragments/lib/graphqlapi/graphql-from-node.mdx
src/pages/cli/function/index.mdx

https://github.com/aws-amplify/docs/issues/2840
- update CLI function prompts 
- replace API url ref with the generated API URL env var

update `add function`

---

src/fragments/lib/storage/android/configureaccess/50_customization.mdx
src/fragments/lib/storage/native_common/configureaccess/common.mdx

android - [#1659](https://github.com/aws-amplify/amplify-android/pull/1659)
Add documentation for AWSS3PluginPrefixResolver in Android

feat(Storage-Android): AWSS3PluginPrefixResolver

---

src/pages/cli/graphql/authorization-rules.mdx

_Issue #[9645](https://github.com/aws-amplify/amplify-cli/issues/9645)
- updated lambda auth function response required fields

update lambda auth function response required fields

---

src/fragments/lib/client-configuration/js/js-configuration.mdx

#4061
Add note about placement of `Amplify.configure()`

add note about project level config

---

src/pages/cli/restapi/override.mdx

Added an example of overriding a property for a specific REST API route

Expand on existing override docs for REST APIs

---

src/fragments/lib/graphqlapi/graphql-from-node.mdx

Closes https://github.com/aws-amplify/docs/issues/3902

Highlight need to update function for API access env vars

---

src/pages/cli/auth/import.mdx

Related: https://github.com/aws-amplify/docs/pull/4158

add auth import lifecycle callout

---

src/pages/cli/storage/import.mdx

add storage import lifecycle callout

---

src/fragments/start/getting-started/reactnative/integrate.mdx

Platform is used in StyleSheet but not imported

We need Platform imported for StyleSheet

---

src/fragments/lib/graphqlapi/ios/query-data.mdx

_Description of changes:_ Add iOS doc updates for paginatedList() to list() renaming. Ref: https://github.com/aws-amplify/amplify-ios/pull/1702

chore(Datastore): Add iOS doc updates for paginatedList() to list() renaming

---

src/pages/cli/graphql/search-and-result-aggregations.mdx

fix for https://github.com/aws-amplify/amplify-cli/issues/9728

Updated parameter name to be used for open search

---

src/fragments/lib/auth/flutter/user_attributes/20_update_user_attribute.mdx
src/fragments/lib/auth/flutter/user_attributes/30_confirm_attribute.mdx
src/fragments/lib/auth/flutter/user_attributes/40_resend_code.mdx

https://github.com/aws-amplify/amplify-flutter/issues/1489
Update code example to match the latest implementation in amplify-flutter auth category.

fix(flutter): auth user attributes code examples

---

src/pages/cli/usage/containers.mdx

Add some instructions for using your own docker container specification

update: Add steps for custom container API spec

---

src/directory/directory.js
src/fragments/lib/geo/native_common/getting_started/common.mdx
src/fragments/lib/geo/native_common/maps/common.mdx
src/fragments/lib/geo/native_common/search/common.mdx

Removes mention of dev preview in navigation menu and dev preview callouts for iOS Geo.

chore(iOS): remove dev preview callouts for iOS Geo

---

src/components/FeaturesGrid/index.tsx

Geo iOS is now GA, so this PR updates the main description of Geo on the homepage accordingly. It also changes the endpoint to be non js specific.

chore(core): update Geo description and endpoint on homepage

---

src/fragments/start/getting-started/common/prereq.mdx
src/pages/cli/start/install.mdx

https://create-react-app.dev/docs/getting-started/

fix: update minimum required versions of Node and NPM

---

src/fragments/start/getting-started/common/prereq.mdx
src/pages/cli/start/install.mdx

fix: fix callout links

---

src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/geo/js/search.mdx

- Remove outdated React code sample
- Add Callout to goto UI docs for React components if developer is using React.
Maps:
Search:

feat(geo): update Geo to reflect React component release

---

src/pages/cli/project/override.mdx
src/pages/cli/storage/override.mdx

added override examples for storage and project.

add new override examples

---

src/pages/console/uibuilder/override.mdx

Add clarification of overriding individual components within a collection. 

add clarification for overrideItems

---

src/fragments/lib/analytics/js/autotrack.mdx

_Issue #, [2070](https://github.com/aws-amplify/docs/issues/2070)
_Description of changes:_ Adding note about providing the location information for Analytics 

note about location

---

src/fragments/start/getting-started/next/api.mdx

Closes #2627 
Update tutorial with recent CLI prompts. Modified wording to call out use of example schema `Post`

update nextjs db api getting started

---

src/fragments/lib/push-notifications/js/getting-started.mdx

https://github.com/aws-amplify/docs/issues/3794
Closes #3794 
Fixed import to reflect https://www.npmjs.com/package/@react-native-community/push-notification-ios

Fix import in getting started example

---

src/pages/cli/graphql/authorization-rules.mdx
src/pages/cli/graphql/data-modeling.mdx

_Description of changes:_ add correction on the current behaviour of IAM public access and API key

add correction on the current behaviour of IAM public access and API key

---

src/pages/cli/storage/overview.mdx

docs(cli): add callout for updating storage access permissions

---

cspell.json
src/pages/cli/graphql/data-modeling.mdx

_Description of changes:_ Added better wording suggested

create better wording for Data modeling advanced

---

src/directory/directory.js

Makes a directory entry for https://github.com/aws-amplify/docs/pull/4255

doc: add identity claim change guides to directory

---

src/components/FeatureFlags/feature-flags.json

mod feature flag identifier

---

src/pages/cli/custom/cdk.mdx
src/pages/cli/graphql/override.mdx

when adding customer manged resource, customers will need to add additional permission on top of amplify provided permissions.

add information on customer managed resoures

---

src/pages/cli/graphql/troubleshooting.mdx

n/a
updates script to point to amplify-category-api repository

docs(cli): update raw github link for OpenSearch backfill script

---

src/pages/console/uibuilder/eventhandling.mdx

Adding import statements to address #4273

---

src/fragments/ui/auth/flutter/authenticator.mdx
src/fragments/ui/flutter/installation.mdx
src/fragments/ui/web/installation.mdx

N/A
* Update the links from the UI Components pages to point to platform specific URLs where possible.
* Update link text with "Amplify UI" to increase SEO juice
_Testing:_
Ran `yarn dev` and tested UI Components pages for each framework

fix: update links to Amplify UI docs for better SEO

---

src/pages/console/uibuilder/eventhandling.mdx

Addresses #4275

---

src/fragments/lib/auth/native_common/signout/common.mdx
src/fragments/sdk/auth/android/working-with-api.mdx

feat(auth): add content for token revocation when signing out

---

src/pages/cli/reference/feature-flags.mdx

_Issue #, if available:_https://github.com/aws-amplify/amplify-cli/issues/10033
added information on convention changes in feature flags to prevent confusion in usage of camel case.

added info on feature flags convention

---

src/pages/cli/custom/cdk.mdx

_Description of changes:_ added documentation on how to add CLI user permissions.

add information on how to give CLI iam user permissions

---

src/pages/cli-legacy/graphql-transformer/relational.mdx

update wording around prompt after db creation

---

src/directory/directory.js
src/fragments/lib/project-setup/flutter/escape-hatch/escape-hatch.mdx
src/fragments/start/getting-started/flutter/nextsteps.mdx
src/pages/lib/project-setup/escape-hatch/q/platform/[platform].mdx

- Adds documentation around the SigV4 package customers can used to directly interact with AWS

chore(flutter): AWS SigV4 docs

---

src/fragments/lib/project-setup/native_common/prereq/common_header.mdx
src/fragments/start/getting-started/common/prereq.mdx
src/pages/cli/start/install.mdx

Update node/npm versions, and removed callouts for CRA NPM/Node version numbers.

Update node/npm versions

---

src/pages/cli/graphql/authorization-rules.mdx

Adding documentation on null responses for field-level authorization

---

src/fragments/lib/analytics/flutter/getting-started/20_installLib.mdx
src/fragments/lib/auth/flutter/getting_started/20_installLib.mdx
src/fragments/lib/datastore/flutter/getting-started/20_installLib.mdx
src/fragments/lib/datastore/flutter/sync/10-installPlugin.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/project-setup/flutter/create-application/20_pubspec.mdx
src/fragments/lib/restapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/storage/flutter/getting-started/20_installLib.mdx
src/fragments/start/getting-started/flutter/add-api.mdx
src/fragments/start/getting-started/flutter/setup.mdx
src/fragments/ui/flutter/installation.mdx

Bumps version references to ^0.5.0

chore(flutter): Bump versions to ^0.5.0

---

src/fragments/lib/auth/js/getting-started.mdx

remove react native authenticator

remove react native authenticator

---

src/pages/cli/geo/geofencing.mdx

N/A
Add a note in the geofences docs that users added to a Cognito User Pool Group should be re-authenticated for the proper permissions to take form.

chore: Add note to re-authenticate users in geofences docs

---

src/fragments/start/getting-started/react/auth.mdx

#4306
Update docs so it wraps the app in `withAuthenticator` which should fix issue with the input losing focus.

Fix: Update React Getting Started Guide To Use withAuthenticator

---

src/fragments/lib/analytics/native_common/getting-started/common.mdx

Add a sentence with a link to the Cognito Identity Pool docs, so people can read more about what we're doing under the hood.
Fixes #4351

Add information about cognito identity pools

---

src/fragments/lib/analytics/js/getting-started.mdx
src/pages/lib/analytics/getting-started/q/platform/[platform].mdx

I missed 2 places to add Cognito information in #4352 

Add more Cognito information.

---

src/pages/cli/geo/maps.mdx

Please reflect the pull request for "amplify-cli" when it is merged.
https://github.com/aws-amplify/amplify-cli/issues/10290
https://github.com/aws-amplify/amplify-cli/pull/10115
- Two new map styles were added.
Explore (data provided by HERE)
ExploreTruck (data provided by HERE)
- One existing map style was added.
Imagery (data provided by Esri)

Map Style Add

---

src/fragments/lib/auth/flutter/signin_with_custom_flow/10_cli_setup.mdx

Shows how to switch auth flow in amplify config. Submitted in response to user feedback.

fix(flutter): show how to switch auth flow in config

---

src/fragments/lib/geo/ios/escapehatch.mdx
src/fragments/lib/geo/ios/maps/20_display_map.mdx
src/fragments/lib/geo/ios/maps/30_styles.mdx
src/fragments/lib/geo/ios/search/10_search_by_text.mdx
src/fragments/lib/geo/ios/search/20_search_by_coordinates.mdx
src/fragments/lib/geo/ios/search/30_location_search_map.mdx

_Description of changes:_ Continuation of last PR https://github.com/aws-amplify/docs/pull/4374
Add `async` version of Geo APIs for iOS based on `dev-preview` branch on `amplify-ios`.

Add developer preview version for Geo APIs

---

src/pages/cli/graphql/authorization-rules.mdx

- CLI PR: https://github.com/aws-amplify/amplify-category-api/pull/23

add documentation to allow more granular access for @auth read operation

---

src/fragments/lib/geo/js/geofences.mdx

chore(geo): fix saveGeofence typo

---

src/pages/cli/migration/identity-claim-changes.mdx

Adds an example of changes to a a list query with filter when looking for both owner formats.

doc: add filtered list query

---

src/fragments/lib/graphqlapi/flutter/query-data.mdx

https://github.com/aws-amplify/amplify-flutter/issues/1695
Adds examples for using query predicates for Flutter API GraphQL Model helpers. 

Chore(Flutter): API Query Predicates Examples

---

src/pages/cli/geo/geofencing.mdx

_Issue #, if available:_https://github.com/aws-amplify/amplify-cli/issues/10649
change the amplify geo populate to import per PR changes by https://github.com/aws-amplify/amplify-cli/pull/10038

changing populate to import in geo

---

src/pages/console/adminui/access-management.mdx

Issue: https://github.com/aws-amplify/amplify-adminui/issues/24
Mention all the AWS resources that are created when enabling Studio.

update: mention resources created on enabling Studio

---

src/fragments/lib/datastore/js/examples.mdx
src/fragments/start/getting-started/react/api.mdx
src/fragments/start/getting-started/vanillajs/data-model.mdx
src/fragments/ui-legacy/api/react/connect.mdx
src/fragments/ui-legacy/auth/react/tutorial.mdx
src/fragments/ui-legacy/interactions/react/chatbot.mdx
src/pages/cli-legacy/graphql-transformer/predictions.mdx

updated imports for Amplify JS

updated imports for Amplify JS

---

src/fragments/start/getting-started/reactnative/getting-started-steps-ui.mdx

fix for https://github.com/aws-amplify/amplify-js/issues/3682#

Add instructions to install Cognito Library

---

cspell.json
src/fragments/guides/authentication/js/email-only-authentication.mdx
src/fragments/lib/ssr/js/getting-started.mdx
src/fragments/start/getting-started/next/api.mdx
src/fragments/ui/auth/react/overriding-sign-up-submit.mdx

https://github.com/aws-amplify/amplify-ui/issues/2256
Add DataStore SSR example; fix Next.js API example; update UI imports

add DataStore SSR example; fix Next.js API example; update UI imports

---

src/fragments/lib/predictions/android/identify-text.mdx
src/fragments/lib/predictions/android/interpret.mdx
src/fragments/lib/predictions/android/label-image.mdx
src/fragments/lib/predictions/android/translate.mdx

_Description of changes:_ Fixes errors in the Android code blocks for the predictions docs.

fix(Android): Correct predictions code blocks

---

src/pages/cli/graphql/authorization-rules.mdx

Added a callout for developers using the `private` level access control on their `@model`s about the behavior with connected models 

fix(cli): add callout for connected private models

---

src/fragments/lib/auth/flutter/signin/60_runtime_auth_flow.mdx
src/fragments/lib/auth/native_common/signin/common.mdx

Documents authFlow parameter for flutter's `signIn` API.

feat(flutter): runtime authFlow

---

src/fragments/lib/geo/js/maps.mdx

- Add missing map API documentation

fix(geo): add map apis to map documentation

---

src/pages/cli/graphql/data-modeling.mdx

Added custom primary key with relation model section in `CLI/API(GraphQL)/Data modeling`

feat(cli): add custom primary key with relation model section

---

src/directory/directory.js
src/fragments/lib/geo/js/existing-resources.mdx
src/fragments/lib/geo/js/google-migration.mdx

- typo fixes
- add your own resource doc page updates to show examples with multiple
- wording updates

fix: Small geo doc fixes

---

src/fragments/lib/datastore/ios/advanced-workflows/custom-primary-key/delete-snippet.mdx
src/fragments/lib/datastore/ios/advanced-workflows/custom-primary-key/query-snippet.mdx

Added iOS code snippets (Query,Delete) for the CPK docs PR (https://github.com/aws-amplify/docs/pull/4452)

feat(data): Custom Primary Key iOS code snippets

---

src/fragments/lib/project-setup/flutter/create-application/20_pubspec.mdx
src/fragments/start/getting-started/flutter/setup.mdx

Update broken link for pub.dev 

pub.dev link update

---

src/fragments/lib/auth/js/emailpassword.mdx

Moved resend confirmation to sign up section

Moved position of resend sign up documentation

---

src/pages/cli/graphql/data-modeling.mdx

Revise the GraphQL Data modeling instructions to be more beginner friendly and clear

Revise GraphQL Data Modeling instructions for clarity

---

src/fragments/lib/auth/js/start.mdx

Adding `signUpVerficationMethod` option

Adding `signUpVerficationMethod` option

---

src/pages/cli/reference/files.mdx

Add two missing files to reference

Add missing files to reference

---

src/fragments/lib/storage/js/list.mdx

Added instruction on how to access all files from S3 using list API.

docs: @aws-amplify/storage Access all files from storage using list API

---

src/fragments/lib/auth/flutter/delete_user/10_delete_user.mdx

remove iOS callout from delete user page

remove iOS callout from delete user page

---

src/fragments/lib/datastore/android/data-access/delete-snippet.mdx
src/fragments/lib/datastore/android/data-access/query-basic-snippet.mdx
src/fragments/lib/datastore/android/real-time/observe-query-snippet.mdx
src/fragments/lib/datastore/android/real-time/observe-snippet.mdx

Fixes issue #4482

---

src/fragments/lib/push-notifications/js/getting-started.mdx
src/fragments/lib/push-notifications/js/overview.mdx
src/fragments/lib/push-notifications/js/reactnative.mdx
src/pages/lib/push-notifications/getting-started/q/platform/[platform].mdx
src/pages/lib/push-notifications/overview/q/platform/[platform].mdx
src/pages/lib/push-notifications/testing/q/platform/[platform].mdx
src/pages/lib/push-notifications/working-with-api/q/platform/[platform].mdx

Make push notifications support platform support clear

---

src/fragments/lib/datastore/flutter/advanced-workflows/custom-primary-key/query-snippet.mdx

Use block switcher for amplify-flutter query by cpk example. And update description.

Use block switcher for Flutter query by CPK examples

---

src/pages/cli/reference/usage-data.mdx

fix: usage data wording

---

src/directory/directory.js
src/pages/console/uibuilder/override.mdx
src/pages/console/uibuilder/slots.mdx

Updated "Slot" to "Component slot" label

---

src/pages/cli/graphql/authorization-rules.mdx

- Amended the "how it works" section's GraphQL type in the @auth directive to include "get, list, sync, search"
- Fixed a typo in the existing content

Updating authorization rule operations with more granular detail

---

src/pages/cli/graphql/custom-business-logic.mdx

Addresses #4250

---

src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
src/fragments/lib/in-app-messaging/js/prerequisites.mdx
src/fragments/start/getting-started/reactnative/setup.mdx

Revert "fix(native): Update references to RN"

---

src/pages/console/uibuilder/slots.mdx

Updating documentation for the Slots/Nested Collections feature

Adding many-to-many caveat

---

src/fragments/lib/storage/js/list.mdx

fixes https://github.com/aws-amplify/docs/issues/4571

fix: remove extra semicolon

---

customHttp.yml

_Description of changes:_ Add `X-XSS-Proteection` header to security headers in `amplify.yml`

Add X-XSS-Protection header

---

src/fragments/lib/analytics/ios/escapehatch.mdx
src/fragments/lib/analytics/ios/getting-started/10_preReq.mdx
src/fragments/lib/analytics/ios/getting-started/20_installLib.mdx
src/fragments/lib/analytics/ios/getting-started/30_initAnalytics.mdx
src/fragments/lib/analytics/ios/getting-started/40_record.mdx
src/fragments/lib/analytics/ios/identifyuser.mdx
src/fragments/lib/analytics/ios/record.mdx

- Removing all references to Cocoapods.
- Updating iOS min version.
- Updated `Escape Hatch` code to match the new SDK.
- Tweaking some code blocks for cosmetic reasons.
- Rewording/rewriting some sections to fix typos, improve readability and provide more information.

Updating Analytics V2 docs for iOS

---

cspell.json
src/pages/cli/graphql/override.mdx

fix: add missing word to spellcheck dictionary

---

src/fragments/lib/auth/ios/getting_started/30_initAuth.mdx
src/fragments/lib/auth/ios/user_attributes/40_resend_code.mdx
src/fragments/lib/geo/ios/escapehatch.mdx
src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
src/fragments/lib/geo/ios/getting_started/40_init_geo.mdx
src/fragments/lib/geo/ios/maps/30_styles.mdx
src/fragments/lib/geo/ios/search/10_search_by_text.mdx
src/fragments/lib/geo/ios/search/20_search_by_coordinates.mdx
src/fragments/lib/geo/ios/search/30_location_search_map.mdx

_Description of changes:_ 
- Updates the public apis in geo to async/await pattern
- Fix an api in auth

chore: Change async await calls in Geo iOS

---

src/fragments/lib/graphqlapi/ios/advanced-workflows/10_example.mdx
src/fragments/lib/graphqlapi/ios/advanced-workflows/20_custom.mdx
src/fragments/lib/graphqlapi/ios/advanced-workflows/30_nested.mdx
src/fragments/lib/graphqlapi/ios/advanced-workflows/40_multiple.mdx
src/fragments/lib/graphqlapi/ios/authz/20_oidc.mdx
src/fragments/lib/graphqlapi/ios/authz/21_oidc.mdx
src/fragments/lib/graphqlapi/ios/authz/22_lambda.mdx
src/fragments/lib/graphqlapi/ios/authz/30_multi.mdx
src/fragments/lib/graphqlapi/ios/getting-started/10_preReq.mdx
src/fragments/lib/graphqlapi/ios/getting-started/20_installLib.mdx
src/fragments/lib/graphqlapi/ios/getting-started/30_initapi.mdx
src/fragments/lib/graphqlapi/ios/getting-started/50_createtodo.mdx
src/fragments/lib/graphqlapi/ios/mutate-data.mdx
src/fragments/lib/graphqlapi/ios/query-data.mdx
src/fragments/lib/graphqlapi/ios/subscribe-data.mdx
src/fragments/lib/restapi/ios/delete.mdx
src/fragments/lib/restapi/ios/fetch.mdx
src/fragments/lib/restapi/ios/getting-started/10_preReq.mdx
src/fragments/lib/restapi/ios/getting-started/20_installLib.mdx
src/fragments/lib/restapi/ios/getting-started/30_initapi.mdx
src/fragments/lib/restapi/ios/getting-started/40_postTodo.mdx
src/fragments/lib/restapi/ios/update.mdx

_Description of changes:_ Update GraphQL and REST API documentation for Amplify iOS v2.

chore(api): Update API docs for Amplify iOS v2

---

src/fragments/lib/storage/ios/configureaccess/10_protected_upload.mdx
src/fragments/lib/storage/ios/configureaccess/20_protected_download.mdx
src/fragments/lib/storage/ios/configureaccess/50_customization.mdx
src/fragments/lib/storage/ios/download.mdx
src/fragments/lib/storage/ios/escapehatch.mdx
src/fragments/lib/storage/ios/getting-started/10_preReq.mdx
src/fragments/lib/storage/ios/getting-started/20_installLib.mdx
src/fragments/lib/storage/ios/getting-started/30_initStorage.mdx
src/fragments/lib/storage/ios/getting-started/40_upload.mdx
src/fragments/lib/storage/ios/list.mdx
src/fragments/lib/storage/ios/remove.mdx
src/fragments/lib/storage/ios/upload.mdx

Updating all **Storage** pages
- Removing all references to Cocoapods.
- Updating iOS min version.
- Updating all code snippets to match the new APIs.

Updating Storage v2 docs for iOS

---

customHttp.yml

- Set `X-Frame-Options` to `DENY`

Set X-Frame-Options to 'DENY'

---

src/fragments/lib/analytics/ios/identifyuser.mdx
src/fragments/lib/auth/ios/signin/10_signUp.mdx
src/fragments/lib/auth/ios/signin/40_multi_factor_signup.mdx
src/fragments/lib/auth/ios/signin_with_custom_flow/20_signup.mdx
src/fragments/lib/auth/ios/user_attributes/40_resend_code.mdx
src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
src/fragments/lib/datastore/ios/auth-model.mdx

fix(Auth): Updating Auth documentation fixed with disparities

---

src/fragments/lib/analytics/ios/getting-started/10_preReq.mdx
src/fragments/lib/auth/ios/getting_started/10_preReq.mdx
src/fragments/lib/datastore/ios/getting-started/10_preReq.mdx
src/fragments/lib/geo/ios/getting_started/10_pre_req.mdx
src/fragments/lib/graphqlapi/ios/getting-started/10_preReq.mdx
src/fragments/lib/ios-prereq-category.mdx
src/fragments/lib/ios-prereq-xcode.mdx
src/fragments/lib/predictions/ios/getting-started/20_preReq.mdx
src/fragments/lib/project-setup/ios/prereq/prereq.mdx
src/fragments/lib/restapi/ios/getting-started/10_preReq.mdx
src/fragments/lib/storage/ios/getting-started/10_preReq.mdx
src/fragments/start/getting-started/ios/setup.mdx

N/A
- Updates Xcode and OS version prerequisites.
- Adds fragments for single source of truth for prerequisites.

chore(ios): add prereq fragments

---

src/fragments/lib/analytics/ios/escapehatch.mdx
src/fragments/lib/auth/ios/escapehatch/10_awsmobileclient_escape.mdx
src/fragments/lib/geo/ios/escapehatch.mdx
src/fragments/lib/ios-escape-hatch-warning.mdx
src/fragments/lib/ios.mdx
src/fragments/lib/storage/ios/escapehatch.mdx

* Updating reference from AWS iOS SDK to AWS SDK for Swift
* Add stability note

fix(iOS): update reference from AWS iOS SDK to AWS SDK for Swift

---

src/fragments/lib/analytics/ios/existing-resources.mdx
src/fragments/lib/analytics/ios/getting-started/30_initAnalytics.mdx
src/fragments/lib/analytics/ios/getting-started/40_record.mdx
src/fragments/lib/analytics/ios/identifyuser.mdx
src/fragments/lib/analytics/ios/record-event-code.mdx
src/fragments/lib/analytics/ios/record.mdx
src/pages/lib/analytics/existing-resources/q/platform/[platform].mdx

- Creating a fragment for the recording code, to avoid duplication
- Creating an iOS specific page of using existing resources so we can omit the `pinpointTargeting` section.
- Updated Swift UI instructions to use `init` instead of `UIApplicationDelegateAdaptor`
- Also renamed the options to just **Swift UI** and **UIKit** and swapped them.
- Fixed a compilation issue in the **Identify User** code, and changing it to use the good syntax while at it 😌

Updating Analytics docs

---

src/fragments/lib/info/ios/data-information.mdx

N/A
Removes Legacy SDK column and updates table in `iOS > Info > Data Information`.

fix(ios): update data information

---

src/fragments/lib/project-setup/ios/combine/combine.mdx

feat: update ios combine support

---

generatePathMap.cjs.js
src/utils/withFilterOverrides.ts

- Add filter overrides for `react-native`
- Add `/lib/q/platform/react-native` object to `generatePathMap.cjs.js`

React native picker updates

---

src/fragments/lib/datastore/ios/data-access/query-sort-multiple-snippet.mdx
src/fragments/lib/datastore/ios/data-access/save-snippet.mdx
src/fragments/lib/datastore/ios/relational/delete-snippet.mdx
src/fragments/lib/datastore/ios/relational/query-snippet.mdx
src/fragments/lib/datastore/ios/relational/save-many-snippet.mdx

fix(datastore): minor updates for V2

---

src/fragments/lib/graphqlapi/ios/subscribe-data.mdx

_Description of changes:_ Update combine flavor of GraphQLAPI subscribe

chore(API): Update combine flavor of GraphQLAPI subscribe

---

src/fragments/lib/geo/android/maps/20_display_map.mdx

Fix typo in 20_display_map.mdx

---

src/fragments/lib/storage/android/download.mdx

Added comma in download URL code

---

src/fragments/lib-v1/auth/ios/password_management/10_reset_password.mdx
src/fragments/lib/auth/ios/access_credentials/10_fetchAuthSession.mdx
src/fragments/lib/auth/ios/getting_started/30_initAuth.mdx
src/fragments/lib/auth/ios/password_management/10_reset_password.mdx
src/fragments/lib/auth/ios/signin/10_signUp.mdx
src/fragments/lib/auth/ios/signin/20_confirmSignUp.mdx
src/fragments/lib/auth/ios/signin/40_multi_factor_signup.mdx
src/fragments/lib/auth/ios/signin_next_steps/10_signin.mdx
src/fragments/lib/auth/ios/signin_next_steps/50_reset_password.mdx
src/fragments/lib/auth/ios/signin_next_steps/60_confirm_signup.mdx
src/fragments/lib/auth/ios/signin_with_custom_flow/20_signup.mdx
src/fragments/lib/auth/ios/signin_with_custom_flow/30_confirmSignup.mdx
src/fragments/lib/auth/ios/signout/20_global_signout.mdx
src/fragments/lib/auth/ios/user_attributes/20_update_user_attribute.mdx
src/fragments/lib/auth/ios/user_attributes/30_confirm_attribute.mdx

* Minor update and cleanup of v2 auth documentation code snippets

fix(iOS): cleanup v2 auth code snippets

---

src/fragments/lib-v1/datastore/ios/data-access/query-predicate-multiple-snippet.mdx
src/fragments/lib-v1/datastore/ios/data-access/query-predicate-or-snippet.mdx
src/fragments/lib-v1/datastore/ios/getting-started/60_saveSnippet.mdx
src/fragments/lib/datastore/ios/data-access/observe-update-snippet.mdx
src/fragments/lib/datastore/ios/data-access/query-pagination-snippet.mdx
src/fragments/lib/datastore/ios/data-access/query-predicate-multiple-snippet.mdx
src/fragments/lib/datastore/ios/data-access/query-predicate-or-snippet.mdx
src/fragments/lib/datastore/ios/data-access/query-sort-snippet.mdx
src/fragments/lib/datastore/ios/data-access/save-snippet.mdx
src/fragments/lib/datastore/ios/data-access/update-snippet.mdx
src/fragments/lib/datastore/ios/getting-started/60_saveSnippet.mdx
src/fragments/lib/datastore/ios/relational/delete-snippet.mdx
src/fragments/lib/datastore/ios/relational/query-snippet.mdx
src/fragments/lib/datastore/ios/relational/save-many-snippet.mdx
src/fragments/lib/datastore/ios/relational/save-snippet.mdx
src/fragments/lib/datastore/ios/sync/20-savePredicate.mdx

Up to Syncing data to cloud sections

fix(datastore): bug bash V2 docs (up to Sync Data To Cloud section)

---

src/fragments/lib/auth/ios/signout/10_local_signout.mdx
src/fragments/lib/auth/ios/signout/20_global_signout.mdx

N/A
Updates auth signout examples to include full error handling.

fix(ios): update auth signout examples

---

src/fragments/lib/datastore/ios/conflict.mdx
src/fragments/lib/datastore/ios/getting-started/50_initDataStore.mdx
src/fragments/lib/datastore/ios/real-time/observe-snippet.mdx
src/fragments/lib/datastore/ios/setup-auth-rules/10_multiauth-snippet.mdx
src/fragments/lib/datastore/ios/sync/20-savePredicate.mdx
src/fragments/lib/datastore/ios/sync/40-clear.mdx
src/fragments/lib/datastore/ios/sync/50-selectiveSync.mdx

_Description of changes:_ Fix iOS v2 Datastore docs section.

chore(datastore): Fix v2 datastore docs

---

src/fragments/guides/api-graphql/ios/subscriptions-by-id.mdx

N/A
Updates Guides > API (GraphQL) for v2

fix(ios): update guides - api (graphql)

---

src/components/TableOfContents/index.tsx

_Issue #, if available:_  #4687
- Update sticky nav height value in the TOC code

Update sticky header height

---

src/directory/directory.js
src/fragments/guides/datastore/parallel-processing-ios.mdx

_Description of changes:_ Updated the code snippet to reflect the changes in datastore guide

chore: Updated datastore guide with v2 code

---

src/fragments/start/getting-started/angular/auth.mdx
src/fragments/start/getting-started/angular/data-model.mdx
src/fragments/start/getting-started/angular/hosting.mdx
src/fragments/start/getting-started/angular/setup.mdx
src/pages/start/getting-started/hosting/q/integration/[integration].mdx

_Description of changes:_ This updates getting started guide. Fixes some bugs that I've found along the way:
- Components were not styled at all, even including the Authenticator.
- Solution: import `theme.css` from Amplify UI. This is a required step for Authenticator anyway.
- A lot of code snippet was not TypeScript strict mode compliant. Angular 12 turns on strict mode by default.
- Solution: strictly type everything 😈 
- The sample app will **not** hide the protected component even if user hasn't authenticated. 
- Solution: abstract API logic into its own Angular component, and put it inside the Authenticator. This is the standard Angular practice and recommended Authenticator usage.
By submitting this pull request, I confirm that my contribution is made …

Update Angular getting started guide

---

src/fragments/guides/api-rest/ios/express-api-call.mdx
src/fragments/guides/api-rest/ios/rest-api-call.mdx

fix: update iOS API (REST) guide

---

src/pages/cli/auth/override.mdx

Closes https://github.com/aws-amplify/amplify-cli/issues/11178#issue-1408131252

docs: update preferred_username for override

---

src/fragments/lib/ios.mdx

_Description of changes:_ Add callout about the upgrade guide for v2 Amplify Swift

chore: Information regarding upgrade Amplify for swift v2

---

src/fragments/lib/graphqlapi/js/subscribe-data.mdx
src/pages/cli/graphql/data-modeling.mdx

Added more clarity on empty object as sub filter

---

src/fragments/lib/auth/common/social_signin_web_ui/configure_auth_category.mdx

update docs to match new Facebook UI

---

src/fragments/lib/auth/js/manageusers.mdx

https://github.com/aws-amplify/amplify-js/issues/987
Not ready for merge until https://github.com/aws-amplify/amplify-cli/pull/10773 has been merged.
Clarify how to update and verify a Cognito user email address change with full app example.

fix: add section to clarify steps to update Cognito user email address with example

---

src/fragments/lib/auth/ios/access_credentials/10_fetchAuthSession.mdx

_Description of changes:_ Add documentation about force refresh for auth v2

chore(auth): Add information about force refresh

---

src/fragments/lib/auth/ios/signin_with_custom_flow/10_cli_setup.mdx
src/fragments/lib/auth/ios/signin_with_custom_flow/40_signin.mdx
src/fragments/lib/auth/ios/signin_with_custom_flow/50_custom_challenge.mdx

_Description of changes:_ Change the documentation to reflect v2 custom auth flow.

fix(auth): Fix auth custom authflow for v2

---

src/pages/cli/graphql/authorization-rules.mdx

Added explicit headers for multi-user data access

---

src/pages/console/uibuilder/responsive.mdx

Adding version requirements for CLI

small change

---

cspell.json
src/directory/directory.js
src/fragments/lib/ios.mdx
src/fragments/lib/project-setup/ios/upgrade-guide/upgrade-guide.mdx
src/pages/lib/project-setup/upgrade-guide/q/platform/[platform].mdx

_Description of changes:_ Adds upgrade guide for swift

Add upgrade guide for swift

---

src/fragments/lib/storage/js/copy.mdx
src/fragments/lib/storage/js/download.mdx
src/fragments/lib/storage/js/getting-started.mdx
src/fragments/lib/storage/js/list.mdx
src/fragments/lib/storage/js/upload.mdx
src/pages/lib/storage/overview/q/platform/[platform].mdx

update storage for v5

---

src/fragments/lib-v1/storage/js/list.mdx
src/fragments/lib/storage/js/list.mdx

fix(storage): Update from comments in prior pr

---

src/fragments/lib-v1/graphqlapi/js/subscribe-data.mdx
src/fragments/lib-v1/pubsub/js/subunsub.mdx
src/fragments/lib/graphqlapi/js/subscribe-data.mdx
src/fragments/lib/pubsub/js/reconnect-description.mdx
src/fragments/lib/pubsub/js/subunsub.mdx

docs: Add reconnect guidance to subscriptions

docs: Add reconnect guidance to subscriptions

---

src/components/FeatureFlags/feature-flags.json
src/pages/cli/graphql/data-modeling.mdx

N/A
* Update docs for secondary indexes, feature flag default behavior, and provide examples of usage in data modeling page.
* Relevant CLI PR: https://github.com/aws-amplify/amplify-cli/pull/11348

feat: document enabled feature flag, and usage in secondary index section of data modeling page

---

src/fragments/lib/storage/ios/configureaccess/10_protected_upload.mdx
src/fragments/lib/storage/ios/configureaccess/20_protected_download.mdx
src/fragments/lib/storage/ios/download.mdx
src/fragments/lib/storage/ios/getting-started/40_upload.mdx
src/fragments/lib/storage/ios/list.mdx
src/fragments/lib/storage/ios/remove.mdx
src/fragments/lib/storage/ios/upload.mdx

_Description of changes:_ Make document changes based on the api change https://github.com/aws-amplify/amplify-swift/pull/2543

Update storage api doc to reflect api changes

---

cspell.json
src/fragments/lib/geo/android/escapehatch.mdx

- Update escape hatch for Location client to return Kotlin SDKs Location client

chore: update location escape hatch

---

src/fragments/lib/storage/android/escapehatch.mdx

Change `AmazonS3Client` to `S3Client` in v2

change `AmazonS3Client` to `S3Client` in v2

---

src/fragments/lib/analytics/android/escapehatch.mdx
src/fragments/lib/android-kotlin-java-interop.mdx
src/fragments/lib/auth/android/escapehatch/escapehatch.mdx
src/fragments/lib/geo/android/escapehatch.mdx
src/fragments/lib/predictions/android/escapehatch.mdx
src/fragments/lib/project-setup/android/upgrade-guide/upgrade-guide.mdx
src/fragments/lib/storage/android/escapehatch.mdx

- add interop callout in java block for each of the escape hatch page.
- few updates on upgrade guide as per review.

add java interop callout

---

src/fragments/lib/restapi/js/getting-started.mdx

https://github.com/aws-amplify/docs/issues/4803
Clarify regional endpoints messaging callout.

Clarify Regional endpoints messaging

---

src/fragments/lib/auth/android/access_credentials/10_fetchAuthSession.mdx

Added section on how to force refresh during fetchauthsession call

chore(Auth): Add info about force refresh in fetchauthsession

---

src/fragments/lib/project-setup/android/upgrade-guide/upgrade-guide.mdx

- changes as per review comments.

changes to upgrade guide

---

src/directory/directory.js
src/fragments/lib/info/android/app-uninstall.mdx
src/fragments/lib/info/native_common/app-uninstall/common.mdx
src/pages/lib/info/app-uninstall/q/platform/[platform].mdx

Added Uninstall callout that auth data cannot persist an uninstall.

Android v2 Uninstall Documentation

---

src/fragments/lib/predictions/android/escapehatch.mdx

Fix android build :fingers-crossed:

---

src/fragments/lib-v1/restapi/flutter/delete.mdx
src/fragments/lib-v1/restapi/flutter/fetch.mdx
src/fragments/lib-v1/restapi/flutter/getting-started/40_postTodo.mdx
src/fragments/lib-v1/restapi/flutter/update.mdx
src/fragments/lib-v1/restapi/native_common/getting-started/common.mdx
src/fragments/lib/graphqlapi/flutter/advanced-workflows/50_interceptor.mdx
src/fragments/lib/graphqlapi/flutter/authz/30_multi.mdx
src/fragments/lib/graphqlapi/flutter/authz/auth_mode.mdx
src/fragments/lib/graphqlapi/native_common/authz/common.mdx
src/fragments/lib/restapi/flutter/delete.mdx
src/fragments/lib/restapi/flutter/fetch.mdx
src/fragments/lib/restapi/flutter/getting-started/10_preReq.mdx
src/fragments/lib/restapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/restapi/flutter/getting-started/40_postTodo.mdx
src/fragments/lib/restapi/flutter/update.mdx
src/fragments/lib/restapi/native_common/getting-started/common.mdx

DO NOT MERGE UNTIL DEV-PREVIEW for Dart API category released.
This PR has updates for dev preview of amplify-flutter API category (implemented in Dart for wider platform support). Most of the changes are in REST API but there are a few additions for GraphQL as some missing features are added here.

[DO NOT MERGE UNTIL DEV-PREVIEW for Dart API category released] feat(flutter): update API for dev preview

---

src/directory/directory.js
src/fragments/lib-v1/auth/flutter/getting_started/60_developerPreview.mdx
src/fragments/lib/auth/flutter/getting_started/60_developerPreview.mdx
src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
src/fragments/lib/project-setup/flutter/platform-setup/sqlite3_wasm.mdx
src/fragments/lib/storage/flutter/configureaccess/10_protected_upload.mdx
src/fragments/lib/storage/flutter/configureaccess/20_protected_download.mdx
src/fragments/lib/storage/flutter/configureaccess/30_private_upload.mdx
src/fragments/lib/storage/flutter/configureaccess/50_customization.mdx
src/fragments/lib/storage/flutter/copy.mdx
src/fragments/lib/storage/flutter/dev-preview-api-callout.mdx
src/fragments/lib/storage/flutter/download.mdx
src/fragments/lib/storage/flutter/get-properties.mdx
src/fragments/lib/storage/flutter/getting-started/10_preReq.mdx
src/fragments/lib/storage/flutter/getting-started/20_installLib.mdx
src/fragments/lib/storage/flutter/getting-started/30_initStorage.mdx
src/fragments/lib/storage/flutter/getting-started/40_upload.mdx
src/fragments/lib/storage/flutter/getting-started/50_developerPreview.mdx
src/fragments/lib/storage/flutter/list.mdx
src/fragments/lib/storage/flutter/move.mdx
src/fragments/lib/storage/flutter/remove.mdx
src/fragments/lib/storage/flutter/sqlite3_wasm.mdx
src/fragments/lib/storage/flutter/upload.mdx
src/fragments/lib/storage/flutter/upload/upload-create-file.mdx
src/fragments/lib/storage/native_common/configureaccess/common.mdx
src/fragments/lib/storage/native_common/getting-started/common.mdx
src/fragments/start/getting-started/flutter/build.mdx
src/pages/lib/storage/copy/q/platform/[platform].mdx
src/pages/lib/storage/get-properties/q/platform/[platform].mdx
src/pages/lib/storage/move/q/platform/[platform].mdx

Refactoring amplify-flutter Storage category documentation to include the latest changes of the new Dart written Storage S3 plugin.

feat(flutter): dart storage developer preview

---

src/fragments/lib/analytics/flutter/getting-started/10_preReq.mdx
src/fragments/lib/analytics/flutter/getting-started/20_installLib.mdx
src/fragments/lib/analytics/flutter/sqlite3_wasm.mdx
src/fragments/lib/project-setup/flutter/platform-setup/sqlite3_wasm.mdx

Add instructions for analytics dart first 

Add analytics dart first instructions

---

src/fragments/lib/storage/android/escapehatch.mdx

add newline to fix callout rendering

---

src/fragments/lib/auth/android/signin_with_custom_flow/20_signup.mdx
src/fragments/lib/auth/android/signin_with_custom_flow/30_confirmSignup.mdx
src/fragments/lib/auth/android/signin_with_custom_flow/40_signin.mdx
src/fragments/lib/auth/android/signin_with_custom_flow/50_custom_challenge.mdx
src/fragments/lib/auth/android/switch-auth/switch-auth.mdx

All Android v2 custom flow samples have Kotlin Callbacks, Kotlin Coroutines, Java, RxJava

Android Custom Flow code samples

---

src/pages/cli/usage/mock.mdx

This reverts commit a41430d7da23add063bd04443959a0348486567a.

Revert "feat(cli-mock): add section for searchable mocking (#4775)"

---

src/fragments/guides/hosting/nextjs.mdx

_Description of changes:_ Adds YouTube video as requested by @swaminator!

Add next.js video

---

src/fragments/lib-v1/auth/ios/access_credentials/10_fetchAuthSession.mdx
src/fragments/lib/auth/ios/access_credentials/10_fetchAuthSession.mdx

_Description of changes:_ remove print statements from V1 & V2 “Access credentials” code samples.

fix: Remove print statements from V1 & V2 “Access credentials” code samples

---

src/fragments/lib-v1/auth/android/signin_web_ui/20_platform_specific_setup.mdx

Removed suggestion to use custom redirect activity. HostedUIRedirectActivity should always be used.

Amplify Android v1 Web Sign in Cleanup

---

src/fragments/lib-v1/graphqlapi/android/getting-started.mdx
src/fragments/lib-v1/graphqlapi/android/getting-started/10_preReq.mdx
src/fragments/lib-v1/restapi/android/getting-started/10_preReq.mdx

#4689 didn't get combined properly with the v2 docs release

Reapply minSDK changes to lib-v1

---

src/fragments/lib-v1/auth/android/signin_web_ui/20_platform_specific_setup.mdx
src/fragments/sdk/auth/android/hosted-ui.mdx

Android API used cancelled instead of canceled.

Fix canceled spelling

---

Readme.md

Adding styleguide to readme and a few edits

---

src/pages/cli/usage/containers.mdx

#4758 
Updated the broken link with the updated working link. 
While updating that link I also noticed some of the links were hyperlinks instead of relative links which seems out of the general convention followed in this repo.
So I updated those to being relative links instead. If this change is not required please let me know I will remove that commit. 

Updated broken link

---

cspell.json
src/fragments/cli-install-block.mdx
src/fragments/lib-v1/storage/js/upload.mdx
src/fragments/lib/project-setup/flutter/create-application/30_provisionBackend.mdx
src/fragments/lib/storage/js/browser-uploads.mdx

Revert "updated findings from Nika"

---

src/fragments/lib-v1/datastore/android/relational/save-many-snippet.mdx
src/fragments/lib-v1/project-setup/android/async/async.mdx
src/fragments/lib/datastore/android/relational/save-many-snippet.mdx
src/fragments/lib/project-setup/android/async/async.mdx

change editor to user

---

src/pages/guides/functions/dynamodb-from-js-lambda/q/platform/[platform].mdx

https://github.com/aws-amplify/docs/issues/4114
Adding a sample showing how to delete an item from DynamoDB

Adding Delete ddb sample

---

src/components/SearchBar/Autocomplete.tsx
src/components/SearchBar/functions/groupBy.ts
tasks/build-algolia-search.mjs

_Issue #, if available:_ 4384
This PR updates the algolia search to index nested fragments within the docs, also removes unparsable lines from the mdx files.  This PR also fixes a bug in the algolia search filtering based on the platform being viewed.

Search results

---

src/styles/elements.css

corrects CSS issue to properly format code styles in table cells

fix: table cell code block styles

---

src/fragments/lib/project-setup/react-native/run-react-native.mdx
src/fragments/lib/storage/js/upload.mdx
src/fragments/start/getting-started/reactnative/integrate.mdx
src/fragments/start/getting-started/reactnative/setup.mdx

add run commands to library guide for React Native

add run commands to library guide for React Native

---

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml

- Add CodeQL workflow to use CodeQL action: https://github.com/github/codeql-action

Add codeql github workflow

---

customHttp.yml
src/pages/_document.tsx

- Add Content Security Policy to customhttp.yml

Add CSP to custtomhttp.yml

---

src/fragments/lib/analytics/android/getting-started/30_initAnalytics.mdx
src/fragments/lib/analytics/android/getting-started/40_record.mdx
src/fragments/lib/auth/android/getting_started/30_initAuth.mdx
src/fragments/lib/auth/android/getting_started/40_fetchSession.mdx
src/fragments/lib/datastore/android/getting-started/60_initDataStore.mdx
src/fragments/lib/datastore/android/getting-started/70_saveSnippet.mdx
src/fragments/lib/predictions/android/getting-started/40_init.mdx
src/fragments/lib/predictions/android/getting-started/50_translate.mdx
src/fragments/lib/storage/android/getting-started/30_initStorage.mdx
src/fragments/lib/storage/android/getting-started/40_upload.mdx

_Description of changes:_ Adding import statements to all category getting started pages for clarity.

chore: Add imports to getting started for all categories

---

src/fragments/lib/datastore/flutter/getting-started/10_preReq.mdx
src/fragments/lib/storage/js/autotrack.mdx
src/fragments/sdk/pubsub/android/getting-started.mdx

- Prereq for PR #4341, to fix syntax errors in mdx files.
- Angle brackets need to be wrapped in curly braces and a quote 

fix: wrap angle brackets in curly braces

---

STYLEGUIDE.md

Update styleguide to include guidance on links within mdx files.

update styleguide to include markdown links

---

src/fragments/start/getting-started/react/auth.mdx

_Issue #, if available:_ #4952
- Fix broken link

Fix broken link to auth getting started page

---

src/fragments/lib/geo/js/google-migration.mdx
src/fragments/lib/geo/js/maps.mdx

Update the CDN artifact version to reflect the new release: https://cdn.amplify.aws/
I have confirmed the sample apps work as expected.

feat: update CDN artifact versions

---

src/pages/cli/usage/headless.mdx

Added curly braces to JSON code block.

---

src/fragments/lib/auth/js/mfa.mdx

(chore) - TOTP setup refactor

---

src/fragments/lib/graphqlapi/js/subscribe-data.mdx
src/fragments/lib/pubsub/js/subunsub.mdx
src/fragments/lib/utilities/js/hub.mdx

Resolved customer feedback here https://github.com/aws-amplify/amplify-js/issues/9824#issuecomment-1367827632
Updated hub message payload since there was a syntax error

updated hub message payload

---

src/fragments/lib/xr/getting-started.mdx

Just a small change in the docs

Fixed a broken link

---

src/pages/console/adminui/access-management.mdx

closes https://github.com/aws-amplify/docs/issues/5008
Amplify studio settings can only be accessed after we select an Amplify project. added a step.

update steps for invite team members

---

src/fragments/start/getting-started/vanillajs/setup.mdx

fix(data): remove deprecated logo from JS Getting Started code snippet

fix(data): remove deprecated logo from JS Getting Started code snippet

---

Readme.md

_Description of changes:_ Added a callout in the README to request callout in PR description when redirects are needed.

docs: update README to call out need for redirects in contribution guide

---

src/fragments/start/getting-started/android/setup.mdx

fix(docs): Remove lifecycle viewmodel from setup

---

.github/PULL_REQUEST_TEMPLATE.md

Adding styleguide to PR template

---

src/fragments/lib/datastore/js/other-methods.mdx

fix(data): fix DataStore typo

---

src/fragments/lib/auth/ios/social_signin_web_ui/10_cli_setup.mdx

fix: https://github.com/aws-amplify/amplify-cli/issues/8097, https://github.com/aws-amplify/amplify-cli/issues/9478
chore: Add input validation for private key in sign in with apple oauth flow
See more details on this PR https://github.com/aws-amplify/amplify-cli/pull/11790

chore: Add input validation for private key in sign in with apple oauth flow

---

src/directory/directory.js
src/pages/cli/reference/ssm-parameter-store.mdx

add cli page for ssm parameter store usage

---

generatePathMap.cjs.js
tasks/generate-sitemap.ts

update sitemap generator to remove chooseFilter pages

---

.github/workflows/check_for_redirects.yml
.mergify.yml

- Add a new workflow, `check_for_redirects.yml`, to check the diff of the target branch against the base branch and count how many deleted files there are. If deleted files count > 0, then we add a `redirects-needed` label
- Add two Mergify pull request rules
- First rule is run when the `redirects-needed` label is added. It adds a comment to the PR asking the PR author what redirects are needed
- Second rule is to help automate the label with forked PRs. For the `check_for_redirects.yml` workflow, it is ran on the `pull_request` event and so `GITHUB_TOKEN` is not passed to forked PRs. Mergify checks to see if this workflow fails, meaning that it failed trying to add the label. If it sees this then it adds the label for us
**If this PR should not be merged upon approval for any reason, …

Add redirects label workflow

---

.github/workflows/check_for_deleted_assets.yml
.mergify.yml

- Add a new workflow to check if an asset was deleted. (Very similar to the [redirects workflow](https://github.com/aws-amplify/docs/blob/main/.github/workflows/check_for_redirects.yml))

Add workflow to check for deleted assets

---

src/pages/cli/start/workflows.mdx

adds a note in the "typical workflows" page of CLI's "getting started" section to recommend using [git-secrets](https://github.com/awslabs/git-secrets)
closes #5069

add a note recommending git-secrets for scanning

---

package.json
src/components/Feedback/__tests__/index.test.tsx
src/components/Feedback/index.tsx
yarn.lock

- Refactor the feedback component to use only Adobe Analytics

Refactor feedback component to use only adobe analytics

---

src/fragments/lib/graphqlapi/js/delta-sync.mdx
src/fragments/lib/graphqlapi/js/query-data.mdx
src/fragments/lib/xr/getting-started.mdx
src/fragments/ui/auth/react-native/authenticator.mdx
src/pages/ui/customization/translations/q/framework/[framework].mdx

Updates to JS and RN docs to remove/fix broken or outdated links per docs team findings. 

fix(JS/RN): broken or outdated links in docs

---

src/pages/console/data/data-model.mdx

The current data modeling example is outdated. It uses GraphQL transformer v1 and customers are not able to successfully deploy the template schema in Studio without manual intervention. 
This change updates the sample template to use a new version of the schema that uses GraphQL transformer v2.

Amplify Studio: update sandbox sample schema to align with tutorial docs and use graphQL transformer v2

---

src/pages/console/adminui/access-management.mdx

- Moves Studio resources reference to the bottom of the document, as adding users is much more relevant than explaining the resources details
- Expands managed resources into lists, for better visibility
- Gives instructions on how to re-create resources, as we'll soon link to them from a few specific errors on the console, to provide users with a better UX login experience 
https://github.com/aws-amplify/amplify-studio/issues/780
https://github.com/aws-amplify/amplify-studio/issues/800
https://github.com/aws-amplify/amplify-studio/issues/780
https://github.com/aws-amplify/amplify-studio/issues/689
https://github.com/aws-amplify/amplify-studio/issues/684
https://github.com/aws-amplify/amplify-studio/issues/23
**If this PR should not be merged upon approval for any reason, please submit as …

[Studio] Expand Studio managed resources and add instructions for resetting Studio

---

amplify.yml
next.config.js
src/pages/contribute/index.tsx

- Add a new custom env var `PROD_ENV` to conditionally fetch data for contribute page

Add custom env var to conditionally fetch data for contribute page

---

src/components/Layout/index.tsx
src/pages/contribute/index.tsx

- Comment out issues cards from contribute page

Comment out issues cards

---

src/fragments/lib-v1/auth/native_common/getting_started/common.mdx
src/fragments/lib/auth/native_common/getting_started/common.mdx
src/fragments/sdk/storage/android/getting-started.mdx
src/fragments/sdk/storage/android/transfer-utility.mdx

fix(android): Fixing broken links pointing to reference documents

---

src/fragments/lib/geo/existing-resources.mdx

Removed "just" following the writing style guide

Remove "just" from geo fragment

---

src/fragments/ui/react-native/installation.mdx
src/pages/ui/auth/authenticator/q/framework/[framework].mdx

Adding install steps for React Native authenticator
#4755

fix(react-native): add install steps

---

STYLEGUIDE.md

Added Rule # 21 to the styleguide specifying indent spacing 

feat(docs): added rule for indent spacing to styleguide

---

src/pages/cli/migration/lazy-load-custom-selection-set.mdx

adds `graphql` to fenced code block to enable syntax highlighting

chore: add graphql language to fenced code block for syntax highlighting

---

cspell.json
src/fragments/start/getting-started/reactnative/setup.mdx

added amplify init instructions and entry into cspell.json
closes #4902

added amplify init instructions for RN project setup

---

src/constants/versions.ts

chore: Update Amplify for Android v2 version

---

src/fragments/lib/geo/android/getting_started/40_init_geo.mdx
src/fragments/lib/geo/android/maps/30_styles.mdx
src/fragments/lib/geo/android/search/10_search_by_text.mdx
src/fragments/lib/geo/android/search/20_search_by_coordinates.mdx

_Description of changes:_ 
- Added documentation for using the new Coroutines and RxJava APIs for the Geo category
- Removed import statements from examples for consistency with other category docs

Add Coroutines and Rx docs for Geo category

---

src/fragments/start/getting-started/android/setup.mdx

Add desugaring to getting-started

---

src/fragments/lib-v1/project-setup/android/create-application/40_verifyAmplifyLibraries.mdx
src/fragments/lib/project-setup/android/create-application/40_verifyAmplifyLibraries.mdx

fix(android): Fix out of order setup step

---

src/fragments/lib/auth/js/hub_events/10_listen_events.mdx

Added missing auth events from [`Auth.ts`](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts)

fix(JS/RN): added missing auth events

---

src/fragments/lib/graphqlapi/graphql-from-node.mdx

- linked to pagination docs from the GraphQL from Node guide
Addresses #5271

Add pagination note on the GraphQL from Node docs

---

src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx

fixes ExpoSQLite import

---

src/components/contribute/QuickstartResources.tsx
src/fragments/cli-config.mdx
src/fragments/guides/hosting/custom-domains.mdx
src/fragments/guides/hosting/nextjs.mdx
src/fragments/guides/hosting/password-protected-deployments.mdx
src/fragments/guides/hosting/pull-request-previews.mdx
src/fragments/lib-v1/datastore/native_common/how-it-works.mdx
src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
src/fragments/lib/datastore/native_common/how-it-works.mdx
src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
src/pages/console/uibuilder/bestpractices.mdx

added sandbox attribute to iframes

securing iframes

---

src/fragments/lib-v1/storage/flutter/remove.mdx
src/fragments/lib/storage/flutter/remove.mdx

chore(flutter): update Amplify Flutter v1 doc - storage remove

---

src/directory/directory.mjs
src/fragments/lib/storage/flutter/get-properties.mdx
src/pages/lib/storage/get-properties/q/platform/[platform].mdx

- update Amplify Flutter Storage get file properties doc and code snippet for v1
- update page title to remove developer preview
- remove page for v0 as it is not used

chore(Flutter): update Amplify Flutter Storage getProperties API doc

---

src/directory/directory.mjs
src/fragments/lib/storage/flutter/copy.mdx

Update Amplify Flutter Storage copy API docs:
- update docs and code snippets for v1
- remove the copy doc from v0
- update the page title to remove developer preview from the title

chore(Flutter): update Amplify Flutter Storage copy API docs

---

src/fragments/lib-v1/storage/flutter/list.mdx
src/fragments/lib/storage/flutter/list.mdx

Update Amplify Flutter Storage list API docs:
- remove block switcher as we use version switcher
- clean up v0 doc
- update v1 doc and code snippets

chore(Flutter):update Amplify Flutter Storage list API docs

---

src/fragments/lib-v1/analytics/flutter/enable-disable/disable.mdx
src/fragments/lib-v1/analytics/flutter/enable-disable/enable.mdx
src/fragments/lib-v1/analytics/flutter/getting-started/10_preReq.mdx
src/fragments/lib-v1/analytics/flutter/getting-started/20_installLib.mdx
src/fragments/lib-v1/analytics/flutter/getting-started/30_initAnalytics.mdx
src/fragments/lib-v1/analytics/flutter/getting-started/40_record.mdx
src/fragments/lib-v1/analytics/flutter/identifyuser.mdx
src/fragments/lib-v1/analytics/flutter/record.mdx
src/fragments/lib/analytics/flutter/enable-disable/disable.mdx
src/fragments/lib/analytics/flutter/getting-started/10_preReq.mdx
src/fragments/lib/analytics/flutter/getting-started/20_installLib.mdx
src/fragments/lib/analytics/flutter/getting-started/30_initAnalytics.mdx
src/fragments/lib/analytics/flutter/getting-started/40_record.mdx
src/fragments/lib/analytics/flutter/identifyuser.mdx
src/fragments/lib/analytics/flutter/record.mdx
src/pages/lib-v1/analytics/enable-disable/q/platform/[platform].mdx

Update Analytics docs for the V1 release of Flutter. 
- [ x ] amplify-libraries
- [ x ] Flutter

Update Analytics v0 and v1 docs.

---

src/fragments/lib/push-notifications/common/getting_started/getting-started.mdx
src/fragments/lib/push-notifications/react-native/getting_started/40_install_lib.mdx
src/fragments/lib/push-notifications/react-native/getting_started/expo-callout.mdx

This PR pins amplify versions for Push Notifications to prevent Expo users from running into build issues

fix(notifications): Update RN PN docs to pin versions temporarily

---

cspell.json
src/directory/directory.mjs
src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
src/fragments/lib/project-setup/flutter/platform-setup/sqlite3_wasm.mdx
src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx
src/pages/lib/project-setup/upgrade-guide/q/platform/[platform].mdx

Adds an upgrade guide for Flutter from v0 to v1. It also makes v0/v1 specific changes to setup section and prerequisites to remove the block switchers and put the content in appropriate places.
- [ x] Flutter

feat: Flutter v0-v1 upgrade guide

---

src/fragments/lib/graphqlapi/flutter/authz/10_userpool.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/10_preReq.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/20_installLib.mdx
src/fragments/lib/restapi/flutter/getting-started/10_preReq.mdx
src/fragments/lib/restapi/flutter/getting-started/20_installLib.mdx

Provides updates to API category docs for v1 GA

chore(Flutter): API v1 updates

---

src/fragments/lib/graphqlapi/flutter/advanced-workflows/10_example.mdx
src/fragments/lib/graphqlapi/flutter/advanced-workflows/20_custom.mdx
src/fragments/lib/graphqlapi/flutter/advanced-workflows/30_nested.mdx
src/fragments/lib/graphqlapi/flutter/advanced-workflows/40_multiple.mdx
src/fragments/lib/graphqlapi/flutter/advanced-workflows/50_interceptor.mdx
src/fragments/lib/graphqlapi/flutter/authz/10_userpool.mdx
src/fragments/lib/graphqlapi/flutter/authz/2X_add_plugin.mdx
src/fragments/lib/graphqlapi/flutter/authz/30_multi.mdx
src/fragments/lib/graphqlapi/flutter/authz/auth_mode.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/30_initapi.mdx
src/fragments/lib/graphqlapi/flutter/getting-started/40_codegen.mdx
src/fragments/lib/graphqlapi/flutter/mutate-data.mdx
src/fragments/lib/graphqlapi/flutter/query-data.mdx
src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
src/fragments/lib/graphqlapi/native_common/authz/common.mdx

More cleanup of Flutter API v1 docs

chore(flutter): v1 API docs cleanup

---

src/fragments/lib/project-setup/android/create-application/30_provisionBackend.mdx
src/fragments/lib/project-setup/android/create-application/40_verifyAmplifyLibraries.mdx
src/fragments/lib/project-setup/native_common/create-application/50_nextSteps.mdx
src/fragments/start/getting-started/android/nextsteps.mdx

fix(android): Add minor improvements to android getting started guide

---

src/pages/console/formbuilder/call-to-action.mdx
src/pages/console/formbuilder/customize.mdx
src/pages/console/formbuilder/overrides.mdx
src/pages/console/formbuilder/overview.mdx
src/pages/console/formbuilder/validations.mdx
src/pages/console/tutorial/bindui.mdx
src/pages/console/tutorial/buildui.mdx
src/pages/console/tutorial/collections.mdx
src/pages/console/tutorial/data.mdx
src/pages/console/uibuilder/collections.mdx
src/pages/console/uibuilder/databinding.mdx
src/pages/console/uibuilder/eventhandling.mdx
src/pages/console/uibuilder/figmatocode.mdx
src/pages/console/uibuilder/slots.mdx

feat: update studio references and minor fixes

---

src/fragments/lib/push-notifications/react-native/getting_started/40_install_lib.mdx

This PR unpins the library version for Amplify Push Notifications instructions for React Native.

chore(react-native): Unpin library version for Push

---

src/fragments/lib/analytics/android/identifyuser.mdx
src/fragments/lib/analytics/flutter/identifyuser.mdx
src/fragments/lib/analytics/ios/identifyuser.mdx
src/fragments/lib/analytics/native_common/identify-use-cases.mdx

Adding additional details relating to use cases of when to use `Analytics.identifyUser` api to document for iOS, Android, and Flutter platform
Screenshot:
https://github.com/aws-amplify/docs/issues/3084

amplify-library: add use cases to identifyUser library api

---

src/fragments/lib-v1/datastore/android/getting-started/70_saveSnippet.mdx
src/fragments/lib-v1/datastore/android/other-methods/30_stop.mdx
src/fragments/lib-v1/predictions/android/identify-text.mdx
src/fragments/lib/datastore/android/getting-started/70_saveSnippet.mdx
src/fragments/lib/datastore/android/other-methods/30_stop.mdx
src/fragments/lib/predictions/android/getting-started/50_translate.mdx
src/fragments/lib/predictions/android/identify-text.mdx
src/fragments/lib/push-notifications/android/identify_user/10_get_auth_user.mdx
src/fragments/lib/storage/android/query-transfers.mdx

fix(android): Misc docs inconsistency fix

---

src/fragments/lib/pubsub/js/getting-started.mdx
src/pages/lib/pubsub/getting-started/q/platform/[platform].mdx

Small typo in console instructions for pubsub
Modified fragment imports
Closes #5313 

fix (JS/RN): updated 'secure' to 'security' for pubsub console instructions

---

package.json
yarn.lock

- Update `vm2` resolution to `3.9.16`

Update vm2 resolution

---

src/fragments/lib/auth/js/manageusers.mdx
src/pages/lib/auth/manageusers/q/platform/[platform].mdx

more descriptive arguments for verifyCurrentUserAttributeSubmit
fixed custom attributes link
modified imports for fragments
Closes #5361 , Closes #5209 

fix (JS/RN): fixed manage users auth page

---

src/pages/console/data/content-management.mdx
src/pages/console/data/data-model.mdx

https://github.com/aws-amplify/amplify-studio/issues/913

feat: update cms and data limitations

---

src/pages/cli/storage/overview.mdx

feat: add callout about remove storage

---

next.config.js
src/components/Hydrate/index.tsx
src/plugins/code-hike-add-hydration.tsx
src/plugins/import.tsx

Add plugin to fix code-hike hydration error

---

src/fragments/lib/project-setup/flutter/platform-setup/android.mdx

Updates Android platform setup docs for recent Gradle changes described here: https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide
aws-amplify/amplify-flutter#2937

chore(flutter): Update Android platform docs

---

src/fragments/start/getting-started/vue/setup.mdx

fix(CLI): Add authentication method option to Vue getting started guide

---

src/pages/console/adminui/extend-cli.mdx

documents cli flow common issues and their remediation steps 

feat: add studio cli flow troubleshooting

---

src/fragments/lib/interactions/js/getting-started.mdx
src/pages/lib/interactions/getting-started/q/platform/[platform].mdx

added callout about cli lexv1 only support for interactions
changed fragment/imports
Closes #5068 

chore(JS/RN): added callout about cli lexv1 only support for interactions

---

src/fragments/start/getting-started/next/api.mdx

chore(nextJS): updated nextjs getting-started with accurate cli prompts

---

src/fragments/lib/auth/ios/getting_started/45_authenticator.mdx
src/fragments/lib/auth/native_common/getting_started/common.mdx

Adding a mention to the Authenticator components in the Swift docs
N/A

feat(Authenticator): Adding a mention to the Authenticator components in the Swift docs [Swift]

---

src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx

Adds platform-specific changes to the migration guide for Flutter v1.
https://github.com/aws-amplify/amplify-flutter/issues/2947

fix(flutter): Add platform-specific changes to migration guide

---

src/fragments/lib/storage/js/download.mdx
yarn.lock

https://github.com/aws-amplify/docs/issues/5364

fix(JS): Update FAQ for Storage.get()

---

src/pages/cli/usage/mock.mdx

changes related to https://github.com/aws-amplify/amplify-cli/pull/12268
The cli mock flow will now support lambda function when running `amplify mock` with multi select. additionally, `amplify mock function` will support multi select as well.

feat: (pending-release) adds info on multiSelect workflow for mock and functions

---

src/pages/console/data/data-model.mdx

Amplify studio does not support split schemas in Data modelling. The Studio team will be providing a message when pushing a split schema to studio.
The PR documents this message and provides mitigation steps.

feat: add multi split schema mitigation instructions

---

src/pages/cli/usage/mock.mdx

Revert "feat: (pending-release) adds info on multiSelect workflow for mock and functions"

---

src/fragments/lib/auth/js/social.mdx
yarn.lock

Example on how to catch errors that may happen when using `Auth.federatedSignIn()`
https://github.com/aws-amplify/docs/issues/5182

feat(JS):Catch Errors during federatedSignIn

---

src/fragments/lib-v1/flutter.mdx
src/fragments/lib/flutter.mdx
src/pages/lib-v1/q/platform/[platform].mdx
src/pages/lib/q/platform/[platform].mdx

updated intro for Flutter library
- [X ] Flutter

updated intro for libraries

---

src/components/LandingHeroCTA/index.tsx
yarn.lock

feat: Update landing page with additional integrations

---

cspell.json
src/fragments/lib/auth/android/getting_started/05_authenticatorCallout.mdx
src/fragments/lib/auth/android/getting_started/45_authenticator.mdx
src/fragments/lib/auth/native_common/getting_started/common.mdx

Followup to #5398, add callout to Android Authenticator

feat(android): Add Authenticator callout to Android docs as well

---

cspell.json
src/fragments/guides/hosting/nextjs.mdx

The documentation can be updated to avoid updating the `eslint` rules and the code by only updating the next configuration

Updating documentation for next for SSG

---

src/fragments/lib/storage/flutter/download.mdx
src/fragments/lib/storage/js/download.mdx

Added clarification of the purpose of validateObjectExistence and its timeliness.

chore(flutter): clarify the purpose of validateObjectExistence flag of the getUrl API

---

src/directory/directory.mjs
src/fragments/lib/predictions/ios/escapehatch.mdx
src/fragments/lib/predictions/ios/getting-started/30_installLib.mdx
src/fragments/lib/predictions/ios/getting-started/40_init.mdx
src/fragments/lib/predictions/ios/getting-started/50_translate.mdx
src/fragments/lib/predictions/ios/identify-entity.mdx
src/fragments/lib/predictions/ios/identify-text.mdx
src/fragments/lib/predictions/ios/interpret.mdx
src/fragments/lib/predictions/ios/label-image.mdx
src/fragments/lib/predictions/ios/text-speech.mdx
src/fragments/lib/predictions/ios/transcribe.mdx
src/fragments/lib/predictions/ios/translate.mdx
src/fragments/start/getting-started/ios/nextsteps.mdx

Adds documentation for newly released Amplify Swift v2 - Predictions.

feat(predictions): add amplify-swift predictions v2 documentation

---

src/pages/console/data/data-model.mdx

currently the docs does not callout the limitation of `index` directive on data modelling.
additionally, studio only supports index directive on a hasMany relationship 

feat: adds index directive limitation and callout

---

src/fragments/lib/push-notifications/react-native/migrate-from-previous-version.mdx

https://github.com/aws-amplify/docs/issues/5448
https://github.com/aws-amplify/amplify-js/issues/11303#issuecomment-1529451029

chore(JS): callout for Push Notification migration guide

---

src/pages/cli/auth/admin.mdx

https://github.com/aws-amplify/docs/issues/5408

chore(CLI): Block switcher for admin actions

---

src/pages/cli/usage/mock.mdx

https://github.com/aws-amplify/docs/pull/5438
opened a new one as the other one was reverted.

feat: Multi select mock and functions

---

src/pages/cli/graphql/authorization-rules.mdx

Add reference to the sample code to sign GraphQL API request using IAM authorization.

docs(graphql): add sample code reference to cli iam auth section

---

src/fragments/lib/project-setup/flutter/prereq/prereq.mdx

update dev preview mention

---

src/pages/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/[platform].mdx

@aws-amplify/amplify-adminui#443 

Addresses aws-amplify/admin-ui#443

---

src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx

Adds docs for Amplify Flutter's reconnection workflow
https://github.com/aws-amplify/amplify-flutter/issues/2897

chore(Flutter): Amplify Flutter API subscription reconnection guide

---

src/components/Page/metaContent.tsx

remove feedback component from mobile

---

src/fragments/lib/geo/js/geofences.mdx
src/fragments/lib/geo/js/search.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/js/full-example.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/js/hoc-setup.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/js/install-dependencies.mdx

Fix docs to change imports to use new packages `ui-react-geo` and `ui-react-notifications`

chore(amplify-ui): fix docs to change imports to use new packages ui-react-geo and ui-react-notifications
