- js/api.md
Otherwise, had to read library code to find variables argument to mutation function.
Closes aws-amplify/amplify-js#1762.
> update Connect mutation doc to show variable passing

- cli/concept.md
- js/interactions.md
> update with the added CLI interactions category

- Gemfile.lock
- _config.yml
- js/graphql.md
This adds a bunch of GraphQL documentation and a new section to the amplify docs to contain it.
> Initial GraphQL docs

- js/react.md
Was reading through this quickly and missed the amplify init.  Suggest it should appear like the other shell commands that are not optional.
> Highlight amplify init as a shell command

- js/analytics.md
- js/angular.md
- js/start.md
- js/storage.md
Fix Syntax highlighting issue while rendering jsx and json on analytics, storage, start and angular docs.
> fix(docs): Syntax highlighting fix for jsx and json

- js/analytics.md
If non-string values are provided in an event the `record()` method will silently fail. The documentation doesn't specify this which led to confusion on why my events weren't being recorded. Other users have reported the same confusion, see the below issue.
https://github.com/aws-amplify/amplify-js/issues/712
Updating the documentation for `record()` to specify that strings are required for attribute values.
> Specifying the required type in record() example

- ios/manualsetup.md
Shows how to use one of the auto-generated service interfaces (SQS) within an iOS app. This will allow advanced customers to follow basic instructions when the standard higher level clients aren't enough for their use case.
> Instructions for using the autogenerated service interfaces

- ios/analytics.md
- ios/how-to-ios-setup-push-notifications.md
- ios/push-notifications.md
This doesn't break anything locally, and I *think* it will work once we get onto the server. Probably.
Sections affected:
* [Analytics](https://aws-amplify.github.io/docs/ios/analytics#monitor-analytics)
* Should display image of Pinpoint Console below the text "It may take up to 15 minutes for metrics to become visible"
* [Push Notifications](https://aws-amplify.github.io/docs/ios/push-notifications#add-amazon-pinpoint-targeted-and-campaign-push-messaging)
* Should display image of Xcode project setup below the text "choose the Capabilities tab, and then turn on Push Notifications"
* [Setting up Push Notifications](https://aws-amplify.github.io/docs/ios/how-to-ios-setup-push-notifications#step-1-create-an-app-id)
* Most steps have screenshots of Apple.com website
Tapping reviewers …
> Add image_base to fix ios doc images

- android/api.md
- android/start.md
- ios/api.md
- ios/authentication.md
- ios/start.md
Added `amplify console api` to the Getting Started and API sections to allow customer to easily open their API for testing with client app. Also fixed small error in the iOS Auth guide.
> Added the amplify console command to instructions

- .spelling
- cli/graphql.md
- js/graphql.md
The redirect for /docs/js/graphql forwarded to /cli/graphql, which does not work, because the docs site is nested inside the aws-amplify.io site. To solve this problem, I add a js/graphql.md that forwards users to the new location.
> Fix redirect for js/graphql

- android/start.md
Updated Step 1 configuration for app/build.gradle by replacing the configuration `compile` with `implementation` because the `compile` is now obsolete and has been replaced with `implementation`
-- Actual message in Android Studio is pasted below:
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Replaced config `compile` with `implementation`

- cli/init.md
The `amplify/` directory is not part of the resources provisioned by the parent CloudFormation stack.
> Fix indentation

- js/authentication.md
There is an option added to `currentAuthenticatedUser` to bypass the cache.
Now when calling `currentAuthenticatedUser`, it will first check if user data(attributes, mfa methods) is cached. If is, it will read from the cache and return. This avoids sending request to Cognito every time this method is called.
> Add option to currentAuthenticated User

- js/start.md
Without this change, the example hard-codes us-east-1, so the
"View Events on the Amazon Pinpoint Console" link doesn't work if
you picked another region when configuring the Amplify CLI.
> js/start.md: use aws_project_region in app.js example

- cli/multienv.md
Found another typo, this time in `multienv.md`.
Sorry for all the PR spamming, can also add this as one with #321 - whatever you guys prefer. 😊 
**Update:** Also changed a string wrongly referring to `"master"` instead of `"dev"` and added a `"master"` before for consistency.
> Fix typo in multienv.md

- android/api.md
Addressing feedback from https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/11 about how to initialize client for complex objects.
> Add code to initialize AWSAppSyncClient for complex objects

- android/storage.md
Updating Android Storage docs for the changes released in `2.11.0`.
Please refer [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2110) for more information.
> [Android][S3] Update doc for 2.11.0 changes

- android/storage.md
choosePhoto method doesn't need view as parameter, removing the same
> removing redundant view parameter from choosePhoto method

- android/api.md
.toString() doesn't return the actual token value, thus will cause unauthorized error if you call an API request with it.
.getTokenString() does return the actual token value.
> Fixed incorrect method of passing of token

- js/storage.md
The docs code has typo.
```
Storage.put('test.txt', 'File content'),{
progressCallback(progress) {
console.log(`Uploaded: ${progress.loaded}/${progress.total}`);
},
});
```
It will throws `SyntaxError: /src/pages/index.jsx: Unexpected token, expected ";" (78:1)`
```
Storage.put('test.txt', 'File content', {
progressCallback(progress) {
console.log(`Uploaded: ${progress.loaded}/${progress.total}`);
},
});
```
Thanks
> fix typo in Storage API docs

- ios/api.md
Use AWSCacheConfiguration instead of the deprecated databaseURL, in advance of the AppSync iOS 2.10.0 release.
@muellerfr Please don't merge this until we release AppSync iOS 2.10.0. I'm just getting this on your radar so you can review in advance of the release.
> Use cacheConfiguration

- js/authentication.md
Hello together,
in the authentication doc was an error within the withAuthenticator section. The variables were not in an object form, so react refused to take this variables because it didn't know the variables.
So I fixed the doc that you provide the variables/values as an object that it works again.
Best,
Tixamala
> Fixed withAuthenticator parameter object

- js/service-workers.md
This shows that the service worker must first be registered.
I used the GitHub interface; I'm not sure why the line ending changed.
Closes aws-amplify/amplify-js#2703
> Slight changes to Service Worker docs; makes example more copy-able

- ios/analytics.md
- ios/api.md
- ios/authentication.md
- ios/how-to-cognito-integrate-an-existing-identity-pool-ios.md
- ios/manualsetup.md
- ios/pubsub.md
- ios/push-notifications.md
- ios/start.md
- ios/storage.md
https://github.com/aws-amplify/docs/issues/477
iOS SDK version is upgraded from 2.8.0 to 2.9.0
AppSync iOS SDK version is upgraded from 2.9.0 to 2.10.0
to match the latest.
> Upgrade the iOS SDK version to 2.9.0 and AppSync SDK version to 2.10.0

- js/authentication.md
https://github.com/aws-amplify/amplify-js/issues/2862
Add Loading React component to documentation for Authenticator
> Add Loading component to React Auth UI docs

- cli/graphql.md
Role names need be global in an AWS account. Pushing the same role name to different environments causes the deployment to fail.
[Issue #1093](https://github.com/aws-amplify/amplify-cli/issues/1093)
Example code should use the env variable so that the custom resources can be pushed to multiple envs. 
> Add environment to RoleName

- js/react.md
change `creat react-app` to `create-react-app` to be consistent with `create-react-app` docs
Change `yarn create react-app` to `yarn create-react-app` to be consistent with the create-react-app docs.
> Fix a typo in the docs

- js/interactions.md
A typo of the command voiceEnabled. It was as voiceEnable previously and got trouble when doing a demo application using the documentation guide.
> voiceEnabled typo in sample

- js/vue.md
*Description of changes:* This PR is a minor fix to the navigation so one doesn't miss `signUpField` which is the attribute they're looking for in the first place.
*Additional context:* When trying to customize Sign Up component with custom fields and attributes, the documentation links do not point to the correct anchor. That can mislead people from going straight into `signUpFields` where the wrong configuration will be silently accepted by the Sign Up component (another issue altogether).
> Fix Vue Auth navigation link

- ios/manualsetup.md
Add a note about the expected behavior depending on when the AWSMobileClient is initialized in relation to service clients.
Fixes aws-amplify/aws-sdk-ios#1321
> [iOS] Clarify manual setup with AWSMobileClient

- js/react.md
Looks like a variable name from an old example (events vs todos) was left with a stale name.
> Rename variable newEvent to newTodo for clarity

- js/authentication.md
In the `authentication` document, there is typo. This PR fixes it.
> fix(typo): uses to users

- android/start.md
Discrepancy in suggested version of an Android SDK plugin in Amplify docs.
https://aws-amplify.github.io/docs/android/start#step-1-create-a-new-app
classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.8.+'
https://aws-amplify.github.io/docs/android/api#import-sdk-and-config
classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.9.+'
Changed the 2.8.+ to 2.9.+
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*
> Updated aws-android-sdk-appsync-gradle-plugin version to 2.9.+ in android/start.md

- js/api.md
none
REST Custom Authorization Header example : 
As per discussion with Richard : add "Bearer" keyword in the Authorization header and use accessToken instead of ID Token 
> add bearer keyword and use accesstoken for REST custom request example

- js/start.md
JS issue [#3424](https://github.com/aws-amplify/amplify-js/issues/3424)
Points users to linking requirement for RN.
> fixing react-native linking requirement url

- android/analytics.md
- ios/analytics.md
Fixes #726 
Add links to the documentation containing the limits imposed by Amazon Pinpoint: Currently includes the events ingestion limits and endpoint limits.
> [Analytics] Update docs with service limits

- js/api.md
Due to some unescaped liquid tags in code block the docs site has compilation warnings. This change fixes that by wrapping the given content into raw statements.
> Fix liquid compile warning for unescaped curly braces

- js/authentication.md
Changing react comment to '//' style to avoid empty childen component on copy/paste
> Fixes 'cannot read override of undefined' error

- android/push-notifications-handle-fcm.md
As described in the following AWS blog[1], we have to add `PinpointNotificationReceiver` to the AndroidManifest file in order to use "Open you app" action, which opens the app when the user taps on a notification. I am adding this note to the documentation.
[1] Create an Android Mobile App with Pinpoint using Mobile Hub
https://aws.amazon.com/blogs/mobile/create-an-android-mobile-app-with-pinpoint-using-mobile-hub/
> Update Android Push Notification docs to handle "Open your app" action

- cli-toolchain/graphql.md
Issue: #1766
Adds documentation on how to add authorization to subscription fields while @auth directive support is being designed and implemented.
> Adding docs on authorizing subscription fields.

- js/authentication.md
From what I can see in the source code, the language here is confusing. When is "appropriate"? Does that mean just before it expires? When the user calls Auth.currentSession()?
I think it makes it clearer that the refresh will take place only when a user consuming the API makes calls into the API itself.
This is a recreation of #745 which I had to recreate as I deleted my fork.
> Updating auto-refresh language

- js/start.md
Launch the GraphQL site in a new tab so customers don't navigate away.
> Launch in a new tab

- theme/_sass/components/_redesign.scss
Fix mobile menu on safari showing above view container.
> fix mobile menu view

- cli-toolchain/graphql.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-cli/pull/1953
Describes how to use the limit argument of @connection.
> Adds docs for @connection limits.

- js/authentication.md
JS Repo 3815
Adding note that Authenticator 'hide' prop is not available for react native.
> adding note that Authenticator 'hide' prop is not available for react native

- ios/manualsetup.md
Clarified location of archived SDKs for iOS. Customer was confused where the archives listed as we never specify that it isn't under `https://sdk-for-ios.amazonwebservices.com/latest/`
> Clarified location of archived SDKs for iOS

- ios/start.md
There was an extra "and" in the documentation which was a typo
> Fixes grammatical typo

- js/api.md
Changing AUTH_TYPE in the OIDC section of the AppSync client docs from 'IAM' to 'OPENID_CONNECT'.
> changing AUTH_TYPE for OIDC section of appsync docs

- js/react.md
- js/start.md
CRA documentation (https://create-react-app.dev/docs/getting-started) suggests this:
> If you've previously installed create-react-app globally via npm install -g create-react-app, we recommend you uninstall the package using npm uninstall -g create-react-app to ensure that npx always uses the latest version.
---
> Recommend npx create-react-app over npm install -g

- android/api.md
- android/storage.md
- ios/api.md
- ios/storage.md
- js/api.md
- js/storage.md
https://github.com/aws-amplify/docs/issues/885
Lambda trigger section was present in API category. We are removing it and updating the storage section with more description for Lambda trigger for all platforms.
> Remove Lambda triggers section from API and update Storage category

- cli-toolchain/quickstart.md
*Issue #:* related to #906 
*Description of changes:* Editing AppSync schema is no longer necessary. #906 cleaned up this section following multi-auth deployment but this part was probably left off.
> Update "GraphQL from Lambda" following multi-auth

- js/predictions.md
Changing the reference of Pinpoint in the manual setup section to Cognito Federated Identities.
There was a typo referring to Pinpoint in the documentation. I believe it should be about Cognito Federated Identities.
> Update prediction.md reference to Pinpoint

- .spelling
- js/start.md
*Related Issues*
#949
Updating React Native getting started docs for 0.60 and above
> Updating React Native getting started docs for 0.60 and above

- .github/stale.yml
In order to not add pending closed response to issues labels for our libraries, updating extempt labels
> chore: Update stale bot to exempt library labels

- ios/api.md
Subscription example incorrectly instructed customers to discard the watcher, which would result in the result handler not being invoked after discarding.
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/304
> Fix subscription watcher

- cli-toolchain/usage.md
*Issue #, if available:* #970
Removed an unicode character (\u2028) character that made the IAM Policy invalid if copied as-is.
> Remove Invalid JSON character in IAM Policy

- ios/start.md
Currently says API.shift where it should say API.swift
N/A
Corrects 'API.shift' typo to intended 'API.swift'
> Fix reference to generated API.swift file

- .spelling
- cli-toolchain/quickstart.md
https://github.com/aws-amplify/amplify-cli/pull/2443
Adds ability for Cognito User Pool Groups, setting permissions in a category on these groups, and creation of the AdminQueries infrastructure for running Administrative actions against a User Pool from a client application. Also includes sample React app code
> Initial docs for Admin Auth

- js/authentication.md
Issue #, if available:
 aws-amplify/amplify-cli#779
 aws-amplify/amplify-js#3405
 Added oauth config to Manual Setup
> feat(auth): Add optional oauth config to Manual Setup

- ios/analytics.md
- ios/api.md
- ios/datastore.md
- ios/storage.md
similar to https://github.com/aws-amplify/docs/pull/1048
Remove unneeded pod installs since the AmplifyPlugins subspec pulls it in
> Update iOS pods to remove Amplify, AWSPluginsCore

- ios/predictions.md
Since Predictions uses iOS 13, it has to be outside the main AmplifyPlugins pod.
> Updated pod path for Predictions

- _config.yml
Added "platform=purejs" query string key/value to "Getting Started" link.
> adding query string to getting started link

- .spelling
- cli-toolchain/graphql.md
- ios/predictions.md
- sdk/ios/api.md
- sdk/ios/start.md
- sdk/ios/storage.md
No issue number raised.
This PR corrects any incorrect casings of the IDE *Xcode* - it's a lowercase "c".
Is there any way to ensure the casing of `Xcode` is always enforced via `.spelling`?
> Corrected XCode -> Xcode

- ios/datastore.md
The colon in `amplify:tools` may lead to confusion in the Podfile, where the tool is referenced as `amplify-tools`.
> Documentation update

- ios/datastore.md
Docs incorrectly refer to location of `schema.graphql` as `amplify/backend/api/schema.graphql`. if the schema.graphql file is there, running `amplify codegen models` complains with the error:
```
Error: Could not find a schema at /path/to/amplify/backend/api/amplifyDatasource/schema.graphql
```
Updated correct location to `amplify/backend/api/amplifyDatasource/schema.graphql`
> Fixes schema.graphql location

- js/interactions.md
Fixes: #1087
Customer found a broken link within our interactions page. In looking at other API references (e.g. [API](https://aws-amplify.github.io/docs/js/api#api-reference)), I do see the updated link has similar structure. 
> fix: (@aws-amplify/interactions) Fix broken API Reference link

- ios/datastore.md
It was "API", copied over from the API docs. But, it should say "DataStore," which is the topic of discussion for the doc.
Resolves https://github.com/aws-amplify/docs/issues/1062
> Fix Page Title for iOS DataStore Docs

- ios/predictions.md
*Description of changes:* Type in manual config json with a wrong key of Storage. Should be "Predictions"
> Updated a typo in the manual configuration section

- js/datastore.md
The input argument is `_version` not `_input`.
> fix: _input -> _version

- cli-toolchain/graphql.md
Started with https://github.com/aws-amplify/amplify-cli/issues/2981
Created this PR to fix that issue: https://github.com/aws-amplify/amplify-cli/pull/3454
But other issues were brought up here: https://github.com/aws-amplify/amplify-cli/pull/3454#discussion_r384692060
And we decided that the best path forward was to update the docs until a more permanent solution can be implemented.
If an owner auth rule is specified besides create, create must also be specified to ensure that the creator is stored with the record. This updates the graphql transform docs to reflect that requirement.
> explicitly specify 'owner create' auth rule in examples with explanation

- capi/src/visitors/links.ts
- client/src/components.d.ts
- client/src/docs-ui/card/card.tsx
- docs/docs.md
* in page links now get wrapped with the `in-page-link` component.
* absolute links now get wrapped with the `external-link` component.
* fixes for docs card.
> fix: always use internal link components

- capi/src/inject/filtered-version-routes.ts
When on an sdk page, if the user selected JavaScript from the platform select, they are now redirected to the lib root for JS.
> chore: re-route js filter clicks to lib when on sdk

- capi/src/init-node/html-to-hyperscript.ts
- docs/lib/push-notifications/fragments/js/getting-started.md
Use of `style` attr was resulting in page rendering problems in certain getting started sections. Now Capi will throw an error at compile time.
> fix: throw error if style attr encountered in markdown html

- js/predictions.md
- js/pubsub.md
Update docs as per https://github.com/aws-amplify/amplify-js/pull/5085 to import providers and types from the root package
> Update docs to import providers and types from the root package

- js/api.md
*Description of changes:* With modularization update, API category is now split between Rest and Graphql modules while also providing backwards compatible API module.
> Update modular imports section of javascript API category

- client/src/cache.ts
- client/src/docs-ui/internal-link/internal-link.tsx
- client/src/docs-ui/page/page.tsx
Dramatically improves performance. Preloads assets for pages based on which links have rendered on a given page (waits until after first paint).
> Page data preloading

- tasks/build.ts
Until we solve the flicker bug, let's re-disable prerendering (which only helps with the initial page load)
> Temporarily redisable prerendering

- docs/lib/storage/download.md
- docs/lib/storage/upload.md
Currently the titles for the storage "Download files" and "Upload files" docs are flipped.
This pull request reverses the titles for those two docs.
> Fix incorrect titles for the storage "Download/Upload files" docs

- capi/src/visitors/links.ts
Clicking on tiles didn't route to correct page when ios or android platforms selected
> fix: mobile link override regression

- docs/lib/analytics/fragments/android/start.md
- docs/lib/datastore/fragments/android/start.md
- docs/lib/getting-started/fragments/android/setup.md
- docs/lib/graphqlapi/fragments/android/start.md
- docs/lib/storage/fragments/android/start.md
*Description of changes:* We shipped a new version of Amplify Android today but didn't update the version number in the docs. This change updates from 0.9.1 -> 0.10.0.
> Bump Amplify Android version to 0.10.0

- Readme.md
*Description of changes:* Removes outdated preview URL and credentials (which, if you're going to publish credentials to GitHub, why enforce their usage to begin with?)
> Remove outdated preview URL and credentials

- .gitignore
*Description of changes:* Something, somewhere, is configured to dump diagnostic reports to the main project directory. Adding the file pattern to prevent these from accidentally being checked in.
> Ignore diagnostic report files

- docs/sdk/storage/fragments/android/getting-started.md
- docs/sdk/storage/fragments/android/graphql-api.md
- docs/sdk/storage/fragments/android/transfer-utility.md
- docs/sdk/storage/getting-started.md
*Description of changes:* Mostly resolves broken links but does some other minor clean-up such as fixing service name references (e.g. it's Amazon Cognito, not AWS Cognito) and clarifies why TransferUtility doesn't work well with Cognito for huge (>50 minute) transfers.
> Fixes for Android Storage SDK documentation

- docs/sdk/auth/fragments/android/how-it-works.md
- docs/sdk/auth/fragments/ios/how-it-works.md
- docs/sdk/configuration/fragments/android/setup-options.md
- docs/sdk/configuration/fragments/ios/setup-options.md
- docs/sdk/configuration/menu.json
- docs/sdk/configuration/setup-options.md
- docs/sdk/menu.json
- docs/start/getting-started/fragments/android/nextsteps.md
- docs/start/getting-started/fragments/ios/nextsteps.md
*Issue #, if available:* https://github.com/aws-amplify/docs/issues/1371
*Description of changes:* In our previous docs site, there was a section of the SDK docs for developers who wish to use the low level clients. This change moves that over and adds it to the SDK docs under a "Configuration" header.
Note: I did not proofread these documents or check them for currency, rather this is a straight port of what is in master.
> Add SDK Setup Options

- capi/src/inject/filtered-version-routes.ts
- client/src/docs-ui/choose-anchor/choose-anchor.tsx
- client/src/docs-ui/internal-link/internal-link.tsx
* when on a JS lib page, and switching platforms, SDK is now the default
* /sdk js option -> /lib js
* /lib ios and android option -> sdk ios and android
> Default and impossible paths

- capi/src/visitors/links.ts
- docs/lib/push-notifications/fragments/js/getting-started.md
* any invalid links now error out
* it's now possible to reference an asset in markdown with query params (ie. `~/lib/some/path.md?platform=ios` or even `~/lib/some/path.md?platform=ios#some-section`)
Please validate this works well! Given we're about to replace all query params with hard paths, this is a temporary fix.
> chore: re-enable link errors and support query strings in md

- docs/lib/predictions/fragments/ios/text-speech.md
I found the code sample did not actually emit audio :(.  Seems like `player` needs to be saved in an instance variable and stick around in memory in order for the audio to be played.  Previously player was going out of scope, and the audio was not being played.
> Instructions and code sample: text to speech

- client/stencil.config.ts
*Issue #, if available*: n/a
*Description of changes:* Reload page on changes in development
For whatever reason, the default reload behavior of Hot Module
Replacement is not working within this project which results in the
content author being forced to tediously reload on changes. This change
configures the behavior to `pageReload` which will do a full refresh of
the page on rebuild.
See: https://stenciljs.com/docs/dev-server#dev-server-config
By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.
> Reload page on changes in development

- docs/sdk/auth/fragments/ios/federated-identities.md
**Note** this should not be merged until we release https://github.com/aws-amplify/aws-sdk-ios/pull/2425, since code snippets in the documentation reference enum values that were added in that PR.
> Add Sign in with Apple federated identity docs for iOS

- docs/sdk/auth/fragments/android/federated-identities.md
Add documentation for Sign in with Apple via Amazon Cognito Identity Pools.
**Note:** The code snippet has not yet been tested and should be verified before merging.
> Add Sign in with Apple federated identity docs for Android

- capi/src/init-node/index.ts
- client/src/amplify-ui/code-block/__snapshots__/code-block.spec.ts.snap
- client/src/amplify-ui/code-block/code-block.spec.ts
- client/src/amplify-ui/code-block/code-block.tsx
- client/src/components.d.ts
- docs/lib/analytics/getting-started.md
*Description of changes:* Hide copy button for console snippets
Right now, we show the copy button for output that's meant to be
expository rather than a block we expect a developer to copy and paste.
The most common example is CLI output: while this is useful to see to
understand what options should be selected, there's no value in copying
it into your clipboard.
This change suppresses the copy button if the language is set to
"console" which is defined in Linguist. See: https://bit.ly/2XsAkBq
> Hide copy button for console snippets

- docs/lib/graphqlapi/fragments/android/getting-started.md
Since `api` does not require `auth`, the sample code should not include initialization of AWSMobileClient, because AWSMobileClient requires `auth`.   Initializing AWSMobileClient without auth configured results in a RuntimeException.
> GraphQL API Sample Code Update

- docs/cli/auth/triggers.md
Updating the code sample to send a user variable instead of an string based on the context.
> Send user instead of string

- client/src/docs-ui/menu/menu.tsx
*Description of changes:* Swap SDK and Libraries
Once Libraries are GA we can swap them back (and remove the parentheticals) but at the moment the default option being second doesn't make a lot of sense.
> Swap SDK and Libraries in Slider

- capi/src/write/sitemap.ts
- client/src/sitemap.xml
- Keeping datemod accurately up to date is non-trivial
- Datemod is mostly ignored by search crawlers
- Remove datemod until we have a more dynamic solution
> Remove datemod from sitemap

- client/src/amplify-ui/code-block/__snapshots__/code-block.spec.ts.snap
- client/src/amplify-ui/code-block/code-block.spec.ts
- client/src/amplify-ui/code-block/code-block.style.tsx
- client/src/amplify-ui/code-block/code-block.tsx
- client/src/components.d.ts
*Description of changes:* Suppress line numbers for console blocks
Line numbers aren't particularly meaningful for console output blocks, so this change suppresses them. As a result, it renames `oneLineStyle` to `noLineNumbersStyle`.
- Extract "console" to constant
- Make lineNumbers property a number (instead of parsing it later), and
not optional
- Make language not optional
**Before**
**After**
> Suppress line numbers for console blocks

- docs/lib/graphqlapi/advanced-workflows.md
- docs/lib/graphqlapi/fragments/js/complex-objects.md
Fixes: #1693 
Adding missing docs to the API GraphQL section - docs v1 [reference](https://aws-amplify.github.io/docs/js/api#complex-objects)
> fix(api-graphql-docs) add missing docs

- docs/lib/push-notifications/fragments/js/getting-started.md
N/A no issue # open
Updated Push notifications getting started guide to use the new @react-native-community/push-notification-ios library for iOS as the react native library as been deprecated and recommends this community library.
Also modernised the documentation on this page to reflect react native 0.60 no longer requiring linking and prefers just a pod install command to update libraries needed for native compilation
> Updated iOS Push Notifications guide

- docs/cli/start/install.md
It takes two clicks and a scroll to get to the CLI install command. Moving it above the fold.
> Tweak the cli install command to be above the fold

- client/src/utils/transform-search-data.ts
lvl1 is no longer accounted for in search results, which means we add the given filter label to the lvl0.
> fix: include filter in lvl0, not lvl1

- docs/cli/graphql-transformer/directives.md
fix: #1666 - document default limits and missing @searchable arguments
fix: #947 fix supported auth modes for @auth and `oidc` provider
chore: fix table alignments, add missing `graphql` specified for snippets
> fix: #1666 and #947 limit and auth modes documentation for direcives

- docs/start/getting-started/data-model.md
- docs/start/getting-started/fragments/common/data-model-footer.md
- docs/start/getting-started/fragments/common/nextsteps-header.md
- docs/start/getting-started/fragments/common/prereq.md
- docs/start/getting-started/installation.md
- docs/start/getting-started/nextsteps.md
- docs/start/getting-started/setup.md
The content for iOS and Android's getting started is getting replaced. 
**This PR moves existing content out of the way**.
Therefore, by applying these changes, you should see the following.  Notice that ReactNative is unchanged, but iOS and Android have nothing:
**iOS**
**Android**
**ReactNative**
> Move existing getting-started content out for iOS and Android

- client/src/docs-ui/menu/menu.tsx
- client/src/docs-ui/secondary-nav/secondary-nav.tsx
- client/src/docs-ui/select-anchor/select-anchor.tsx
- docs/fragments/lib/android-sdk.md
- docs/fragments/lib/android.md
- docs/fragments/lib/ios-sdk.md
- docs/fragments/lib/ios.md
Proposal for how the landing page for libraries looks for iOS:
**Updates include:**
* Put back the switcher
* Using nothing/Legacy -- please give feedback here
* **Amplify Library iOS**
* Removed reference to preview
* Added callout
* **Amplify Library Android**
* Removed reference to preview
* Added callout
* **AWS SDK iOS**
* Removed references to preview
* Added FAQ question per comments
* **AWS SDK Android**
* Removed references to preview
* Added FAQ question per comments
Proposal for how the landing page for libraries looks for iOS
Proposal for how the landing page for libraries looks for Android:
Proposal for how the landing page for SDK looks for iOS
Proposal for how the landing page for SDK looks for Android:
By submitting this pull request, I confirm that you can use, modify, …
> Remove references to preview for amplify libs

- docs/sdk/analytics/endpoints.md
- docs/sdk/analytics/events.md
- docs/sdk/analytics/getting-started.md
- docs/sdk/analytics/kinesis.md
- docs/sdk/api/graphql.md
- docs/sdk/api/rest.md
- docs/sdk/auth/custom-auth-flow.md
- docs/sdk/auth/device-features.md
- docs/sdk/auth/drop-in-auth.md
- docs/sdk/auth/federated-identities.md
- docs/sdk/auth/getting-started.md
- docs/sdk/auth/guest-access.md
- docs/sdk/auth/hosted-ui.md
- docs/sdk/auth/how-it-works.md
- docs/sdk/auth/working-with-api.md
- docs/sdk/fragments/android/library-callout.md
- docs/sdk/fragments/ios/library-callout.md
- docs/sdk/fragments/library-callout.md
- docs/sdk/pubsub/getting-started.md
- docs/sdk/pubsub/working-api.md
- docs/sdk/push-notifications/getting-started.md
- docs/sdk/push-notifications/messaging-campaign.md
- docs/sdk/push-notifications/setup-push-service.md
- docs/sdk/sdk.md
- docs/sdk/storage/configure-access.md
- docs/sdk/storage/getting-started.md
- docs/sdk/storage/graphql-api.md
- docs/sdk/storage/transfer-utility.md
*Description of changes:* We recommend to developers to start new applications with the Amplify
Libraries. This pull puts a callout on the top of every SDK page promoting the Libraries. albrid@ provided the copy.
> Put banner on top of SDK pages

- client/src/amplify-ui/code-block/code-block.tsx
*Description of changes:* Users currently can't hit the copy button more than once. On the second press it will say "failed to copy."
It appears we're using a ref to keep a handle on the div to grab its textContent. When the component unmounts, React calls the binding with null to prevent memory leaks.  When it mounts, React will call the binding again with the element.  Apparently in some browsers these callbacks happen out of order, such that we override our reference with null. The React documentation lightly hints at this possibility: https://reactjs.org/docs/refs-and-the-dom.html#callback-refs. This
change ignores calls with null as an argument.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Fix copy button to work more than once

- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
- docs/start/getting-started/fragments/android/native_setup.md
*Description of changes:* Changes for issues in IDE integration
This weekend, several issues became apparent in testing our IDE
integration:
- The 1.0.0 we cut on Friday will need to be replaced with a patch
release as the previous one did not work properly on Windows
- It also wasn't available on jCenter as of Sunday afternoon, 36+ hours
later, meaning we'll need to specify mavenLocal() in another
configuration block
This change increments to 1.0.1 (not yet released, pending testing on
Tuesday) and adds another mavenLocal() to the tutorial and project setup
sections.
> Changes for issues in IDE integration

- client/src/docs-ui/choose-anchor/choose-anchor.tsx
*Description of changes:* Since we want to direct the user to /lib from now on, this code is no longer necessary. Removing the function and inlining the small piece that returns the list of pages.
> Remove logic to patch in SDK paths

- docs/lib/graphqlapi/fragments/android/getting-started/10_preReq.md
- docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
- docs/lib/graphqlapi/fragments/android/getting-started/30_initapi.md
- docs/lib/graphqlapi/fragments/android/getting-started/40_codegen.md
- docs/lib/graphqlapi/fragments/android/getting-started/50_createtodo.md
- docs/lib/graphqlapi/fragments/android/mutate-data.md
- docs/lib/graphqlapi/fragments/android/query-data.md
- docs/lib/graphqlapi/fragments/android/subscribe-data.md
- docs/lib/graphqlapi/fragments/ios/getting-started/10_preReq.md
- docs/lib/graphqlapi/fragments/ios/getting-started/20_installLib.md
- docs/lib/graphqlapi/fragments/ios/getting-started/30_initapi.md
- docs/lib/graphqlapi/fragments/ios/getting-started/40_codegen.md
- docs/lib/graphqlapi/fragments/ios/getting-started/50_createtodo.md
- docs/lib/graphqlapi/fragments/ios/mutate-data.md
- docs/lib/graphqlapi/fragments/ios/query-data.md
- docs/lib/graphqlapi/fragments/ios/subscribe-data.md
- docs/lib/graphqlapi/fragments/native_common/getting-started/common.md
- docs/lib/graphqlapi/getting-started.md
API docs for GraphQL
- migrate structure to Storage doc's getting started.
- consolidate to Todo schema (Android was using Blog schema)
- update iOS code snippets to use latest Model-based API calls
- updated Android code snippets to use Todo class instead of Blog
- reordered the sections to be the rest of mutation/query/subscriptions before concepts and configure authorization modes
Future section ideas
- "Authorizing API calls with Amplify Auth" for owner based auth models.
- "Advanced schemas" enums, lists, connections
> [Native][AmplifyAPIGraphQL] doc updates

- docs/lib/project-setup/fragments/ios/create-application/40_verifyAmplifyLibraries.md
@royjit found a difference in behavior for an empty config.. updating the configuration to:
* Remove the error that was coming up before
* Described how to turn on logging.
> Update create your application with logging and remove error

- docs/lib/storage/fragments/native_common/getting-started/common.md
bucketnames need to be all lowercased.
> updating storagebucket name to be all lowercase

- docs/docs.md
- docs/fragments/features-grid.md
Updating front page to direct users to amplify lib instead of sdk
> Direct users to amplify lib instead of sdk

- docs/lib/datastore/conflict.md
- docs/lib/datastore/fragments/ios/conflict.md
- docs/lib/datastore/fragments/ios/data-access/query-predicate-multiple-snippet.md
- docs/lib/datastore/fragments/ios/data-access/query-predicate-snippet.md
- docs/lib/datastore/fragments/ios/relational/query-snippet.md
- docs/lib/datastore/relational.md
1.  perhaps this is an xcode issue? i'm on 11.3.1
2.
**Removed this change from this PR due merge conflict**
3. Following the Non-relational sections have a Post model with optional rating, status. moving to relational then uses required fields, this breaks some of the existing functions i had added as i was following along. updating the schema to use optionals to match previous Post model in the relational example
```
type Post @model {
id: ID!
title: String!
rating: Int // keep optional
status: PostStatus // keep  optional
comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}
```
4. The lazy loading of comments is amazing! This is a minor change here to replace the comment about fetching with DataStore.query just to make …
> [iOS] [datastore] run-through sections updates

- client/src/docs-ui/page/page.tsx
Normalizes trailing slashes. `lib/q/platform/js/` just as good as `lib/q/platform/js`.
> chore: strip trailing slash if present in pathname

- docs/lib/datastore/fragments/ios/real-time/observe-snippet.md
Previous example used a Combine subscription that was released at the end of the method, which would cause Combine to release the subscription
Fixes #1865
> fix: Retain subscription in publisher example

- docs/fragments/lib/android.md
- docs/fragments/lib/ios.md
*Description of changes:* Starting the Libraries page off with an explanation about how it is different from another offerrng is strange. Rather than rewording it, let's nix it.
> Remove FAQ question from Libraries page

- docs/lib/predictions/fragments/ios/getting-started/30_installLib.md
- docs/lib/predictions/fragments/ios/getting-started/40_init.md
- docs/lib/predictions/fragments/ios/getting-started/50_translate.md
Addressing bug found in documentation here:
https://github.com/aws-amplify/docs/issues/1900
> fix: predictions to reference auth category

- docs/lib/auth/fragments/android/getting_started/30_initAuth.md
Users who are getting started want to copy/paste from this tutorial.
Several users were receiving a runtime failure resulting from not calling `Amplify.configure`.
We can help prevent this situation by including `Amplify.configure` into the auth setup documentation.
> fix: tweak android auth init steps

- docs/lib/datastore/fragments/android/real-time/observe-snippet.md
*Description of changes:* We don't use a Java getter for item, thus bare `item` won't work here. We have to call the method.
> Fix callback to call method

- cspell.json
- docs/lib/auth/fragments/js/manageusers.md
- docs/lib/auth/fragments/js/start.md
*Issue #:* #1904 (#1138, #983 and #1687)
*Description of changes:* This PR fixes examples on how to create a custom storage object.
- #1138, #983: Update references from MemoryStorage to MyStorage
- #1687: Pass an uninitialized class, instead of an initialized one, as a storage object
> Update docs on customized storage objects

- docs/sdk/auth/fragments/ios/federated-identities.md
- docs/sdk/auth/fragments/ios/getting-started.md
- docs/sdk/pubsub/fragments/ios/getting-started.md
*Description of changes:* This change removes the pod file version for AWS iOS dependencies, so that the app will take the latest version of SDK.
> chore: Remove the version number from the podfile dependency

- docs/lib/predictions/fragments/ios/getting-started/50_translate.md
- docs/lib/predictions/fragments/ios/identify-entity.md
- docs/lib/predictions/fragments/ios/identify-text.md
- docs/lib/predictions/fragments/ios/interpret.md
- docs/lib/predictions/fragments/ios/label-image.md
- docs/lib/predictions/fragments/ios/text-speech.md
- docs/lib/predictions/fragments/ios/transcribe.md
- docs/lib/predictions/fragments/ios/translate.md
**Notes:**
- Amplify.Predictions code snippets were using the outdated callback
model and developers using current version could not compile their code
- All snippets were compiled in Xcode to verify their correctness
- All snippets were formatted using SwiftFormat to ensure consistency
- Removed unnecessary parameters for conciseness
**References:**
- Related to https://github.com/aws-amplify/amplify-ios/issues/614
> fix outdated iOS Predictions code snippets

- client/src/docs-ui/search-bar/__snapshots__/search-bar.spec.ts.snap
- client/src/docs-ui/search-bar/search-bar.style.ts
- client/src/docs-ui/search-bar/search-bar.tsx
- client/src/utils/transform-search-data.ts
- Bump search results from 5 to 10
- add responsive height with scrolling
- fix bug that was grouping all results under one heading (i.e. `Documentation (Android)`)
> Bump search results number

- docs/lib/analytics/existing-resources.md
- docs/lib/analytics/fragments/existing-resources.md
- docs/lib/analytics/menu.json
*Description of changes:* Users can use existing Amazon Pinpoint resources with the Analytics category but this was not documented. This change adds a page for iOS and Android that outlines that minimal configuration for Analytics to use existing resources.
> Add manual configuration for Analytics

- docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md
> fix: maven central not local in android datastore

- docs/lib/graphqlapi/fragments/native_common/getting-started/common.md
We've had a couple GitHub issues like https://github.com/aws-amplify/amplify-android/issues/591 as well as Discord users who have been getting errors using API due to conflict detection being enabled.  This adds a troubleshooting note to ensure conflict detection is disabled when using API.
> Add troubleshooting note to disable DataStore when using API category

- docs/lib/graphqlapi/existing-resources.md
- docs/lib/graphqlapi/fragments/existing-resources.md
- docs/lib/graphqlapi/fragments/native_common/authz/common.md
- docs/lib/graphqlapi/menu.json
*Issue #, if available:* #2094
*Description of changes:*  Adds a page showing iOS and Android developers how to use an existing AWS AppSync API.
- Fix typo in authorization documentation
> Docs for existing GraphQL API resources

- docs/lib/auth/fragments/js/emailpassword.md
- docs/lib/auth/fragments/js/mfa.md
Convert capital-cased function name to camelcase, making it consistent to other function names.
> Convert capital-cased function name to camelcase (typo)

- docs/lib/datastore/auth-model.md
- docs/lib/datastore/fragments/ios/auth-model.md
- Called out some limitation regarding using auth directive
- Adding new section called "Models with authorization"
- for JS and Android, current just shows in development amplify call out
- for iOS, added some content 
> [iOS][DataStore] Models with auth directive

- docs/lib/analytics/existing-resources.md
- docs/lib/auth/existing-resources.md
- docs/lib/graphqlapi/existing-resources.md
- docs/lib/restapi/existing-resources.md
- docs/lib/storage/existing-resources.md
*Issue #, if available:* #2139
*Description of changes:* Don't show existing resources section in JS
The self-closing tag used for inline-fragment is invalid which causes
this page to appear in the menu for JavaScript where we have no content.
This change puts in an explicit close tag which continues to render the
content and ensures it doesn't appear in the menu for JavaScript where
there isn't any content.
> Don't show existing resources section in JS

- docs/lib/storage/fragments/ios/getting-started/40_upload.md
https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios#initialize-amplify-storage
Corrected key name for code sample in https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios#initialize-amplify-storage
> Correct key name ("myKey" to "ExampleKey")

- docs/cli/graphql-transformer/directives.md
'to the mutation' doesn't make sense, since the context is talking about a query
> deleted some words

- cspell.json
- docs/lib/graphqlapi/fragments/graphql-from-node.md
issue: https://github.com/aws-amplify/amplify-cli/issues/4841
CLI PR: https://github.com/aws-amplify/amplify-cli/pull/4923
Rename the API key environment variable name to match our other env var naming convention.
> Rename api key env name

- js/api.md
Currently this example usage of Connect will always show the "error" state, as the connect callback is called with `errors: []` when successfully ran. 
This means people using this example code will see "error" in their app even though the request was successful and data has been retrieved. 
> Fix broken Connect component example

- docs/cli/graphql-transformer/directives.md
Self-explanatory, copy and paste the @auth definition into a new .graphql file and watch your IDE go crazy over `OBJECT, FIELD_DEFINITION`.
Change the incorrect syntax into correct syntax. I verified that the change matches up with the [actual implementation.](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-auth-transformer/src/ModelAuthTransformer.ts#L157)
Yes. lol
> Fix syntax typo in @auth definition

- docs/lib/storage/fragments/android/download.md
- docs/lib/storage/fragments/android/upload.md
Add Android code snippets to show how to use a progress listener callback for the uploadFile and downloadFile APIs.
> Add progress listener to Android storage

- docs/lib/auth/fragments/ios/hubEvents/10_listen_events.md
We recently annotated Amplify APIs that return AmplifyOperation subclasses with `@discardableResult`, since the operation is only necessary for cancellation. However, Hub APIs continue to return non-discardable UnsubscribeTokens, which must be used to remove registered listeners from Hub.
> chore: Clarify Auth.listen returns an unsub token

- docs/sdk/auth/fragments/android/hosted-ui.md
Turns out the manifestPlaceholder in the build.gradle was not enough and a copying of the activity in the AndroidManifest file was needed.
> Updates documentation for HostedUI fix

- docs/sdk/auth/fragments/android/hosted-ui.md
Since we're now adding a new activity to the AndroidManifest.xml file with an intent, clarified the cleanup step to specify which intent to remove.
>  Small tweak to HostedUI wording

- docs/guides/api-graphql/building-a-form-api.md
- docs/guides/api-graphql/graphql-pagination.md
- docs/guides/api-graphql/lambda-resolvers.md
- docs/guides/api-graphql/query-with-sorting.md
- docs/guides/api-graphql/subscriptions-by-id.md
- docs/guides/api-rest/express-server.md
- docs/guides/api-rest/go-api.md
- docs/guides/api-rest/node-api.md
- docs/guides/api-rest/python-api.md
- docs/guides/fragments/flutter/flutterAPIWarning.md
- docs/guides/fragments/flutter/flutterFuncWarning.md
- docs/guides/functions/cognito-trigger-lambda-dynamodb.md
- docs/guides/functions/connecting-a-rest-api.md
- docs/guides/functions/dynamodb-from-js-lambda.md
- docs/guides/functions/dynamodb-from-python-lambda.md
- docs/guides/functions/graphql-from-lambda.md
- docs/guides/functions/graphql-server-in-lambda.md
- docs/guides/functions/integrating-dynamodb-with-lambda.md
- docs/guides/guides.md
- docs/lib/storage/fragments/flutter/download.md
- docs/lib/storage/fragments/flutter/upload.md
Flutter Preview has no support for API so we want to warn developers not to read the flutter docs contained in Guides.
> Add Flutter Warning to Guides

- capi/src/inject/filtered-version-routes.ts
- capi/src/write/filters-by-route.ts
- docs/guides/api-graphql/building-a-form-api.md
- docs/guides/api-graphql/graphql-pagination.md
- docs/guides/api-graphql/lambda-resolvers.md
- docs/guides/api-graphql/query-with-sorting.md
- docs/guides/api-graphql/subscriptions-by-id.md
- docs/guides/api-rest/express-server.md
- docs/guides/api-rest/go-api.md
- docs/guides/api-rest/node-api.md
- docs/guides/api-rest/python-api.md
- docs/guides/fragments/flutter/flutterAPIWarning.md
- docs/guides/fragments/flutter/flutterFuncWarning.md
- docs/guides/functions/cognito-trigger-lambda-dynamodb.md
- docs/guides/functions/connecting-a-rest-api.md
- docs/guides/functions/dynamodb-from-js-lambda.md
- docs/guides/functions/dynamodb-from-python-lambda.md
- docs/guides/functions/graphql-from-lambda.md
- docs/guides/functions/graphql-server-in-lambda.md
- docs/guides/functions/integrating-dynamodb-with-lambda.md
- docs/guides/guides.md
*Description of changes:* Redirect Flutter users to platform docs
Instead of showing a warning on Guides, just redirect the user to the
existing documentation if they happen to use the Flutter dropdown on
this page. This is what we do on the SDK pages for JavaScript so it fits
an existing pattern, and it eliminates unnecessary pages. This also
fixes a bug on the SDK pages where using the Flutter dropdown would
result in a 404.
> Redirect Flutter users to platform docs

- docs/lib/project-setup/fragments/android/prereq/prereq.md
- docs/start/getting-started/fragments/android/setup.md
*Issue #, if available:* #2305 
*Description of changes:* Change Android Studio dependency
Due to changes in desugaring in Android Studio, we require the latest
version. This change moves the requirement to 4.0 which is the current
stable release.
> Change Android Studio dependency

- docs/lib/client-configuration/configuring-amplify-categories.md
- docs/lib/client-configuration/fragments/js/js-configuration.md
- docs/lib/client-configuration/menu.json
- docs/lib/menu.json
This PR adds a new top level nav item to the Libraries documentation showing all of the available configuration for `Amplify.configure`.
This PR is based on customer feedback around:
1. Bringing existing AWS resources when not using the Amplify CLI
2. Understanding what configurations are available
> Added new client configuration page and nav item for JS libraries

- docs/lib/graphqlapi/fragments/android/subscribe-data.md
Our subscribe example is currently broken. This fixes it.
> Removes double declaration

- docs/start/getting-started/fragments/android/setup.md
*Issue #, if available:* #2382 
*Description of changes:* Looks like we introduced a regression when adding fixes for multidex. This re-adds the imports.
> Add plugin imports in tutorial

- docs/ui/auth/fragments/web/authenticator.md
https://github.com/aws-amplify/docs/issues/2303
Fix incorrect back-tick to single quote
> Fix incorrect back-tick to single quote

- docs/start/getting-started/fragments/next/api.md
Related to https://github.com/aws-amplify/docs/issues/2397
https://docs.amplify.aws/start/getting-started/data-model/q/integration/next#api-with-incremental-static-site-generation-ssg references `pages/[id].js`, but should be `pages/posts/[id].js`.
> Fix path to pages/posts/[id].js

- client/src/docs-ui/choose-integration-anchor/__snapshots__/choose-integration-anchor.spec.ts.snap
- client/src/docs-ui/choose-integration-anchor/choose-integration-anchor.tsx
- client/src/styles/spacing-utils.scss
As we've been adding more platform support, our integration picker has been growing. This PR shrinks the amount of space the picker requires, so the customer can see all supported platforms at one glance.
New:
Old:
> Makes the integration picker fit onto one screen

- docs/start/getting-started/fragments/reactnative/getting-started-steps.md
**Don't merge until https://github.com/aws-amplify/amplify-js/pull/6817 is released**
Remove references to `react-native-vector-icons` in "Getting Started" instructions, as it is being removed as a dependency for `aws-amplify-react-native`.
---
> Remove react-native-vector-icons from getting started

- docs/lib/auth/fragments/js/getting-started.md
The angular path is incorrect to import awsconfig
For angular example, in app.module.ts, to reference awsconfig, the path would be '../aws-exports'; instead of './aws-exports';
> Fix angular example path

- docs/lib/datastore/fragments/android/sync/20-savePredicate.md
- docs/lib/datastore/fragments/android/sync/30-savePredicateComparison.md
The DataStore includes one query method which accepts a second parameter
of type `QueryOptions`. All other DataStore methods use only a
`QueryPredicate`.
The `Where.matches` utility method will convert a `QueryPredicate` into
a `QueryOptions`. This can be used as an adapter when dealing with the
`query(...)` method which accepts `QueryOptions`.
However, `save(...)` and `delete(...)` just take a predicate, itself.
So, we need to remove the `Where.matches(...)` bit from the
documentation. It doesn't compile.
> fix: Android DataStore ops that take predicate

- client/src/components.d.ts
- package.json
- yarn.lock
*Issue #, if available:* [#6852](https://github.com/aws-amplify/amplify-js/pull/6852)
*Description of changes:* With the latest rollup issue fix, we can safely bump aws-amplfiy versions to latest. This PR also uses "aws-amplify" imports in favor of modular imports.
I've tested it to run on `yarn start` and `yarn build && serve client/www` without any console errors.
> deps: bump aws-amplify to latest

- docs/lib/auth/fragments/js/manageusers.md
*Issue #, if available:* [amplify-js#6863](https://github.com/aws-amplify/amplify-js/issues/6863)
*Description of changes:* This explains what `Auth.forgotPassword` does prior to calling `Auth.forgotPasswordSubmit`.
> auth: add explanation to `forgotPassword(username)`

- docs/sdk/api/fragments/android/rest.md
The `AWSMobileClient` *is an* `AWSCredentialsProvider`, it is not
composed of one. The documentation imagined a fictitious
`getCredentialsProvider()` accessor method on the `AWSMobileClient`,
which does not exist.
This was found by user oras@ on Discord; thanks.
> fix: compiler error in android sdk auth docs

- docs/lib/auth/fragments/js/advanced.md
https://github.com/aws-amplify/amplify-js/issues/7015
With Identity Pool Federation, automatic token refresh for Google & Facebook is not supported in React Native due to the reliance on the web SDKs:
https://github.com/aws-amplify/amplify-js/blob/34de0f252ddea559a6bc959610522cc19fe340f6/packages/core/src/OAuthHelper/GoogleOAuth.ts#L25
https://github.com/aws-amplify/amplify-js/blob/34de0f252ddea559a6bc959610522cc19fe340f6/packages/core/src/OAuthHelper/FacebookOAuth.ts#L24
This just adds a callout so the current behavior is more explicit.
> add refresh token note for React Native

- docs/lib/analytics/fragments/existing-resources.md
- docs/lib/auth/fragments/existing-resources.md
- docs/lib/graphqlapi/fragments/existing-resources.md
- docs/lib/restapi/fragments/existing-resources.md
- docs/lib/storage/fragments/existing-resources.md
Following up on a request from @renebrandel and @mohitsriv to add a note to the "Use Existing Resources" topic in each of the following iOS and Android categories that provides customers with a link to how to install the Amplify libraries:
Analytics
API(GraphQL)
API(REST)
Authentication
Storage
> Added links to Amplify libraries installation

- docs/start/getting-started/fragments/reactnative/setup.md
aws-amplify/amplify-cli#5483
The wrong directory path `/` is included in the documentation. Changing to the correct paths `./` fixes the issue mentioned above.
*Other notes:*
`amplify-cli` PR: aws-amplify/amplify-cli#5654
> fix(reactnative): correct directory path

- docs/start/getting-started/fragments/next/api.md
> Revert "Fix Next.js link & remove from UI drop-down"

- docs/cli/graphql-transformer/directives.md
- docs/cli/plugins/plugins.md
- added `@ttl` 3rd party directive to the docs
- moved custom transformer & directives section into a note
> Adding `@ttl` directive to the docs

- docs/lib/auth/fragments/js/social.md
Fix a typo in the program `isLocalhost` in the 'Configure Auth Categor' section of social.md.
> Fix typo 'isLocalhost' in social.md

- .github/workflows/spellcheck.yml
*Description of changes:* Currently the entire test suite must run whenever docs change. This splits the workflow into two parts: spellcheck which runs on every pull request and test which ignores changes made in the docs directory.
> Don't run tests on docs changes

- docs/start/getting-started/fragments/angular/setup.md
I got `ng: command not found` when going through the Angular getting started tutorial. Seems like this command fixes the issue.
> fix: update Angular install command

- client/src/components.d.ts
- docs/lib/auth/fragments/js/getting-started-steps-basic-auth.md
- docs/lib/auth/fragments/js/getting-started.md
- docs/lib/datastore/fragments/js/getting-started/30_platformIntegration.md
- docs/start/getting-started/fragments/reactnative/auth.md
- docs/start/getting-started/fragments/reactnative/getting-started-steps-ui.md
- docs/start/getting-started/fragments/reactnative/setup.md
- Update Auth & DataStore install instructions for React Native.
- Specifically, call out when `amazon-cognito-identity-js` & `@react-native-community/netinfo` are needed.
https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#configure-your-application
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#setup-local-development-environment
http://localhost:3333/start/getting-started/auth/q/integration/react-native#create-login-ui
> fix: update Auth & DataStore install instructions for React Native

- docs/lib/auth/fragments/existing-resources.md
- docs/lib/auth/fragments/flutter/existing-resources.md
- docs/lib/graphqlapi/fragments/native_common/authz/common.md
- docs/lib/restapi/fragments/android/authz.md
- docs/lib/restapi/fragments/ios/authz.md
- docs/sdk/analytics/fragments/android/events.md
- docs/sdk/analytics/fragments/ios/events.md
- docs/sdk/api/fragments/android/graphql.md
- docs/sdk/api/fragments/ios/graphql.md
- docs/sdk/auth/fragments/android/custom-auth-flow.md
- docs/sdk/auth/fragments/android/getting-started.md
- docs/sdk/auth/fragments/ios/custom-auth-flow.md
- docs/sdk/auth/fragments/ios/getting-started.md
- docs/sdk/auth/fragments/ios/hosted-ui.md
- docs/sdk/configuration/fragments/ios/setup-options.md
- docs/sdk/push-notifications/fragments/ios/getting-started.md
- docs/start/getting-started/fragments/vanillajs/nextsteps.md
*Description of changes:* Cognito User Pools app clients do not require a secret to operate. Removing references to this configuration element to make it clear it isn't necessary.
> Remove AppClientSecret references

- docs/lib/datastore/fragments/android/setup-auth-rules/owner_based_auth_oidc.md
- docs/lib/datastore/fragments/native_common/setup-auth-rules.md
- Adds an Android section for how to provide your own `OidcAuthProvider`.  
- Corresponding iOS PR: https://github.com/aws-amplify/docs/pull/2613
- Screenshot:
> feat(datastore) Add Android section for OIDC auth provider

- docs/start/getting-started/fragments/ios/add-api.md
The example for subscribing to mutation events did not include a clear way to decode and switch logic based on the . This update includes an example of how to accomplish the two, making it clear to the user how to handle an object that was created, updated, or deleted.
> Update subscription example in iOS Getting Started

- docs/lib/pubsub/fragments/js/getting-started.md
Our [official documentation](https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js#aws-iot) shows to import from the `lib` folder of `node_modules` in order to reference the providers folder which has the potential for being tree shaken out within Angular 9+ applications. Please see this [issue](https://github.com/aws-amplify/amplify-js/issues/7085). 
> fix:Update pubsub import path

- docs/start/getting-started/fragments/android/setup.md
Currently in the Android getting started guide, the minimum SDK version link isn't rendered properly. 
Added blank lines around the callout component to ensure link renders properly.
> Making link pretty in Android getting started

- docs/cli/usage/lambda-triggers.md
Removed the "d" from associated
before: "You can also associated a Lambda trigger with...."
after: "You can also associate a Lambda trigger with...."
> Update to fix grammatical error/typo in lambda-triggers.md

- client/src/amplify-ui/cli-feature-flag/feature-flags.json
https://github.com/aws-amplify/amplify-cli/issues/5554
corresponding CLI PR: https://github.com/aws-amplify/amplify-cli/pull/5745
The CLI is adding a feature flag around gql schema reserved word validation. This PR adds docs for the FF.
> gql validation ff docs

- docs/fragments/lib/js.md
Removing the blurb in regards to the AWS SDK v3 for JavaScript callout. The AWS SDK team supports all use cases for Amplify in their version 3.
> fix:remove AWS SDK 3 callout

- client/src/components.d.ts
- client/src/docs-ui/page/page.tsx
- client/src/docs-ui/secondary-nav/__snapshots__/secondary-nav.spec.ts.snap
- client/src/docs-ui/secondary-nav/secondary-nav.tsx
Just what it says in the title.  See the bug report for more info
Corrected behavior due to these changes.
> Only show menu open button when page has a menu

- docs/lib/auth/fragments/js/social.md
https://github.com/aws-amplify/amplify-js/issues/6122
- Add section for "Known Limitations" to be more explicit about any differences when using `federatedSignIn`
- Call out that device tracking & remembering is not supported at this time
> Add known limitations to JS OAuth docs

- docs/lib/datastore/fragments/ios/sync/19-sync-save-delete-predicate.md
- docs/lib/datastore/fragments/native_common/sync-save-delete-predicate.md
- docs/lib/datastore/fragments/native_common/sync.md
*Description of changes:* iOS currently doesnot support delete with predicate in Datastore. This PR removes the documentation regarding this
> fix(datastore): Remove predicate documentation from delete in iOS

- docs/lib/project-setup/fragments/native_common/prereq/common_header.md
Link to the NPM downloads page instead of the landing page, which has no clear call to action.
> Link to NPM downloads page instead of landing page

- docs/lib/push-notifications/fragments/js/getting-started.md
- Adding FCM ApiKey location to push notification docs
While trying to solve https://github.com/aws-amplify/amplify-js/issues/7131 I found it very hard to find the FCM Apikey, even @mauerbac can attest to this. I think we were looking in the wrong place, but there was nothing about the same in the docs.
Simply added a line with the exact link of where you can find this ApiKey
Source: https://stackoverflow.com/questions/37337512/where-can-i-find-the-api-key-for-firebase-cloud-messaging
> Update push notification docs

- docs/lib/datastore/fragments/ios/other-methods.md
formatting is off for this new page. It is currently showing:
> fix(DataStore): documentation formatting for other methods

- docs/lib/project-setup/fragments/flutter/prereq/cliInstall.md
- docs/start/getting-started/fragments/flutter/add-api.md
- docs/start/getting-started/fragments/flutter/setup.md
Update Flutter setup instructions to not use the preview tag for CLI
> Update setup to not use preview tag for CLI

- docs/ui/auth/fragments/react/auth-state-management.md
*Issue #, if available:* [amplify-js#7123](https://github.com/aws-amplify/amplify-js/issues/7123)
*Description of changes:* This removes the return keyword within `useEffect`.
> Remove return keyword within useEffect

- docs/lib/datastore/fragments/flutter/sync/10-installPlugin.md
*Description of changes:* Temporarily remove the `add API plugin` section since we don't have an API plugin and we automatically add if we detect the api configuration in `amplifyconfiguration.dart`.
This change will be reverted once we release the API plugin.
> Update flutter datastore sync docs for developer preview

- docs/lib/datastore/fragments/js/data-access/query-single-item-snippet.md
- docs/lib/datastore/fragments/js/real-time/observe-snippet.md
- docs/lib/datastore/fragments/native_common/data-access.md
Added the following updates:
1. Instructions for querying for single item by ID
2. Closing a subscription
> Sidenote - I think that it would make sense to document __1__ on other platforms as well as, from what I can tell, we assume this knowledge as of now by just referencing it as _an instance of a model_ (i.e., [here](https://docs.amplify.aws/lib/datastore/data-access/q/platform/ios#delete))
> Added minor updates to javascript datastore

- docs/lib/project-setup/fragments/flutter/prereq/prereq.md
#2751 
Bumps the minSDK version for amplify-flutter w/ Android.
> fix(amplify_flutter) cites correct minSDK version for android in flutter

- docs/cli/usage/containers.md
To add note about auth needing to be added manually for the hosting scenario as it doesn't initiate the flow
> Add note about auth on hosting category

- docs/lib/analytics/fragments/existing-resources.md
The Analytics existing resources snippet lacks a pinpointTargeting section, which causes at least the iOS plugin to fail
> fix: Add pinpointTargeting to existing resources

- docs/sdk/push-notifications/fragments/android/handle-fcm.md
https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/android#handling-fcmgcm-push-notifications
The sample code of `Adding Receiver` has double quotation mark errors which is not suitable for programming language.
So I fixed it.
> fix double quotation mark errors

- docs/sdk/push-notifications/fragments/android/handle-fcm.md
https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/android#open-a-deep-link
The code example above uses DeepLinkActivity but the code example below uses DeeplinkActivity.
If you use this example as it is, it will not be compiled.
So I changed below DeeplinkActivity to DeepLinkActivity (Lower case letter changed to upper case)
> fix a case-sensitive error in the DeepLink example

- docs/ui/auth/fragments/web/authenticator.md
Replace `AmplifySignOut` with a `AmplifyGreetings` which is actually used in the example code.
> Fix import module in Greetings example with React

- docs/cli/usage/customcf.md
The language on https://docs.amplify.aws/cli/usage/customcf is not clear how to keep the file names of custom templates unique. The code uses a glob here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/push-resources.js#L30
> Clarify how to keep the file names for custom cf templates unique

- docs/lib/datastore/fragments/android/relational/save-many-snippet.md
In the portion of Android DataStore documentation discussing
many-to-many relationships, there is a code snippet showing a
triple-nested saved. This code is accompanied by a note "we're working
on ways to improve this experience." It is an out-of-date note. Since
the callout was written, we have improved the experience by adding
support for RxJava. The note is updated to highlight RxJava as a
possible solution to the nested callbacks.
> fix: advertise rxjava as solution to nested android calls

- docs/lib/datastore/fragments/js/sync/50-selectiveSync.md
In JavaScript's documentation of the Selective Sync feature for
DataStore, `(c)` is used as the single parameter name in most of the
lambdas that are shown. Ostensibly, this parameter name was selected to
represent a `Comment` model, which is one of the types referenced in the
documentation. It is *also* used for `Post` and `User`, which makes no
sense.
To remedy this, we just use full nouns, instead: `user`, `post`, `comment`.
In all places where non-`Comment` models are referenced, the updated name
is used, in place of `c`.
Additionally, the optional parentheses are dropped, as JavaScript allows
for single-parameter arrow functions.
> fix: use sensible param names in arrow functions

- client/src/docs-ui/ui-component-props/ui-component-props.tsx
To handle re-render in stencil's component lifecycle, it needs to use `componentWillRender` instead of `componentWillLoad` when app uses stencil-router.
Fixes: https://github.com/aws-amplify/docs/issues/2703
Refs: https://stenciljs.com/docs/component-lifecycle
> fix: handle re-render in ui-component-props

- docs/lib/analytics/fragments/android/getting-started/20_installLib.md
- docs/lib/auth/fragments/android/getting_started/20_installLib.md
- docs/lib/datastore/fragments/android/getting-started/20_installLib.md
- docs/lib/datastore/fragments/android/getting-started/30_platformIntegration.md
- docs/lib/datastore/fragments/android/sync/10-installPlugin.md
- docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
- docs/lib/graphqlapi/fragments/android/getting-started.md
- docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
- docs/lib/predictions/fragments/android/getting-started/30_installLib.md
- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
- docs/lib/project-setup/fragments/android/rxjava/rxjava.md
- docs/lib/restapi/fragments/android/getting-started/20_installLib.md
- docs/lib/storage/fragments/android/getting-started/20_installLib.md
- docs/start/getting-started/fragments/android/setup.md
Core Desugaring is at 1.1.1.
Amplify Android is at 1.6.8.
Amplify Tools Gradle Plugin is at 1.0.2.
Android Gradle Plugin is at 4.1.1.
> fix: update amplify android dependency versions

- docs/lib/graphqlapi/fragments/js/mutate-data.md
copy and paste error, code example was showing the same sample as previous box. The text right before the code sample was referencing an example with graphqlOperation
> fix wrong code example

- docs/cli/usage/customcf.md
Custom AWS Resources is a clearer and better name IMO, especially for devs new to AWS.
> Rename custom cloudformation stacks to custom aws resources

- docs/start/getting-started/fragments/next/api.md
In ["Connect API and database to the app" section of Next.js tutorial](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next), there is the below instruction:
> Select the explicit values below to enable IAM (for public read access) and Cognito User Pools (for authenticated access).
However, you use not IAM but API key for public access throughout the section.
I have replaced IAM with API key to meet the context.
> fix: wrong authorization type in Next.js tutorial

- docs/ui/auth/fragments/web/authenticator.md
The links were not pointing to the correct id's, so it wasn't possible to jump to right place to see what properties you could be passing in.
N/A
I updated the anchor tags to point to `#props-attr-amplify-authenticator` instead of `#props-amplify-authenticator`, since `#props-amplify-authenticator` doesn't seem to link to anything on the page.
> Fix anchor links in React docs for Auth Props

- client/src/utils/track.ts
Fix: Just guard all `s` accesses
Locally validated!
The issue is that the `s_code` is blocked as an analytics library, which makes `s` undefined.
> Fix adblocker breaking docs site

- docs/cli/auth/admin.md
Updates to make clear:
1. The limit as defined [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html#CognitoUserPools-ListUsers-request-Limit)
2. Clarification in the introduction of Admin Actions documentation
> Updates to admin queries docs

- docs/cli/graphql-transformer/searchable.md
added some additional comments on where to obtain the script parameters
the linked script had a different actual name than the codeblock showed
my change edits the code block to reflect the correct script name.  The other comments were just about clarifying where the parameters can be obtained, since the examples had just partial replacements and might be confusing to some (i.e. they might just lookup their api__id and not replace the others).
> update minor misspelling of the script name

- client/src/docs-ui/menu/menu.style.ts
`overflow: overlay` doesn't work on non-Webkit browsers.
> Fix footer on Firefox

- docs/lib/analytics/fragments/android/getting-started/20_installLib.md
- docs/lib/auth/fragments/android/getting_started/20_installLib.md
- docs/lib/datastore/fragments/android/getting-started/20_installLib.md
- docs/lib/datastore/fragments/android/sync/10-installPlugin.md
- docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
- docs/lib/graphqlapi/fragments/android/getting-started.md
- docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
- docs/lib/predictions/fragments/android/getting-started/30_installLib.md
- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
- docs/lib/project-setup/fragments/android/rxjava/rxjava.md
- docs/lib/restapi/fragments/android/getting-started/20_installLib.md
- docs/lib/storage/fragments/android/getting-started/20_installLib.md
- docs/start/getting-started/fragments/android/setup.md
Now Amplify Android is at 1.6.9.
> fix: update amplify android dependency version to 1.6.9

- client/src/docs-ui/menu/menu.style.ts
Based on discussion in [this PR](https://github.com/aws-amplify/docs/pull/2839) -- `auto` is preferred over `scroll` because there's no scroll bar if not required.
> Update overflow behavior again: thank you @wlee221!

- docs/start/getting-started/fragments/flutter/integrate.md
- docs/start/getting-started/fragments/flutter/setup.md
*Original PR* https://github.com/aws-amplify/docs/pull/2851
*Description of changes:* Update flutter getting started code samples as per refactor
> Update flutter getting started code samples as per refactor

- docs/start/getting-started/fragments/next/api.md
There is wrong file path in ["Connect API and database to the app" section of Next.js tutorial](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next).
When you follow the tutorial instruction, `schema.graphql` file should be placed in `amplify/backend/api/nextamplified/`.
> fix: schema file path in Next.js tutorial

- docs/lib/datastore/fragments/ios/sync/19-sync-save-delete-predicate.md
- docs/lib/datastore/fragments/native_common/sync-distributed-data.md
- docs/lib/datastore/fragments/native_common/sync-save-delete-predicate.md
This reverts https://github.com/aws-amplify/docs/pull/2636 
> fix(datastore): revert Remove predicate documentation from delete in iOS

- docs/lib/analytics/fragments/android/getting-started/20_installLib.md
- docs/lib/auth/fragments/android/getting_started/20_installLib.md
- docs/lib/datastore/fragments/android/getting-started/20_installLib.md
- docs/lib/datastore/fragments/android/sync/10-installPlugin.md
- docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
- docs/lib/graphqlapi/fragments/android/getting-started.md
- docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
- docs/lib/predictions/fragments/android/getting-started/30_installLib.md
- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
- docs/lib/project-setup/fragments/android/rxjava/rxjava.md
- docs/lib/restapi/fragments/android/getting-started/20_installLib.md
- docs/lib/storage/fragments/android/getting-started/20_installLib.md
- docs/start/getting-started/fragments/android/setup.md
Amplify Android has moved from 1.6.11 to 1.16.11.
See [the Amplify Android 1.16.11 release notes](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.16.11) for more details.
> Advertise 1.16.11 as the current Android version

- client/src/amplify-ui/external-link/external-link.tsx
- client/src/components.d.ts
- client/src/docs-ui/card/__snapshots__/card.spec.ts.snap
- client/src/docs-ui/card/card.tsx
- client/src/docs-ui/choose-integration-anchor/__snapshots__/choose-integration-anchor.spec.ts.snap
- client/src/docs-ui/choose-integration-anchor/choose-integration-anchor.tsx
- client/src/docs-ui/internal-link-button/__snapshots__/internal-link-button.spec.ts.snap
- client/src/docs-ui/internal-link-button/internal-link-button.tsx
- client/src/docs-ui/internal-link/internal-link.tsx
- client/src/docs-ui/landing-hero-cta/__snapshots__/landing-hero-cta.spec.ts.snap
- client/src/docs-ui/landing-hero-cta/landing-hero-cta.tsx
- client/src/docs-ui/page/page.tsx
- client/src/docs-ui/search-bar/search-bar.tsx
- client/src/utils/track.ts
- client/src/utils/transform-search-data.ts
- Adobe Analytics doesn't send an `eVar` if its value is equal to 0, even if it's in the list of `eVar`s to send.
> Adobe Analytics -- second round of changes!

- docs/lib/project-setup/fragments/ios/create-application/40_verifyAmplifyLibraries.md
https://github.com/aws-amplify/docs/issues/2823
Adds a note regarding how to get set up with the new SwiftUI App lifecycle
> fix(ios-getting-started): add main app example with app delegate

- docs/lib/storage/fragments/js/getting-started.md
S3 bucket CORS Policies require JSON instead of XML now.
- https://github.com/aws-amplify/amplify-js/issues/169
- converted the old xml CORS policy to JSON. 
> Update getting-started.md with CORS Policy

- docs/lib/datastore/fragments/flutter/getting-started/50_initDataStore.md
- docs/lib/datastore/fragments/flutter/sync/10-installPlugin.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/274 https://github.com/aws-amplify/amplify-flutter/pull/350
*Description of changes:* API Plugin is no longer added "by default" in flutter and customers have to add it to their project explicitly to enable cloud sync similar to other platforms.
> chore: Update flutter datastore sync docs

- docs/lib/graphqlapi/fragments/flutter/subscribe-data.md
Add Flutter docs for the GraphQL Subscribe API
> chore: Add Flutter docs for the GraphQL Subscribe API

- docs/lib/analytics/fragments/flutter/getting-started/30_initAnalytics.md
- docs/lib/datastore/fragments/flutter/getting-started/50_initDataStore.md
- docs/lib/graphqlapi/fragments/flutter/getting-started/30_initapi.md
- docs/lib/restapi/fragments/flutter/getting-started/30_initapi.md
*Issue #, if available:* Possibly source of https://github.com/aws-amplify/amplify-flutter/issues/380
Make all code samples for configure use await and synchronize across all categories
> fix: synchronize flutter getting started across categories

- cspell.json
- docs/lib/auth/fragments/ios/signin_next_steps/10_signin.md
- docs/lib/auth/fragments/ios/signin_next_steps/20_confirm_sms_mfa.md
- docs/lib/auth/fragments/ios/signin_next_steps/30_confirm_custom_challenge.md
- docs/lib/auth/fragments/ios/signin_next_steps/40_confirm_new_password.md
- docs/lib/auth/fragments/ios/signin_next_steps/50_reset_password.md
- docs/lib/auth/fragments/ios/signin_next_steps/60_confirm_signup.md
- docs/lib/auth/fragments/ios/signin_next_steps/70_done.md
- docs/lib/auth/fragments/native_common/signin_next_steps/common.md
- docs/lib/auth/menu.json
- docs/lib/auth/signin_next_steps.md
*Issue #, if available:* https://github.com/aws-amplify/docs/issues/1892
This PR adds a new section under auth called "Sign in next steps"
> feat(auth): Add documentation for next step in auth

- docs/ui/auth/fragments/react/auth-state-management.md
Fixes #2928
Reverts aws-amplify/docs#2742. This was false; it needs a destroyer.
> Revert "Remove return keyword within useEffect"

- docs/lib/project-setup/fragments/ios/prereq/prereq.md
> fix: correct a wrong version number

- docs/lib/analytics/fragments/js/autotrack.md
*Description of changes:* We should have a disclaimer saying that [Page Event Tracking](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js#page-event-tracking) is unsupported for React Native, just like we do for [Page View Tracking](https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js#page-view-tracking).
> docs(analytics): add disclaimer for unsupported feature

- .github/CODEOWNERS
The aws-amplify GitHub organization has various teams. We map these into
a CODEOWNERS file to automatically assign required reviewers.
The Flutter team is currently required to wait for someone *not* on
their team to review their documentation updates. Specifically, they
have to wait for amplify-native. However, the JS team has no such
restriction. The JS team reviews their own documentation.
Let's all be like JS.
> Enable feature teams to review their own documentation

- docs/console/adminui/extend-cli.md
The instructions said to navigate to open a new terminal window and
run `amplify pull --appId ...` without mentioning that one should
be in the directory that they would like amplify cli to install their
project in. If the user does not infer this it will install in their
home directory which is very likely not their choice project directory.
I updated the instructions to tell the user to change to their desired
directory before running the `amplify pull --appId ...` command. 
Hopefully in the future this can save some headache for users like me 
who did not infer this need and had to figure out what was installed 
in my home directory that should not have been there! 🙃
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Improved 'Amplify CLI configuration without AWS' steps 

- docs/lib/storage/fragments/native_common/getting-started/common.md
The native_common Storage documentation talks about the
amplifyconfiguration.json / amplifyconfiguration.dart. It incorrectly
says that the former is for JavaScript. The surrounding verbiage also
needs some minor updates for better clarity of wording.
> Native storage docs make a false statement about JavaScript

- .github/CODEOWNERS
Automatically assign reviewers for console documentation.
> Add a CODEOWNERS rule for the Console documentation

- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
Now, the link inside the warning box under Android getting started - Install Amplify libraries is not clickable.
This PR puts the link inside an HTML <a> tag so that the link is clickable.
> fix: make the link inside warning box clickable

- docs/lib/analytics/fragments/flutter/getting-started/10_preReq.md
- docs/lib/auth/fragments/flutter/getting_started/10_preReq.md
- docs/lib/datastore/fragments/flutter/getting-started/10_preReq.md
- docs/lib/graphqlapi/fragments/flutter/getting-started/10_preReq.md
- docs/lib/project-setup/fragments/flutter/prereq/prereq.md
- docs/lib/restapi/fragments/flutter/getting-started/10_preReq.md
- docs/lib/storage/fragments/flutter/getting-started/10_preReq.md
- docs/start/getting-started/fragments/flutter/setup.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-flutter/issues/402 https://github.com/aws-amplify/amplify-flutter/issues/359
*Description of changes:* Add notes that flutter's stable version is required to work with amplify libraries for now.
> chore(amplify-flutter): Add notes that flutter's stable version is required

- client/src/utils/track.ts
Pass `eVar61` so that these external link clicks have the page name associated with them
> External links were tracking but not being associated with the docs project; this fixes that

- docs/lib/graphqlapi/fragments/js/subscribe-data.md
https://discord.com/channels/705853757799399426/717109993416949811/813523850523836416
Some people has been getting `uncaught error` when the subscription fails. This is because they did not include the `error` event in their code as this is not demonstrated in the doc.
add `error` event into sample code
> fix: add error event in API subscription sample code

- client/src/docs-ui/select-anchor/select-anchor.tsx
It turns out that the solution was very simple the whole time.  Just update the links contained in the framework switcher any time the page changes, not just the first time.
> FIx switching framework kicking users back to the start of their browsing

- docs/lib/datastore/fragments/flutter/setup-auth-rules.md
- docs/lib/datastore/setup-auth-rules.md
Our docs erroneously state that Flutter datastore supports OIDC.  This PR corrects the issue.
> fix: Marks OIDC as 'coming soon' in Flutter auth directives section

- cspell.json
- docs/lib/datastore/fragments/flutter/getting-started/10_preReq.md
Updates Datastore Docs with temporary fix for Flutter 2.
> fix: Flutter 2 Compatibility Warning for DataStore

- docs/lib/datastore/fragments/js/real-time/observe-snippet.md
https://github.com/aws-amplify/amplify-js/issues/7242
Callout devs to wary that subscriptions will be terminated upon calling `DataStore.clear()`.
I was wondering if I should link the issue above into the docs as the solution discussed seems helpful.
> feat: add callout to DataStore.observe

- docs/lib/auth/fragments/android/access_credentials/10_fetchAuthSession.md
- docs/lib/auth/fragments/android/device_features/10_rememberDevice.md
- docs/lib/auth/fragments/android/device_features/20_forgetDevice.md
- docs/lib/auth/fragments/android/device_features/30_fetchDevice.md
- docs/lib/auth/fragments/android/escapehatch/10_awsmobileclient_escape.md
- docs/lib/auth/fragments/android/getting_started/30_initAuth.md
- docs/lib/auth/fragments/android/getting_started/40_fetchSession.md
- docs/lib/auth/fragments/android/hub_events/10_listen_events.md
- docs/lib/auth/fragments/android/password_management/10_reset_password.md
- docs/lib/auth/fragments/android/password_management/20_confirm_reset_password.md
- docs/lib/auth/fragments/android/password_management/30_change_password.md
- docs/lib/auth/fragments/android/signin/10_signUp.md
- docs/lib/auth/fragments/android/signin/20_confirmSignUp.md
- docs/lib/auth/fragments/android/signin/30_signIn.md
- docs/lib/auth/fragments/android/signin/40_multi_factor_signup.md
- docs/lib/auth/fragments/android/signin/50_multi_factor_confirm_signin.md
- docs/lib/auth/fragments/android/signin_web_ui/20_platform_specific_setup.md
- docs/lib/auth/fragments/android/signin_web_ui/30_signin.md
- docs/lib/auth/fragments/android/signout/10_local_signout.md
- docs/lib/auth/fragments/android/signout/20_global_signout.md
- docs/lib/auth/fragments/android/social_signin_web_ui/20_signin.md
- docs/lib/auth/fragments/android/user_attributes/10_fetch_attributes.md
- docs/lib/auth/fragments/android/user_attributes/20_update_user_attribute.md
- docs/lib/auth/fragments/android/user_attributes/30_confirm_attribute.md
- docs/lib/auth/fragments/android/user_attributes/40_resend_code.md
**This PR update the Auth docs for Android.**
Until the coroutines support achieves 1.0, we will document both types of Kotlin interaction alongside each other:
1. Using Kotlin with the traditional callback API
2. Using Kotlin with the Coroutine support
> Android Auth: Re-introduce Kotlin callbacks alongside coroutines

- docs/lib/datastore/fragments/android/data-access/delete-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-basic-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-pagination-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-predicate-or-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-predicate-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-sort-multiple-snippet.md
- docs/lib/datastore/fragments/android/data-access/query-sort-snippet.md
- docs/lib/datastore/fragments/android/data-access/save-snippet.md
- docs/lib/datastore/fragments/android/data-access/update-snippet.md
- docs/lib/datastore/fragments/android/datastore-events.md
- docs/lib/datastore/fragments/android/getting-started/70_querySnippet.md
- docs/lib/datastore/fragments/android/real-time/observe-snippet.md
- docs/lib/datastore/fragments/android/relational/delete-snippet.md
- docs/lib/datastore/fragments/android/relational/query-snippet.md
- docs/lib/datastore/fragments/android/sync/40-clear.md
In order for the language switcher's state management to work properly,
we need to use the same title for the Flow/Coroutine group.
Previously, some snippets said "Kotlin - Coroutines (Beta)", while
others said "Kotlin - Flow (Beta)". While that may be an optimal
distinction from the user's standpoint, it's better to have the
persistent toggle working in the switcher.
> Android docs: uniform label for coroutine APIs

- docs/lib/graphqlapi/fragments/android/advanced-workflows/50_interceptor.md
- docs/lib/graphqlapi/fragments/ios/advanced-workflows/50_interceptor.md
- docs/lib/graphqlapi/fragments/native_common/advanced-workflows/common.md
Adds documentation to the **Advanced Workflows** page in the GraphQL API documentation for **iOS and Android**.
Explains how to add custom headers to outgoing GraphQL requests.
> Add iOS & Android docs for custom GraphQL headers

- docs/lib/auth/fragments/js/customui.md
The React Native theme link was broken, pointing to a .js file instead of the .ts
Updated the React Native theme link to a .ts file, from obsolete .js.
> Update customui.md to fix broken React Native theme link

- docs/lib/datastore/fragments/flutter/data-access/delete-snippet.md
- docs/lib/datastore/fragments/flutter/data-access/query-basic-snippet.md
- docs/start/getting-started/fragments/flutter/setup.md
Small change to include instructions on updating the minSdkVersion in AndroidManifest for our Getting Started docs section.
> fix: FlutterGettingStarted Android MinSdkVersion

- docs/lib/project-setup/fragments/android/create-application/30_provisionBackend.md
Amplify CLI v4.45.0 provides Android Studio as an option of default editor. It's better to replace IntelliJ IDEA with Android Studio in our backend provision guideline.
> Update backend provision guideline with latest CLI version

- docs/fragments/cli-install-block.md
- Amplify CLI now supports M1 MacBooks for cURL installations
- Warning not necessary anymore
> Removing unnecessary notice about M1 now that CLI supports it

- docs/lib/datastore/fragments/flutter/getting-started/10_preReq.md
The `<amplify-callout>` needs an extra line feed in order to properly render markdown inside it.
---
> fix warning box markdown rendering

- docs/cli/teams/shared.md
Provide workaround for restoring  **team-provider-info.json** using `amplify pull`. The previous documentation link, as referenced in the issue below, is no longer available and no solution is currently outlined.
https://github.com/aws-amplify/amplify-cli/issues/3274
> update(shared.md): provide option for restoring team-provider-info.json if missing

- docs/start/getting-started/fragments/vue/setup.md
*Issue #, if available:* closes #3003, closes #3024
*Description of changes:* This fixes typo that said `ui-vue` instead of `ui-components`. Also adds a clarification that `ui-components` is only for Vue 3.
> fix(getting-started): clarify Vue 2 vs Vue 3 installation guide

- client/src/amplify-ui/responsive-grid/responsive-grid.tsx
- client/src/amplify-ui/toc/toc-provider/toc-provider.tsx
- client/src/amplify-ui/toc/toc/toc.tsx
- client/src/docs-ui/in-page-link/in-page-link.tsx
- client/src/docs-ui/search-bar/search-bar.tsx
- client/src/docs-ui/select-anchor/select-anchor.tsx
- client/src/globals.d.ts
- client/src/utils/track.ts
New global objects:
- Adobe `s` object
- Algolia docsearch object
- AWS Shortbread object
Also `ts-ignore` on Stencil `Watch` and `Listen` statements isn't necessary anymore.
> Purge @ts-ignore statements by declaring types on globals

- docs/lib/storage/fragments/android/download.md
https://github.com/aws-amplify/amplify-android/issues/1241
Android docs for Storage currently does not document the usage of `getUrl()` API. This PR adds a brief section describing how to use it.
> [Android] add documentation for getUrl

- docs/start/getting-started/fragments/vue/setup.md
*Description of changes:* This is equivalent to using `<a>`, but is more consistent with other markdown files. Thanks @tjleing for bringing this up!
> docs(getting-started): Use markdown style link instead of `<a>`

- docs/lib/project-setup/fragments/android/coroutines/coroutines.md
Previously, it was easy to miss the instruction to import `com.amplifyframework.kotlin.core.Amplify` in order to use the Kotlin plugins.  It's buried in the introduction section.  This PR adds it to the installation section as well.
> fix(android): add guidance to import different Amplify facade to use Kotlin coroutine support

- docs/ui/auth/fragments/web/authenticator.md
Corrected reference to AmplifyTotpSetup component which was incorrectly capitalised as AmpliftyTOTPSetup.
> Fix reference to AmplifyTotpSetup.

- docs/lib/datastore/fragments/android/data-access/save-snippet.md
> fix(android/datastore): Fix typo in `kotlin` coroutines `datastore.save()` example

- client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
- client/src/amplify-ui/cli-feature-flag/feature-flags.json
- docs/cli/reference/feature-flags.md
Marking as a draft until the CLI PR is merged.
https://github.com/aws-amplify/amplify-cli/pull/6919
Add the `useInclusiveTerminology` FF.
> Add documentation for CLI FF useInclusiveTerminology

- docs/console/data/data-model.md
- replace inaccessible datastore link with `/lib/datastore/getting-started`
> fix(adminui data-model): replace inaccessible datastore link

- docs/start/getting-started/installation.md
Closes https://github.com/aws-amplify/docs/issues/3093
Fixes 404 links on https://docs.amplify.aws/start/getting-started/installation
This is done by adding missing integration fragments for:
- iOS
- Android
- Flutter
Additionally it reorders the fragments to be in the order they appear in the UI.
> fix(flutter/guides): Add missing integration fragments to getting started page

- docs/cli/teams/sandbox.md
- docs/cli/teams/shared.md
In description, we use main as branch name and use the same branch name in code examples as well.
> fix(cli): use the same branch name in example with description

- docs/lib/storage/cancel-requests.md
- docs/lib/storage/fragments/js/cancel-requests.md
- docs/lib/storage/menu.json
Refs: https://github.com/aws-amplify/amplify-js/pull/8088
*Description of changes:* Documentation for the Storage.cancel API that is used for cancelling in-flight get or put requests made by `Storage`.
> Adding documentation for the Storage.cancel API

- docs/console/console.md
Breaking Stencil builds locally
> (fix): `containertag` is correct

- client/prerender.config.ts
The nuclear option -- no CSS options were going to work because of aforementioned Stencil bug.  Just don't pre-render the code blocks, and we won't run into pre-rendered `class`es differing from `class`es in browser.
Closes #3091 and subsumes #3100.
> (fix): Code block duplicating in some scenarios

- docs/cli/usage/iam.md
Add `s3:PutEncryptionConfiguration` to the CLI policy to support creating SSE-enabled buckets in the CLI.
Also removed `s3:HeadBucket` which is not a valid IAM policy. See https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html
> add bucket encryption policy and remove non-existant HeadBucket policy

- docs/lib/datastore/fragments/flutter/getting-started/50_initDataStore.md
- update `codegen/ModelProvider.dart` to `models/ModelProvider.dart` in the initial code snippet for flutter datastore getting started (it was correct in the second snippet)
- fix inconsistencies between the plugin configuration & comment between the two snippets
> fix(flutter): update flutter code snippets in datastore getting started

- docs/start/getting-started/fragments/angular/setup.md
#4515
In response to issue where customers were struggling to use angular for internet explorer since we did not document the polyfill code that needed to be added to src/polyfills.ts for Angular
added code snippets to https://docs.amplify.aws/start/getting-started/setup/q/integration/angular to help our customers use amplify and angular for IE11
> fix(angular docs): Adding polyfil documentation for angular

- docs/ui/auth/fragments/react/sign-out.md
<AmplifySignOut> on React has a prop of `buttonText`, the docs show this as `button-text` which is incorrect. 
Docs updated to reflect correct API of `<AmplifySignOut buttonText="Log out"></AmplifySignOut>` rather than `<AmplifySignOut button-text="Log out"></AmplifySignOut>`.
> Update AmplifySignOut buttonText prop to correct case

- docs/ui/auth/fragments/react/sign-out.md
Deployment build error introduced here: https://github.com/aws-amplify/docs/pull/3162
Fixes a deployment build error by wrapping AmplifySignOut in a jsx code fence.
```
2021-05-03T20:29:56.712Z [INFO]: `capi` compiling docs
2021-05-03T20:29:58.767Z [WARNING]: (node:2343) UnhandledPromiseRejectionWarning: Error: Invalid tag "amplifysignout" encountered in "/codebuild/output/src139141315/src/docs/docs/ui/auth/fragments/react/sign-out.md". See instructions on adding valid tags at "/codebuild/output/src139141315/src/docs/Readme.md#adding-to-valid-tag-list"
at Hyperscript (/codebuild/output/src139141315/src/docs/capi/src/init-node/html-to-hyperscript.ts:53:13)
at /codebuild/output/src139141315/src/docs/capi/src/init-node/html-to-hyperscript.ts: …
```
> Fix build error on react sign-out page

- docs/docs.md
Removes YouTube embed from the home page.
> Remove Home Page YouTube Embed

- docs/lib/analytics/fragments/js/record.md
https://github.com/aws-amplify/docs/issues/3151
Removes the following line from the Analytics (JS) section describing recording custom events:
`Attribute values must have the type String or be an array of strings.`
It appears Pinpoint API documentation does not specify exactly what types of values they accept within the `Attributes` object. When attempting to pass an `array` of `strings` in my sample app, the server responds with a `400` error.
Removing this line from the documentation will help avoid further confusion as seen from https://github.com/aws-amplify/docs/issues/3151.
> chore(analytics-js): remove custom event attribute value type line

- docs/ui/auth/fragments/angular/custom-form-fields.md
- docs/ui/auth/fragments/angular/password-manager.md
- docs/ui/auth/fragments/ionic/custom-form-fields.md
- docs/ui/auth/fragments/react/custom-form-fields.md
- docs/ui/auth/fragments/react/password-manager.md
- docs/ui/auth/fragments/vue/custom-form-fields.md
- docs/ui/auth/fragments/web/authenticator.md
*Issue #, if available:* https://github.com/aws-amplify/amplify-js/issues/5782
*Description of changes:* https://github.com/aws-amplify/amplify-js/pull/8243 added workaround to partially enable password manager. This PR documents those changes.
> docs(ui): document password workaround

- docs/cli/graphql-transformer/function.md
Adds `graphql` to fenced code blocks for https://docs.amplify.aws/cli/graphql-transformer/function#usage
> docs(cli): add language to fenced code blocks

- docs/lib/graphqlapi/fragments/graphql-from-node.md
When retrieving large results in GraphQL queries from Lambda functions, you must wait to get all the chunks before parsing the data. This fix makes the example work for every cases.
> Fix results with chunks in GraphQL queries from lambda function

- docs/cli/graphql-transformer/resolvers.md
Fixes: https://github.com/aws-amplify/docs/issues/2417
This commit briefly introduces the concept of VTL and links to the official VTL docs, as well as the AppSync VTL reference.
> docs: add brief VTL explainer

- docs/start/getting-started/fragments/angular/setup.md
Fix IE 11 Imports
As of core-js 3+ entry points do not need es6 or es7 specified. They should be replaced with just "es".
See CommonJS entry points section
https://github.com/zloirock/core-js/blob/master/README.md#ecmascript-typed-arrays
> Modified imports for IE 11 Support

- docs/cli/graphql-transformer/codegen.md
*Issue #, if available:* closes aws-amplify/docs#2720
see also: aws-amplify/amplify-codegen#138
Previously, users could execute the amplify codegen command with a --max-depth flag. Accordingly, when users would run amplify codegen --help the above usage would be described. However, at some point in 2019, the above flag was changed to --maxDepth (see aws-amplify/amplify-cli#2175). To date, neither the CLI help nor the official documentation reflect this change.
This PR addresses the official documentation.
> fix(cli/codegen): Migrate `--max-depth` flag to `--maxDepth`

- docs/lib/analytics/fragments/flutter/getting-started/30_initAnalytics.md
- docs/lib/datastore/fragments/flutter/getting-started/50_initDataStore.md
- docs/lib/graphqlapi/fragments/flutter/getting-started/30_initapi.md
- docs/lib/restapi/fragments/flutter/getting-started/30_initapi.md
initState can only be overriden in State<> and not from the StatefulWidget
> fix: Flutter initState

- docs/lib/auth/fragments/js/advanced.md
https://github.com/aws-amplify/docs/issues/3136
closes #3136 
- Updates the import statements in the code examples from the legacy component approach to the new namespace
- Updates the `federated` property names in the code examples based on the [declared](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/types/auth-types.ts#L24-L40) `interface`
> fix(@auth): update import statements and federated property names

- docs/lib/auth/fragments/android/signin/10_signUp.md
Small fix to Android docs: 
* Add missing semicolon to signup code sample.
> fix: missing semicolon on android signup sample

- docs/cli/graphql-transformer/function.md
Added a note to relevant Lambda documentation and pointed out requirements for using typed event input. 
As a first-time Lambda, I was unfamiliar with the expected input format for these functions. This note adds a link to the relevant Lambda documentation. While the examples in this document are helpful for the general expected design, it is difficult to understand the important parts required to implement a correct lambda resolver for a GraphQL function. I added the note to help other developers using more strongly typed languages such as Golang, Java, and C# should they encounter this error.
Thank you for considering this change!
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Add note for using structured types with functions

- docs/sdk/auth/fragments/android/hosted-ui.md
https://github.com/aws-amplify/aws-sdk-android/pull/2473
Updates Android documentations for using Hosted UI via `AWSMobileClient`. This PR contains updated documentations for applying a fix for hosted-UI sign-out error that was introduced in v2.18.0.
This PR will stay in draft until https://github.com/aws-amplify/aws-sdk-android/pull/2473 is released. The version numbers specified in this PR are subject to changes until then.
> Update hosted-ui docs for Android

- docs/lib/graphqlapi/fragments/ios/query-data.md
Should be "with optional parameters `limit` and `where` to specify the page size and condition" instead of "limit` and `where` to specific the page size and condition"
You can get the list of items using `.paginatedList` with optional parameters `limit` and `where` to specific the page size and condition. By default, the page size is 1000.
> Found another typo

- docs/lib/graphqlapi/fragments/ios/subscribe-data.md
Don't believe there should be a semicolon unless it's something specific to the API
> Removed semicolon

- docs/ui/auth/fragments/react/select-mfa-type.md
- docs/ui/auth/fragments/vue/select-mfa-type.md
`ui-component-props` handles `prop-type` as `attr` with no value only for the initial load. Passing a correct `prop-type` fixes an issue that showing `undefined` when user comes from different page which is how the other page manages prop-type.
Fixes: https://github.com/aws-amplify/docs/issues/2705
> fix: provide prop-type on select-mfa-type

- docs/cli/graphql-transformer/directives.md
Added the following two 3rd party directives:
**`@firehose`**
This directive can be added to any `@model` annotated GraphQL type. It will then convert it into a pipeline resolver and add the specified function to it, in addition to the original data source. The specified function is therefore called for every mutation and query that is done to the `@model` type. This allows to for example implement an audit logger.
**_Source code:_** https://github.com/LaugnaHealth/graphql-firehose-transformer
**`@retain`**
This directive can be added to any `@model` annotated GraphQL type. It will then set the `DeletionPolicy` of the generated DynamoDB table to `Retain`. This helps to prevent losing any production data by mistake (e.g. when a type name was changed or a type was removed).
This solves a …
> docs: added @firehose and @retain directives

- docs/lib/auth/fragments/android/signin_web_ui/20_platform_specific_setup.md
Update instructions to use new redirect activity that addresses hostedUI sign-out issue.
~Will be in draft until https://github.com/aws-amplify/amplify-android/pull/1353 is merged and released.~
> [Android] updated instructions for signing in with web UI

- docs/lib/auth/fragments/flutter/getting_started/20_installLib.md
_Issue #, if available:_ N/A
- Remove `}` from code snippet in auth getting started
> fix: typo in flutter auth getting started

- docs/lib/analytics/fragments/ios/getting-started/20_installLib.md
- docs/lib/auth/fragments/ios/getting_started/20_installLib.md
- docs/lib/datastore/fragments/ios/getting-started/20_installLib.md
- docs/lib/restapi/fragments/ios/getting-started/20_installLib.md
- docs/lib/storage/fragments/ios/getting-started/20_installLib.md
- Adds remaining SPM guides for the rest of the categories
- this is built on top of the initial SPM guide under GraphQL API:  https://github.com/aws-amplify/docs/pull/3288
> fix(iOS): Add SPM guide per category

- docs/lib/analytics/fragments/android/getting-started/20_installLib.md
- docs/lib/auth/fragments/android/getting_started/20_installLib.md
- docs/lib/datastore/fragments/android/getting-started/20_installLib.md
- docs/lib/datastore/fragments/android/sync/10-installPlugin.md
- docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
- docs/lib/graphqlapi/fragments/android/getting-started.md
- docs/lib/graphqlapi/fragments/android/getting-started/20_installLib.md
- docs/lib/predictions/fragments/android/getting-started/30_installLib.md
- docs/lib/project-setup/fragments/android/coroutines/coroutines.md
- docs/lib/project-setup/fragments/android/create-application/20_gradle.md
- docs/lib/project-setup/fragments/android/rxjava/rxjava.md
- docs/lib/restapi/fragments/android/getting-started/20_installLib.md
- docs/lib/storage/fragments/android/getting-started/20_installLib.md
- docs/start/getting-started/fragments/android/setup.md
Update Amplify versions to the latest release.
> chore: bump amplify versions to 1.8.0

- docs/lib/storage/fragments/ios/download.md
- docs/lib/storage/fragments/ios/upload.md
- add operation functionality such as cancel/pause/resume to the upload and download docs
- mention multipart upload after 5MB for upload API
> fix(Storage): iOS storage operations cancel/pause/resume

- docs/lib/storage/fragments/flutter/getting-started/10_preReq.md
Fix a typo on the Flutter Storage Doc (Getting started)
> Typo on Storage doc

- client/prerender.config.ts
Issue: UI components pages like [Sign Out](https://docs.amplify.aws/ui/auth/sign-out/q/framework/react) and [Chatbot](https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react#props-attr-amplify-chatbot) were displaying certain content multiple times.  Issue only manifested when the problematic page was the first page of a user's visit (i.e. upon refresh) which indicated prerendering problem.
Fix: just don't prerender `ui-component-props`.  Similar reasoning to https://github.com/aws-amplify/docs/pull/3147 -- this entire class of problems should be resolved when we move to Next.js, so this is just a stopgap.
Checked locally: `yarn build` and then `npx serve client/www`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Fix `ui-component-props` rendering multiple times by removing from prerendering

- docs/cli/graphql-transformer/key.md
n/a
Changes `createdAt` type from `String` to `AWSDateTime` as it does not appear to have a significant reason to be a string and it is noted in a later (unrelated) graphql snippet to be of type `AWSDateTime`
> fix(cli): correct createdAt type from string to awsdatetime

- docs/guides/location-service/menu.json
Removing (Public preview) from the guides menu. Amazon Location is now in GA.
> Update menu.json, removing (Public Preview)

- docs/lib/project-setup/fragments/flutter/null-safety/null-safety.md
- docs/lib/project-setup/fragments/flutter/prereq/prereq.md
- docs/lib/project-setup/fragments/native_common/prereq/flutter_null_safety.md
- docs/lib/project-setup/menu.json
- docs/lib/project-setup/null-safety.md
- docs/start/getting-started/fragments/flutter/prereq.md
_Description of changes:
Adds null safety docs for amplify-flutter.
Note: feature flag section of CLI docs will need to be updated once we know the version number of the CLI which will first include the dart feature flag.
> chore(flutter): adds null safety docs for amplify-flutter

- docs/lib/datastore/fragments/flutter/conflict.md
- docs/lib/datastore/fragments/flutter/getting-started/60_initDataStore.md
- docs/lib/datastore/fragments/flutter/relational/query-snippet.md
- docs/lib/datastore/fragments/flutter/relational/save-many-snippet.md
- docs/lib/datastore/fragments/flutter/relational/save-snippet.md
- docs/lib/datastore/fragments/flutter/sync/10-installPlugin.md
- docs/lib/project-setup/fragments/flutter/create-application/40_verifyAmplifyLibraries.md
* Remove `// @dart=2.9`
* improve snippets accuracy
* Add DataStore custom configuration example
> chore: Update Flutter datastore docs code snippets for null safety

- docs/lib/project-setup/fragments/flutter/null-safety/null-safety.md
Cleanup for Flutter null safety page
> fix: cleanup for Flutter null safety page

- client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
- client/src/amplify-ui/cli-feature-flag/feature-flags.json
N/A
Add documentation for `enableDartNullSafety` Amplify CLI Feature Flag which allows the existing Amplify projects to selectively upgrade to null safe Flutter DataStore models. 
> feat(cli-feature-flag): add documentation for enableDartNullSafety Amplify CLI Feature Flag

- docs/cli/auth/import.md
From a trouble ticket I received:
> 
> There seem to be misleading information in the following doc [1] where it say:
> 
> User Pools require at least two app clients with the following conditions:
> 
> At least one “Web app client”: an app client without a client secret
> At least one “Native app client“: an app client with a client secret
> 
> That's not true - having two app-clients is not necessary. Having one app-client without a client-secret is mandatory to complete the amplify import auth process.
> 
> Can we have the docs updated for this please?
> 
> == References ==
> [1] https://docs.amplify.aws/cli/auth/import#import-an-existing-cognito-user-pool
> 
This PR reflects the change I was suggested.
Would someone from …
> Update CLI Auth docs -  having two app clients is not necessary

- docs/lib/auth/fragments/android/access_credentials/10_fetchAuthSession.md
- docs/lib/auth/fragments/flutter/access_credentials/10_fetchAuthSession.md
- docs/lib/auth/fragments/ios/access_credentials/10_fetchAuthSession.md
- docs/lib/auth/fragments/native_common/access_credentials/common.md
_Issue #, if available:_ n/a
- Align the flutter fetchAuthSession docs with iOS and Android, and provide an example of how to access the `identityId` as iOS and Android do.
> chore(flutter/auth): align native auth session docs

- client/src/amplify-ui/cli-feature-flag/__snapshots__/feature-flag.spec.ts.snap
- client/src/amplify-ui/cli-feature-flag/feature-flags.json
https://github.com/aws-amplify/amplify-codegen/issues/104
Adds documentation for `handleListNullabilityTransparently` CLI feature flag to be released with this [Amplify CLI PR](https://github.com/aws-amplify/amplify-cli/pull/7303).
> doc: add CLI Feature Flag for handling nullability of lists in Datastore Modelgen

- docs/lib/auth/fragments/js/social.md
_Issue #, if available:_ N/A
_Description of changes:_ It took me a while to realize that they are additional steps required to make redirects work on React Native. Figured this might help others in the future. I also updated the Expo Linking guide's URL since the previous value redirects to this new one.
> Add link to the React Native Linking guide

- docs/guides/authentication/fragments/js/managing-user-attributes.md
- docs/lib/auth/fragments/js/manageusers.md
Follow existing `updateUserAttributes`, add samples code for the upcoming `AuthdeleteUserAttributes` api in JS.
Related PR: https://github.com/aws-amplify/amplify-js/pull/7342
API review has been done internally.
> add sample codes for Auth.deleteUserAttributes in JS

- docs/cli/graphql-transformer/examples.md
Fixed "The mutations argument on the aws_subscribe directive has an invalid value"
Issue #, if available:
The mutations argument should be lists, but it is string in the final example in the document. After amplify push, it will return the error "The mutations argument on the aws_subscribe directive has an invalid value". So I guess, this code just missed the square brackets, and I added them.
> Missed the square brackets in the example code

- docs/guides/functions/configuring-lambda.md
- Amplify CLI launched with the capabilities for configuring environment variables and secrets for Functions
- Guides traditional provided an option to configure these via custom resources. This is not needed anymore.
> Change guides to use CLI's Function env vars & secrets feature

- docs/start/getting-started/fragments/reactnative/setup.md
_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/8577
_Description of changes:_ Updating code snippet in the Install Amplify Libraries section of the React Native to include src directory in import of aws-exports file.
> update React Native import and configure code snippet

- docs/cli/graphql-transformer/auth.md
https://github.com/aws-amplify/amplify-cli/issues/6953
Corrects example outputs based on the example schema, where owner ID should not populate as an editor when not also specifying `create` in the "editors" rule's operations.
> fix(cli/auth): correct multi-auth example outputs

- docs/lib/pubsub/fragments/js/getting-started.md
command attach-principal-policy has been deprecated https://docs.aws.amazon.com/cli/latest/reference/iot/attach-principal-policy.html
Replaced with current command attach-policy https://docs.aws.amazon.com/cli/latest/reference/iot/attach-policy.html
I also tested this on my end and I can confirm that it work as expected
> change in attach-policy command

- docs/lib/geo/fragments/js/search.md
https://github.com/aws-amplify/amplify-js/issues/8690
https://github.com/aws-amplify/amplify-js/issues/8691
Reverse Longitude and Latitude as they were in the wrong order.
> fix(geo): reverse coordinate order

- docs/lib/geo/fragments/js/maps.md
Fixes a typo ("Ersi" should be "Esri").
> Typo: Ersi → Esri

- docs/lib/datastore/fragments/ios/real-time/observe-snippet.md
_Description of changes:_ `Datastore.stop()` and `Datastore.clear()` will not complete the publisher and the subscribers will continue to receive subscription events. Related PR : https://github.com/aws-amplify/amplify-ios/pull/1273
> Update subscription behavior on clear()/stop() in iOS

- docs/lib/geo/existing-resources.md
Until other platforms are ready to add their docs, we need to make the entire `existing-resources` section JS only. I missed this in the previous PR as I didn't look at other platforms.
> fix(geo): remove geo from non-js platforms

- Readme.md
- client/src/docs-ui/menu/menu.tsx
n/a
Changes community Discord invite link to use vanity URL `discord.gg/amplify`. This change could help improve community insights to better determine how new members join the server.
--- 
> fix: all Discord invite links to use vanity URL

- docs/lib/graphqlapi/fragments/flutter/authz.md
- docs/lib/graphqlapi/fragments/flutter/authz/30_multi.md
- docs/lib/graphqlapi/fragments/native_common/authz/common.md
This PR has the following:
* update documentation for flutter apiName parameter to configure multiple authorization modes as that was implemented
* correct a small typo in common native configuration example
**NOTE:** This PR should not be merged until flutter releases 0.2.2 which includes the auth mode change.
> chore(flutter): multiple GraphQL auth modes in flutter, native config typo

- docs/lib/geo/fragments/js/getting-started.md
- docs/lib/geo/fragments/js/maps.md
- docs/lib/geo/fragments/js/search.md
Updates to `@amplify-js/geo` and `maplibre-gl-js-amplify` now have given us the ability to infer `region` for customers so that they no  longer have to code that in themselves.
> feat(geo): remove `region` as plugin now infers it from maps

- docs/cli/teams/overview.md
https://github.com/aws-amplify/amplify-cli/issues/7250
This pull request adds documentation for the fact that Amplify CLI manages a section of each project's .gitignore file which should not be touched by the application owner.
> docs(overview): define which section of .gitignore is managed by amplify

- docs/lib/graphqlapi/fragments/android/authz/20_oidc.md
- docs/lib/graphqlapi/fragments/android/authz/21_oidc.md
- docs/lib/graphqlapi/fragments/android/authz/22_lambda.md
_Description of changes:_ Replace calls to the deprecated AWSApiPlugin constructor `AWSApiPlugin(authProviders)` in the Android libraries docs.
> Replace deprecated constructor call in Android docs

- src/directory/directory.js
With the migration to NextJS, the link to Geo => Search was wrong. This PR updates `directory` to point to the correct location for the MDX file for Geo Search.
> fix(geo): fix geo search link in directory

- src/components/Menu/index.tsx
- src/components/Page/index.tsx
- src/components/Page/styles.tsx
- src/pages/ChooseFilterPage.tsx
Resolves the issue of content being too close to the right edge of the mobile screen:
Passes `menuIsOpen` to content styles to determine if content should be full width or not.
When the menu is open, set the content to be 100vw, so that it doesn't appear "scrunched" on the side.
When the menu is closed, set the content to be fluid, so it fills the space with proper padding.
|  Menu Open  | Menu Closed  | 
|---|---|
|  <img width="447" alt="image" src="https://user-images.githubusercontent.com/2081699/129777845-a7eb5c13-9771-4c3c-8d63-babf9b082bf7.png">  | <img width="451" alt="image" src="https://user-images.githubusercontent.com/2081699/129778405-9f3a06a2-5551-4d4b-969b-10dfe8e32b4d.png"> |
> Use menuIsOpen state to determine the width of content

- docs/cli/graphql-transformer/model.md
_Issue:_ #3402
_Description of changes:_ Updated the position of the text `This would create and configure a single query field post(id: ID!): Post and no mutation fields.` to be under the relevant code example.
> fixed cli/graphql-transformer name override content position

- src/fragments/lib/geo/js/maps.mdx
Migration removed the `.md` extension from the github link and broke it.
> fix(geo): fix link to drawPoints markdown file

- src/components/Menu/FilterSelect/index.tsx
- src/components/Menu/index.tsx
- src/components/Page/index.tsx
- src/pages/ChooseFilterPage.tsx
soln: pass `filterKind` through dependency chain so that we don't have to rederive it from the router url which doesn't exist at render time
as a bonus, this also fixes the screamingfrog 404s -- they were coming from the prerendered FilterSelect dropdown:
vs.
> (fix) FilterSelect not showing correct text on mobile

- src/components/Menu/VersionSwitcher/index.tsx
Problem: /ui pages like https://docs.amplify.aws/ui/ where you have to choose a framework (`ChooseFilterPage`s) have broken links on the UI/UI-legacy version switcher.  Hovering the "Legacy" button, see the link at the bottom of the image:
Solution: add hrefs of `ChooseFilterPage`s to the lists of hrefs that are allowed to appear in a UI switcher; also don't result in undefined when on a page with no filterKey (/ui/**/q/framework/[filterKey]).
For example, `/ui` results in `filter = ""` instead of `filter = undefined`, and then is allowed to appear in the UI switcher.
- also the href lists for UI and UI-legacy are now created differently.  I don't think this ever manifested into a problem, but the way in this PR is more accurate to the variable names.
> (fix) UI switcher has correct hrefs for both sides on ChooseFilterPages

- src/components/FeatureFlags/FeatureFlagSummary.tsx
- src/components/FeatureFlags/FeatureFlagValues.tsx
- src/components/FeatureFlags/feature-flags.json
- src/components/FeatureFlags/index.tsx
- src/pages/cli/reference/feature-flags.mdx
- src/plugins/import.tsx
_Issue #, if available:_ https://github.com/aws-amplify/docs/issues/3550
Parses feature-flags.json and displays feature flag tables.
> Add missing FeatureFlags to docs

- src/fragments/lib/geo/js/maps.mdx
- Updated based on the geo friction doc
- Added the required css to make map have a height and display correctly
- discovered that mapbox/maplibre's canvas component requires a certain css configuration to set the height of its container
> Fix maps css

- src/utils/getLocalDirectory.ts
Currently the below URL cannot show the content because of `isProductRoot` state machine.
https://docs.amplify.aws/cli/#serverless-containers
Update `isProductRoot` to support `/cli/#hash`. This change is not only for cli but also for further path check with hash right under product root directory.
> Fixes title getter for cli root

- src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
- yarn.lock
Added docs for enabling the SQLite storage adapter for DataStore on React Native
JS PR: https://github.com/aws-amplify/amplify-js/pull/8809
Preview:
> feat: add datastore sqlite doc

- docs/cli/graphql-transformer/versioned.md
_Issue_: https://github.com/aws-amplify/amplify-ios/issues/1238
Updated `@versioned` docs to clarify codegen support.
> fix: update @versioned support

- src/fragments/lib/geo/js/maps.mdx
- Update docs to use 1.0.7 version for maplibre-gl-js-amplify
- Update namespace from `maplibreAmplify` to `MapLibreAmplify`
> chore: update maplibre-gl-js-amplify bundle version and namespace

- src/components/Layout/index.tsx
it was still hiding in `<Layout>`...
> Fully remove docsearch CDN

- src/fragments/lib/geo/js/maps.mdx
- src/fragments/lib/geo/js/search.mdx
- Typing `npm install maplibre-gl` will automatically install the v2 pre release branch now
- Updating docs instructions to install v1
> fix: update maplibre-gl to install major version 1 until we upgrade to v2

- src/fragments/lib/auth/android/getting_started/30_initAuth.mdx
On [this page](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#install-amplify-libraries) one of the codeblocks has incorrect syntax highlighting.  Thank you @swaminator for the find!
> Remove whitespace to fix codeblock in android auth getting-started

- src/fragments/lib/geo/js/getting-started.mdx
_Related issues_
* https://github.com/aws-amplify/docs/issues/3551
* Update minimum needed versions for Amplify-CLI and Amplify-js `@geo`
* Add `amplify init` step in Geo getting started
> chore(geo): add note about minimum needed versions

- src/pages/guides/api-rest/express-server/q/platform/[platform].mdx
- src/pages/guides/api-rest/go-api/q/platform/[platform].mdx
- src/pages/guides/api-rest/node-api/q/platform/[platform].mdx
- src/pages/guides/api-rest/python-api/q/platform/[platform].mdx
Removes extra slashes in the `/lib/restapi/getting-started` links.
> Remove extra slash in link for restapi

- src/fragments/lib/storage/ios/download.mdx
- src/fragments/lib/storage/ios/upload.mdx
- src/fragments/sdk/storage/ios/transfer-utility.mdx
_Issue #, if available:_ https://github.com/aws-amplify/aws-sdk-ios/issues/3668
_Description of changes:_ Add a callout in pause feature in S3.
> chore(storage): Added callout for storage pause feature

- src/fragments/ui/auth/vue/custom-form-fields.mdx
Fix broken prop name; closes #3438
_Issue #, if available:_ 
#3438
Implements change suggested in above issue. 
> Fix Bug re: Incorrect Prop Name in Vue Auth UI Docs

- docs/cli/usage/mock.md
_Issue #, if available:_ [7411 on Amplify-CLI](https://github.com/aws-amplify/amplify-cli/issues/7411)
Added a note describing the fix for this issue on Apple Silicon (M1) Macs
> Amplify Mock: Add note about JDK issues on Apple Silicon

- src/fragments/start/getting-started/angular/data-model.mdx
_Issue #, if available:_ Closes #3376
_Description of changes:_ This reflects Angular 12 changes to the getting started documentation. Angular 12+ turns on `"strict": true` by default, which was triggering all the typescript errors in #3376. Either developers can disable strict mode, or they can use the workaround mentioned in this PR.
We should track these strict mode issues and deliver a holistic solution, which would require cross-team work. But these workaround should unblock developers for the time being.
> Reflect angular 12 changes to docs

- src/fragments/lib/storage/js/getting-started.mdx
https://github.com/aws-amplify/amplify-js/pull/8832
- Adding `copy` to the `StorageProvider` interface
- Added code snippets for getting Typescript support with custom provider
> Add instruction for getting Typescript support with custom storage provider

- .github/dependabot.yml
_Issue #, if available:_ https://github.com/aws-amplify/docs/pull/3415
Adds a dependabot.yml config that performs a daily check for new `@aws-amplify/*` dependency updates so that docs stay up to date.
> Add dependabot config to update any packages starting with "@aws-amplify"

- docs/cli/geo/maps.md
- docs/cli/geo/menu.json
- docs/cli/geo/search.md
- src/directory/directory.js
- src/pages/cli/geo/maps.mdx
- src/pages/cli/geo/search.mdx
**Do not merge yet**
Remove the developer preview banner for GA of Geo CLI category plugin.
Minor updates to `choose default resource question`
Region support callout looks like this:
> feat(cli-geo-category): remove dev preview banner

- src/fragments/lib/auth/js/getting-started.mdx
_Issue #, if available:_ [3454](https://github.com/aws-amplify/docs/issues/3454)
Getting started documentation for JS library only shows libraries for Vue 2 not Vue 3. New getting started has a tab for Vue 2 and Vue 3. 
> Updated getting started for Vue 3

- src/directory/directory.js
- src/fragments/lib/geo/js/maps.mdx
- src/fragments/lib/troubleshooting/js/strict-mode.mdx
- src/fragments/start/getting-started/angular/data-model.mdx
- src/pages/lib/troubleshooting/strict-mode/q/platform/[platform].mdx
_Issue #, if available:_ #2918, #3140, #3376, [stackoverflow](https://stackoverflow.com/questions/69353284/integration-issue-in-angular-with-aws-amplify-for-google-sign-up/69356521)
_Description of changes:_ This adds troubleshooting section for using Typescript strict mode. This is prominent on Angular 12+ users as Angular 12 turns on strict mode by default, but this is relevant to all users who uses stricter TypeScript settings. I pulled it out to a separate troubleshooting for that reason, and we can reference this document from issues and [UI docs](https://ui.docs.amplify.aws/ui) as well.
> Strict mode troubleshooting

- src/pages/cli/graphql-transformer/connection.mdx
- src/pages/console/data/relationships.mdx
https://github.com/aws-amplify/amplify-adminui/issues/333#issuecomment-931096223
Added a note on Admin UI not supporting custom naming for m:m relations
> Warn about custom naming for m:m in Admin UI

- src/fragments/lib/auth/ios/signin_with_custom_flow/10_cli_setup.mdx
_Issue #, if available:_ https://github.com/aws-amplify/amplify-ios/issues/1381
_Description of changes:_ CLI made changes to remove the hard coded challenge value to be added during custom auth flow. This PR changes the step in iOS setup for custom auth to use a random generator for creating challenge
> chore(auth): Fix the custom auth to match CLI

- src/pages/cli/usage/iam.mdx
_Description of changes:_ lambda:GetLayerVersion already covers lambda:GetLayerVersionByArn
https://github.com/aws-amplify/docs/pull/3619 got stale, so re-opening here.
> fix: remove unnecessary IAM permission

- src/fragments/lib/analytics/js/getting-started.mdx
https://github.com/aws-amplify/amplify-js/issues/9138
Removing the line `Amplify.record()` from the example code snippet because it can cause confusion with the usage of the `record` method by making it seem like it can be called without arguments when it [expects either a string or object ](https://github.com/aws-amplify/amplify-js/blob/49da354140141a0dc88d6a3922ce79728857630e/packages/analytics/src/Analytics.ts#L232) as the first argument.
It will throw an error if called as is in the code snippet.
> remove Analytics.record() from code snippet

- .prettierrc
_Issue not applicable:_
Changing the `.prettierrc` according to the current style of the documentation.
> Changing .prettierrc to match the style of documentation

- src/pages/cli/graphql-transformer/resolvers.mdx
- src/styles/elements.css
Issue : #3677 
The content of the table seems to cutoff [here](https://docs.amplify.aws/cli/graphql-transformer/resolvers/#custom-resolvers). 
Fixed them by adding a overflow where scrollbars only appear when the content is overflowing. The table now even looks responsive.
> fix:table cutoff

- src/pages/cli/migration/cli-auth-signup-changes.mdx
Currently last two code snippets of https://docs.amplify.aws/cli/migration/cli-auth-signup-changes/ is not highlighted properly. Adding `ts` to do so.
> Add typescript syntax highlight to `cli-auth-signup-changes/`

- src/fragments/lib/auth/js/advanced.mdx
The `Authentication Advanced Workflows` doc says that `validationData` for Lambda triggers `Pre Autnetication` and `Pre Sign-up` can be an array of key-value pairs. The code inside AmplifyJS Auth package [here](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L335) and [here](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L485) suggests that it should be an object. This PR updates the comment to change the wording from `array` to `object`.
> Update comment about validationData been an object instead of an array

- src/pages/cli/graphql-transformer/http.mdx
https://github.com/aws-amplify/amplify-cli/issues/6520
I've submitted a pull request (https://github.com/aws-amplify/amplify-cli/pull/7277) to amplify-cli that adds support for a `${region}` template in the graphql `@http` annotation's `url` field. This commit adds documentation for that change, to be merged after the source PR adds the feature.
> document ${region} template for @http directive

- src/fragments/lib/storage/flutter/configureaccess/10_protected_upload.mdx
- src/fragments/lib/storage/flutter/download.mdx
- src/fragments/lib/storage/flutter/upload.mdx
- src/fragments/lib/storage/flutter/upload/upload-create-file.mdx
_Issue #, if available:_ Related to our PR to add progress callbacks to the Flutter Storage API: https://github.com/aws-amplify/amplify-flutter/pull/928
_Description of changes:_ Update our code examples to use the progress callbacks 
> Update storage api examples with progress callback

- src/pages/cli/graphql-transformer/http.mdx
https://github.com/aws-amplify/docs/issues/3738
- update httpx.mdx for correct `aws_region` ref
> update httpx.mdx for correct `aws_region` ref

- src/fragments/sdk/storage/ios/transfer-utility.mdx
* [aws-sdk-ios#3474](https://github.com/aws-amplify/aws-sdk-ios/issues/3474)
The docs on auto-resume for Transfer Utility needs to be revised to use the features in the current code base.
> updates docs on how to auto-resume s3 network tasks

- src/fragments/guides/location-service/setting-up-your-app-js.mdx
Now that Geo is in GA, the old Amazon Location Guide in our docs is set for deprecation and removal. The first step for this is adding a banner to point people to use Amplify Geo instead. This PR adds that banner:
> docs(geo): add Geo banner to Location Service Guide

- src/plugins/code-block.tsx
live:
staging:
https://docs.amplify.aws/start/getting-started/setup/q/integration/android/#add-amplify-to-your-application
> Fix bug where second version in code block isn't replaced (start page)

- src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx
Hosted UI instructions currently specify the usage of a <queries> element in the AndroidManifest, which requires a gradle plugin upgrade in the customers app. See this[ blog post](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html) for context.
> fix(flutter): Specifies gradle plugin for queries element in manifest

- src/pages/cli/function/secrets.mdx
Inconsistencies were identified from this CLI issue https://github.com/aws-amplify/amplify-cli/issues/8426
- updates `amplify env add --yes` to include environment name flag, `amplify env add --envName <new env name> --yes`
- updates `amplify checkout envB` to `amplify env checkout envB`
> fix(docs): CLI env commands

- src/fragments/lib/auth/flutter/signin_web_ui/40_private_session.mdx
- src/fragments/lib/auth/native_common/signin_web_ui/common.mdx
Adds documentation for `preferPrivateSession` API parameter in Flutter Social Sign In docs. 
> fix(flutter): preferPrivateSession docs

- src/pages/cli/hosting/hosting.mdx
In the documentation for Hosting, it states that there should be a redirect address but it does not specify what that address should be. I have created a react app with navigation controlled by react-router. I think it would be best for our customers to have that route stated explicitly without having to look through various stack overflow pages.
> chore(updating hosting.mdx): add explicit redirect address

- src/fragments/lib/auth/js/advanced.mdx
- src/fragments/lib/auth/js/getting-started.mdx
- src/fragments/start/getting-started/angular/setup.mdx
- src/fragments/start/getting-started/ionic/setup.mdx
- src/fragments/start/getting-started/next/api.mdx
- src/fragments/start/getting-started/next/setup.mdx
- src/fragments/start/getting-started/react/setup.mdx
_Description of changes:_ This PR fixes references to `@aws-amplify/ui-[framework]` to version 1, since we just published `2.x.x` and need to be careful about ui code snippets on the doc.
Pinning it to 1.x.x to unblock customers for now, and next sprint we can update the snippets to use v2.
> Update UI references to v1

- src/fragments/lib/geo/ios/getting_started/10_pre_req.mdx
N/A
Update the minimum Xcode version pre-requisite for the AmplifyMapLibreAdapter from Xcode 13.0 to Xcode 12.0 based on [changes](https://github.com/aws-amplify/amplify-ios-maplibre/commit/f3dd65f32861d7e6491a3dd08d9f70f35889c1e8).
Change covers AmplifyMapLibreAdapter release [0.1.2](https://github.com/aws-amplify/amplify-ios-maplibre/releases/tag/0.1.2). 
> chore(iOS): Geo update adapter Xcode version pre-req

- src/pages/cli/migration/transformer-migration.mdx
The image owner-auth-migration.png was used twice (once to show v1 schema and again to show v2 schema), but it includes both original and migrated schema, so I removed the duplicate image and adjusted the alt text
> Fixed duplicate images

- src/components/SidebarLayoutToggle/styles.tsx
Currently some text in footer is hidden due to the Sidebar layout toggle button in Mobile view
This pull request fixes this issue.
> fix:hidden footer text

- src/pages/cli/start/workflows.mdx
Adds a callout for folks upgrading the CLI and attempting to use the new GraphQL directives before migrating their schema 
> chore(cli): add callout for gql transformer v2 migrations on cli upgrade

- src/pages/cli/geo/maps.mdx
- src/pages/cli/geo/search.mdx
Adds a brief comment on why Auth is needed for Maps and Search capabilities of CLI. 
_ScreenShots:_
> Add why auth is needed for maps and search functionality

- src/fragments/cli/plugins/custom-transformer.mdx
This PR updates the Custom Transformer page to reflect GraphQL Transformer V2 changes.
>Note: Since the `@versioned` directive was deprecated the code examples shows off `@model` snippets instead.
> chore: update customer transformer page to gql v2

- src/fragments/lib/datastore/native_common/real-time.mdx
- Update Observe Query docs with the goal of clarifying that it can be used for real-time use cases after sync has completed.
> chore: update observeQuery docs

- src/fragments/lib/datastore/ios/data-access/save-snippet.mdx
- src/fragments/lib/datastore/ios/data-access/update-snippet.mdx
- src/fragments/lib/datastore/ios/getting-started/60_saveSnippet.mdx
N/A
The existing `Combine` example snippet for `Amplify.DataStore.save(…)` doesn't compile due it implicitly ignoring the closure argument in `receiveValue`.
This PR adds the anonymous closure argument in `receiveValue` closure.
> fix(iOS): Add anonymous closure argument to DataStore.save() Combine

- src/utils/withFilterOverrides.ts
Docs site was linking the user to the js getting started section from the flutter UI components page. The cause was that we weren't handling flutter cases in the `withFilterOverrides` function. This PR attempts to solve that issue. The overall  function could possibly use some refactoring in order to scale with more frameworks, but I think this solves the immediate issue.
> fix(flutter): handles setting platform and framework to flutter

- src/fragments/guides/api-graphql/js/image-and-file-uploads.mdx
- src/fragments/guides/hosting/git-based-deployments.mdx
- src/fragments/guides/hosting/local-deployments.mdx
- src/fragments/guides/location-service/setting-up-your-app-js.mdx
- src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
- src/fragments/start/getting-started/react/setup.mdx
- src/fragments/ui-legacy/auth/react/tutorial.mdx
Reverts aws-amplify/docs#3874
This is no longer needed. The JS team has a new patch for CRA with webpack 5.
> Revert "Update references to CRA"

- src/pages/cli/graphql/authorization-rules.mdx
_Issue #, if available:_ Resolves #3896
Platforms are automatically included in relative links. Removing the platform part of the URL allows the link to be relative for the platform the user has been viewing. (E.g. if they were looking at JS docs then the JS platform should be automatically included, same for flutter, etc...)
> Fix broken graphql API links

- src/fragments/lib/auth/ios/signin_web_ui/20_platform_specific_setup.mdx
> chore: Auth iOS sign in with webUI Xcode 13 SwiftUI app URLScheme

- src/fragments/sdk/auth/android/hosted-ui.mdx
> [Android] Fix wrong package name being used for SDK documentation

- src/pages/cli/usage/headless.mdx
https://github.com/aws-amplify/amplify-cli/issues/9458
Realized that some recently added headless commands were not documented
> feat: add docs for headless import auth and headless storage

- src/pages/cli/graphql/custom-business-logic.mdx
Akshbhu recommended using cdk.FN.ref in https://github.com/aws-amplify/amplify-cli/issues/9391
This is the right approach and should be updated.
Migration info for users using going from ES to OS was added as well, the data source is renamed automatically when migrating and resolvers need to be updated as such.
https://github.com/aws-amplify/amplify-cli/issues/9424
Updated resolver template to use cdk.FN.ref and added note about going from Elastic to OpenSearch
> Updated custom resolver info

- src/fragments/lib/datastore/native_common/callout/datastore-clear-with-auth.mdx
- src/fragments/lib/datastore/native_common/other-methods.mdx
- src/fragments/lib/datastore/native_common/setup-auth-rules.mdx
Add a callout about calling `DataStore.clear()` on user signing in/signing out when using Auth in DataStore authorization rules section to reduce confusion.
> Add callout about calling DataStore.clear() when using auth

- src/pages/cli/custom/cdk.mdx
Fix typo in "Use CDK to add custom AWS resources" page
Fix typo in the "Use CDK to add custom AWS resources" page of the docs. There is a missing space after a period and before the word "Edit"
> fix: remove typo in docs

- src/fragments/lib/pubsub/js/getting-started.mdx
I am not sure about this but in my case the promise of Auth.currentCredentials() is the interface “ICredentials” and has only keys starting with a lower-case letter. 
export interface ICredentials {
accessKeyId: string;
sessionToken: string;
secretAccessKey: string;
identityId: string;
authenticated: boolean;
expiration?: Date;
}
_Description of changes: info.IdentityId; to info.identityId;
> Possible typo in the AWS Amplify PubSub docs

- src/pages/cli/usage/containers.mdx
https://github.com/aws-amplify/amplify-cli/issues/7661
Update the `docker-compose.yml` example to include the correct secret usage.
> docs(api): update docker example for container secrets

- src/fragments/lib/graphqlapi/android/query-data.mdx
- Amplify.API.query(request) gives the response, no field 'response' found error
- while catching exception, error is the var name instead of failure
> updated bugs found while implementation

- src/fragments/start/getting-started/flutter/add-api.mdx
Small update - wrong function name was used for configuring Amplify
> Small update - wrong function name was used for configuring Amplify

- src/fragments/start/getting-started/ios/integrate.mdx
N/A
Added a project generated snippet in the iOS getting started guide for clarity that it should remain.
> fix(iOS): Add missing snippet in iOS getting started

- src/components/Footer/index.tsx
n/a
Changes footer from using hardcoded year `2021` to generate year based on current date with `new Date().getFullYear()`
> fix: footer copyright date to use current year

- Readme.md
_Description of changes:_ Updated readme to add steps for debugging the docs site in a browser's dev tools.
> Add steps to debug client code in browser dev tools

- package.json
Spellcheck is slow
Make spellcheck faster by running on pre-commit and only checking modified files.
In testing, this brings spell check time down to < 1 sec (assuming a reasonably sized commit diff), as opposed to ~45 seconds when spellchecking the whole repo.
The script would be a little cleaner if we upgraded to cspell v 5 which has a `--file-list stdin` option but I'm not sure if other stuff would break doing that.
> chore: add spellcheck diff script

- src/fragments/lib/project-setup/native_common/prereq/common_body.mdx
- src/fragments/start/getting-started/common/prereq.mdx
- src/pages/cli/start/install.mdx
#2320
- Context: CLI is already defaulting to Amplify-scoped policy but documentation doesn't reflect it yet. This PR fixes that.
> Updates documentation to use Amplify-scoped policy

- src/pages/cli/graphql/search-and-result-aggregations.mdx
We aren't using opensearch and parameter names have changed, updating docs to reflect that
> fix: we don't use elasticsearch anymore

- src/pages/cli/graphql/custom-business-logic.mdx
https://github.com/aws-amplify/amplify-cli/issues/9856
- Splits single table into three separate tables by GraphQL operation
- [Query](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts#L46-L47) table inherits original table
- [Mutation](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts#L66-L67) table changes pre/postDataLoad with pre/postUpdate
- [Subscription](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-graphql-transformer-core/src/transformer-context/resolver.ts#L85) table to gain the `preSubscribe` slot using the description from `preDataLoad` …
> fix(docs): CLI - split supported resolver slots by operation

- src/pages/cli/graphql/custom-business-logic.mdx
corrects subscription resolver slot description for `preSubscribe`
> fix(docs): CLI - correct subscription resolver slot description

- src/pages/cli/migration/override.mdx
n/a
adds `api` to sample override command `<api|auth|project|storage>`
> docs(cli): add `api` to override sample command

- src/fragments/lib/geo/android/escapehatch.mdx
- src/fragments/lib/geo/ios/escapehatch.mdx
N/A
Updated links on Location escape hatch pages for Android and iOS to include guides and API references as part of the Deprecation Plan for Amazon Location Guides.
After merging this PR, we need to set up 301's as follows:
1. https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/ios/ &rarr; https://docs.amplify.aws/lib/geo/getting-started/q/platform/ios/
2. https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/android/ &rarr; https://docs.amplify.aws/lib/geo/getting-started/q/platform/android/
3. https://docs.amplify.aws/guides/location-service/tracking-device-location/q/platform/ios/ &rarr; https://docs.amplify.aws/lib/geo/escapehatch/q/platform/ios/
4. …
> chore(native): update escape hatch reference links

- src/directory/directory.js
- Remove location service guide link from guides for JS only
- Already setup redirect for https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/js/ to https://docs.amplify.aws/lib/geo/getting-started/q/platform/js/
> chore: remove directory route for location service guide js

- src/fragments/lib/datastore/flutter/sync/20-savePredicate.mdx
- src/fragments/lib/datastore/flutter/sync/30-savePredicateComparison.mdx
- src/fragments/lib/datastore/native_common/sync-distributed-data.mdx
- src/fragments/lib/datastore/native_common/sync.mdx
- Add DataStore "Distributed Data" section for amplify-flutter doc
- Removed `plain` custom syntax on a code block as it breaks local build, the doc page renders the same without it
Preview
> [missing-page] add distributed data section for amplify-flutter

- src/fragments/lib/project-setup/flutter/null-safety/null-safety.mdx
- src/fragments/lib/project-setup/native_common/prereq/flutter_null_safety.mdx
Add drop non-nullsafety support warning for amplify-flutter
Preview:
> Add drop non-nullsafety support warning for amplify-flutter

- src/fragments/lib/datastore/flutter/sync/50-selectiveSync.mdx
Add missing "Advanced use case - Query instead of Scan" section for flutter docs.
Preview:
> fix(flutter): add missing advanced use case of sync expression section

- src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
- src/fragments/lib/geo/ios/maps/10_install_adapter.mdx
n/a
Added language clarifying incompatibility between existing Amplify dependencies added via cocoapods with the Amplify-MapLibre adapter added via SPM.
> fix(ios): add language clarifying cocoapods / spm incompatibility in geo adapter

- src/pages/console/adminui/access-management.mdx
**Problem:**
The documentation was not clear on the account level implications of
granting a user full access on an Amplify Backend.
**Solution:**
Add a callout to warn the customer and link further documentation on the
policy grants.
**Testing Done:**
```
yarn jest
yarn dev
```
> Adds warning regarding Full Access level users

- src/fragments/lib/auth/android/signin_web_ui/20_platform_specific_setup.mdx
Followup on [this issue](https://github.com/aws-amplify/amplify-android/issues/1648) where users expressed that the docs were not clear enough on this use case of redirecting to another Activity when using Social Sign-in.
> Add docs for Android Social Sign-in redirects

- src/pages/cli/function/index.mdx
n/a
changes default Node.js runtime from `12.x` -> `14.x`
> docs(cli): change default Node.js function runtime version

- src/pages/cli/project/command-hooks.mdx
ref aws-amplify/amplify-cli#9346
change document to match implementation for data parameter structure in hooks script.
Once, I try to change implementation to match documentation, but, it is not a safe change (aws-amplify/amplify-cli#9347). So, I change documentation. 
> fix data parameter structure in hooks script

- src/fragments/lib/storage/js/download.mdx
Old note about Download Progress
This is now working and documentation about how to use it was added in https://github.com/aws-amplify/docs/pull/3238/files
> Removed "Download progress is not possible"

- src/pages/cli/auth/override.mdx
https://github.com/aws-amplify/amplify-cli/issues/1204
fixes https://github.com/aws-amplify/docs/issues/4059
Adds custom attribute example for auth overrides:
```ts
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper'
export function override(resources: AmplifyAuthCognitoStackTemplate) {
const myCustomAttribute = {
attributeDataType: 'String',
developerOnlyAttribute: false,
mutable: true,
name: 'my_custom_attribute',
required: false,
}
resources.userPool.schema = [
...(resources.userPool.schema as any[]), // Carry over existing attributes (example: email)
myCustomAttribute,
]
}
```
> docs(cli): add Cognito custom attribute override example

- src/fragments/lib/graphqlapi/js/authz.mdx
_Issue #3743_
Changed the key of auth type `AWS_LAMBDA` within the `new AWSAppSyncClient()` method from `authToken` to ` token` according to the aws-appsync SDK.
> Changing authToken to token

- src/fragments/start/getting-started/vue/data-model.mdx
_Issue #, if available:_ https://github.com/aws-amplify/docs/issues/3534
due to race conditions caused in appsync query via js function adding the subscribe can mitigate the issue.
> added vue getting started subscribe in created method

- src/fragments/start/getting-started/next/api.mdx
_Issue #, if available:_ #4013
_Description of changes:_ Fix "<Server Error
Error: Body must be a string. Received: undefined." bug by using Amplify UI version consistently in the guide
> Use UI version 1 consistently in the Next.js getting started guide

- cspell.json
- src/fragments/guides/hosting/nextjs.mdx
https://github.com/aws-amplify/docs/issues/3520
https://github.com/aws-amplify/docs/issues/3776
Update the static Next.js section to reflect that `next export` does not support the Image component. SSR support in Hosting does support the component and now has a link to the support docs.
> Update Hosting Next.js support statements

- src/fragments/start/getting-started/reactnative/setup.mdx
Changed the order of the quickstart guide for RN to first create the RN app, then initialize the Amplify project.
> update change to react native quickstart guide

- src/pages/cli/plugins/plugins.mdx
- Adding a doc entry for amplify-graphql-seed-plugin in third party plugins section
> Add entry for amplify graphql seed plugin in third party plugins section

- src/fragments/lib/datastore/native_common/how-it-works.mdx
Mutation is missing the full selection set for DataStore clients to receive a fully accurate subscription event containing the mutation response.
Add `createdAt` and `updatedAt` so that they are returned in the subscription event
> fix: Getting-Started iOS - add necessary selection set for datastore sync

- src/pages/cli/usage/headless.mdx
https://github.com/aws-amplify/amplify-cli/pull/9786
Updates auth headless payload paths to version 2
> fix: update headless auth path to version 2

- .gitignore
- amplify.yml
- tasks/generate-sitemap.ts
No crawling allowed if we're on a preview branch (to potentially avoid unnecessary 404 alerting).
Requires setting `ALLOW_ROBOTS` flags in Amplify Console.
Interesting point: docsearch and `yarn` installing packages depends on `NODE_ENV` being set.
> Add a flag to configure `robots.txt` depending on preview branch

- src/fragments/lib/analytics/ios/getting-started/20_installLib.mdx
- src/fragments/lib/auth/ios/getting_started/20_installLib.mdx
- src/fragments/lib/datastore/ios/getting-started/20_installLib.mdx
- src/fragments/lib/graphqlapi/ios/getting-started/20_installLib.mdx
- src/fragments/lib/ios-spm.mdx
- src/fragments/lib/restapi/ios/getting-started/20_installLib.mdx
- src/fragments/lib/storage/ios/getting-started/20_installLib.mdx
These updates reflect the updated steps for adding Packages to an iOS project using Swift Package Manager (SPM) with Xcode 13.
This revision puts the first two primary steps for SPM in a reusable .mdx file and embeds that file into the relevant Getting Started pages for the supported categories.
Since this copy is being reused, initial statements like:
> To install the Amplify Storage and Authentication to your application...
have been updated to:
> To install Amplify Libraries to your application...
PS
If there is a way to pass variables to reusable .mdx files, that method should be used instead of the implementation of this PR.
> Update SPM installation instructions for iOS

- src/fragments/lib/datastore/native_common/other-methods.mdx
https://github.com/aws-amplify/amplify-flutter/issues/1470
To clarify that `Amplify.DataStore.clear` also stops DataStore sync process, so it's clear to customers that no need of calling `Amplify.DataStore.stop` before calling `Amplify.DataStore.clear`.
> fix(datastore): clarify clear method also stops DataStore sync process

- src/pages/guides/api-graphql/lambda-resolvers/q/platform/[platform].mdx
The Lambda resolvers tutorial has the customer create the `addingfunction` then operate on the `echofunction`, then creating the `addingfunction` again later on. The AppSync schema then references the `addingfunction` by the name `addfunction` which doesn't work.
> fix: Lambda Resolver tutorial naming issues

- src/pages/cli/auth/override.mdx
_Issue [#9307](https://github.com/aws-amplify/amplify-cli/issues/9307)
- document how to use `auth override` in order to add social providers to the amplify generated cognito user pool
> auth override add cognito user pool social provider

- src/fragments/lib/datastore/flutter/getting-started/50_codegenCli.mdx
This PR has a small fix to correct the path of codegen files for flutter.
> fix(flutter): correct codegen directory

- src/fragments/lib/graphqlapi/ios/advanced-workflows/30_nested.mdx
Fix example query
The example in the docs describes getting a Post with comments only, `getPostWithComments`. However the example query does the inverse, `getCommentWithPost`
> Update iOS advanced workflow docs on nested data

- src/pages/cli-legacy/graphql-transformer/overview.mdx
- src/pages/cli/graphql/overview.mdx
Clarifies that `--allow-destructive-graphql-schema-updates` can be used in production to make breaking changes to an API if necessary, but backups should be created if table data needs to be retained.
> fix: clarify wording around when to use destructive updates flag

- src/fragments/start/getting-started/react/setup.mdx
According to the JSDoc of ``Amplify.d.ts`` default import of 'Amplify' is deprecated.
```ts
export declare const Amplify: AmplifyClass;
/**
* @deprecated use named import
*/
export default Amplify;
```
Change docs to reflect ``.d.ts`` file.
```ts
import Amplify from "aws-amplify";
import awsExports from "./aws-exports";
Amplify.configure(awsExports);
```
Should be:
```ts
import { Amplify } from "aws-amplify";
import awsExports from "./aws-exports";
Amplify.configure(awsExports);
```
> Change from default to named import.

- src/fragments/lib/datastore/js/other-methods.mdx
https://github.com/aws-amplify/amplify-js/issues/8658
Remove note that DataStore must be started before it can be cleared. https://github.com/aws-amplify/amplify-js/pull/9768
> feat: clear DataStore without first starting

- src/fragments/ui/storage/web/s3-image.mdx
#3243 
Images not shown if `img-key="{{file.key}}"` instead of `imgKey="{{file.key}}"`. Issue might have been transferred to amplify-js, but the problem still has not been remedied. In fact, an error is now thrown if `img-key="{{file.key}}"` is done in Anglar. 
Add examples of data binding the  "img-key" attribute in Angular and Ionic
Angular
Ionic
> Added Angular & Ionic data binding examples

- src/fragments/lib/geo/android/getting_started/20_cli_resources.mdx
- src/fragments/lib/geo/ios/getting_started/20_cli_resources.mdx
Removes resource provisioning portion of "getting started" that uses the `@geo` tagged cli version on iOS and Android.
> chore(native/geo): remove geo tagged cli setup

- src/fragments/sdk/push-notifications/android/handle-fcm.mdx
- src/fragments/sdk/push-notifications/android/setup-fcm.mdx
- src/fragments/sdk/push-notifications/ios/getting-started.mdx
- src/pages/sdk/push-notifications/setup-push-service/q/platform/[platform].mdx
_Issue #, if available:_ #4002
_Description of changes:_ Adds missing instructions to the Android SDK docs for setting up FCM push notifications. Also fixes a code formatting issue in the iOS SDK push notification docs.
> fix(Android): add push notification setup section

- src/pages/cli/graphql/authorization-rules.mdx
_Description of changes:_ Adds missing comma to authorization docs example with multiple authorization rules.
> docs(graphql): fix minor error in example

- tasks/build-algolia-search.mjs
Remove check for descriptions when creating Algolia index
> Remove check for description (unused)

- src/components/SearchBar/Autocomplete.tsx
- src/components/SearchBar/index.tsx
- tasks/build-algolia-search.mjs
This operation is atomic, so customers don't find situations
when there are no objects in the index.
This change also makes the index name configurable per environment,
so we can have different indexes in production and staging.
@jakeburden test this in staging before merging 🙏 
> Move indexes instead of deleting objects

- src/pages/cli/project/troubleshooting.mdx
Replaces the single dash in front of the flag with two dashes.
Before: `amplify push —allow-destructive-graphql-schema-updates`
After: `amplify push --allow-destructive-graphql-schema-updates`
> Fix --allow-destructive-graphql-schema-update snippet

- src/fragments/lib/analytics/js/getting-started.mdx
https://github.com/aws-amplify/docs/issues/2866
- Adds a callout for the max endpoint quota from Pinpoint documentation
- Adds a `(default)` label to the `optOut` option
> Add callout for endpoint quotas and defaults for Analytics (JS)

- src/pages/cli/graphql/data-modeling.mdx
_Issue #, if available:_https://github.com/aws-amplify/docs/issues/3662
Provide specific examples on graphql auto generated queries disabling, renaming and creating custom query
> change the generated queries in graphql data modeling

- src/fragments/lib/auth/common/sms/flows.mdx
- src/fragments/lib/auth/js/mfa.mdx
- src/fragments/lib/auth/native_common/signin/common.mdx
#4128 
Cognito is planning to add below update:
"Note: If you create or update an SMS MFA configuration for your Cognito user pool, the Cognito service will send a test SMS message to an internal number in order to verify your configuration. You will be charged for these test messages by Amazon SNS. For information about Amazon SNS pricing, see Worldwide SMS Pricing."
Whenever Cognito SMS Configuration is enabled implicitly by amplify, please add callout to reflect the above.
> Add callouts for internal test SMS configuration verification

- src/fragments/start/getting-started/ios/generate-model.mdx
N/A
There's currently an issue that the `schema.graphql` file generated by the CLI doesn't automatically get added to the Xcode project. A fix for the underlying issue is being worked on, but in the meantime, this change adds a callout advising how to add it themselves.
> fix: ios getting started - add temporary callout for schema.graphql

- src/fragments/lib/auth/js/device_features/30_fetchDevice.mdx
None
The original snippet throws an error as the `catch` block passes `err` but the log references `error`. This fixes that and formats the snippet to align with the style of other snippets on this page.
> Fix typo in Auth.fetchDevices JS snippet

- src/components/FeatureFlags/feature-flags.json
This documents the new CLI feature flag for changes to the default identity claim on GQL API mutations.
> doc: documents feature flag for changing the default identity claim

- src/pages/cli/graphql/authorization-rules.mdx
Updates the `@auth` docs to describe the new default identity claim as `<sub>:<username>`.
> doc: add changes to default identity claim and description

- src/pages/cli/migration/identity-claim-changes.mdx
Related changes: https://github.com/aws-amplify/amplify-cli/pull/10196
Adds migration guides/docs to the identity claim changes in the CLI. The default identity claim is changing form 'username' to 'sub::username'.
> add identity claim change docs

- src/pages/cli/graphql/override.mdx
added an example on how to change the model datasource `baseTableTtl` using dynamoDbConfig.
Note: using the `.` annotation will not work for the ['deltaSyncConfig']['baseTableTtl'] parameters. the build will the following error.
```
Build error : Packaging overrides failed with the error:
Command failed with exit code 2: C:\amplify\appsyncsubs\amplify\backend\node_modules\.bin\tsc --project C:\amplify\appsyncsubs\amplify\backend\api\appsyncsubs\build\tsconfig.resource.json
../override.ts(4,73): error TS2339: Property 'deltaSyncConfig' does not exist on type 'DynamoDBConfigProperty | IResolvable'.
Property 'deltaSyncConfig' does not exist on type 'IResolvable'
```
but the example works verified this with the `aws appsync get-data-source --api-id <api id> --name …
> added api override example for dynamodb as datasource

- src/fragments/cli/plugins/custom-transformer.mdx
- src/pages/cli-legacy/graphql-transformer/searchable.mdx
N/A, tracked in an internal ticket.
During migration of the graphql-transformer packages from the cli repo to the api category repo we'd missed docs updates that we need to make. This updates the paths for any links that matched the following regex:
```
github.com/aws-amplify/amplify-cli.*(amplify-graphql-auth-transformer|amplify-graphql-default-value-transformer|amplify-graphql-function-transformer|amplify-graphql-http-transformer|amplify-graphql-index-transformer|amplify-graphql-maps-to-transformer|amplify-graphql-migration-tests|amplify-graphql-model-transformer|amplify-graphql-predictions-transformer|amplify-graphql-relational-transformer|amplify-graphql-schema-test-library|amplify-graphql-searchable-transformer|amplify-graphql-transfo …
```
> fix: update source code links for migrated api packages

- src/pages/cli/usage/lambda-triggers.mdx
changes Vue example to import all modules, removes import of the deprecated default export
> fix: vue example to not use Amplify default export

- src/pages/console/uibuilder/responsive.mdx
Removes some confusing props from the UiBuilder responsive docs that don't seem to be needed in the example.
> Fix uibuilder responsive example

- src/pages/cli/graphql/authorization-rules.mdx
_Issue #, if available:_ #4292, 404 page for `per-user--owner-based-data-access`
_Description of changes:_ Added the hash symbol to the url so it links to the heading instead of a 404 page
> Add missing hash symbol to url

- src/fragments/start/getting-started/reactnative/add-api.mdx
Currently, the RN getting started guide does not include steps to deploy **Auth** in the _Connect to the Cloud_ section. The Auth needs to be deployed as we are using @auth directive is used. 
This will bring this guide in parity to flutter getting started guide which also needs Authentication to be deployed.
> Add missing step to deploy auth in RN getting started guide

- src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx
This PR adds the instructions for using ExpoSQLiteAdapter for datastore for Expo CLI built apps.
> Add datastore getting started docs for exposqliteadapter

- src/fragments/lib/datastore/flutter/setup-auth-rules/10_multiauth-snippet.mdx
https://github.com/aws-amplify/amplify-flutter/issues/815
- Removes warning about lack of multiauth support in Flutter
- Adds multiauth configuration example
> chore(flutter): Add multiauth docs

- src/fragments/lib/datastore/flutter/conflict.mdx
https://github.com/aws-amplify/amplify-flutter/issues/230
Add document and usage example of the `conflictHandler` of DataStore in amplify-flutter.
> feat(fluter): add document for conflictHandler API

- src/components/Menu/FilterSelect/index.tsx
- src/components/Page/index.tsx
- src/directory/directory.js
- src/fragments/guides/api-graphql/flutter/subscriptions-by-id.mdx
- src/pages/guides/api-graphql/subscriptions-by-id/q/platform/[platform].mdx
In amplify-flutter, there was a request for subscription onCreate with a filter. https://github.com/aws-amplify/amplify-flutter/issues/1482
I noticed there were examples for other platforms but not for flutter, so this PR adds example for flutter. This is the only entry for flutter in "guides" section of docs, so there were some changes to configuration code to enable flutter entries for guides. Right now, this is the only part available. 
> feat(flutter): add 'guide' for flutter GraphQL subscription with filter

- src/fragments/lib/auth/js/advanced.mdx
- src/fragments/lib/auth/js/social.mdx
_Description of changes:_ This removes outdated reference to the old `aws-amplify-react` package in this [page](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/). Auth0 is no longer supported directly by the latest Authenticator, and the current recommended approach with Auth0 is to setup directly with Amplify JS with snippets as described [here](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#federate-with-auth0).
Also moves Amplify UI Components call out to social sign-in page, which Authenticator does support officially.
> Remove outdated references to legacy ui packages

- src/components/Footer/index.tsx
This PR updates the footer sentence to include the word "software" without which the sentence sounds incomplete. Also fixes some of the formatting so that Copyright and All Rights Reserved are on their own lines. 
*Before:*
*After:*
*Updates:*
* "Amplify open source, documentation and community are supported" => "Amplify open source _software_, documentation and community are supported" (without "software, this sounded incomplete)
* Put Copyright and All Rights Reserved on their own lines for readability
> fix: footer text and formatting

- src/fragments/lib/graphqlapi/ios/advanced-workflows/30_nested.mdx
#4322 
Fixed code snippet in nested object query on the Advanced Workflows page in API (GraphQL) iOS.
- Fixed compiler error (mismatched types + extraneous `.self`.
- Added `decodePath` to address runtime deserialization issue in example.
> fix(ios): API - add `decodePath` to nested query

- src/pages/cli/graphql/data-modeling.mdx
https://github.com/aws-amplify/amplify-ios/issues/1657
Adds a temporary callout to the CLI data modeling section of API (GraphQL) to inform customers that this feature will not work on iOS.
> fix(cli): add callout in many-to-many for iOS

- src/pages/start/q/integration/[integration].mdx
Changed references of Amplify Console to Amplify Hosting in the Getting Started page.
> Changed references of Amplify Console to Amplify Hosting

- src/pages/console/uibuilder/bestpractices.mdx
- Youtube embeds in `Figma-to-Code best practices` were not showing up in prod because they were blocked by the content security policy. Change them to use `youtube-nocookie.com` embed links.
> Change youtube.com embeds to youtube-nocookie.com

- .github/actions/fetch_amplify_backend/action.yml
- .github/workflows/build.yml
- build_support/pull-environment.sh
- Forked PRs are not able to build on github workflow because they don't have access to environment variables in the Docs repo. Use `pull_request_target` to handle PRs
- Based off of https://github.com/aws-amplify/amplify-ui/pull/855
> Use 'pull_request_target' for Github workflow

- src/pages/cli/migration/identity-claim-changes.mdx
Updates the docs to use match instead of wildcard. After doing some manual testing, the wildcard operator doesn't seem to work with colon (I couldn't find docs that named it as a reserved character), so I've tested with match to make sure the desired behavior works. This updates the docs to reflect.
> doc: change wildcard filter to match

- src/fragments/lib/auth/android/signin_web_ui/20_platform_specific_setup.mdx
[3644](https://github.com/aws-amplify/docs/issues/3644)
[amplify-android 1536](https://github.com/aws-amplify/amplify-android/issues/1536)
Add a Callout for Amplify 1.17.8+ on how to capture sign in cancellations if necessary.
> Fix: Callout to inform customer to capture cancelled sign in

- src/fragments/start/getting-started/reactnative/integrate.mdx
https://github.com/aws-amplify/docs/issues/4395
Fix broken link in React Native Getting Started guide that points to the Observe Query Results in Real-Time page - 
https://docs.amplify.aws/start/getting-started/integrate/q/integration/react-native/#querying-for-todos-and-observing-updates-in-real-time
> Fix broken link for Observe Query Results in Real-Time

- src/pages/cli/migration/identity-claim-changes.mdx
Accompanies https://github.com/aws-amplify/amplify-category-api/pull/517
Adds an explanation and workaround for breaking changes with configuring a primary key's sort key that is used for owner auth.
> doc: add section about breaking @primaryKey/@auth changes

- src/fragments/start/getting-started/next/api.mdx
- src/fragments/start/getting-started/next/setup.mdx
Fixes: https://github.com/aws-amplify/docs/issues/4418
This PR corrects the [AmplifyAuthenticator import statement](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#optional-test-your-api) which was resulting in an [error for a customer](https://github.com/aws-amplify/docs/issues/4418). 
It also updates a few out-of-date npm commands for installing Amplify libraries.
> docs(fix): correct AmplifyAuthenticator import statement in NextJS tutorial

- src/pages/cli/graphql/troubleshooting.mdx
- fixes small typo "none of one" -- assumed to be "none or one"
- adds inline code blocks where necessary
> fix: typo in GraphQL troubleshooting guide

- src/fragments/start/getting-started/flutter/integrate.mdx
Fix "The getter 'isCompleted' isn't defined for the type 'Todo'."
I was following the `Getting Started` docs for creating a To-Do app using `amplify-flutter`. On the integration step, I copied the boilerplate UI code from the docs. `todo.isCompleted` was giving a `not-defined` error. Changing that to `todo.isComplete` resolved the issue and I could run the app.
Error message:
```
The getter 'isCompleted' isn't defined for the type 'Todo'.
Try importing the library that defines 'isCompleted', correcting the name to the name of an existing getter, or defining a getter or field named 'isCompleted'.
```
> Update integrate.mdx (flutter)

- src/components/FeatureFlags/feature-flags.json
- src/pages/cli/usage/headless.mdx
- src/pages/cli/usage/mock.mdx
CLI is moving to split branch names `dev` and `main`. This PR changes all urls pointing to CLI repo to point to the `main` branch. Ref: https://github.com/aws-amplify/amplify-cli/pull/10663
> chore: change master to main

- src/components/FeatureFlags/feature-flags.json
Documents the flipping of the feature flag to change the default identity claim here: https://github.com/aws-amplify/amplify-cli/pull/10580
> doc: feature flag for useSubUsernameForDefaultIdentityClaim

- src/fragments/lib/datastore/android/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/flutter/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/ios/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/js/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/js/data-access/update-snippet.mdx
- src/fragments/lib/datastore/native_common/data-access.mdx
Expands on the warnings about working with stale data in DataStore, updates the save examples to reflect recommended usage, and adds examples of addressing with `observeQuery`.
> expanded warnings and examples about working with stale data

- src/fragments/lib/datastore/flutter/advanced-workflows/custom-primary-key/query-snippet.mdx
Add Flutter custom primary key query code example.
Delete record by custom primary key is not applicable to amplify-flutter.
> Add amplify-flutter query code example

- src/fragments/lib/geo/js/search.mdx
- Update location search docs to include documentation on `searchIndexName` to override the default search index
> fix(geo): update location search API docs to include searchIndexName

- src/pages/cli/graphql/authorization-rules.mdx
N/A
Add a callout to `owner` auth mode docs which details how to lock down updates to the owner field.
> chore: add callout details that owner auth by default allows reassignment

- src/fragments/lib/storage/js/upload.mdx
#10053 in aws/amplify-js repo
https://github.com/aws-amplify/amplify-js/issues/10053
**Change:** Added a callout element with a note explaining the difference between Type and contentType in terms of uploading objects into S3. I also added an example, so users understand the implications of the note when uploading and accessing S3 files. 
**Background:** There can be confusion when users upload a file to S3 because the Type displayed in the S3 console is based on the extension of the 'key' of the uploaded file, while the contentType which determines how S3 treats the object is stored in the metadata. This means when a developer uploads a file, it could lead to confusion since Type in the S3 console may not match the contentType passed …
> Adding additional info on contenttype and type for s3

- src/fragments/lib/auth/js/advanced.mdx
- src/fragments/lib/auth/js/emailpassword.mdx
Adds auto sign in usage in sign up section
Adds clientMetadata and validationData usage for auto sign-in within advanced workflows section
> Add auto sign-in after sign-up usage documentation

- src/fragments/lib/auth/android/signin_web_ui/20_platform_specific_setup.mdx
- src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx
_Issue #, if available:_ #4397
_Description of changes:_ Sets the "android:exported" property on activities for sign in with web UI and social sign in.
> fix(android, flutter): add exported property to activities

- src/pages/cli/usage/mock.mdx
Add support for mocking the lambda triggers attached to `@model` types defined in customer's schema. 
These triggers are added following the CLI flow as noted [here](https://docs.amplify.aws/cli/usage/lambda-triggers/#as-a-part-of-the-graphql-api-types-with-model-annotation).
> feat(cli): add support for DDB lambda trigger mocking

- src/fragments/lib/ssr/js/getting-started.mdx
added callout for SSR not working for Server side functions without req object
> added callout for SSR not working for Server side functions without req object

- src/fragments/lib/datastore/android/data-access/query-predicate-multiple-snippet.mdx
- src/fragments/lib/datastore/android/data-access/query-predicate-or-snippet.mdx
- src/fragments/lib/datastore/android/data-access/save-snippet.mdx
- src/fragments/lib/datastore/android/getting-started/70_saveSnippet.mdx
- src/fragments/lib/datastore/flutter/data-access/query-predicate-multiple-snippet.mdx
- src/fragments/lib/datastore/flutter/data-access/query-predicate-or-snippet.mdx
- src/fragments/lib/datastore/flutter/data-access/save-snippet.mdx
- src/fragments/lib/datastore/flutter/getting-started/60_saveSnippet.mdx
- src/fragments/lib/datastore/flutter/getting-started/80_saveSnippet.mdx
- src/fragments/lib/datastore/js/data-access/delete-snippet.mdx
- src/fragments/lib/datastore/js/data-access/query-predicate-multiple-snippet.mdx
- src/fragments/lib/datastore/js/data-access/query-predicate-or-snippet.mdx
- src/fragments/lib/datastore/js/data-access/save-snippet.mdx
- src/fragments/lib/datastore/js/sync/20-savePredicate.mdx
- src/fragments/lib/datastore/js/sync/30-savePredicateComparison.mdx
- src/fragments/lib/datastore/native_common/data-access.mdx
- src/fragments/lib/datastore/native_common/getting-started.mdx
As a developer reads through the [DataStore - Getting started - JavaScript - AWS Amplify Docs](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/) the GraphQL schema shifts from using `DRAFT` and `PUBLISHED` as the initial values of the `enum PostStatus` to using `ACTIVE` and `INACTIVE` in subsequent pages and the final example application.  
As a result, developers that start with the [DataStore Getting Started page](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/) and create a GraphQL API with the original schema, **but do not visit the** [Updated Schema section on the DataStore - Relational models - JavaScript - AWS Amplify Docs](https://docs.amplify.aws/lib/datastore/relational/q/platform/js/#updated-schema) are not aware of the updated schema …
> fix(docs): Update DataStore PostStatus enum to be consistent across pages

- src/pages/cli/graphql/data-modeling.mdx
Refactor the CLI CPK docs.
- Added the directive definition in the `How it works` section
- Removed transformer output for each CPK schema as it is explained in the `How it works` section
> fix(cli): refactor the CLI custom primary key docs

- src/pages/cli/migration/cli-migrate-aws-account.mdx
Add a callout to the 'migrate to another account' page that migration may not work correctly if custom resources exist in the project
> add custom resource callout to migration page

- src/fragments/lib/auth/flutter/delete_user/10_delete_user.mdx
**Do not merge until functionality is released.**
feat: removes note stating that Android does not support deleteUse on amplify-flutter.
> feat(flutter): removes disclaimer about deleteUser support on Android

- src/pages/guides/functions/configuring-lambda/q/platform/[platform].mdx
The type for `MemorySize` should be `Int`, but it is shown as a string
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
> corrects memorysize cloudformation type for lambda

- src/fragments/lib/graphqlapi/js/subscribe-data.mdx
- src/fragments/lib/pubsub/js/subunsub.mdx
- [#9824](https://github.com/aws-amplify/amplify-js/issues/9824)
- [#6064](https://github.com/aws-amplify/amplify-js/issues/6064)
- [#4459](https://github.com/aws-amplify/amplify-js/issues/4459)
- [#2692](https://github.com/aws-amplify/amplify-js/issues/2692)
- [#2372](https://github.com/aws-amplify/amplify-js/issues/2372)
Having added Hub messages corresponding the PubSub IoT and MQTT websocket connection changes in [amplify-js PR #10136](https://github.com/aws-amplify/amplify-js/pull/10136), this updates the PubSub documentation with basic instructions on how to access these messages.
> feat: Add PubSub Hub Connection state monitoring instructions

- src/fragments/lib/datastore/native_common/getting-started.mdx
Just noticed that the example schemas code block on [this page](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/#sample-schema) is not closed, which makes the rest of this page kind of unreadable. This PR adds the missing code block closing backticks.
> Fix missing code block closing backticks

- src/pages/cli/restapi/override.mdx
Fixup for https://github.com/aws-amplify/docs/pull/4282. 
_Issue #, if available:_ https://github.com/aws-amplify/amplify-category-api/issues/345
_Description of changes:_ Adds in missing dollar signs to`Fn::Sub` function so that the code works correctly.
> Fixes missing dollar signs in string substitution.

- src/fragments/lib/graphqlapi/js/mutate-data.mdx
Amplify transformers do not support cascading delete on many to many relations and this is currently called out in datastore docs.
With this PR, adding the same warning to API category as well.
> chore(api): callout delete warning in api similar to datastore

- src/pages/cli/graphql/authorization-rules.mdx
Issue #4249 
The example graphql schema had an issue when used with datastore. After talking to @renebrandel he suggested this change, although the wording could be improved a bit, I'm sure.
> chore: add datastore callout to multiauth docs

- src/pages/cli/migration/identity-claim-changes.mdx
These changes discuss the implications of enforcing stricter owner identity claims in Auth V2 transformers. 
Relevant changes in API plugin can be found [here](https://github.com/aws-amplify/amplify-category-api/pull/673).
**DO NOT MERGE** until the CLI API plugin changes are live.
> feat(cli-api): add callout for invalid owner identity claims check

- src/fragments/lib/predictions/js/text-speech.mdx
- src/fragments/lib/predictions/js/transcribe.mdx
- src/fragments/lib/predictions/js/translate.mdx
_Description of changes:_ The amplify CLI flow for predictions are different from what the docs describe.
on documentation:
```
? What would you like to convert? 
Convert text into a different language 
Convert text to speech 
❯ Convert speech to text 
Learn More 
```
on CLI:
```
? What would you like to convert? (Use arrow keys)
Translate text into a different language 
> Generate speech audio from text 
Transcribe text from audio
```
> fix:prediction convert flow

- src/pages/cli/project/command-hooks.mdx
CLI issue: https://github.com/aws-amplify/amplify-cli/issues/10253
CLI PR: https://github.com/aws-amplify/amplify-cli/pull/10667
doc changes related to no longer pushing/pulling hook files to the s3 deployment bucket
> doc: command hooks file management changes

- src/directory/directory.js
- src/fragments/lib/project-setup/ios/create-application/50_nextSteps.mdx
- src/fragments/lib/project-setup/native_common/create-application/common.mdx
- src/fragments/start/getting-started/ios/integrate.mdx
- src/fragments/start/getting-started/ios/nextsteps.mdx
* Remove the predictions category from the Amplify iOS Library V2 documentation
Screenshot:
> remove iOS V2 predictions category

- src/pages/cli-legacy/graphql-transformer/config-params.mdx
- src/pages/cli/graphql/override.mdx
https://github.com/aws-amplify/amplify-category-api/issues/715
Provide explicit instructions for how to override opensearch streaming lambda runtime so customers are able to search the top bar if necessary
> Fix: explain how to override streaming lambda runtime

- src/pages/_document.tsx
_Issue #, if  #available:_ closes #4569
- Added `https://img.shields.io` to img-src CSP headers
> Update CSP to allow img.shields.io for img-src

- src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
_Issue #, if available:_ Please see screenshots
_Description of changes:_ Fix heading on Sign In Next Steps page for iOS Auth
> Fix heading on iOS Sign in next steps Auth page

- src/pages/cli/auth/override.mdx
_Issue #, if available:_ https://github.com/aws-amplify/amplify-cli/issues/11065
adding callouts for when using a override on a auth resource. Cognito attribute changes are considered as schema change on a CloudFormation deployment causing errors on project push. The callout aims to warn users on this behaviour.
> callout on auth attributes override

- src/fragments/guides/hosting/nextjs.mdx
Right now, NextJS guides shows unnecessary backticks in [one of the code blocks](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/#adding-amplify-hosting-1:~:text=amplify%20add%20hosting-,%60%60%60console,-%3F%20Select%20the%20plugin).
This PR removes the aforementioned backticks.
> doc(nextjs): Remove unnecessary backticks.

- src/fragments/lib/graphqlapi/ios/advanced-workflows/40_multiple.mdx
- src/fragments/lib/graphqlapi/ios/getting-started/50_createtodo.mdx
- src/fragments/lib/graphqlapi/ios/mutate-data.mdx
- src/fragments/lib/graphqlapi/ios/query-data.mdx
- src/fragments/lib/graphqlapi/ios/subscribe-data.mdx
- src/fragments/lib/restapi/ios/delete.mdx
- src/fragments/lib/restapi/ios/fetch.mdx
- src/fragments/lib/restapi/ios/getting-started/40_postTodo.mdx
- src/fragments/lib/restapi/ios/update.mdx
n/a
Removes unnecessary parentheses in catch statements.
```swift
// changes this:
catch(let error as Foo) {} 
// to this:
catch let error as Foo {}
// and changes this:
catch (let error) {}
// to this: 
catch {}
```
> fix(ios): remove unnecessary parens in catch statements

- src/fragments/lib/geo/ios/maps/10_install_adapter.mdx
N/A
Removes warning about cocoapods usage in iOS Geo. This warning is no longer applicable as v2 doesn't support cocoapods.
> fix(ios): geo remove cocoapods warning

- src/fragments/start/getting-started/ios/setup.mdx
Fixing the link for the **Add packages...** screenshot in the Getting Started tutorial:
> Fixing broken image in Getting Started tutorial

- src/fragments/lib-v1/storage/ios/getting-started/40_upload.mdx
- src/fragments/lib/storage/ios/getting-started/40_upload.mdx
- src/fragments/lib/storage/ios/upload.mdx
N/A
Changes usage of `let data = dataString.data(using: .utf8)!` to `let data = Data(dataString.utf8)` to encourage use of language best practices.
> fix(ios): change data init in storage to remove force unwrap

- src/fragments/lib/auth/ios/getting_started/30_initAuth.mdx
- src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
- src/fragments/lib/ios-spm.mdx
- src/fragments/lib/project-setup/ios/create-application/20_install_libraries.mdx
- src/fragments/lib/project-setup/ios/create-application/30_provisionBackend.mdx
- src/fragments/lib/project-setup/ios/create-application/31_provisionBackend.mdx
- src/fragments/start/getting-started/ios/setup.mdx
_Issue #, if available:_ None 
_Description of changes:_ Replace Amplify iOS with Amplify library for Swift
> Replace Amplify iOS with Amplify library for Swift

- src/fragments/lib/storage/ios/getting-started/30_initStorage.mdx
N/A
Remove the usage of `AppDelegate` in the SwiftUI example of initializing Storage.
> fix(ios): drop appdelegate from swiftui example of initializing Amplify

- src/fragments/lib/auth/native_common/existing_resources/common.mdx
A comma is written that violates the JSON syntax.
Simply copying and pasting and rewriting the placeholder will result in a syntax error.
Remove the comma and modify it to match the JSON syntax.
The pages affected by this fix will be the following
- https://docs.amplify.aws/lib/auth/existing-resources/q/platform/android/
- https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios/
- https://docs.amplify.aws/lib/auth/existing-resources/q/platform/flutter/
- 
> Remove commas that result in JSON syntax errors.

- src/fragments/lib/graphqlapi/android/getting-started.mdx
- src/fragments/lib/graphqlapi/android/getting-started/10_preReq.mdx
- src/fragments/lib/restapi/android/getting-started/10_preReq.mdx
Updates minimum sdk version from 16, to 21 due to library restriction
> chore(android): Update aws-api Android minSDK to 21

- src/fragments/lib/ios.mdx
Remove the Swift SDK warning banner from main landing page since it's already provided in the escape hatch sections.
> fix(ios): remove swift sdk banner from swift landing page

- src/fragments/lib/auth/android/password_management/10_reset_password.mdx
_Description of changes:_ Fixes an error in the Android reset password code snippet.
> fix(Android): correct reset password code block

- src/constants/links.ts
- src/fragments/lib-v1/datastore/ios/data-access/query-pagination-snippet.mdx
- src/fragments/lib-v1/graphqlapi/ios/getting-started.mdx
- src/fragments/lib/datastore/ios/data-access/query-pagination-snippet.mdx
- src/fragments/lib/graphqlapi/ios/getting-started.mdx
N/A
Update broken API docs links after renaming to amplify-swift
> fix(swift): update API docs links after renaming

- src/components/FeatureFlags/feature-flags.json
The description for the true value indicates a link not specific to the modelgen package.  This commit changes the link to the correct URL
_Issue #, if available:_ #4468
_Description of changes:_ Updated URL to the correct value.
> Update link in feature-flags.json

- src/fragments/lib-v1/geo/ios/dev-preview-callout.mdx
- src/fragments/lib-v1/geo/ios/getting_started/30_install_lib.mdx
- src/fragments/lib-v1/graphqlapi/ios/getting-started.mdx
- src/fragments/lib-v1/ios-spm.mdx
- src/fragments/lib-v1/project-setup/ios/create-application/20_install_libraries.mdx
- src/fragments/lib/geo/ios/dev-preview-callout.mdx
- src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
- src/fragments/lib/graphqlapi/ios/getting-started.mdx
- src/fragments/lib/ios-spm.mdx
- src/fragments/lib/project-setup/ios/create-application/20_install_libraries.mdx
- src/fragments/start/getting-started/ios/setup.mdx
`https://github.com/aws-amplify/amplify-ios` is now `https://github.com/aws-amplify/amplify-swift`
> Renaming amplify-ios github URL to amplify-swift

- src/fragments/lib/graphqlapi/js/subscribe-data.mdx
- src/pages/cli/graphql/authorization-rules.mdx
- src/pages/cli/graphql/data-modeling.mdx
Adding docs for subscriptions server side filtering feature.
- Addition of filter argument to support server side filtering.
- Support for multiple owners authorization on subscriptions.
> docs(graphql): subscriptions server side filtering and multiple owners support

- cspell.json
- src/fragments/start/getting-started/vue/data-model.mdx
- src/fragments/start/getting-started/vue/setup.mdx
_Description of changes:_ This updates the getting started guide for Vue.js. Fixes some issues with the guide.
- Getting started guide was using the older Vue CLI which is now in maintenance mode. Updated guide to use Vue's create-vue which is the preferred way of creating Vue apps.
- Fixed bug in data store guide that called subscription that wasn't there.
> Updated Vue getting started guide

- src/fragments/lib/auth/js/social.mdx
N/A
Fix a minor typo in Social sign-in documentation that referenced `Auth.federatedSign()` instead of `Auth. federatedSignIn()` 
> Fixed typo for Auth.federatedSignIn() in lib/auth/js/social

- generatePathMap.cjs.js
going from [iOS v2 root](https://docs.amplify.aws/lib/q/platform/ios/) and clicking on the v1 button works fine, but just going to the resulting [v1 page](https://docs.amplify.aws/lib-v1/q/platform/ios/) directly (or refreshing on that page) gives a 404.
fix: add SSG for section roots to `lib-v1` as well
> Fix lib-v1 error where refresh on root gave 404

- src/fragments/start/getting-started/next/api.mdx
- src/fragments/start/getting-started/next/hosting.mdx
> fix: edits to next.js getting started to bring it current

- src/directory/directory.js
- src/fragments/lib/devpreview/android/getting_started/10_intro.mdx
- src/fragments/lib/devpreview/android/getting_started/20_goal.mdx
- src/fragments/lib/devpreview/android/getting_started/30_preReq.mdx
- src/fragments/lib/devpreview/android/getting_started/40_installLib.mdx
- src/fragments/lib/devpreview/android/getting_started/50_nextSteps.mdx
- src/fragments/lib/devpreview/native_common/getting_started/common.mdx
- src/pages/lib/devpreview/getting-started/q/platform/[platform].mdx
Fixes #4727
Adds page accidentally removed in #4567
> Add Android dev-preview files back

- src/components/Menu/FilterSelect/index.tsx
https://github.com/aws-amplify/docs/issues/4729
- extract current pathname from `window.location`
> fix: ignore queries while switching platform

- src/fragments/lib/analytics/android/escapehatch.mdx
- src/fragments/lib/analytics/android/record.mdx
Add Hub documentation, put autoflush in correct location in amplifyconfiguration.json, change escape hatch return type
> Update Analytics documentation for GA

- src/fragments/lib/utilities/js/hub.mdx
_Issue #, if available:_ #8807
Adds code snippet and description for Remove Hub listener event section. Moves Channels section to the beginning of the doc.
> docs(hub) add hub remove code snippet example

- src/components/FeatureFlags/feature-flags.json
Added the documentation for custom primary key feature flag `respectPrimaryKeyAttributesOnConnectionFields`. The default value is false for both old and new projects. The default value will be switched to true once the Studio CMS v2 project is finished.
> docs(CPK): add feature flag docs for CPK

- src/fragments/lib/analytics/android/getting-started/30_initAnalytics.mdx
passing `(this)` was used before for auto session tracking -- no longer required because we get the `Application` from a different source (plugin initialization)
> New method of initializing Analytics

- src/fragments/guides/hosting/nextjs.mdx
- src/fragments/lib-v1/android.mdx
- src/fragments/lib-v1/flutter.mdx
- src/fragments/lib-v1/ios.mdx
- src/fragments/lib-v1/ssr/js/getting-started.mdx
- src/fragments/lib/android.mdx
- src/fragments/lib/flutter.mdx
- src/fragments/lib/ios.mdx
- src/fragments/lib/ssr/js/getting-started.mdx
- src/fragments/start/getting-started/android/build-footer.mdx
- src/fragments/start/getting-started/common/build-footer.mdx
- src/fragments/start/getting-started/flutter/build-footer.mdx
- src/fragments/start/getting-started/ios/build-footer.mdx
- src/pages/cli/usage/mock.mdx
_Issue #, if available:_ resolves #4693
Searched the repository for emojis and made the following changes:
- Removed two instances of ⚡️
- Removed all instances of 🚀
- Removed all instances of 👇,  used in comments inside code snippets to point to the following line, not really needed.
Emojis not removed:
- Left all instances of ✅ & ❌, used in tables and code snippets representing cli logs.
- Left [one instance of ⬇️](https://github.com/aws-amplify/docs/blob/main/src/pages/console/uibuilder/override.mdx?plain=1#L42) used in a comment inside a code snippet. Could be removed, but is pretty useful since it points to the exact attribute it's talking about. 
Possible Future work:
- Update the table format for all tables in …
> Remove emojis from the docs

- src/fragments/start/getting-started/react/setup.mdx
_Issue #, if available:_ N/A
Removed a superfluous letter u from the React getting started setup guide.
> Remove minor typo in React getting started

- src/fragments/lib/graphqlapi/js/getting-started.mdx
- src/fragments/lib/graphqlapi/js/js-configure.mdx
- src/fragments/lib/graphqlapi/js/react-native-configure.mdx
Adds the missing libraries to the `npm install` command to the getting started section of GraphQL API section for React Native.
Missing libraries in the `npm install` command : `@react-native-async-storage/async-storage` and `@react-native-community/netinfo`
> fix(docs): React native add the missing required libraries for configure application section in GraphQL API.

- src/fragments/sdk/auth/android/hosted-ui.mdx
_Issue #, if available:_ https://github.com/aws-amplify/aws-sdk-android/issues/3006
Add instructions to SDK auth docs to handle sign in cancellation for webui. Refer: https://github.com/aws-amplify/aws-sdk-android/issues/3006#issuecomment-1305987150
> fix(android): add instructions to handle sign in cancellation for webui

- src/fragments/lib-v1/predictions/js/getting-started.mdx
- src/fragments/lib-v1/push-notifications/js/getting-started.mdx
- src/fragments/lib/predictions/js/getting-started.mdx
- src/fragments/lib/push-notifications/js/getting-started.mdx
- src/fragments/ui-legacy/vue/overview.mdx
This change cleans up lingering usage of deprecated default exports from the `amplify-js` repo, which will be fully removed for the upcoming v5 release.
> chore: Clean up lingering usage of deprecated default exports.

- src/fragments/lib/auth/common/device_features/common.mdx
- src/fragments/lib/auth/js/emailpassword.mdx
- src/fragments/lib/auth/js/react-native-mfa.mdx
- src/fragments/lib/auth/js/react-native-social.mdx
- src/pages/lib/auth/mfa/q/platform/[platform].mdx
- src/pages/lib/auth/social/q/platform/[platform].mdx
This change cleans up some incorrect information in the React Native docs and creates a few RN-related files/pages. It also changes the order of the functions in the `Sign up, Sign in & Sign out` page because following them in the previous order might have been confusing.
> React Native Auth fixes noticed during v5 testing

- src/fragments/lib/geo/js/google-migration.mdx
- Added a google migration doc for location search and stand alone location search components
- Screenshots below
> chore: added a location search google places migration doc

- src/directory/directory.js
- src/fragments/lib/auth/ios/advanced/advanced.mdx
- src/fragments/lib/auth/ios/signin_with_custom_flow/50_custom_challenge.mdx
- src/fragments/lib/auth/ios/switch-auth/switch-auth.mdx
- src/pages/lib/auth/advanced/q/platform/[platform].mdx
- src/pages/lib/auth/switch-auth/q/platform/[platform].mdx
> feat(Auth): Adding documentation for federation and switching auth flow type

- src/fragments/start/getting-started/next/api.mdx
- src/fragments/start/getting-started/next/setup.mdx
Fixes to the Next.JS documentation for Getting Started with Amplify after `No current user` errors occurred when following steps in guide.  Everything works locally, however there is an issue with Hosting tied to https://github.com/vercel/next.js/issues/41932 and the Frontend build failing for CI/CD.  The error in the logs is the following: 
> fix (next): updated getting started guide after v5 tests

- src/fragments/lib/auth/android/signin/30_signIn.mdx
In the latest version of Android Amplify library to maintain parity with Swift the call to capture if the user is signedin is now called `isSignedIn` instead of `isSignInComplete`
> Fix(Auth): Change issignedinComplete to isSignedIn

- src/fragments/lib/predictions/android/escapehatch.mdx
_Description of changes:_ Add an example of calling a suspend function in Java to the Predictions escape hatch docs and remove the note about suspend functions.
> Update Predictions escape hatch Java sample

- src/fragments/lib/auth/android/password_management/20_confirm_reset_password.mdx
Confirm reset password requires a username field. This is now added in the docs to reflect that change.
> Fix(Auth): Confirm reset password requires a username field

- src/fragments/lib/auth/android/password_management/20_confirm_reset_password.mdx
There is a quotation missing that was a typo in the previous PR. This is fixed here.
> Fix(Auth): Confirm reset password typo fix

- tasks/build-algolia-search.mjs
_Issue:_ #4384
This small PR fixes a bug that was stopping all top level fragments from being indexed.  Once live top level fragments will be indexed.  This issue can be seen when searching on the docs site for "use existing amazon cognito resources" which currently only shows 2 search results but omits all of the /lib resources 
Current Results
Example of a missing result
Another PR is on its way which will include the ability to index nested fragments
> fix bug so that top level fragments are included in search index

- src/fragments/lib/datastore/js/data-access/delete-snippet.mdx
- src/fragments/lib/datastore/js/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/js/data-access/query-predicate-multiple-snippet.mdx
- src/fragments/lib/datastore/js/data-access/query-predicate-or-snippet.mdx
- src/fragments/lib/datastore/js/data-access/query-predicate-snippet.mdx
- src/fragments/lib/datastore/js/examples-react-native.mdx
- src/fragments/lib/datastore/js/examples.mdx
- src/fragments/lib/datastore/js/real-time/observe-query-snippet.mdx
- src/fragments/lib/datastore/js/relational/query-many-snippet.mdx
- src/fragments/lib/datastore/js/relational/query-snippet.mdx
- src/fragments/lib/datastore/js/relational/save-snippet.mdx
- src/fragments/lib/datastore/js/sync/20-savePredicate.mdx
- src/fragments/lib/datastore/js/sync/30-savePredicateComparison.mdx
- src/fragments/lib/datastore/js/sync/50-selectiveSync.mdx
- src/fragments/lib/datastore/native_common/relational.mdx
- Updated all predicates to use new format
- Changed code relational models sections
- Expanded the many-to-many section
> [DO NOT MERGE] Adding DataStore JS lazy loading docs

- src/directory/directory.js
- src/fragments/lib/auth/android/switch-auth/switch-auth.mdx
- src/fragments/lib/auth/ios/switch-auth/switch-auth.mdx
- src/pages/lib/auth/switch-auth/q/platform/[platform].mdx
Switching Auth flow documentation is missing in Android. This PR adds that.
> Docs(Auth): Add switching auth flow documentation

- src/fragments/lib/analytics/android/identifyuser.mdx
- src/fragments/lib/auth/android/advanced/advanced.mdx
As part of upgrade to v2, getCurrentUser is now only available as async call. 
> chore(Auth): update getCurrenUser reference to use async method

- src/directory/directory.js
- src/fragments/lib/auth/android/signin_next_steps/10_signin.mdx
- src/fragments/lib/auth/android/signin_next_steps/20_confirm_sms_mfa.mdx
- src/fragments/lib/auth/android/signin_next_steps/30_confirm_custom_challenge.mdx
- src/fragments/lib/auth/android/signin_next_steps/40_confirm_new_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/50_reset_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/60_confirm_signup.mdx
- src/fragments/lib/auth/android/signin_next_steps/70_done.mdx
- src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
- src/pages/lib/auth/signin_next_steps/q/platform/[platform].mdx
Sign in guide is missing from Android documentation. This PR adds it.
> Fix(Auth): Addition of sign in guide in docs

- src/fragments/lib/auth/android/signin_next_steps/10_signin.mdx
- src/fragments/lib/auth/android/signin_next_steps/20_confirm_sms_mfa.mdx
- src/fragments/lib/auth/android/signin_next_steps/30_confirm_custom_challenge.mdx
- src/fragments/lib/auth/android/signin_next_steps/40_confirm_new_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/50_reset_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/60_confirm_signup.mdx
Add missing instructions in java for SignInNextSteps
> Fix(Auth): Add missing instructions in java for SignInNextSteps

- cspell.json
- src/fragments/cli-install-block.mdx
- src/fragments/lib-v1/storage/js/upload.mdx
- src/fragments/lib/project-setup/flutter/create-application/30_provisionBackend.mdx
- src/fragments/lib/storage/js/browser-uploads.mdx
Updates to docs based on feedback from Nika
Also fixes https://github.com/aws-amplify/docs/issues/4837
> updated findings from Nika

- src/pages/cli/usage/mock.mdx
Document the support for mocking the `@searchable` GraphQL directive.
**DO NOT MERGE** until CLI >=`10.5.1` is GA.
> feat(cli-mock): add section for searchable mocking

- src/fragments/lib/analytics/js/update-endpoint.mdx
closes aws-amplify/amplify-js#9608
This pull request emphasizes about some of rules that apply to `updateEndpoint` method of aws-amplify/amplify-js library.
Especially the fact that all fields in the `endpoint.attributes` should be given as an array, otherwise the `updateEndpoint` method will fail with:
`AWSPinpointProvider - updateEndpoint failed [TypeError: undefined is not a function]`
It took me some decent amount of time to investigate on that error, so I believe that having these notes in the documentation should prove helpful to somebody.
There are also other notes given about the `endpoint` object structure, which can be confusing.
In original documentation it is unclear whether fields being optional or required comparing to other …
> `updateEndpoint` description improvement - optional fields & `attributes` fields type

- src/fragments/lib/auth/android/signin_next_steps/10_signin.mdx
- src/fragments/lib/auth/android/signin_next_steps/20_confirm_sms_mfa.mdx
- src/fragments/lib/auth/android/signin_next_steps/30_confirm_custom_challenge.mdx
- src/fragments/lib/auth/android/signin_next_steps/40_confirm_new_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/50_reset_password.mdx
- src/fragments/lib/auth/android/signin_next_steps/60_confirm_signup.mdx
Sign in next steps is missing kotlin coroutines and RxJava snippets. This PR adds them.
> Fix(Auth): Sign in next steps is missing kotlin coroutines and RxJava snippets

- src/fragments/lib/restapi/js/getting-started.mdx
_Issue #, if available:_ 
closes https://github.com/aws-amplify/docs/issues/4454
changes "import" to "reference" to mitigate confusion with `amplify import`
> update import to reference for REST API

- src/fragments/lib/auth/native_common/guest_access/common.mdx
> Fix CLI spacing

- src/components/SearchBar/Autocomplete.tsx
- src/components/SearchBar/functions/groupBy.ts
- src/components/SearchBar/index.tsx
Issue #, if available: 4384
This PR increases the maximum number of displayed search results from 6 to 20 and also filters the search results based on the platform that is currently being viewed.
> increase search results and filter by platform

- STYLEGUIDE.md
Adding the style guide we have started using for new content internally. When referring to the styleguide in PR reviews, call out individual rules using their numbers. Cheers!
> New STYLEGUIDE!

- src/fragments/lib/auth/ios/getting_started/10_preReq.mdx
N/A
Adds a callout outlining requirements to use Auth in a macOS app in the prereq section of the getting started page for Swift Auth.
> fix(swift): auth add macos keychain callout

- src/fragments/lib/auth/android/signin_web_ui/20_platform_specific_setup.mdx
Removed a tag that is built into Amplify and not needed by customer to implement.
> Remove unnecessary queries tag for Web sign on Android Manifest

- src/fragments/lib-v1/info/ios/data-information.mdx
- src/fragments/lib/info/ios/data-information.mdx
_Issue #, if available:_ #4769
_Description of changes:_ Change proposed in my last PR #4769 and accepted to be introduced by @rachelnabors 
[data-information.mdx](https://github.com/aws-amplify/docs/blob/main/src/fragments/lib/info/ios/data-information.mdx?plain=1#L3-L68) was the only table using `Y` & `N` instead of ✅ & ❌. Both versions of the table have been updated.
Changes Example:
Before:
Now:
> Data Information Table Format update

- src/fragments/start/getting-started/react/auth.mdx
Replaced the div html tags with View components imported from the UI library.
_Issue #, if available:_ https://github.com/aws-amplify/docs/issues/4756
Replaced the div tags with View component tags in the "[Bonus: Use Amplify UI Primitives](https://docs.amplify.aws/start/getting-started/auth/q/integration/react/#bonus-use-amplify-ui-primitives)" section.
> Updated "Bonus: Use Amplify UI Primitives" Section

- src/directory/directory.js
* remove device tracking from the Swift Library navigation menu.  Feature is not yet released.
> remove device tracking from Swift navigation

- src/fragments/lib/geo/js/search.mdx
Add documentation on new Geo APIs - searchForSuggestions and searchByPlaceId
> feat: add docs on new Geo APIs - searchForSuggestions and searchByPlaceId

- src/directory/directory.js
- src/pages/cli/function/configure-options.mdx
_Issue #, if available:_ https://github.com/aws-amplify/amplify-cli/issues/10894
Moves the `Configuring Lambda function settings` from Guides to Functions category. The page provides information on configuring a Lambda function options such as runtime and memory. 
Page will be the new point of reference as the older page has been removed on https://github.com/aws-amplify/docs/pull/4576 
> chore: move Lambda config page from guides to cli functions

- src/fragments/lib/interactions/js/getting-started.mdx
Fixes: https://github.com/aws-amplify/amplify-ui/issues/3086
Fixes: https://github.com/aws-amplify/amplify-ui/issues/3091
Fixes: https://github.com/aws-amplify/amplify-ui/issues/2994
Changes a ChatBot link to point to the legacy documentation (see [Amplify UI docs](https://ui.docs.amplify.aws/react/getting-started/migration#:~:text=AmplifySignOut-,AmplifyChatbot,-AmplifyPhotoPicker)). 
> Fix ChatBot link

- src/pages/console/storage/file-storage.mdx
closes:https://github.com/aws-amplify/docs/issues/4357 
Fixes broken link in studio storage. Would like additional information on the intention behind the wording.
> chore:replace broken studio storage link

- src/fragments/lib/auth/ios/social_signin_web_ui/10_cli_setup.mdx
Issue: #4678
- adds clarity to the user input format for Sign In With Apple prompts
> fix: clarify input format for sign in with apple parameters

- src/pages/cli/reference/iam-roles-mfa.mdx
In addition to sharing files between the AWS CLI and other AWS SDKs, there are formatting rules that must be followed when configuring the config/credentials files, which must be documented.
This also addresses this issue, where the formatting of the config/credentials file came into question: https://github.com/aws-amplify/amplify-cli/issues/10525 .
Documented the formatting of the config & credentials files.
> Document the format of config & credentails files

- src/fragments/lib/graphqlapi/graphql-from-node.mdx
Amplify CLI provides a new Nodejs function template to call a Graphql API called `AppSync - GraphQL API request (with IAM)` .
The PR add information on using the template.
> Add information on new graphql Nodejs function template on CLI

- src/fragments/lib/troubleshooting/js/strict-mode.mdx
- src/fragments/start/getting-started/android/build-footer.mdx
- src/fragments/start/sample-apps/android/todo-app.mdx
#4899 #4895 
updated links within the Android and JS/React Native Getting Started Guides to remove 404 pages that user is direct to. 
> fix (docs): updated getting started guides to remove links to 404 page

- src/fragments/lib/storage/ios/upload.mdx
* Update Swift Storage Upload documentation to include steps to access and upload security scoped resources
> chore: add documentation for uploading security scoped resources

- src/fragments/lib/push-notifications/js/getting-started.mdx
This fix removes step 8 which explicitly pinned the gradle distribution at 6.3 which causes issues and is an unnecessary step. It also adds a callout about android 12+ versions.
> fix: android getting started for react native push notifications

- src/components/FeatureFlags/feature-flags.json
Documents the behavior of `populateOwnerFieldForStaticGroupAuth` GraphQL Transformer Feature Flag that is being set to `true` in [this CLI PR](https://github.com/aws-amplify/amplify-cli/pull/11230) for new customers.
> feat(cli): add populateOwnerFieldForStaticGroupAuth FF

- .github/workflows/build.yml
- .github/workflows/spellcheck.yml
- Split cpsell into its own workflow so it can run independently of the build step and not require the `run-tests` label
> Split cspell into its own workflow

- src/pages/cli/graphql/authorization-rules.mdx
https://github.com/aws-amplify/amplify-category-api/issues/749
Clarifies that an AWS Resource or IAM role name may be added to custom-roles.json for access to be granted. Also adds details of what policy must be added by linking to Appysync IAM authorization details.
> clarify custom-roles.json

- src/fragments/lib/analytics/js/record.mdx
NA
This change updates the Amplify JS Analytics docs to clarify usage of the `immediate` flag with the Pinpoint & Kinesis providers.
> chore: Update JS Analytics docs to clarify `immediate` flag usage with Kinesis.

- src/components/Menu/styles.tsx
_Issue #, if available:_ #4943
- Add extra `padding-bottom` to the Menu component so that there is more
_To test:_
1. Go to `/lib/auth/manageusers/q/platform/js/`
2. Expand some of the section collapsible headers in the left menu
3. Try to scroll down in the left menu
- You should be able to scroll and reach the bottom of the menu without having to scroll the content page
> fix: add bottom padding to menu so there is more room to scroll

- src/pages/cli/graphql/authorization-rules.mdx
Adds a callout to provide additional information about the `delete` mutation behavior with respect to the `@auth` rule.
> fix: add callout for delete mutation permissions

- cspell.json
- src/fragments/lib-v1/project-setup/native_common/prereq/common_body.mdx
- src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
We had a PR come in that recommended installing CLI with `sudo`. CLI doesn't need that much power. There should never be a reason for Amplify devs to need `sudo`, and to prevent any possible abuse getting merged in by accident in the future, adding it to our linter.
> block merging 'sudo' in content

- cspell.json
- src/fragments/lib/project-setup/flutter/platform-setup/platform-setup.mdx
- Add an example of how to package dependencies on linux
> chore(flutter): add snapcraft.yaml example in platform setup

- src/fragments/lib-v1/auth/android/password_management/10_reset_password_note.mdx
- src/fragments/lib-v1/auth/native_common/password_management/common.mdx
- src/fragments/lib/auth/native_common/password_management/common.mdx
_Description of changes:_ Currently the documentation mentions that reset and confirm reset password have to be used in the same session but that is not correct for V2 for Android or V1/V2 for iOS.
> fix(auth): Removed the note about confirm reset password needing to be in conjuction with reset password

- src/pages/console/uibuilder/eventhandling.mdx
The Pr adds a callout for customers using datastore with multi auth types. added a link to library docs for configuration.
> added callout for multi auth for datastore

- tasks/check-link-tags.mjs
This pull request adds a task that will scan all mdx files looking for `<a>` tags and will throw an error if one is found.  This is to ensure that all mdx content uses the markdown syntax for links which utilizes plugins to ensure that external links are handled correctly.
> create a task that will scan all mdx files for A tags

- src/fragments/lib/auth/js/emailpassword.mdx
adds `forceAliasCreation` clarification to js `confirmSignUp` docs
> adds forceAliasCreations clarification to auth docs

- src/pages/cli/graphql/custom-business-logic.mdx
- yarn.lock
The latest v2 docs is containing cdk reference code for unit resolvers. Hence submitting  pull request is to add cdk reference code for pipeline resolvers.
> added pipeline resolver cdk code

- src/fragments/start/sample-apps/android/todo-app.mdx
_Issue #, if available:_ #4958
_Description of changes:_ Updates the connect to cloud instructions for setting up the Amplify Android ToDo sample app, removing a link that 404s.
> fix(android): update todo sample app setup

- .github/CODEOWNERS
While mechanisms to secure the PR process are being implemented, we are using a manual process to merge PRs, limiting merge permissions to the DocsEng team only. We are using the CODEOWNERS file to manage these permissions for the time being.
> Update CODEOWNERS to be the documentation team only

- src/fragments/lib-v1/auth/ios/password_management/10_reset_password.mdx
- src/fragments/lib/auth/ios/password_management/10_reset_password.mdx
- src/fragments/lib/utilities/js/hub.mdx
Fixing spacing issues
Fixing spacing issues
> Fixing spacing issues

- src/components/NextPrevious/styles.tsx
revisiting https://github.com/aws-amplify/docs/pull/4928
before:
after:
> fix: h4 margin for prev/next buttons

- .github/workflows/tagcheck.yml
This PR adds a github workflow to run the script that scans all of the mdx files for HTML A link tags.  We should always be using the markdown syntax for links in the mdx files and this script will block if PRs are found with html a link tags.
> add github workflow to run the link tag check script on each PR

- package.json
- yarn.lock
- Update resolutions for `decode-uri-component` and `json5` based on dependabot alerts
> chore: add resolutions for 'decode-uri-component' and 'json5'

- src/fragments/lib/auth/android/device_features/40_trackDevice.mdx
- src/fragments/lib/auth/common/device_features/common.mdx
- src/fragments/lib/auth/flutter/device_features/40_trackDevice.mdx
- src/fragments/lib/auth/ios/device_features/40_trackDevice.mdx
- src/fragments/lib/auth/js/device_features/40_trackDevice.mdx
This changes the original wording asking customers to open a feature request to instead point at all of the existing feature requests in each repo/platform
https://github.com/aws-amplify/amplify-js/issues/9318
https://github.com/aws-amplify/amplify-flutter/issues/1515
https://github.com/aws-amplify/amplify-swift/issues/2708
https://github.com/aws-amplify/amplify-android/issues/2258 …
> fix(js, ios, android, flutter, react native) added individual callouts to device tracking feature requests 

- src/fragments/lib/xr/getting-started.mdx
- src/fragments/lib/xr/sceneapi.mdx
adds deprecation message on top of each XR page
> Adds deprecation message for XR

- src/fragments/lib-v1/geo/existing-resources.mdx
- src/fragments/lib/geo/existing-resources.mdx
> fix(android, swift): add geo unauth role info

- src/pages/cli/usage/containers.mdx
> update malformed link

- src/styles/elements.css
_Description of changes:_ Added styling to code snippets in MDX headings to coordinate font size with heading size.
Before: 
After:
> style: add styling for code snippets in MDX headings

- src/fragments/lib/datastore/android/conflict.mdx
See: aws-amplify/amplify-android#2201
Sync retries are managed by DataStore's Sync Engine. This logic is neither optional nor configurable.
> Remove doSyncRetry from DataStoreConfiguration

- src/directory/directory.js
- Info tab is only supported for iOS, whereas filters were set to android leading to 404 page not found.
link to broken page: https://docs.amplify.aws/sdk/info/overview/q/platform/ios/
- [] iOS
> fix: Replace filter for Info tab under SDK from android to ios

- src/fragments/lib/auth/common/overview.mdx
- src/fragments/lib/xr/getting-started.mdx
- src/fragments/lib/xr/sceneapi.mdx
- [] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.
> added dates to Sumerian deprecation

- src/fragments/lib/datastore/ios/getting-started/50_initDataStore.mdx
this actually does not exist anymore on the latest SwiftUI version and is not required to get DataStore initialized. It's pretty confusing and this code snippet does not work as is.
> fix: updating to iOS DataStore initialization docs

- src/fragments/lib/auth/js/overview.mdx
- src/fragments/lib/xr/getting-started.mdx
- src/fragments/lib/xr/sceneapi.mdx
Updated messaging for Sumerian no longer being available after 2/21/2023
> [Amplify JS] updated messaging

- src/pages/cli/reference/files.mdx
Updates the CLI file reference page to include files and folders that are shared in `~/.amplify` and `~/.aws/amplify` directories.
> add shared files in CLI file reference page

- src/fragments/guides/hosting/nuxt.mdx
changed `nuxt-amplify` to `amplify-nuxt` in line 26. `amplify-nuxt` is the correct name of the directory
> Modifed wrong code reference in amplify nuxt.js docs

- src/directory/directory.js
- src/pages/console/formbuilder/overview.mdx
This PR fixes some broken links in the docs pages.
Resolves #5076 
Update the relative link to the correct data-model documentation page.
Resolves #5081 
The cache page for react-native docs was missing from the Sidebar menu / secondary nav. 
I wasn't certain how it was being mapped but from what I could gather is it was through the filters in the directory.js file. If thats incorrect, let me know I can roll the changes back. 
> Fix broken links

- src/components/Page/index.tsx
- Move back placement of some react hooks so choose filter pages gets displayed when switching to a grayed out platform
> Move back placement of hooks

- src/pages/console/formbuilder/customize.mdx
Adds a callout section to clarify the conditions for toggling list behavior on Form Builder inputs
> Add clarifying callout for list inputs

- src/pages/console/uibuilder/bestpractices.mdx
> Fix typo for component structure image

- src/fragments/lib-v1/datastore/ios/sync/50-selectiveSync.mdx
- src/fragments/lib-v1/datastore/native_common/setup-env-cli.mdx
- src/fragments/lib-v1/datastore/native_common/sync.mdx
- src/fragments/lib/datastore/flutter/relational/save-many-snippet.mdx
- src/fragments/lib/datastore/js/data-access/observe-update-snippet.mdx
- src/fragments/lib/datastore/js/examples.mdx
- src/fragments/lib/datastore/js/real-time/observe-snippet.mdx
- src/fragments/lib/datastore/js/relational/query-many-snippet.mdx
- src/fragments/lib/datastore/js/sync/50-selectiveSync.mdx
- src/fragments/lib/datastore/native_common/setup-auth-rules.mdx
- src/fragments/lib/datastore/native_common/setup-env-cli.mdx
- src/fragments/lib/datastore/native_common/sync.mdx
fix(data): fix broken DataStore code snippet; fix spelling and grammatical errors
> fix(data): fix broken DataStore code snippet; fix spelling and grammatical errors

- src/fragments/lib/storage/android/query-transfers.mdx
In the text above the codeblock it mentions that the customer can pause/resume/start/cancel an operation after calling `getTransfer(id)` but did not detail how that is done.
> Android > Storage: provide examples of storage pause/resume/start/cancel operations

- src/fragments/lib/auth/android/signin_next_steps/80_current_user.mdx
- src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
Get Current User documentation is currently missing. This PR adds that.
> feat(auth): Adding documentation for getCurrentUser

- cspell.json
- src/fragments/lib/datastore/flutter/getting-started/20_installLib.mdx
Add extra instruction for Android installing DataStore library in a Flutter project.
- [] Ready to merge
> fix(flutter): add android extra step installing DataStore lib

- src/pages/console/data/data-model.mdx
> chore: add unsupported directives for studio

- src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
add note on cpk ff with sqlite
https://github.com/aws-amplify/amplify-js/issues/10872
https://github.com/aws-amplify/amplify-js/issues/10693
Some customers are missing that CPK is not supported with SQLite. Adding an additional note to the getting started guide.
> add note on cpk ff with sqlite

- src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
Change expo initialization to use `npx create-expo-app` because `expo init` is no longer supported.
```
> expo init AmplifyDataStoreExpo
$ expo init is not supported in the local CLI, please use npx create-expo-app instead
```
> replace expo init with npx create-expo-app

- amplify.yml
- next.config.js
- Remove old environment variables for amplify api
- Update Amplify build spec to run algolia index only on main branch
> Update amplify build spec to run algolia index on main branch only

- src/fragments/guides/hosting/git-based-deployments.mdx
There is an incorrect numeration [here](https://docs.amplify.aws/guides/hosting/git-based-deployments/q/platform/js/): 1, 2, 4
> fix: numeration on git-based hosting tutorial

- src/fragments/lib/auth/js/start.mdx
- src/fragments/lib/interactions/js/getting-started.mdx
closes #4974
removes "read more" links pointing to a deprecated page
> fix: revise references to deprecated lambda node version update page

- src/fragments/lib/auth/js/advanced.mdx
The previous API (GAPI) used for Google sign-in is being [deprecated](https://developers.google.com/identity/sign-in/web/reference) at the end of March, 2023.
Our javascript documentation currently cites GAPI. This PR introduces a federated sign-in example using the newer Google Identity Services API. 
> chore(js): Updated federatedSignIn docs for new Google client

- src/pages/cli/graphql/custom-business-logic.mdx
Add a limitation on using CDK to define custom resolvers.
https://github.com/aws-amplify/amplify-category-api/issues/1220
> fix(cli-graphql): add custom cdk resolver limitation

- src/fragments/lib/graphqlapi/flutter/mutate-data.mdx
- src/fragments/lib/graphqlapi/flutter/query-data.mdx
This PR has changes for GraphQL model helpers in dev preview of amplify-flutter related to adding support for custom primary key (CPK). There are a few changes to model helpers that used to assume a string value for `id` field but now accept more complicated identifiers.
> chore(flutter): GQL model helper changes for CPK in dev preview

- src/components/FeatureFlags/feature-flags.json
- src/directory/directory.js
- src/pages/cli/graphql/data-modeling.mdx
- src/pages/cli/migration/lazy-load-custom-selection-set.mdx
_References:_
- Custom Selection Set -> https://github.com/aws-amplify/amplify-swift/pull/2526
- LazyReference -> https://github.com/aws-amplify/amplify-swift/pull/2583
- Codegen -> https://github.com/aws-amplify/amplify-codegen/pull/504 
- CLI feature flag -> https://github.com/aws-amplify/amplify-cli/pull/11566 
- Docs -> https://github.com/aws-amplify/docs/pull/4934  (You are here)
This PR adds the feature flag notes and migration guide for lazy loading and custom selection set.
To view locally, `yarn && yarn dev` then navigate to the following links:
- http://localhost:3000/cli/migration/lazy-load-custom-selection-set/
- http://localhost:3000/cli/reference/feature-flags/#generateLazyReferenceAndModelPath
Or in Github UI: …
> feat(cli): migration guide for lazy loading and custom selection set feature flag

- src/fragments/lib/auth/js/delete_user.mdx
- src/fragments/lib/auth/native_common/delete_user/common.mdx
> changes Legacy link on Delete User section for JS/RN

- src/utils/getLocalDirectory.ts
Update isProductRoot function to recognize query params
> have isProductRoot recognize query params

- src/fragments/sdk/configuration/ios/setup-options.mdx
- src/fragments/sdk/pubsub/ios/working-api.mdx
Fixing broken links in the following pages:
- https://docs.amplify.aws/sdk/pubsub/working-api/q/platform/ios/
- https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios/
> fix: Fixing broken links in some iOS SDK pages

- src/directory/directory.js
- src/fragments/lib/storage/android/transfer-acceleration.mdx
- src/pages/lib/storage/transfer-acceleration/q/platform/[platform].mdx
* Added a new page for S3 Acceleration Endpoint use on Android
> feat(android): Add new page for S3 acceleration endpoint

- src/constants/links.ts
- src/utils/globalnav.ts
> add contribute to global nav

- src/fragments/lib/ssr/js/getting-started.mdx
- src/fragments/lib/ssr/js/next-js-callout.mdx
- src/fragments/start/getting-started/next/api.mdx
Added a callout that highlights SSR was intended/developed for NextJS and does not work in a middleware context
Resolves #5045 
> Added callout for only NextJS SSR support

- src/fragments/lib/auth/flutter/signin/30_signIn.mdx
The following sample code appears to have a typo.
https://github.com/aws-amplify/docs/blob/bf3c733bbb7e48617c37f69fdac47868728aaf17/src/fragments/lib/auth/flutter/signin/30_signIn.mdx?plain=1#L13
I think ``result.isSignedIn`` is correct, not ``res.isSignedIn``. 
Resolves https://github.com/aws-amplify/docs/issues/5245
> Fix typo for flutter sign in

- src/fragments/guides/api-graphql/android/subscriptions-by-id.mdx
- src/fragments/guides/api-graphql/common/subscriptions-by-id.mdx
- src/fragments/guides/api-graphql/flutter/subscriptions-by-id.mdx
- src/fragments/guides/api-graphql/ios/subscriptions-by-id.mdx
- src/fragments/guides/api-graphql/js/subscriptions-by-id.mdx
- src/pages/guides/api-graphql/subscriptions-by-id/q/platform/[platform].mdx
This PR reflects the new GraphQL subscriptions by id work flow in Flutter enabled by https://github.com/aws-amplify/amplify-flutter/pull/2650. 
Draft should not be merged until above PR is completed.
> chore(flutter): GraphQL subscriptions by id

- src/fragments/start/getting-started/angular/nextsteps.mdx
- src/fragments/start/getting-started/react/nextsteps.mdx
- src/fragments/start/getting-started/vue/nextsteps.mdx
Removed incorrect link to Push Notification category for JS platforms/frameworks
continuation of #5151 
Closes #5185 
> fix(js): removed push notification from JS frameworks getting started

- src/fragments/lib-v1/storage/js/upload.mdx
- src/fragments/lib/project-setup/flutter/create-application/30_provisionBackend.mdx
- src/fragments/lib/storage/js/browser-uploads.mdx
rehash of the infamous #4836 PR
The typo changes and the change to the flutter project setup calling out create react app instead of flutter for the CLI
resolves #4837 (for real this time)
> fix(JS/flutter): readdresses typos and correct flutter typing

- src/fragments/lib/storage/js/list.mdx
The private and protected examples destructure the `results` out of the response object. This migrates the public example to follow the same pattern.
See the examples on the [JS Storage List](https://docs.amplify.aws/lib/storage/list/q/platform/js/) page for context.
> fix: Public example should align with others

- src/fragments/lib/auth/js/manageusers.mdx
Fixed indent on `Password & user management` page for both JS and RN
Closes #5208 
> fix(JS/RN): updated code spacing on pass/user management page for JS/RN

- src/fragments/lib/storage/js/getting-started.mdx
removes unnecessary `-S` flag on the npm install for the storage category in JS/RN
[This flag is no longer necessary as of npm v5.0](https://blog.npmjs.org/post/161081169345/v500#:~:text=%2D%2Dsave%20is%20no%20longer%20necessary)
closes #4955 
> fix(JS/RN): removed -S flag when installing amplify library in storage category
