aws-amplify/docs

.github/workflows/check_for_redirects.yml

- Separate the step where we print the number of deleted files into a separate line since we can't access the variable in the same step it was created
- Remove extra file path specification from `diff` command

Updates to redirects workflow

---

src/fragments/lib/auth/js/mfa.mdx
src/fragments/lib/auth/js/react-native-mfa.mdx

Adds `SELECT_MFA_TYPE` for `Auth.signIn` challenges. Replace QRCode with QRCodeCanvas in code snipped for setting up TOTP since QRCode component is deprecated in the most recent version of qrcode.react library

fix(js): Adds Select_mfa_type to MFA challenges

---

src/fragments/lib/interactions/js/getting-started.mdx

Removes reference to deprecated ChatBot UI component. The ChatBot component was exported from [@aws-amplify/ui-components](https://www.npmjs.com/package/@aws-amplify/ui-components) which was deprecated.
https://github.com/aws-amplify/amplify-ui/issues/3542

fix: reference to deprecated chatbot component (JS, UI, amplify-libraries)

---

src/fragments/lib/storage/js/existing-resources.mdx
src/pages/lib/storage/existing-resources/q/platform/[platform].mdx

modified storage 'use existing AWS resources' page to have accurate information for JS/RN
Resolves #5159 

fix(js/rn): modified storage 'use existing AWS resources' page 

---

src/components/FeatureFlags/feature-flags.json

The CPK flag `respectPrimaryKeyAttributesOnConnectionField` is set to true for new projects
A follow-up PR of https://github.com/aws-amplify/amplify-cli/pull/11373

chore: CPK feature flag default true for new projects

---

src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx

…e Getting Started docs (#5258)

fix(data): update React Native installation instructions for DataStore Getting Started docs (#5258)

---

src/pages/guides/functions/appsync-operations-to-lambda-layer/q/platform/[platform].mdx

_Description of changes:_ 
Updated AppSync operations to a Lambda layer example snippet 
when we get response from ``` https.request ``` it will be large when first time 'data' event will be fired and argument ``` data `` will be not full response, it will be just chunk of response, so I updated that snippet and now **by this PR:** on data event it we will add chunk to response and only on 'end' we will parse and resolve Promise

fix(docs): Update AppSync operations to a Lambda layer

---

src/pages/console/formbuilder/customize.mdx

Updating the list input section on form builder for clarity
https://github.com/aws-amplify/amplify-studio/issues/863

chore(studio) update formbuilder customize page

---

src/pages/cli/restapi/override.mdx

Modifies code samples to use specific variable names, updates usage of `UserPoolId` in favor of the existing output `UserPoolArn` to simplify setup.
n/a

refactor rest api cognito override to use arn output

---

src/components/FeatureFlags/feature-flags.json

N/A
Add docs for feature flags:
* useFieldNameForPrimaryKeyConnectionField
* showFieldAuthNotification
* shouldDeepMergeDirectiveConfigDefaults

Add missing documentation for GraphQL Transformer feature flags.

---

src/pages/cli-legacy/graphql-transformer/auth.mdx
src/pages/cli/graphql/authorization-rules.mdx

Removes previous dynamic group authorization limitations

Updated docs for real-time multi-group authorization

---

src/fragments/common/writable-vs-mutable-attributes.mdx
src/fragments/lib/auth/js/start.mdx
src/pages/cli/auth/import.mdx

Updating the callout messaging clarifying the use of attributes with social sign in.
https://github.com/aws-amplify/docs/issues/5222
https://github.com/aws-amplify/amplify-js/issues/3526#issuecomment-1460962106

fix(CLI/JS): Updating social sign-in attribute mappings callout on imported Auth

---

src/fragments/lib/datastore/js/sync/50-selectiveSync.mdx

Our language around reevaluating selective sync expressions was inaccurate, and led at least customer to believe sync expressions were effectively reevaluated upon every meaningful DataStore interaction.
This PR attempts to clarify the more nuanced relationship between DataStore method calls, start/stop states, and the relationship to selective sync expression evaluation.
_By submitting this pull request, I confirm that my contribution …

clarified DataStore selective sync reevaluation language

---

src/fragments/lib/datastore/native_common/schema-updates.mdx

Adding the path to the local GraphQL API schema that needs to be updated before re-deployment. This is to reflect the GraphQL API [documentation](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/#updating-your-graphql-schema) which clearly mentions it to the reader.

[DataStore] mention path to GraphQL API schema

---

src/fragments/lib/datastore/js/data-access/save-snippet.mdx

DataStore JS automatically converts optional `undefined` fields to `null`. This is a special JavaScript concern. This PR proposes a callout just under the JS `save()` snippet, since this might otherwise be unexpected behavior.

added callout for DataStore JS auto-conversion of `undefined` to `null`

---

src/fragments/lib/auth/ios/signin_web_ui/30_signin.mdx

`Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)` without try await before it does not work.
close #5249

fix: add `try await` to `Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)`

---

src/pages/cli/graphql/authorization-rules.mdx
src/pages/cli/graphql/data-modeling.mdx

feat(api): add code samples 1/2

---

src/fragments/start/getting-started/angular/setup.mdx

IE11 is end-of-life'd as of 2/14/2023. The callout isn't meaningful for our new customers anymore.

Removes IE11 support notice for Angular given it's deprecated

---

src/fragments/lib/datastore/js/data-access/observe-update-snippet.mdx
src/fragments/lib/datastore/native_common/data-access.mdx
src/fragments/lib/datastore/react-native/data-access/observe-update-snippet.mdx

fix(data): replace broken JS example with a working React Native example (5257)
Fixes https://github.com/aws-amplify/docs/issues/5257

fix(data): replace broken JS example with a working React Native example (5257)

---

src/fragments/lib/analytics/native_common/getting-started/30_initAnalytics.mdx
src/fragments/lib/analytics/native_common/getting-started/common.mdx
src/fragments/lib/common/js/import_configuration.mdx
src/fragments/lib/common/react-native/import_configuration.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/react-native/configure-amplify.mdx
src/fragments/lib/interactions/js/frontend.mdx
src/fragments/lib/interactions/js/getting-started.mdx
src/fragments/lib/predictions/js/getting-started.mdx
src/fragments/lib/restapi/js/getting-started.mdx
src/fragments/lib/storage/js/getting-started.mdx

Standardized the way `Configuring your app` steps calls out the entry file. React Native docs were showing instructions meant for JS
Added fragments for JS/RN to re-use throughout the docs. Removed unnecessary file after the fragments were created
Also fixed indent for code blocks in files touched.
Resolves #4903

fix(JS/RN): standardized 'configuring your app' steps

---

src/pages/cli/graphql/authorization-rules.mdx

Add callout warning that granular read operations are not recommended if the datastore is used in the meantime
https://github.com/aws-amplify/amplify-flutter/issues/2526

chore: add callout for granular read use case

---

src/fragments/lib/geo/ios/maps/10_install_adapter.mdx

Added note relating to macOS [not being supported at this time](https://github.com/maplibre/maplibre-gl-native/blob/9d37d3d4aab293675f3df3a7f9bee7b2f476daf5/platform/ios/platform/macos/README.md?plain=1#L22) by MapLibre.
So, this is the note:
~~- [ ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.~~
~~- [ ] Are any files being deleted with this PR? If so, have the needed redirects been created?~~
~~- [ ] Are all links in MDX files using the MDX link syntax …

chore(geo): Added note relating to macOS

---

src/pages/cli/usage/headless.mdx

_Issue #, if available:_ https://github.com/aws-amplify/amplify-cli/issues/9065

Add platform independent sample script for headless init

---

src/pages/cli/project/command-hooks.mdx

Added a *optional* field *runtime_options* to capture options passed in hooks-config.json
amplify cli 

feat: adding cli options to commands hooks

---

src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx

No issue.
The DataStore "Getting started" page for Expo has an import statement that imports a non-existent named export of `ExpoSQLiteAdapter`. The export is [actually a default export](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteAdapter.ts#L8):
```typescript
export default ExpoSQLiteAdapter;
``` 
Importing the non-existent named export leaves the developer with the import being `undefined`.  Using that undefined value in the documented `DataStore.configure` call leads to DataStore falling back to a default storage adapter without notifying the user.
This PR changes the import statement in the docs from `import { ExpoSQLiteAdapter }` to `import ExpoSQLiteAdapter` …

Import default export of ExpoSQLiteAdapter

---

src/pages/cli/graphql/authorization-rules.mdx

https://github.com/aws-amplify/amplify-category-api/issues/872
Adding an additional recommendation about fields which shouldn't be used for `ownerField`.

chore: update owner field docs

---

src/fragments/lib/datastore/js/setup-env-js.mdx
src/fragments/lib/datastore/native_common/setup-env.mdx

- Adds npm instructions for DataStore Getting Started guides because it was missing for "Option 2" route
Closes #2294

Adds npm instructions for DataStore Getting Started guides

---

src/pages/cli/graphql/examples-and-solutions.mdx

Fixed example to indicate a "list" query instead of a "get" operation.
#3588

fixed example to address #3588

---

src/fragments/lib/graphqlapi/native_common/advanced-workflows/common.mdx

Added more info on the implications of combining multiple GraphQL operations in a single request.
#4968

Added more context on combining multiple GraphQL operations client-side

---

src/fragments/lib/graphqlapi/js/authz.mdx

Fixes broken Block switcher that displayed an extra selector for JavaScript on [this page](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/react-native/#aws-lambda) and removed the content at the bottom of the section
Apparently `<Block>` doesn't play nice without newlines between the component and the content
Current Broken version:
Fixed version:
Resolves #5316 
_By submitting this pull request, I confirm that my contribution …

fix(JS/RN): fixed broken block switcher on graphQL authz page

---

src/fragments/lib/predictions/js/getting-started.mdx

Missing comma found when copying IAM policy

[fix/typo](JS/RN) Missing comma in Predictions IAM policy

---

src/fragments/start/getting-started/next/api.mdx

Noticed a minor typo in [this excellent documentation page](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#deploying-the-api) and wanted to help out!
Thanks for the great documentation.
https://github.com/aws-amplify/docs/issues/5357
- N/A (the docs, not the product itself are impacted)
- N/A
- N/A
- N/A

Amplify Getting Started Docs (NextJS/API) has a minor typo

---

package.json
yarn.lock

Add resolution for vm2

---

src/fragments/lib-v1/storage/flutter/download.mdx
src/fragments/lib/storage/flutter/download.mdx

- update Amplify Flutter docs for storage download page to use version switcher instead of block switcher
- update code snippets for v1

chore(Flutter): Update storage download docs for Amplify Flutter

---

generatePathMap.cjs.js

Updating the default pathmap to include `flutter-references` and `contribute`

add contribute and flutter-references to the default pathMap

---

src/fragments/lib-v1/datastore/android/sync/50-selectiveSync.mdx
src/fragments/lib-v1/datastore/ios/sync/50-selectiveSync.mdx
src/fragments/lib/datastore/android/sync/50-selectiveSync.mdx
src/fragments/lib/datastore/flutter/sync/50-selectiveSync.mdx
src/fragments/lib/datastore/ios/sync/50-selectiveSync.mdx
src/fragments/lib/datastore/js/sync/50-selectiveSync.mdx

Clarifies that selective sync conditions are applied after `@auth` rules. 
Same copy diff is applied to each platform.
https://github.com/aws-amplify/amplify-swift/issues/1635

fix(datastore): clarify selective sync with @auth rules

---

src/directory/directory.mjs

With the formal release of Amplify Flutter V1 and the Push Notification Plugin, we want to remove the "developer preview" label from the page.
Note: although this PR removes an entry from the `directory.mjs`, it doesn't change the page URL.

chore(flutter): remove developer preview label from PN docs

---

src/fragments/lib/datastore/ios/real-time/observe-query-snippet.mdx
src/fragments/lib/datastore/ios/real-time/observe-snippet.mdx

Adds missing async/await examples to `Swift` > `DataStore` > `Real time`
https://github.com/aws-amplify/docs/issues/5254
https://github.com/aws-amplify/amplify-swift/issues/2811

fix(swift): add async/await snippets for datastore observe/observeQuery

---

package.json
yarn.lock

- Update `vm2` resolution to 3.9.17

Update vm2 resolution to 3.9.17

---

src/fragments/start/getting-started/flutter/build.mdx

Remove warning label and fix wording.

fix(flutter): Callout wording and severity

---

src/fragments/start/getting-started/flutter/integrate.mdx

Updates the `onPressed` callback to the correct navigation method.

fix(flutter): Getting started `onPressed`

---

src/fragments/lib/storage/js/download.mdx

This change is to enable the users to check the existence of the file.

feat(storage): add validateObjectExistence option in get api

---

src/fragments/lib/storage/android/list.mdx

- Remove example for deprecated list API
- Add examples with `StoragePagedListOptions`

feat(storage): Update list api documentation to add pagination examples

---

src/fragments/lib/auth/ios/getting_started/05_authenticator_callout.mdx
src/fragments/lib/auth/native_common/getting_started/common.mdx

Moving the Authenticator for SwiftUI callout to a Swift-only fragment, as it was being displayed for all native platforms 😓 

fix: Authenticator for Swift callout was displayed for Android and Flutter

---

src/fragments/lib/graphqlapi/flutter/query-data.mdx

Query predicates between and beginsWith had descriptions swapped

Update query-data.mdx: predicate descriptions were mismatched in Flutter docs

---

src/pages/cli/project/permissions-boundary.mdx

created following https://github.com/aws-amplify/docs/pull/5113
The PR add an example on how to use permissions boundary feature in the CLI. 
The shows how to add the permission boundary to an environment and how to test the permissions using a lambda function

feat: add permissions boundary example

---

src/pages/cli/storage/import.mdx

Correcting misinformation on the unlink storage resource.
Currently it says cognito when it should be storage

fix: unlink storage resource info

---

src/directory/directory.mjs

removed Flutter from connect to the cloud

removed Flutter from connect to the cloud

---

src/pages/cli/hosting/hosting.mdx

S3 Changed defaults that do not allow for buckets to have ACLs and therefore CLI removed that ability as well. This is a docs change to reflect that update that is out on Amplify CLI v11.1.1

fix: remove docs around a DEV environment for Amplify Hosting

---

src/pages/start/q/integration/[integration].mdx

Been driving me nuts
Puts Amplify hosting into same list as CLI, Libraries, and Components

Put Amplify Hosting in the same list as CLI in tutorial

---

src/fragments/lib/project-setup/flutter/platform-setup/android.mdx

In the correspondence/debugging for an issue, we learned that we haven't correctly noted Kotlin version requirements so this PR adds that to the platform setup guide for Flutter on Android.
https://github.com/aws-amplify/amplify-flutter/issues/2961

chore(flutter): note Kotlin version requirement in Android guide

---

src/fragments/lib-v1/auth/native_common/signin_next_steps/common.mdx
src/fragments/lib/auth/android/signin_next_steps/10_signin.mdx
src/fragments/lib/auth/android/signin_next_steps/40_confirm_new_password.mdx
src/fragments/lib/auth/android/signin_next_steps/50_reset_password.mdx

Currently we do not support the AuthSignInStep.CONFIRM_SIGN_UP and hence we have to handle the exception thrown if the user is not confirmed.

fix(Android): Fix for documentation to properly handle usernotconfirmedexception

---

src/fragments/start/getting-started/next/api.mdx
src/fragments/start/getting-started/next/setup.mdx

This PR updates the NextJS new application guide to add the `--no-app` parameter to ensure customers are using the pages router. Also called out that Amplify works best with NextJS Pages Router at this time, and fixed some import path errors.

fix: update nextjs guide to use pages router

---

Readme.md

Minor grammatical and punctuation changes.

Minor grammatical and punctuation changes to Readme.md

---

src/pages/cli/graphql/override.mdx

Add DynamoDB override samples
#3963 
- [X ] Ready to merge

Add DynamoDB config parameters override samples

---

src/pages/cli/reference/files.mdx

Removes stale explanatory references for Cognito under the `aws-exports.js` file reference
fixes https://github.com/aws-amplify/docs/issues/4931

chore: remove stale explanations from aws-exports.js file reference

---

src/pages/console/adminui/extend-cli.mdx
src/pages/console/uibuilder/figmatocode.mdx

documents figma to code limitation on support for React Server Components

feat: add limitation on figma to code

---

src/fragments/lib/predictions/js/getting-started.mdx

In React Native where lazy bundling is enbled by default, and other newer browser tools, customer using `Predictions` category will see error `Error: More than one or no providers are configured`.
By default the React Native’s Metro bunder lazy-loads the Predictions class. As a result the class is not registered to the Amplify singleton before Amplify.addPluggable(new AmazonAIPredictionsProvider()); is called. Making this change ensures the `Predictions` class is imported and referred before `addPluggable()` is called.
P88158994
**Please add the product(s)/platform(s) affected to the …

docs(predictions): make sure refer Predictions class before using it

---

src/components/Menu/styles.tsx

Added width to mobile secondary nav to fix the below issue:
With no explicit width set, when list items in the nav spanned two lines, the width of the nav exceeded 100%. This issue would not be seen when no visible heading spanned two lines. 

fix: mobile secondary nav overlap fix

---

src/components/Menu/index.tsx
src/components/Menu/styles.tsx
src/components/MobileMenuIcons/styles.tsx
src/components/Page/metaContent.tsx
src/components/TableOfContents/index.tsx
src/components/TableOfContents/styles.tsx

- addressed mobile menu max-width
- fixed desktop toc and menu widths
- changed tablet behavior to show mobile icons and expand to desktop width

styling fixes for issues introduced by #5334

---

src/fragments/lib/auth/js/getting-started-steps-basic-auth-react-native.mdx
src/fragments/lib/react-native-polyfills.mdx
src/fragments/start/getting-started/reactnative/setup.mdx

Fix to the Amplify docs to update React Native dependency installations and INCLUDE `amazon-cognito-identity-js` where it was missing in the Expo CLI block switcher (causing issues with Auth methods in production builds).  Also added it within the In-App Messaging docs in the event someone is building with EAS.  Issue [#11401](https://github.com/aws-amplify/amplify-js/issues/11401) was opened because of this.   
REMOVED `core-js` in some sections of docs where due to it only being needed for DataStore category (it's covered in those docs as a needed dependency). 
[#11401](https://github.com/aws-amplify/amplify-js/issues/11401)
Which …

fix-(React Native): update React Native dependency installations

---

src/components/Card/styles.tsx
src/components/Menu/Directory/index.tsx
src/components/Menu/VersionSwitcher/index.tsx

3 improvements:
- Fix #4779 by using the URL without hash to create v1/v2 URLs
- Fix #5226 by using the correct link on `Card` components -- hydrations console errors on the [main page](https://docs.amplify.aws/) and [CFPs like this one](https://docs.amplify.aws/lib/interactions/getting-started/) are not resolved.
- Fix directory mistakenly showing two selected pages, for example when on `signin_web_ui` [page](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios/):
HTML: …

Misc. docs engineering improvements

---

src/fragments/lib/in-app-messaging/respond-interaction-events/respond-interaction-events.mdx

Update JS In-App Messaging docs to clarify where TypeScript enums can be imported from.
#5529

chore(js): Clarify in-app enum import source

---

src/pages/console/formbuilder/overview.mdx
src/pages/console/tutorial/collections.mdx
src/pages/console/uibuilder/figmatocode.mdx
src/pages/console/uibuilder/theming.mdx

update `index.js` entrypoint to `src/index.js` and `main.jsx`
add react app creation step as well

fix: index entrypoint reference and add react app creation

---

package.json
yarn.lock

- Add resolution for `fast-xml-parser`

Add resolution for fast-xml-parser

---

src/fragments/lib/graphqlapi/js/working-with-files.mdx

fix(data): update API + Storage header; minor grammatical updates 

fix(data): update API + Storage header; minor grammatical updates

---

src/pages/cli/graphql/custom-business-logic.mdx

Fixed a typo in the description of the "typeName" parameter in the "Structure of the function event" section.

fix(cli): fix typo for Lambda function resolver event

---

.github/workflows/scripts/utilities.js

- Small update to the GitHub action utility script for getting deleted files from a PR:
- Previously, I was filtering inside the "mapping" function of the `paginate` call and even though this worked, it was a little confusing and didn't follow what was being done inside the docs for `paginate`: https://octokit.github.io/rest.js/v19#pagination. Moving the filter outside as a result. …

Filter after mapping request for Github Action utility script

---

src/fragments/guides/hosting/nuxt.mdx

The output build directory has changed for Nuxt 3 to `.output/public`. 
https://nuxt.com/docs/getting-started/deployment#static-hosting
https://github.com/aws-amplify/docs/issues/5518

Update Hosting build settings for Nuxt v2 and v3

---

src/components/Layout/index.tsx

- Previously, the filter was only checking to see if a string was not an empty string using `testValue !== ''`. This didn't filter out `undefined` and `null` so adding that in to be more specific

Filter out undefined and null when setting up the 'title'

---

src/fragments/lib-v1/datastore/android/data-access/delete-snippet.mdx
src/fragments/lib-v1/datastore/android/data-access/update-snippet.mdx
src/fragments/lib-v1/datastore/android/relational/delete-snippet.mdx
src/fragments/lib/datastore/android/data-access/delete-snippet.mdx
src/fragments/lib/datastore/android/data-access/update-snippet.mdx
src/fragments/lib/datastore/android/relational/delete-snippet.mdx

Replace deprecated id method by identifier method.

Amplify Android: replace deprecated id with identifier method

---

src/fragments/start/getting-started/vue/setup.mdx

Fix Vue tutorial - latest npm init vue doesn't require the vite.config.js updates

---

src/fragments/lib/auth/js/mfa.mdx
src/fragments/lib/graphqlapi/js/working-with-files.mdx
src/fragments/lib/in-app-messaging/respond-interaction-events/respond-interaction-events.mdx

Add TS examples for getting-started pages of the Auth category

Add TS examples for getting-started pages of the Auth category

---

src/fragments/lib/storage/ios/list.mdx

Update documentation about storage list request options in Amplify Library for Swift
https://github.com/aws-amplify/amplify-swift/issues/3002
- [] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

fix(storage): Add information about request options

---

generatePathMap.cjs.js
src/directory/directory.mjs

Add Contribute getting started page to directory file so that it is included in the generated pathmap

add contribute getting-started page to directory

---

src/fragments/lib/storage/js/download.mdx

Adding a callout mentioning the expires parameter for Storage.get() will max out at 1hr.
https://github.com/aws-amplify/amplify-js/issues/9346

fix(JS): Call out for expires param when calling Storage.get()

---

src/fragments/lib/storage/js/getting-started.mdx

This change adds a description about `isObjectLockEnabled` in configuration. 

feat(storage): supporting put api when the objectLock is enabled 

---

src/fragments/lib/auth/android/signin_next_steps/30_confirm_custom_challenge.mdx
src/fragments/lib/auth/flutter/signin_with_custom_flow/40_custom_challenge.mdx
src/fragments/lib/auth/ios/signin_next_steps/30_confirm_custom_challenge.mdx

fix(auth): Added documentation for how to handle notauthorized exceptions when fail lambda is true

---

src/fragments/lib/storage/js/upload.mdx

Adding a callout for progressCallback event handler, clarifying how often the event will be fired.
https://github.com/aws-amplify/amplify-js/issues/6068

update(JS): Callout for progressCallback event handler

---

src/fragments/lib/auth/js/manageusers.mdx

The scope of this change is to provide typescript examples for the [Password & user management] section of the the Amplify documentation for authentication.

Added ts examples for Password & user management in the Auth Category

---

src/directory/directory.mjs
src/fragments/lib/auth/flutter/advanced/advanced.mdx
src/pages/lib/auth/advanced/q/platform/[platform].mdx

These docs are largely just copied over from [Android](https://docs.amplify.aws/lib/auth/advanced/q/platform/android/#identity-pool-federation) and [Swift](https://docs.amplify.aws/lib/auth/advanced/q/platform/ios/#identity-pool-federation).
They provide use-case docs for the `federateToIdentityPool` API which was released a while ago.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

feat(flutter): Add `federateToIdentityPool` docs

---

src/fragments/lib/auth/js/react-native-social.mdx
src/fragments/lib/auth/js/react-native-withoauth.mdx
src/fragments/lib/auth/js/social.mdx

The scope of this change is to provide typescript examples for the [Social sign-in (Oauth)] section of the the Amplify documentation for authentication. Examples have been provided for both react and react-native.
Note whilst I have provided a typescript example for "withOAuth Higher-Order Component (HOC)" I see that `aws-amplify-react-native` used in the implementation appears to be on the path to deprecation as per https://github.com/aws-amplify/amplify-js/issues/2286#issuecomment-1272092888 and looks to have been superseded by `@aws-amplify/ui-react-native`. Is there a revised recommended alternative for `useOauth` when using react-native? If there is I would be happy to raise a subsequent PR to revise the example to reflect it.
**If this PR should not be merged upon approval for any …

Add typescript examples for Social sign-in Oauth (react/react-native)

---

src/pages/cli/auth/import.mdx

adds a callout on missing oauth attributes when importing a user pool.
https://github.com/aws-amplify/amplify-cli/issues/12979
related: https://github.com/aws-amplify/amplify-cli/issues/10932

fix: add callout on oauth properties in aws-exports

---

src/components/FeaturesGrid/index.tsx
src/components/Footer/index.tsx
src/components/LinkBanner/index.tsx
src/components/Menu/FilterSelect/index.tsx
src/components/Menu/RepoActions/index.tsx
src/components/NextPrevious/index.tsx
src/pages/index.tsx

- Updated the alt text for decorative images with an empty string

Update alt text for decorative images

---

src/directory/directory.mjs
src/fragments/lib/auth/flutter/signin_next_steps/10_signin.mdx
src/fragments/lib/auth/flutter/signin_next_steps/20_confirm_sms_mfa.mdx
src/fragments/lib/auth/flutter/signin_next_steps/30_confirm_custom_challenge.mdx
src/fragments/lib/auth/flutter/signin_next_steps/40_confirm_new_password.mdx
src/fragments/lib/auth/flutter/signin_next_steps/50_reset_password.mdx
src/fragments/lib/auth/flutter/signin_next_steps/60_confirm_signup.mdx
src/fragments/lib/auth/flutter/signin_next_steps/70_done.mdx
src/fragments/lib/auth/native_common/signin_next_steps/common.mdx
src/pages/lib/auth/signin_next_steps/q/platform/[platform].mdx

Follows the existing [iOS](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/ios/) and [Android](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/android/) docs for the next steps encountered during a sign-in flow.

feat(flutter): Add auth next steps

---

cspell.json
src/pages/cli/project/troubleshooting.mdx

With launch of Amplify CLI [v12.2.0](https://github.com/aws-amplify/amplify-cli/releases/tag/v12.2.0), codegen job timeout is [configurable](https://github.com/aws-amplify/amplify-cli/blob/b2dd685fed463d430f80af39f061f55d3392399d/packages/amplify-util-uibuilder/src/commands/utils/syncAmplifyUiBuilderComponents.ts#L137) using `UI_BUILDER_CODEGENJOB_TIMEOUT` environment variable. By default this timeout value is 2 minutes but customers can increase this value if they are seeing the below timeout error due to large number of UI components -
```
⠋ Generating UI components...🛑 Codegen job never succeeded before timeout
✖ Failed to sync UI components"
```
An `amplify pull` failure troubleshooting section is also introduced to document similar scenarios in future.  
Internal 
**If this PR should …

feat(cli): add codegen timeout scenario for pull failure

---

src/fragments/lib/storage/js/download.mdx

This PR removes a resolved issue(https://github.com/aws-amplify/amplify-js/issues/6157) from FAQ section in docs 

chore(JS/Storage): remove solved issue from FAQs

---

src/fragments/lib/android-escape-hatch-warning.mdx

fix(misc): Fix the link to aws sdk for kotlin

---

src/fragments/lib-v1/datastore/android/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/android/sync/10-installPlugin.mdx
src/fragments/lib-v1/datastore/flutter/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/flutter/sync/10-installPlugin.mdx
src/fragments/lib-v1/datastore/ios/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/ios/sync/10-installPlugin.mdx
src/fragments/lib-v1/datastore/native_common/callout/datastore-auth-rules-cli.mdx
src/fragments/lib-v1/datastore/native_common/data-access.mdx
src/fragments/lib-v1/datastore/native_common/setup-auth-rules.mdx
src/fragments/lib/datastore/android/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/android/sync/10-installPlugin.mdx
src/fragments/lib/datastore/flutter/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/flutter/sync/10-installPlugin.mdx
src/fragments/lib/datastore/ios/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/ios/sync/10-installPlugin.mdx
src/fragments/lib/datastore/js/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/native_common/callout/datastore-auth-rules-cli.mdx
src/fragments/lib/datastore/native_common/data-access.mdx
src/fragments/lib/datastore/native_common/setup-auth-rules.mdx

Remove notContains queryPredicate from list of supported Amplify Flutter Datastore queryPredicates. 
https://github.com/aws-amplify/amplify-flutter/issues/3370

Fix Flutter Datastore QueryPredicates

---

src/pages/lib/graphqlapi/upgrade-guide/q/platform/[platform].mdx

Current [migration](https://docs.amplify.aws/lib/graphqlapi/upgrade-guide/q/platform/js/#option-1-upgrade-to-aws-amplify-recommended) is suggesting to import `Amplify` and `API` from `aws-appsync`, instead it should be from `aws-amplify`

fix: upgrade API GraphQL migration guide

---

package.json
yarn.lock

- Add resolution for `proxy-agent`. `yarn upgrade @aws-amplify/amplify-cli-core` wasn't updating `proxy-agent` to v6 for some reason so added the resolution manually

Add resolution for proxy-agent

---

src/fragments/lib-v1/datastore/android/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/flutter/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/ios/data-access/query-predicate-types.mdx
src/fragments/lib-v1/datastore/native_common/data-access.mdx
src/fragments/lib/datastore/android/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/flutter/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/ios/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/js/data-access/query-predicate-types.mdx
src/fragments/lib/datastore/native_common/data-access.mdx

- Remove the markdown bold asterisks from the fragments

Fix datastore predicates

---

src/fragments/lib-v1/analytics/android/record.mdx
src/fragments/lib-v1/analytics/flutter/record.mdx
src/fragments/lib-v1/analytics/ios/record.mdx
src/fragments/lib/analytics/android/getting-started/40_record.mdx
src/fragments/lib/analytics/android/record.mdx
src/fragments/lib/analytics/flutter/record.mdx
src/fragments/lib/analytics/ios/record.mdx
src/fragments/lib/analytics/js/record.mdx

Add callout for pinpoint event delay
Fixes ambiguities leading to this confusion:
https://github.com/aws-amplify/amplify-flutter/issues/2903

feat: Add callout for Pinpoint event delay

---

src/fragments/lib/storage/native_common/configureaccess/common.mdx

update storage protected access level doc to add the need for identityID of the user who uploaded the file.
https://github.com/aws-amplify/amplify-flutter/issues/3517

fix(lib): update storage protected access level doc (Flutter, iOS, Android)

---

src/pages/cli/reference/ssm-parameter-store.mdx

fixed an issue with the markdown inline code block rendering
before
after

fix rendering of cli's ssm callout

---

src/fragments/lib-v1/restapi/android/update.mdx
src/fragments/lib/restapi/android/update.mdx

Several Kotlin code snippets were using `String.getBytes()` - this Java method is unavailable in Kotlin, the correct call is `String.toByteArray()`. These code snippets would not compile.

fix(android): Replace getBytes with toByteArray in Kotlin code snippets

---

tasks/link-checker.js

Update filter regex to include platform page urls that don't have an ending slash

remove platform pages that have an ending slash

---

package.json
yarn.lock

- Update `@aws-amplify/amplify-cli-core` to 4.2.4
- Removed resolution for `proxy-agent`

Update amplify-cli-core to 4.2.4

---

package.json

- Added the `--no-progress` flag to the spellcheck script. This makes it so that the Github action doesn't log all the files it has checked. The goal of this change is to make it easier to find the spelling errors without having to scroll through a long list of cspell logs.

Update spellcheck command to use --no-progress flag

---

src/pages/cli/function/build-options.mdx

Changes "canned" to "called" on the function build option page located here https://docs.amplify.aws/cli/function/build-options/
#5785

Should say "called" instead of "canned" on function build options page

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Adds default suggested VSCode extensions for prettier and ESLint. When a VS Code user opens the IDE they will be prompted to install these two plugins if missing:

chore: add default vscode extensions prettier and eslint

---

.github/workflows/check_for_broken_links.yml
tasks/link-checker.js

Update the link scanning workflow and script to wait for the page to fully load before looking for scripts, previously some pages weren't fully loaded and links were being missed.

update link scanning workflow

---

src/constants/versions.ts

Amplify Android version update for 2.11.3

Amplify Android version update for 2.11.3

---

src/components/ExternalLinkButton/index.tsx
src/components/InternalLinkButton/index.tsx
src/pages/console/adminui/start.mdx
src/pages/console/index.mdx
src/plugins/import.tsx
src/styles/link-button-styles.tsx

The Amplify Studio main docs page does not have any reference on how to start a new account with Studio. To help fix this issue, I've added the block switcher to this page as the main call to action, instead of the Tutorial. I've also removed the link to the sandbox from this switcher. We want to point customers to create an AWS account first. 
I also added a new ExternalLinkButton that wraps ExternalLink and opens in a new tab. Worked with @wrpeck on this design. 
_By submitting this pull …

chore (Studio): Add Block Start Account Switch To Main Amplify Page

---

src/constants/versions.ts

Version update for release of Amplify Android v2.13.0

Amplify Android Release 2.13.0

---

tasks/link-checker.js

This PR wraps the page loads in a try/catch so that the script will continue to run through failures and not just hang

wrap link retrieval in try/catch

---

src/pages/_app.tsx

Defer the load of the d2c script

defer d2c script

---

src/fragments/lib/auth/android/hub_events/10_listen_events.mdx

`AuthChannelEventName.FEDERATED_TO_IDENTITY_POOL` doesn't currently exist, but the event does.  Bulletproofing the docs code while we fix the enum.

Fix Android Auth Hub docs

---

src/plugins/internal-link.tsx

Links within MDX files to UI docs should open in a new window
Before: 
After:

fix:links to UI docs should be external and open in new window

---

src/components/SecondaryNav/index.tsx

Fixed the SecondaryNav to be marked as `nav` element
Before:
After:

fix: mark SecondaryNav as nav element

---

src/components/TableOfContents/styles.tsx
src/constants/algolia.ts

Fix spacing near page title in On this page TOC
Before 
After

fix:  Fix spacing near page title in On this page TOC

---

cspell.json
src/pages/cli/start/install.mdx

Adds information on prerequisite to install rosetta on silicon Macs 
https://github.com/aws-amplify/amplify-cli/issues/13155
https://github.com/aws-amplify/amplify-cli/issues/10193

update install page prerequisite

---

src/pages/contribute/getting-started.tsx

Added external attribute to Link that should open in new tab

fix(bug): Links at the bottom of Contribute page are marked as external so should  open in a new tab

---

src/components/Menu/RepoActions/index.tsx
src/components/Menu/index.tsx

Putting edit button back on left nav

---

src/directory/directory.mjs
src/pages/lib-v1/auth/delete_user/q/platform/[platform].mdx
src/pages/lib-v1/auth/device_features/q/platform/[platform].mdx

This PR hides the Delete User & Device Management Auth pages from the dev preview docs.

chore: Hide Delete User & Device Management pages from dev preview

---

src/fragments/lib-v1/storage/js/getting-started.mdx

Fix incorrect manual configuration of Amplify JS v6 Storage.

fix(storage): js v6 getting started

---

src/directory/directory.mjs

Removed identify user feature in the left side navbar for JS

Fix: Removed identify user feature in the navbar for JS library

---

src/components/Menu/styles.tsx

Left nav can now scroll independently of the rest of the page. 
Staging: https://scroll-fix.d25wx63wn7as9w.amplifyapp.com/lib/auth/getting-started/q/platform/js/
fixes #5871
fixes #5831
fixes #5528

fix: scroll behavior on left menu

---

src/fragments/lib-v1/analytics/js/getting-started/30_initAnalytics.mdx
src/pages/lib-v1/auth/getting-started/q/platform/[platform].mdx

chore: remove `parseAmplifyConfig` references

---

src/fragments/lib-v1/project-setup/ios/prereq/prereq.mdx
src/fragments/lib/graphqlapi/ios/working-with-files.mdx

* Fix broken links in iOS library documentation

fix: resolve broken links in iOS

---

src/components/Card/styles.tsx

Fix: make only hosting card to point to external link
staging site: https://hosting-fix.d3n2scf4el44ne.amplifyapp.com/

Fix: make only hosting card to point to external link

---

src/fragments/lib-v1/auth/js/hub_events/10_listen_events.mdx
src/pages/lib-v1/auth/social/q/platform/[platform].mdx

Adds back documentation for the `customOAuthState` event now that support has been added back to the library.

chore: Add back custom OAuth state event documentation

---

src/fragments/lib-v1/start/getting-started/next/setup.mdx

Updates the CLI version requirement for Next.js

chore: Update CLI version requirement for Next.js

---

generatePathMap.cjs.js
src/pages/lib-v1/q/platform/[platform].mdx

`lib-v1` pages for Flutter, JS, and React-Native were 404ing. RN and JS should not be accessible, as there is not `lib-v1` content for these pages. Flutter `lib-v1` was missing from `exportPathMaps`
Staging: https://sev2-switcher.d2uvo4z6phh98j.amplifyapp.com/lib-v1/q/platform/flutter/

fix: flutter, js, react-native lib-v1 pages 404ing

---

generatePathMap.cjs.js

Adding js to the default pathmap so that it will generate a base page for lib-v1

add js to lib-v1

---

src/fragments/lib-v1/restapi/flutter/authz.mdx
src/fragments/lib/restapi/flutter/authz.mdx

Removes an outdated disclaimer about OIDC not being supported on Rest API in Flutter (Android platform). The blocker cited in the callout was resolved [here](https://github.com/aws-amplify/amplify-flutter/pull/1028).
N/A

fix(flutter/rest): removes outdated android oidc disclaimer

---

src/fragments/lib-v1/analytics/native_common/getting-started/common.mdx
src/fragments/lib-v1/storage/js/configureaccess.mdx
src/fragments/lib-v1/storage/js/copy.mdx
src/fragments/lib-v1/storage/js/download.mdx
src/fragments/lib-v1/storage/js/existing-resources.mdx
src/fragments/lib-v1/storage/js/get-properties.mdx
src/fragments/lib-v1/storage/js/getting-started.mdx
src/fragments/lib-v1/storage/js/list.mdx
src/fragments/lib-v1/storage/js/remove.mdx
src/fragments/lib-v1/storage/js/transfer-acceleration.mdx
src/fragments/lib-v1/storage/js/upload.mdx
src/pages/lib-v1/storage/existing-resources/q/platform/[platform].mdx

Cleans up storage docs based on feedback on the main PR. Replaced all tabs with 2 spaces as per the style guide.

chore: Clean up storage docs

---

src/components/Page/index.tsx
src/utils/track.ts

Using the trackPageVisit in the Pages component to track all page visits, not just initial and reloaded.
Staging: https://page-view-event.d3kzzkiugubm89.amplifyapp.com/

fix: add trackPageVisit to Pages component

---

src/components/Menu/VersionSwitcher/index.tsx

There is a bug in the  menu version picker. When differentiating JS, it only correctly identifies JS when there is nothing after the ending /. As the user scrolls down the page, they pick up anchors, which on refresh or link redraw the page with the broken version picker.
Repro steps:
- Go to [a page](https://docs.amplify.aws/lib-v1/project-setup/prereq/q/platform/js/) in the JS library that has subheadings
- Scroll down until an anchor appears on the URL
- Refresh the page to redraw with the anchor
_By submitting this pull …

fix: Version switcher query string bug

---

package.json
yarn.lock

- Update next to `13.5.41`
- Remove the resolution for `zod` since this version of next does not depend on `zod` anymore

Upgrade next to 13.5.4

---

src/utils/track.ts

- Add the `expanderId` to the event name
Staging site: https://expander-analytics.d3kzzkiugubm89.amplifyapp.com/lib/auth/getting-started/q/platform/js/
To test:
1. Open up dev tools (make sure you have [Omnibug](https://omnibug.io/) installed)
2. Click on an expander to open it
3. Verify that the event captured by Omnibug has the link name as `ExpanderOpen.{the title of the expander here}`
_By submitting this pull request, I confirm …

Add expander ID to event name

---

amplify.yml
package.json

- Removed unused script in package.json for building one of the deleted amplify backend lambdas we had
- Removed the old `capi` workspace we had
- The repo didn't have the capi directory and so it should be safe to remove this since we don't use workspaces on this repo
- Add in a `build` script that runs the build without optimizing the images
- This should help with local dev and also not make our Github workflow optimize the images
Staging site: https://update-build-scripts.d3kzzkiugubm89.amplifyapp.com/
_ref: MDX: …

Update build scripts

---

src/components/FeaturesGrid/index.tsx

- Creates a new highlighted support for CDK-enabled categories
N/A

Adds highlight for CDK support on main page

---

src/constants/versions.ts

Updating the android library version

release: Update Amplify Android Library's version

---

src/pages/cli/graphql/authorization-rules.mdx

chore: update auth docs now that cdk tokens are supported for adminRole and identityPoolId

---

.github/CODEOWNERS

Revert "Update CODEOWNERS to exclude documentation team from all files"

---

src/pages/lib/graphqlapi/relational/q/platform/[platform].mdx

Added an `<InlineFilter)` tag around the whole of the page content, as any un-filtered content will result in pages being created for all platforms. 
Current:
With Change: 

fix(android): graphqlapi relational models filter patch

---

src/constants/versions.ts

Updating Amplify Android docs to use latest version.

Update Amplify Android Version

---

src/components/Layout/Layout.tsx

- Remove unnecessary `router.isReady` check so it doesn't throw a hydration error in development
To test:
1. Pull down the branch
2. Run `yarn && yarn dev`
3. Visit the localhost site and verify there isn't a hydration error

Remove unnecessary router.isReady check

---

src/pages/index.tsx
src/utils/useClickOutside.ts

Now that SSG is working on next-release/main, useLayoutEffect was throwing some warnings. Converted these to useEffect instead.

fix(next-release/main): useEffect instead of useLayoutEffect

---

src/pages/cli/graphql/overview.mdx

Fix CDK types in the overview. Previous version referred to non-existent types.

fix: Fix CDK types in overview

---

src/components/WhatsNewBanner/index.tsx

- Since the `WhatsNew` banner is already using Amplify UI `Link`, set the `isExternal` property so that it opens in a new tab

Set isExternal to true for whats new banner

---

src/components/Layout/Layout.tsx
src/components/Menu/Menu.tsx
src/components/Menu/MenuItem.tsx
src/directory/directory.mjs
src/pages/[platform]/build-a-backend/api-graphql/index.mdx
src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx
src/pages/gen2/build-a-backend/add-aws-services/index.mdx
src/pages/gen2/build-a-backend/add-aws-services/overriding-resources/index.mdx
src/pages/gen2/index.mdx
src/pages/gen2/index.tsx

Preview site: 
- https://next-release-gen2-directory.d3kzzkiugubm89.amplifyapp.com/
- https://next-release-gen2-directory.d3kzzkiugubm89.amplifyapp.com/gen2/
WIP for updating the `Menu` and `Layout` components to display the correct menu based on if route is at gen2 or not

Handle gen2 route

---

src/utils/traverseHeadings.ts

This PR is to skip over parsing BlockSwitcher Components for the Table of Contents.  We currently have an issue where links are being added to the ToC for content that is hidden by block switchers
Staging Site: https://toc-filtering.dmhjrabi3pkql.amplifyapp.com/

don't parse BlockSwitchers for headers

---

mdx-components.tsx
src/components/Overview/Overview.tsx
src/components/Overview/index.ts
src/pages/[platform]/build-a-backend/index.mdx
src/pages/[platform]/get-started/tutorials/connect-api-and-database.mdx
src/pages/[platform]/get-started/tutorials/index.mdx
src/styles/layout.scss
src/styles/overview.scss
src/styles/styles.scss
src/utils/getChildPageNodes.ts

- Added the `Overview` component to be used in `.mdx` files. When placed in a markdown file and set up correctly, it finds all child pages and displays them in a card
Preview site examples: 
- https://next-release-overview-component.d3kzzkiugubm89.amplifyapp.com/javascript/get-started/tutorials/
- https://next-release-overview-component.d3kzzkiugubm89.amplifyapp.com/javascript/build-a-backend/
_By submitting this pull request, I confirm …

Add page overview component to display child pages as cards

---

src/components/LinkCard/LinkCard.tsx
src/components/LinkCard/index.ts
src/components/LinkCardCollection/LinkCardCollection.tsx
src/components/LinkCardCollection/index.ts
src/pages/_app.tsx
src/pages/index.tsx
src/styles/link-card.scss
src/styles/styles.scss

This feature will add link-card-component to the home page
Staging site: https://link-card-component-home.d21cx590oj6ufl.amplifyapp.com/

feat: add link card component to home page

---

next.config.mjs
package.json
yarn.lock

- Update next to `13.5.6`
- Update next config to use `output: export`
- Update package.json in response to using export there
Staging site: https://update-next-config.d39agkzf0cwtdz.amplifyapp.com/

Update next config

---

src/components/MDXComponents/MDXCode.tsx

- Add the analytics call to copy code button in MDXCode component
Staging site: https://track-code-copy.d1ywzrxfkb9wgg.amplifyapp.com/

chore: Add analytics call to copy code

---

src/components/Layout/Layout.tsx
src/styles/layout.scss
src/styles/toc.scss

Add drop shadow to home page search bar after scrolling. Reduce time for background to show up after scrolling.
https://github.com/aws-amplify/docs/assets/376920/ae6492b1-1535-4c53-8bf0-007ea5f4c627

chore(next-release/main): add drop shadow to search bar on home page after scrolling

---

src/components/Layout/Layout.tsx
src/pages/404.tsx
src/pages/[platform]/index.tsx
src/pages/_app.tsx
src/pages/gen2/index.tsx

- Adds `showBreadcrumbs` static page prop to hide breadcrumbs in layout. 
- Use this to hide breadcrumbs on 404 page, /[platform], and /gen2 pages

chore(next-release/main): add ability to show/hide breadcrumbs on a page, and hide on 404 page

---

src/styles/menu.scss

Use brand.primary color tokens for current nav link color 

fix(next-release/main) current link nav color on gen2

---

.github/CODEOWNERS
Readme.md

Update codeowners file to exclude documentation team for approvals on cspell json file changes.
Tested using this pull request https://github.com/aws-amplify/docs/pull/6138

Chore: Update codeowners file to exclude documentation team for approvals on cspell json file changes

---

src/components/Layout/Layout.tsx
src/pages/_app.tsx

- Move the usage of `router.asPath` as a `key` prop from Layout to the main container in the layout component so that it doesn't re-render everything when we navigate between menu items
Staging site: https://hydration-improvement.d1ywzrxfkb9wgg.amplifyapp.com/

Hydration improvement

---

.github/CODEOWNERS

chore: update codeowner for console

---

src/components/Breadcrumbs/index.tsx
src/components/Layout/Layout.tsx

- Add a check in `generateBreadcrumbs()` to not add the "home" page when on the gen2 route
Staging site: https://gen2-breadcrumbs.d1ywzrxfkb9wgg.amplifyapp.com/

Add check for gen2 in breadcrumbs

---

src/components/Banner/Banner.tsx
src/pages/[platform]/test-page/index.mdx
src/styles/callout.scss

Testing migration content and noticed our Callout messages are sometimes pretty long and the icon looks weird vertically centered. This aligns it to the top.
**After**
Gen2 banner is unchanged

fix(next-release/main): align Message icon to the top instead of vertically centering

---

src/components/Layout/Layout.tsx
src/components/TableOfContents/TableOfContents.tsx
src/pages/[platform]/index.tsx
src/pages/_app.tsx
src/pages/gen2/index.tsx
src/pages/index.tsx

Our content migrated from the current IA does not have the title in the page content, (like `# Page title` in the markdown)
- This updates Layout.tsx to use the pageTitle passed from the meta object of the page has the H1 in Layout.
- Pages that need a custom H1 (like the home page, gen2 home page, or /[platform] index page) can use the static pageProp `useCustomTitle: true` and include an h1 in their page content.
- Renames a Heading interface so it doesn't clash with the Heading Amplify UI primitive name.
_ref: MDX: …

chore(next-release/main): use meta.title for h1, add prop to use custom h1

---

src/styles/commands.scss

- Add `padding-top` to the cli commands heading so it's not right underneath the border separator
Staging site: https://cli-commands-spacing.d1ywzrxfkb9wgg.amplifyapp.com/javascript/tools/cli/commands/

Add padding-top to CLI command class

---

src/directory/directory.mjs
src/fragments/lib/analytics/js/existing-resources.mdx
src/pages/lib/analytics/existing-resources/q/platform/[platform].mdx

- update `use existing resource page` for amplify-js V6

chore(analytics): update use existing resource page for amplify-js v6

---

src/fragments/lib/auth/js/enable_sign_in_sign_up.mdx
src/fragments/lib/auth/js/getting-started-rn.mdx
src/fragments/lib/auth/js/getting-started-set-up-backend-resources-react-native.mdx
src/fragments/lib/auth/js/getting_started/10_setUpBackendResources.mdx
src/fragments/lib/auth/js/react-native-social.mdx
src/fragments/lib/auth/js/react-native-withoauth.mdx
src/fragments/lib/auth/js/social.mdx
src/fragments/lib/auth/js/start.mdx
src/fragments/lib/auth/js/withauthenticator.mdx
src/fragments/lib/datastore/js/examples-react-native.mdx
src/fragments/lib/datastore/js/examples.mdx
src/fragments/lib/geo/js/google-migration.mdx
src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/integrate-your-application.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/js/full-example.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/react-native/configure-amplify.mdx
src/fragments/lib/in-app-messaging/integrate-your-application/react-native/full-example.mdx
src/fragments/lib/restapi/js/authz.mdx
src/fragments/lib/restapi/js/getting-started/11_amplifyInit.mdx
src/fragments/lib/restapi/js/getting-started/30_initapi.mdx
src/pages/lib/auth/getting-started/q/platform/[platform].mdx
src/pages/lib/storage/configureaccess/q/platform/[platform].mdx
src/pages/lib/storage/getting-started/q/platform/[platform].mdx

Rename all existances of `aws-exports.js` import statement where it makes sense.
Some docs content (e.g. RN social sign-in) is not updated from v5 yet so the content is not correct. But the `aws-exports` statements are still replaced.

feat: rename js import of config file

---

src/components/Layout/Layout.tsx
src/pages/_app.tsx
src/utils/track.ts

- Since the `Layout` doesn't re-render each route change now, the `trackPageVisit` doesn't get called when navigating between different routes.
- Followed this doc: https://nextjs.org/docs/pages/api-reference/functions/use-router#routerevents to listen to when a route change gets completed to call the track page visit
Staging site: https://pageview-event.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to the staging site and open up dev tools with the Omnibug tab opened
2. Click around the menu and verify that Page view events get sent when navigating to different pages …

Update when trackPageVisit gets called

---

src/components/Menu/MenuItem.tsx
src/styles/menu.scss

- Add `margin-left` to deeply nested child (level >= 3)
- Update `MenuItem` to keep call parent's `setOpen` to make sure the menu is open when loading a page that is a deeply nested menu item
To test:
1. Go to https://update-menu.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/more-features/analytics/auto-track-sessions/
2. Verify that the menu for this page is open `Build a backend` > `More features` > `Analytics` > `Automatically track sessions`.
- In the menu, `Automatically track sessions` should have the current menu color 
3. Tab through the menu and verify that these deeply nested menu items also open when tabbing through. Previously this was not opening on the deeply nested menu items
**If this PR should not be merged upon approval for any reason, please submit as a …

Update menu to account for menu items nested deeply

---

src/components/GetStartedPopover/GetStartedPopover.tsx
src/components/PlatformNavigator/index.tsx

- Updated platform navigator and getting started popovers to close when tabbed outside of the popover
Staging site: https://update-platform-navigator.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Open the platform navigator and start tabbing through it (either with the `tab` key or `shift+tab` keys)
2. Verify that the platform navigator popover closes when tabbed to an element outside of the popover
3. Repeat steps 1 - 2 above for the getting started popover
HTML: `<a …

Make popover close when tabbed outside of it

---

src/components/Menu/Menu.tsx
src/components/Menu/MenuItem.tsx
src/utils/usePathWithoutHash.ts
src/utils/useRouterAsPath.ts

- Add a hook to get `router.asPath` without the hashmarks
- The menu component was making checks against `router.asPath` with what gets generated in directory.json. This would cause the checks to fail when we were on a url that had a targeted anchor or the hashmark `#` specifying a header. By using this custom hook we can make sure to grab `asPath` without the hash
- Updated `MenuItem` with these cleanup changes:
- Removed useEffect for opening up parent menu items
- Only toggle menu items with directories if we're on that specific route. Previously this would navigate you to the page and then toggle it off if it was already open
Staging site: https://menu-getting-started-button.d1ywzrxfkb9wgg.amplifyapp.com/
Test 1:
1. Go to https://menu-getting-started-button.d1ywzrxfkb9wgg.amplifyapp.co …

Updates to Menu component

---

src/components/MDXComponents/MDXCode.tsx

Hide the Copy button on code snippets that are console examples.
The second code block in this screenshot (from /javascript/tools/cli/custom/cloudformation/) is an example of the console, not something you'd need to copy, so it doesn't show the Copy button now.

fix(next-release/main): hide copy button on console code examples

---

src/components/Breadcrumbs/index.tsx

Fix javascript breadcrumb override to indicate that files in /prev/ are v5 now (not v6 preview anymore)

fix javascript breadcrumb override

---

src/components/Menu/MenuItem.tsx
src/utils/usePathWithoutHash.ts

- Moving set state code back inside useEffect
Staging site: https://fix-menu-errors.d1ywzrxfkb9wgg.amplifyapp.com/
Test 1:
1. Go to https://fix-menu-errors.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/more-features/analytics/auto-track-sessions/
- Verify that the menu item is selected and shown for this deeply nested page
- Verify that there are no console errors related to the menu component
Test 2:
1. Go to https://fix-menu-errors.d1ywzrxfkb9wgg.amplifyapp.com/
2. Click on get started or any of the get started links from the popover and verify that it navigates to the page and also shows intro page in the menu (you might have to scroll down in the left menu to see it)
Test 3:
1. Go to https://fix-menu-errors.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/more-featur …

Fix menu errors

---

src/directory/generateDirectory.mjs

- Use `path.posix.join` so that the `route` property we're building for next.js uses only forward slashes
- Previously on a windows machine `path.join` was creating paths with the double backslashes, `\\`.
Staging site: https://fix-generate-directory.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Pull down the repo
2. Run yarn && yarn dev
3. Verify that the site works as expected and the directory.json gets generated correctly 
_By …

Fix generate directory to account for windows machines

---

src/components/GetStartedPopover/GetStartedPopover.tsx
src/components/PlatformNavigator/index.tsx
src/utils/useTabKeyDetection.ts

There was a bug where once you open the platform navigator and click on the button to close it, it doesn't actually close. It quickly closes and reopens again. This was a bug introduced by #6224 
This was because I added an `onBlur` to the popover div and clicking outside technically registers as an on blur effect and so clicking on the button would cause it to reopen the popover since it only toggles state
To fix, this PR adds a custom hook to help detect if the `Tab` key is pressed so that in the `onBlur` callback we can check to see if we lost focus because of the `Tab` key.
Staging site: https://popover-button-toggle.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to the staging site and test out the platform navigator and the getting started popover
2. Test with tabbing through the …

Add custom hook to detect "Tab" key presses

---

src/directory/directory.mjs
src/styles/menu.scss

- Updated the `:visited` color of the menu items for external links so that it stays consistent with the primary font color
Staging site: https://fix-menu-external-link-visited-color.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Visit the staging link -> In the left menu find the "Amplify UI" external link menu item
2. Click it to open the Amplify UI docs site
3. Go back to the staging site and verify the font color of the menu item hasn't changed
HTML: `<a …

Fix menu external link visited color

---

src/constants/versions.ts

- [] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.

release(android): Update amplify android version in docs

---

src/components/Menu/MenuItem.tsx
src/styles/menu.scss

Current menu item wasn't being highlighted because some styles were overwriting the "current" color. This bug was introduced from #6250. To fix, separated out the styles for making sure the external link wasn't a different color into it's own selector.
Staging site: https://fix-current-menu-color.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Navigate to pages from the menu and verify that the "current" color gets set on the correct menu item
2. Find the "Amplify UI" external link in the menu and click on it to open the external link in a new tab
3. Go back to the docs tab and verify that the "Amplify UI" external link still has it's original color 
Which product(s) are affected by this PR (if …

Fix current menu color

---

src/styles/base.scss
src/styles/code.scss

Adds very basic blockquote styling.
**Gen2**

fix(next-release/main): blockquote styling

---

src/components/GetStartedPopover/GetStartedPopover.tsx
src/pages/[platform]/index.tsx
src/pages/index.tsx

on the platform overview pages, the "Get Started" link goes to /javascript/ but should go to the correct platform getting started page. 
staging: https://next-release-getting-started-button.d1egzztxsxq9xz.amplifyapp.com/

fix: getting started button goes to correct platform page

---

src/styles/callout.scss

- Add margin top and bottom around codeblock when placed in a callout
Staging site: https://codeblock-padding-callout.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1.  Go to https://codeblock-padding-callout.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/more-features/predictions/example-app/

Add margin top and bottom for codeblock when placed in a callout

---

src/components/MDXComponents/MDXLink.tsx

- Update MDX link component to replace `[platform]` with the correct platform
Staging site: https://update-internal-links.d1ywzrxfkb9wgg.amplifyapp.com/
- Don't think there are any links that are using the `[text here](/[platform]/page/here)` format yet for links so I made another branch (off of this branch) with some updated MDX that has test links: https://test-update-internal-links.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://test-update-internal-links.d1ywzrxfkb9wgg.amplifyapp.com/javascript/how-amplify-works/
2. There should be two links under the "Overview" heading
3. Test out that the links work
4. Switch to a different platform and go to the how amplify works page and repeat steps 2-3 with the different platform
**If this PR should not be merged upon approval for any …

Replace [platform] with current platform in internal links

---

src/components/GlobalNav/GlobalNav.tsx
src/components/Layout/Layout.tsx
src/components/SkipToMain/SkipToMain.tsx
src/components/SkipToMain/index.ts
src/styles/base.scss
src/styles/layout.scss

Adds a Skip to main link.
- It needs to be the first element on the page and it has to be in a landmark, so that really leaves putting it in the GlobalNav component.
Test on any page including gen2: https://skiptomain.d2bfwhpcsj9awv.amplifyapp.com/
https://github.com/aws-amplify/docs/assets/376920/597ce2d7-6e43-4419-bb9c-62bd182054f7
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

fix(next-release/main): add "skip to main content" link

---

src/components/VersionSwitcher/index.tsx

Only switch to corresponding versioned pages for build a backend
staging site: https://next-release-version-kickback.dmhjrabi3pkql.amplifyapp.com/

only switch to versioned pages on build a backend

---

src/styles/base.scss

We should allow our images to be inline by default; it works better for images in content for our authors like the existing docs site. 
[On this page](https://next-docs.amplify.aws/javascript/build-ui/uibuilder/slots/), this image was breaking the content 
**With the fix**

fix(next-release/main): make images inline by default, not block

---

src/components/Breadcrumbs/index.tsx
src/styles/breadcrumbs.scss

Shrinks the vertical breadcrumb spacing a tiny bit so they are less spaced out when they start to wrap. Update some values to use tokens.
**before**
**after**

fix(next-release/main): shrink breadcrumb spacing

---

src/styles/toc.scss

Use `xs` spacing for margin-block on ToC links so that it matches up with side nav spacing a little better.
**Before**
**After**

fix(next-release/main) Make spacing less weird on table of contents links

---

src/components/GlobalNav/components/AmplifyNavLink.tsx

Add `margin-inline-start` to Preview badge on gen2 header
**Before**
**After**

fix(next-release/main): increase spacing of preview label for gen2 header

---

src/components/Layout/Layout.tsx
src/styles/layout.scss
src/styles/search.scss
src/styles/variables.scss

This makes it so the search button doesn't flex all the way to the right on large monitors, and instead has a max width it can flex that matches the max width of the content.
[Preview](https://maxwidthforsearchbar.d2bfwhpcsj9awv.amplifyapp.com/)
**Before**
**After**

fix(next-release/main): add max width to search bar container

---

src/components/MDXComponents/MDXCode.tsx
src/styles/code.scss

This moves the Copy code button to the "header" of the code block (where we currently show the file name on the gen2 home page). This does increase the vertical height of the blocks, but the bonus is there are no accessibility issues with overlapping text or having to make the copy code button super tiny.
[Preview](https://codecopybutton.d2bfwhpcsj9awv.amplifyapp.com/)
**Normal code block example with copy button:** 
**Code block with no copy button, like for console blocks**
**Gen2 home page blocks that use fileName prop**
https://codecopybutton.d2bfwhpcsj9awv.amplifyapp.com/ …

fix(next-release/main): add copy button to code block header so it doesn't overlap text

---

src/components/MDXComponents/MDXLink.tsx
src/components/Overview/Overview.tsx

Internal markdown links on /gen2 pages are appending an empty platform query string parameter to the urls. For example, [the links at the bottom of this page](https://next-docs.amplify.aws/gen2/start/manual-installation/#next-steps). Also, the card links in the Overview component on overview pages on /gen2 are appending the same empty query string parameter, [such as this page](https://next-docs.amplify.aws/gen2/build-a-backend/auth/). The links aren't broken, it's just weird.
This PR:
- Only appends the platform query string parameter to markdown links if the platform exists
- Only appends the platform query string parameter to overview pages if the platform exists
**Preview links** 
- [Check markdown links on Gen2](https://gen2linksplatform.d2bfwhpcsj9awv.amplifyapp.com/gen2/start/manual …

fix(next-release/main): remove empty platform query string parameter when platform doesn't exist

---

tasks/generate-sitemap.mjs

remove gen2 from sitemap
staging site: https://next-release-remove-gen2.dmhjrabi3pkql.amplifyapp.com/

remove gen2 from sitemap

---

src/components/FrameworkGrid/FrameworkGrid.tsx
src/components/GetStartedPopover/GetStartedPopover.tsx
src/constants/frameworks.tsx
src/data/platforms.ts
src/pages/index.tsx

This PR makes `react` the default platform on the homepage.
Staging: https://reesscot-make-react-default.d1ywzrxfkb9wgg.amplifyapp.com/

Make react the default platform

---

src/components/Layout/Layout.tsx

chore(next-release/main): Turn off gen2 banners for classic launch

---

src/components/Banner/ClassicBanner.tsx
src/data/link-cards-data.ts

fix: change `Github` to `GitHub` in Linkcard component
Staging Site : https://github-fix.d1ywzrxfkb9wgg.amplifyapp.com 

fix: change Github to GitHub in Linkcard Component

---

src/components/CliCommands/Command.tsx
src/components/CliCommands/CommandHeading.tsx

Not a huge change, but move flags into tables and only use the big code block component for the main command. Subcommands and flags use the inline code element.

Slight cleanup of commands page

---

src/pages/[platform]/prev/start/index.mdx
src/pages/[platform]/prev/start/project-setup/async-programming-model/index.mdx
src/pages/[platform]/prev/start/project-setup/combine-framework/index.mdx
src/pages/[platform]/prev/start/project-setup/create-application/index.mdx
src/pages/[platform]/prev/start/project-setup/escape-hatch/index.mdx
src/pages/[platform]/prev/start/project-setup/index.mdx
src/pages/[platform]/prev/start/project-setup/kotlin-coroutines/index.mdx
src/pages/[platform]/prev/start/project-setup/platform-setup/index.mdx
src/pages/[platform]/prev/start/project-setup/prerequisites/index.mdx
src/pages/[platform]/prev/start/project-setup/rxjava/index.mdx
src/pages/[platform]/prev/start/project-setup/use-existing-resources/index.mdx
src/pages/[platform]/prev/tools/index.mdx
src/pages/[platform]/prev/tools/libraries/index.mdx

This PR hides the breadcrumbs on any pages under /prev/start and /prev/tools
You can't really get to these pages through the nav, and they're mostly just here for reference from previous version. Content folks would prefer to keep them. We don't really want to put them in the nav either so just hiding the breadcrumbs for now.
You can test locally on a page like http://localhost:3000/swift/prev/start/project-setup/create-application/
_By …

fix(next-release/main): hide breadcrumbs on /prev/start and /prev/tools pages

---

src/constants/feature-lists-data.ts

`Android 404s`
[Simple Configuration](https://next-release-main.d1ywzrxfkb9wgg.amplifyapp.com/build-a-backend/auth/set-up-auth/) - should be going to https://next-release-main.d1ywzrxfkb9wgg.amplifyapp.com/android/build-a-backend/auth/set-up-auth/
and User management should be going to https://next-release-main.d1ywzrxfkb9wgg.amplifyapp.com/android/build-a-backend/auth/user-group-management/
Swift shouldn't use JS the same way so that one does not need a link to the React [Cloud-connected UI components](https://ui.docs.amplify.aws/react/connected-components/storage)
Staging site: https://fix-android.d1ywzrxfkb9wgg.amplifyapp.com/
Which …

fix: android link for Simple Configuration in feature list component

---

src/components/Layout/Layout.tsx

Hiding the search
staging site: https://hide-search.dmhjrabi3pkql.amplifyapp.com/

hide search

---

src/components/Menu/Menu.tsx

Hiding cli-legacy and sdk from main menu
staging site: https://hide-legacy-sdk.dmhjrabi3pkql.amplifyapp.com/

remove sdk and cli-legacy from main menu

---

src/styles/spaceship.scss

We increased the width of home page content but did not adjust sizing of the spaceship so it was overlapping the text on some viewport widths.
**Before**
**After**

fix spaceship alignment

---

src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx
src/fragments/lib/troubleshooting/common/upgrading.mdx
src/fragments/start/getting-started/reactnative/setup.mdx
src/pages/[platform]/start/getting-started/auth/index.mdx
src/pages/[platform]/start/getting-started/setup/index.mdx

Add missing step for React Native getting started regarding `@aws-amplify/react-native`

fix(rn): add iOS minimum deployment requirement for new RN deps

---

src/pages/[platform]/build-a-backend/utilities/cache/index.mdx

Update broken link for https://aws-amplify.github.io/amplify-js/api/interfaces/cache.html

Update api reference for cache

---

src/components/Menu/MenuItem.tsx

- Removing the chevron after menu links that have nested pages but none that are available for the current platform.
- Revising MenuLink to show Reference for JS V6, not V5 (swapped)
https://fix-tools.d1egzztxsxq9xz.amplifyapp.com/

hide menu arrow if children are not applicable for platform

---

src/pages/[platform]/start/getting-started/nextsteps/index.mdx

broken url - https://docs.amplify.aws/react-native/build-a-backend/more-features/predictions/set-up-predictions/
parentUrl - https://docs.amplify.aws/react-native/start/getting-started/nextsteps/
linkText - AI/ML

removed AI/ML link from RN getting-started/nextsteps page

---

src/pages/[platform]/start/getting-started/data-model/index.mdx
src/pages/[platform]/start/getting-started/setup/index.mdx

- removed uneccessary `Amplify.configure` section for Next.js customers
- added step-by-step breakdown of generateClient workflow

Updated Next.js Tutorial to address customer feedback

---

src/pages/gen2/reference/cli-commands/index.mdx

Table of contents were linking to the same option and usage links since the headings are the same. Wrapped them in the SubcommandHeading component we use on the classic docs so they can stay a linkable h3 with a unique id. Temporary fix for now for just this page.
Test locally: http://localhost:3000/gen2/reference/cli-commands …

fix(gen2): temp fix for duplicate id on gen2 cli commands page headings

---

package.json
yarn.lock

Issue link https://github.com/aws-amplify/docs/security/dependabot/62
fix: @adobe/css-tools Improper Input Validation and Inefficient Regular Expression Complexity alert 
Staging URL: https://fix-adobe-css-tools.d1ywzrxfkb9wgg.amplifyapp.com/

fix: @adobe/css-tools Improper Input Validation and Inefficient Regular Expression Complexity alert fix

---

src/fragments/lib/ios-escape-hatch-warning.mdx
src/fragments/lib/project-setup/ios/upgrade-guide/upgrade-guide.mdx

Updates broken links to AWS SDK for Swift stability guidelines.
n/a

fix(swift): update broken swift sdk stability links

---

src/pages/[platform]/start/getting-started/data-model/index.mdx

remove `export` const cookiesClient ...

fix: cookiesClient does not export

---

src/pages/contribute/getting-started.tsx

Remove external icon after amplify documentation
Staging site: https://remove-external-icon.d1ywzrxfkb9wgg.amplifyapp.com/contribute/getting-started/

fix: remove external icon after amplify documentation

---

src/components/Overview/Overview.tsx

Make External Card  to open in new Tab when `isExternal `is `true `
[https://fix-external-card...amplifyapp.com](https://fix-external-card.d1ywzrxfkb9wgg.amplifyapp.com/)

fix: make the amplify hosting card open in new tab

---

src/styles/callout.scss

**Before**
**After**
This will add spacing between lines in `Callout` components.
_Staging Site_: https://callouts.d1ywzrxfkb9wgg.amplifyapp.com/
**Testing:**
To test this we need search where _Callout Component_ is used and check if there is space that is added between lines in callout

fix: add spacing for each line in callout component

---

src/fragments/lib/troubleshooting/common/upgrading.mdx

Fixes the import location in a code snippet. 
Renames posts to todos in code snippet returned props.

fix: fix typos in ssr section of migration guide

---

src/styles/banner.scss

Fixes an issue where the button appears centered on mobile and is not aligned well with the rest of the content. Also made the button default to always being below the text, since it sometimes has too much space on the right on larger screens.
Before:
After:

fix: make gen2 banner button align better with text

---

src/pages/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx

Replaces the stale PR #5855 from @sundersc 
Callout additional step required to redeploy the API when granting a function access to the GraphQL API.
https://github.com/aws-amplify/amplify-category-api/issues/679

docs(graphql-api): callout additional step when adding permission to lambda

---

src/pages/gen2/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx
src/pages/gen2/deploy-and-host/sandbox-environments/features/index.mdx

Updated the references from Parameter Store to AWS Systems Manager (SSM) Parameter Store.
N/A

fix: update AWS service name

---

cspell.json
src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx
src/pages/_app.tsx

add schema generation and iterative change info to Connect to existing database page

---

package.json
yarn.lock

Remove `html-entities` from deps and `workbox-build` from devDeps since they are no longer used.

chore: clean up more unused deps

---

src/components/MDXComponents/code-theme.ts

Fixes a red color use in our code highlighting theme that doesn't pass color contrast check ([example](https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/)):
**Before 2.05:1**
**After 5.83:1**
I went through and checked the others and looks like this was the only one that didn't pass at least 4.5:1

fix(a11y): low contrast red color in code example

---

src/pages/gen2/deploy-and-host/fullstack-branching/cross-account-deployments/index.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx

- [x ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 

Edits to two deploy and hosting guides

---

.github/workflows/build.yml
.github/workflows/check_bundle_size.yml
.github/workflows/check_for_broken_links.yml
.github/workflows/check_for_new_files.yml
.github/workflows/check_pr_for_broken_links.yml
.github/workflows/spellcheck.yml
.github/workflows/tagcheck.yml

Test pull request - chore: update github-actions to version 20 from version 16
Staging Site Link
This is a Prod account and gen2 link will not work on the banner
https://chore-github-actions-20.d1ywzrxfkb9wgg.amplifyapp.com/

chore: update github-actions to version 20 from version 16

---

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx

- Add `react-native` to auth migration guide to fix broken link from this page https://docs.amplify.aws/react-native/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/#auth

Add react-native as platform

---

src/pages/[platform]/build-a-backend/more-features/analytics/record-events/index.mdx

I suggest a change for the example of how to record events in Amplify version 6. It seems there is an incorrect example when compared to the actual code implementation in the amplify-js repository.
https://github.com/aws-amplify/docs/issues/6661

fix: wrong example provided in amplify analytics version 6

---

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx

Removes incorrect `@refersTo` directive from the `Blog` type. That directive is only valid for `@model` classes, which is outside the scope of this documentation.

fix: Remove incorrect directives from Blog type

---

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx

Adds outbound rules required to successfully establish connection with the SSM and Database from the customer managed VPC where their SQL Lambda lives.

fix: add required outbound rules to SQL lambda VPC setup

---

src/pages/[platform]/build-ui/formbuilder/call-to-action/index.mdx
src/pages/[platform]/build-ui/formbuilder/customize/index.mdx
src/pages/[platform]/build-ui/formbuilder/data-binding/index.mdx
src/pages/[platform]/build-ui/formbuilder/index.mdx
src/pages/[platform]/build-ui/formbuilder/lifecycle/index.mdx
src/pages/[platform]/build-ui/formbuilder/overrides/index.mdx
src/pages/[platform]/build-ui/formbuilder/special-inputs/index.mdx
src/pages/[platform]/build-ui/formbuilder/validations/index.mdx
src/pages/[platform]/build-ui/uibuilder/bestpractices/index.mdx
src/pages/[platform]/build-ui/uibuilder/collections/index.mdx
src/pages/[platform]/build-ui/uibuilder/databinding/index.mdx
src/pages/[platform]/build-ui/uibuilder/eventhandling/index.mdx
src/pages/[platform]/build-ui/uibuilder/index.mdx
src/pages/[platform]/build-ui/uibuilder/override/index.mdx
src/pages/[platform]/build-ui/uibuilder/responsive/index.mdx
src/pages/[platform]/build-ui/uibuilder/slots/index.mdx
src/pages/[platform]/build-ui/uibuilder/theming/index.mdx

Updating platforms for Figma-to-Code and Formbuilder

---

src/pages/[platform]/how-amplify-works/index.mdx

Got broken link report:
```
url - https://docs.amplify.aws/android/build-ui/formbuilder/
parentUrl - https://docs.amplify.aws/android/how-amplify-works/
linkText - Form Builder
url - https://docs.amplify.aws/android/build-ui/uibuilder/
parentUrl - https://docs.amplify.aws/android/how-amplify-works/
linkText - Figma-to-code generation
```
https://docs.amplify.aws/android/how-amplify-works/#ui-building
`[platform]/build-ui/uibuilder` and `/formbuilder` only exist on JS.
HTML: `<a …

fix(android): broken links to form builder

---

src/pages/[platform]/build-a-backend/graphqlapi/connect-to-api/index.mdx

From customer comment: https://github.com/aws-amplify/amplify-js/issues/12147#issuecomment-1815517219
Fix a wrong code snippet for JS GraphQl API call.
https://github.com/aws-amplify/amplify-js/issues/12147#issuecomment-1815517219

fix(api): wrong JS graphql custom headers example 

---

src/styles/base.scss

Adds some better styling for `<kbd>` elements.
**Before**
**After** (tested with WIP dark mode branch)

chore(styles): add styling for kbd element

---

src/components/Columns/Columns.tsx
src/pages/gen2/index.tsx
src/styles/feature-links.scss

Fixes the incorrect `<li>` nesting on the gen2 home page. Preview: https://gen2homepagecleanup.d2bfwhpcsj9awv.amplifyapp.com/gen2
Currently there is some out of order elements resulting in this markup with a video as a direct child of a `<ul>` and `<li>` elements with no parent `<ul>`. 
**Before**
**After**
Additionally, this updates the Columns component so it can be used as a `<div>` or a `<ul>` parent and some minor CSS fixes to remove extra margins
HTML: `<a …

fix: formatting on gen2 home page

---

src/components/Menu/MenuItem.tsx
src/styles/menu.scss

This PR adds an additional indicator (a small right border) to the currently active page in the main menu.
Context: The style for the currently active page in the main menu currently only relies on a text color change to differentiate it from non-active pages. Since it is low contrast compared to it's non-active siblings an additional indicator is needed to make it more accessible and easier to identify in our long list of menu items.
This also adds aria-current to the current menu item so that screen readers will announce it's current status.
Preview: https://updatecurrentmenustatus.d2bfwhpcsj9awv.amplifyapp.com/
**Before**
**After**
**After (Gen2)**
Which product(s) are affected by this PR (if …

chore: add current page indicator and aria-current to main menu items

---

src/pages/[platform]/start/getting-started/auth/index.mdx

Add explicit install of `react-native-safe-area-context` for expo and vanilla RN Getting Started guide and remove deps install instructions for packages installed in previous step
https://github.com/aws-amplify/docs/issues/6694

fix: update RN getting started guide UI deps

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/restapi/restapi-v5-to-v6-migration-guide/index.mdx

Adds a migration guide for API (REST) category.

feat: add restapi migration guide

---

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx

Re-enables schema generation instructions that we removed on https://github.com/aws-amplify/docs/pull/6659.
Additional changes:
- Add a callout warning that SQL support is not available in ap-east-1 or eu-south-1

chore: Re-enable schema generation instructions

---

src/directory/directory.mjs

- The sitemap for the flutter api reference page had an extra `/` because the directory entry wasn't using `path` and was using `route` to define the URL. Switch to `path` and use the file path to help generate the sitemap
Staging site: https://fix-flutter-api-reference-sitemap.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://fix-flutter-api-reference-sitemap.d1ywzrxfkb9wgg.amplifyapp.com/sitemap.xml
2. Find `flutter-api` and verify that it has only one trailing slash
- Compare that to https://docs.amplify.aws/sitemap.xml, which has two trailing slashes  …

Use 'path' instead of 'route' for flutter api reference directory entry

---

customHttp.yml
src/pages/_document.tsx

- Remove the content security policy section in `customHttp.yml` since we're already setting it in `_document.tsx`

Remove CSP section from customHttp.yml

---

src/fragments/lib-v1/graphqlapi/existing-resources.mdx
src/fragments/lib/graphqlapi/existing-resources.mdx

- Example links were being treated as real links so format them with code text so they aren't clickable
Staging site: https://update-example-links.d1ywzrxfkb9wgg.amplifyapp.com/swift/build-a-backend/graphqlapi/existing-resources/

Make example links use code format

---

src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx

The Gen 2 `amplifyconfiguration.json` gets created at the root of the project not at src.
changed `App.js` to `App.vue`
source: discord report

update vue auth example Gen 2

---

.github/workflows/check_pr_for_broken_links.yml

- Currently the pr link checker workflow uses a configuration variable for the build directory. Configuration variables on the repo aren't passed to PRs from forks though meaning this workflow will fail for these kinds of PRs. Added an environment variable with the build directory for now so fork PRs don't fail
More info here in this github discussion: https://github.com/orgs/community/discussions/44322
_By submitting this pull request, …

Use env var in workflow instead of variable on repo

---

.github/PULL_REQUEST_TEMPLATE.md

The pull request template for this repo currently lists **iOS** as one of the platform options. This should be **Swift** to reflect the name change from Amplify iOS to Amplify Swift, as well as to match the platform options on the docs site.
| Platform Switcher on Site | Current PR Template |
|-|-|
| ![CleanShot 2023-11-27 at 21 52 37@2x](https://github.com/aws-amplify/docs/assets/52051793/54f77f8e-7a78-4c81-b8a5-a1a4af2d6478) | ![CleanShot 2023-11-27 at 21 49 21@2x](https://github.com/aws-amplify/docs/assets/52051793/10f5da82-75e5-4162-b81a-297866f4414a) | …

chore: replace iOS with Swift in pull request template

---

src/directory/directory.mjs

- Noticed `build-a-backend/more-features/geo/configure-maps/` was being shown in the sitemap twice because it was listed twice in directory.json. This also means that this page https://docs.amplify.aws/react/prev/build-a-backend/more-features/geo/configure-maps/, was not accessible in the menu
- Adding the prev should make this appear in the menu now and fix the sitemap duplication …

Fix typo for mdx file in prev section

---

.github/PULL_REQUEST_TEMPLATE.md

Removes link to `link.com` in PR template since it's an actual website and replaces it with our own.

fix: update link example in PR template

---

src/pages/gen2/build-a-backend/auth/manage-mfa/index.mdx

removes `sms` from mfa example when `phone` is not enabled

gen2 fix mfa snippet, remove sms from mfa when phone is not enabled

---

src/pages/gen2/start/mobile-support/index.mdx

Added npx to the amplify sandbox and amplify generate graphql-client-code commands in six places.
- [x ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 

Adding npx to fix blocking error for customers

---

src/pages/[platform]/build-a-backend/restapi/restapi-v5-to-v6-migration-guide/index.mdx

Fixes V6 example for cancel not showing up.

fix: fix v6 block not showing up for cancel example

---

src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx

chore(js-auth): complete oauth in MPAs

---

src/pages/gen2/build-a-backend/auth/manage-user-profile/index.mdx

fix references of `immutable` with `mutable`

gen2 auth fix immutable -> mutable

---

src/fragments/lib/troubleshooting/common/upgrading.mdx

Fixes Storage example in the Migration Guide overview that shows an import of downloadData but uses getUrl.

fix: wrong import shown for storage getUrl in migration guide

---

src/pages/[platform]/start/getting-started/installation/index.mdx

- adds callout for `amplify configure` support
- adds callout for use with IAM roles, IAM Identity Center
- adds instructions for use with both

add callout for sso use, manual configuration instructions

---

src/components/Layout/Layout.tsx

Removed prev/next from overview pages
staging: https://remove-prev-from-overview.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/more-features/analytics/
current on main: https://docs.amplify.aws/react/build-a-backend/more-features/analytics/

remove next/prev from overview pages

---

src/pages/gen2/deploy-and-host/hosting/index.mdx

On `/gen2/deploy-and-host/hosting/`, the "View Hosting Docs" button does not open in a new tab. Updated the `<InternalLinkButton>` to be an `<ExternalLinkButton>`
staging: https://fix-hosting-external-link.d1egzztxsxq9xz.amplifyapp.com/gen2/deploy-and-host/hosting/
original: https://docs.amplify.aws/gen2/deploy-and-host/hosting/
_By submitting this pull request, I confirm that my contribution is made under the terms of …

fix: gen2 page button to external link

---

package.json
yarn.lock

- Add resolution for `follow-redirects` package
- Remove `json5` as resolution since it's already a dev dependency
Staging site: https://follow-redirects-dependabot.d1ywzrxfkb9wgg.amplifyapp.com/

Add resolution for follow-redirects

---

src/components/Layout/Layout.tsx
src/pages/_app.tsx

Fixes a type mismatch for children passed to Layout from _app.tsx; it should always be a ReactElement. This wasn't breaking anything but it was made evident in this error surfaced from our check for `isOverview`.

Layout type fixes

---

src/pages/[platform]/build-a-backend/restapi/gen-ai/index.mdx

Update platforms for Gen AI guide

---

src/components/GlobalNav/GlobalNav.module.scss

Fixes the color and focus color of gen2 mobile menu toggle and home link focus color.
**Before**
**After**

fix(gen2/darkmode): fix color of mobile menu toggle on gen2 darkmode

---

src/pages/gen2/build-a-backend/auth/override-cognito/index.mdx

The original code sample had a mistake in [/gen2/build-a-backend/auth/override-cognito/#override-cognito-userpool-password-policies](https://docs.amplify.aws/gen2/build-a-backend/auth/override-cognito/#override-cognito-userpool-password-policies).
**this is only fixing docs.**

fix: incorrect code sample in documentation

---

src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx

adds commented-out `callbackUrls` and `logoutUrls` in defineAuth snippet. These are new values from the defineAuth template https://github.com/aws-amplify/amplify-backend/pull/856
n/a, this is new

add callback, logout URLs to defineAuth template snippet

---

src/fragments/lib/restapi/js/getting-started/11_amplifyInit.mdx
src/fragments/lib/restapi/js/getting-started/40_postTodo.mdx

Following the guide and attempting to name a REST API `todo-api` results in the following CLI error:
```sh
❯ Resource name should be alphanumeric 
```
Later in the guide, the `post` request currently results in the following error, due to a [bug](https://github.com/aws-amplify/amplify-js/issues/12687):
```sh
POST call failed:  NoCredentials: Credentials should not be empty.
```
Furthermore, even after working around the `NoCredentials` issue, the code snippet references a `response` variable that does not exist, resulting in the following error:
```sh
ReferenceError: response is not defined
```
https://github.com/aws-amplify/amplify-js/issues/12687
Which product(s) are affected by this PR (if …

Small corrections to REST API code snippets

---

src/components/Layout/Layout.tsx

- Add `Gen 2` to page title if we're on a gen2 route
Staging site: https://add-gen2-to-title.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://add-gen2-to-title.d1ywzrxfkb9wgg.amplifyapp.com/gen2/
2. Verify that the meta page title now includes `AWS Amplify Gen 2 Documentation`. This can be checked in dev tools or by hovering over the browser tab (it should show a tool tip and display the page title
3. Try other pages on the gen2 route to verify too 
HTML: `<a …

Add 'Gen 2' to page title if on gen2 route

---

src/fragments/lib/troubleshooting/common/upgrading.mdx

NextJS Migration guide link would be broken if linking from any other platform from the overview.

fix: link to ssr migration guide should be nextjs platform specific

---

src/fragments/lib-v1/in-app-messaging/respond-interaction-events/respond-interaction-events.mdx
src/fragments/lib/in-app-messaging/respond-interaction-events/respond-interaction-events.mdx
src/pages/[platform]/build-a-backend/more-features/in-app-messaging/in-app-messaging-migration-guide/index.mdx

This PR adds additional migration details on the v5 -> v6 migration guide for In-App Messaging.
* Adds input parameter and type changes where applicable
* Adds descriptions of what has changed
* Fixes some existing In-App Messaging documentation errors

feat: add details to In-App Messaging migration guide

---

src/pages/gen2/build-a-backend/data/customize-authz/public-data-access/index.mdx

- The meta object was not getting captured by the regex because the meta object for this page was missing a semicolon. Add semicolon to meta object to fix it
To test:
1. Pull down this branch and visit `/gen2/build-a-backend/data/customize-authz/`
2. Verify that the card for public data access isn't empty …

Add missing semicolon

---

src/pages/[platform]/prev/build-a-backend/index.mdx

Add banner for prev version project setup

---

src/directory/generateDirectory.mjs

- Added an extra error that throws when there is no match for the `meta` object when generating directories. 
- Related to #6831, this page had a meta object but it was not being matched and so generateDirectory.mjs was skipping over the page even though it was listed in directory.mjs.

Throw an error if unable to match for the meta object

---

src/utils/__tests__/useCurrentPlatform.test.ts

- Add test for `useCurrentPlatform`
Coverage results:
```
jest src/utils/__tests__/useCurrentPlatform.test.ts --coverage
PASS  src/utils/__tests__/useCurrentPlatform.test.ts
useCurrentPlatform
✓ should return the current platform based on the query object (8 ms)
-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------|---------|----------|---------|---------|-------------------
All files              |     100 |      100 |     100 |     100 |                   
useCurrentPlatform.ts |     100 |      100 |     100 |     100 |                   
-----------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 …
```

Add test for useCurrentPlatform

---

src/utils/__tests__/getCustomStaticPath.test.ts
src/utils/getCustomStaticPath.ts

- Add tests for `getCustomStaticPath`

Add tests for getCustomStaticPath

---

src/pages/[platform]/build-a-backend/more-features/analytics/existing-resources/index.mdx

Fixes missing JS fragments in Angular, React, Vue, and Next.js for the "Use existing AWS resources" analytics page.

fix: Analytics JS fragments in Angular, React, Vue, and Next.js

---

src/pages/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx
src/pages/gen2/build-a-backend/server-side-rendering/index.mdx

Fixes a typo in the Auth SSR API import path in the Next.js getting started guides.

fix: Fix Auth SSR import path typo in Next.js guides

---

src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx
src/pages/gen2/build-a-backend/storage/index.mdx

Removes wording about needing to install the CDK

---

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx

The content on this page is not an end to end tutorial. It assumes that there is already an existing database and the reader is creating their own schema. The example schemas and sql statements we provide are to serve as examples for the reader.
**The initial schema has the name Blog, but then when SQL statements are introduced, it is using Post instead.**
- Added a Post type to the initial schema to reflect the sql statements and custom query/mutations examples mentioned afterwards. 
**Shall we add a snippet of the CREATE statement for the posts table?**
- We don't provide a CREATE statement for the blog table as the reader is to create their own tables.
There is a CREATE statement for the posts table in the `Apply iterative changes from the database definition` to serve as an example of …

apply changes from feedback

---

src/pages/[platform]/build-a-backend/graphqlapi/client-code-generation/index.mdx

This PR comes from current customer confusion. This below reads that Amplify supports any AppSync schema deployed through CDK.
"Generate GraphQL client helper code with CDK-deployed GraphQL API"
Clarification is needed that we are referring to our Amplify L3 CDK constructs.

Clarify Amplify API Code Generation Statement

---

src/pages/[platform]/build-ui/formbuilder/index.mdx

- [] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.
- [] Are any files being deleted with this PR? If so, have the needed redirects been created?

Modifying code snippet to use correct imported variable

---

src/pages/[platform]/tools/cli/index.mdx
src/pages/[platform]/tools/cli/project/troubleshooting/index.mdx
src/pages/[platform]/tools/cli/usage/mock/index.mdx

Removes references to local amplify mock testing from Flutter paths.
https://github.com/aws-amplify/amplify-flutter/issues/4163

fix(flutter): remove local mock references and page

---

src/fragments/lib/restapi/js/fetch.mdx

Add guidance to access the HTTP response from REST API errors.
https://github.com/aws-amplify/amplify-js/pull/12835

feat(api): access response properties from api errors

---

src/fragments/lib/troubleshooting/common/upgrading.mdx

- The nextjs section had nextjs specific links being built with the `platform` slug. This meant that viewing this page on platforms other than nextjs would create links to 404 pages.
- To fix, added an inline filter for nextjs to wrap around the nextjs sections so that this section is not shown on any other platform page
Staging site: 
- https://fix-404-nextjs-links.d1ywzrxfkb9wgg.amplifyapp.com/react/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6
- https://fix-404-nextjs-links.d1ywzrxfkb9wgg.amplifyapp.com/angular/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6
- https://fix-404-nextjs-links.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6
- …

Add inline filter for nextjs sections

---

src/fragments/lib/graphqlapi/native_common/advanced-workflows/common.mdx

Adds a callout to `NONE` authorization type in adding custom headers to GraqhQL API requests section
Based on recommendation of a customer
https://github.com/aws-amplify/amplify-swift/issues/3491#issuecomment-1924591341

chore: add call out for NONE authorization type in adding custom headers section

---

src/pages/[platform]/tools/cli/index.mdx
src/pages/[platform]/tools/cli/project/troubleshooting/index.mdx
src/pages/[platform]/tools/cli/usage/mock/index.mdx

Removes references to andrioid and swift platforms for mocking via CLI. 

fix(android,swift): remove local mock support

---

src/pages/[platform]/build-a-backend/graphqlapi/set-up-graphql-api/index.mdx

Within a codeblock, there is a reference to a page that no longer exists. This PR updates that link. @heatheramz is this the behavior we want or should this link be removed - the Authorization Rules are referenced and linked in a callout directly below this codeblock:
```
input AMPLIFY {
globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type Todo @model {
id: ID!
name: String!
description: String
}
```
fixes #6830
HTML: `<a …

fix: 404 url referenced in codeblock

---

src/pages/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx

When using `@auth(rules: [{ allow: public, provider: "iam" }])`, customers must also explicitly let the Amplify client configuration file know that they should allow guest access. 
N/A

Add context to explicitly add `allowGuestAccess` when using public iam provider with CDK construct

---

src/components/Footer/Footer.tsx

Fix the size of footer logo and add accessible label
**Before**
**After**

Fix tiny aws logo

---

src/pages/gen2/build-a-backend/auth/add-social-provider/index.mdx

adds `domainPrefix` in example code when use of sign-in with social providers.
The `domainPrefix` is value added at https://github.com/aws-amplify/amplify-backend/pull/856.

fix: add domainPrefix to example of social provider

---

src/pages/gen2/start/mobile-support/index.mdx

- added `WidgetsFlutterBinding.ensureInitialized();` before `await _configureAmplify();` in the Mobile Support - Flutter section of the Gen 2 docs. 
- from the Amplify Flutter Docs - https://github.com/aws-amplify/amplify-flutter/issues/4447

fix: added WidgetsFlutterBinding.ensureInitialized(); before await _configureAmplify();

---

src/pages/[platform]/build-a-backend/storage/upload/index.mdx

The sample under [Monitor progress of upload](https://docs.amplify.aws/react/build-a-backend/storage/upload/#monitor-progress-of-upload) rounds the progress value to the nearest 100 instead of whole number. This fixes that.
N/A

fix: Storage upload progress - update Math.round to whole number instead of 100

---

src/components/SpaceShip/SpaceShip.tsx
src/styles/algolia.scss

- Add aria-hidden to spaceship SVG
- Fix color contrast of search key commands in search input
- Fix misnamed css custom property

fix(a11y): decorative SVG and contrast on search keys

---

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx

Fixes an incorrect path in the Amplify JS v6 auth migration guide.

fix: Fix incorrect auth import path in migration guide (Amplify JS)

---

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx

Updates an incorrect API parameter for the `updateMFAPreference` API in the Amplify JS v6 migration guide.

fix: Update incorrect `updateMFAPreference` parameter in JS v6 migration guide

---

src/pages/[platform]/tools/cli/usage/lambda-triggers/index.mdx

The sections under [this page](https://docs.amplify.aws/react/tools/cli/usage/lambda-triggers/#override-id-token-claims) can be confusing due to how they are nested - this PR is to fix the nesting.
n/a

fix: Nesting of auth cli templates

---

src/pages/[platform]/build-ui/uibuilder/index.mdx

Fix the variable name from `awsconfig` to `amplifyconfig` on the `Figma-to-Code` page.
Fixes #6922 

fix(react): change config variable name on the Figma-to-Code page

---

src/directory/directory.mjs
src/pages/[platform]/sdk/configuration/amplify-compatibility/index.mdx

Android team would like to add a site to better assist users attempting to use Amplify Android v2 with the AWS Android SDK.

chore(android): Guide to support Amplify v2 with AWS Android SDK

---

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx

Reverts aws-amplify/docs#6947
In order to take these changes, the top level section needs to be altered to avoid breaking navigation links. 
We will need to revisit how we want to structure this guide, until then we should revert this change.
cc: @offlineprogrammer  @hibler13

Revert "fix(flutter, js): scope "connect existing cdk" guide to platform"

---

src/components/Layout/Layout.tsx
src/components/Layout/LayoutHeader.tsx

Removes some of the duplicated logic between Layout and LayoutHeader and adds new props to LayoutHeader to accept those values instead.
https://mainmorelayoutrefactor.d2bfwhpcsj9awv.amplifyapp.com/

chore: remove duplicated logic between Layout and LayoutHeader

---

.github/CODEOWNERS
package.json
src/components/Layout/Layout.tsx
src/components/Layout/LayoutHeader.tsx
src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/customize-authz/multi-user-data-access/index.mdx
src/pages/gen1/[platform]/build-ui/uibuilder/index.mdx
src/pages/gen1/[platform]/sdk/configuration/amplify-compatibility/index.mdx
src/pages/gen1/[platform]/tools/cli/usage/lambda-triggers/index.mdx
yarn.lock

chore(next-release/main): update next-release/main with latest from main

---

src/pages/gen2/build-a-backend/auth/add-social-provider/index.mdx

Last night I attempted run through the docs for setting up [Sign In With Apple for Gen 2](https://docs.amplify.aws/gen2/build-a-backend/auth/add-social-provider/) and ran into a couple problems.
1. The `defineAuth` payload for Sign in with Apple was missing a required field `clientId`.
2. The frontend code sample was using v5 of the js library, not v6.
3. I was not clear about what the `domainPrefix: 'subdomain'` field was for. When I omitted it, deployment succeeded but an invalid amplifyconfiguration.json was created
4. I wasn't sure how to access the `email` field of the freshly signed up user. For email/password signed up users, it's in `getCurrentUser()`, but for Sign in with Apple users it's only in `fetchUserAttributes()`.
This PR updates the docs with fixes/clarifications on these …

improve oauth docs

---

src/pages/gen2/build-a-backend/auth/add-social-provider/index.mdx

This PR adds more detail on how to handle receiving oauth responses in multi page apps. Without following the instruction added in this PR, the oauth handshake completes and redirects to the app, but the app leaves you in a signed out state (`getCurrentUser()` throws).
N/A

include usage for multi-page apps

---

package.json
src/components/YoutubeEmbed/__tests__/YoutubeEmbed.test.tsx

chore: add unit test for YoutubeEmbed component

---

src/fragments/lib/restapi/js/delete.mdx
src/fragments/lib/restapi/js/fetch.mdx
src/fragments/lib/restapi/js/getting-started/40_postTodo.mdx
src/fragments/lib/restapi/js/update.mdx

Original JS issue: https://github.com/aws-amplify/amplify-js/issues/12997
Docs issue: https://github.com/aws-amplify/docs/issues/6930
Our REST API docs suggest that the error payload can be console logged as is - however, the Express payload type returns JSON, resulting in "unknown error" being logged to the console when following our current docs. This PR updates the code snippets to log meaningful errors for the user.
HTML: `<a …

fix(data): update REST API docs to document correct error response type

---

src/fragments/lib-v1/auth/common/device_features/common.mdx
src/fragments/lib-v1/auth/native_common/device_features/common.mdx
src/fragments/lib/auth/common/device_features/common.mdx
src/fragments/lib/auth/native_common/device_features/common.mdx
src/pages/[platform]/build-a-backend/auth/manage-mfa/index.mdx
src/pages/[platform]/prev/build-a-backend/auth/manage-mfa/index.mdx
src/pages/[platform]/prev/build-a-backend/auth/remember-device/index.mdx
src/pages/gen2/build-a-backend/auth/manage-mfa/index.mdx

This commit updates the documentation to clarify that using the forgetDevice() API results in the device being neither remembered nor tracked. Previously, the documentation suggested that forgotten devices might still be tracked, leading to confusion about the API's behavior. The revised wording aligns with the detailed description under the "Forgotten" section, ensuring consistency and eliminating ambiguity about how forgotten devices are handled.
HTML: `<a …

Clarify behavior of forgetDevice() API regarding device tracking

---

src/styles/menu.scss

- Add bottom padding to the menu so that the nav links have extra space above the separator for the feedback component
Staging site: https://menu-bottom-padding.d1ywzrxfkb9wgg.amplifyapp.com/
Before:
After:

Add padding to bottom of nav menu

---

src/pages/gen2/build-a-backend/functions/index.mdx
src/pages/gen2/build-a-backend/storage/index.mdx

Add docs for configuring storage triggers
Gen2 storage and functions
NA

add storage trigger docs

---

src/pages/gen2/build-a-backend/functions/index.mdx

[Link](https://docs.amplify.aws/gen2/build-a-backend/functions/#:~:text=Branch%2Dspecific%20environment%20variables%20can%20be%20configured%20for%20Amplify%20hosting%20deployments.) was missing preceding slash

fix: broken link, missing preceding /

---

src/fragments/lib/troubleshooting/common/upgrading.mdx

- Link in file was originally linking to this page: https://aws.amazon.com/blogs/mobile/building-fast-next-js-apps-using-typescript-and-aws-amplify-javascript-v6
- Updated link to https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/ since it looks like the url changed

Fix link for upgrading.mdx in migrate to amplify v6

---

src/pages/gen2/build-a-backend/storage/index.mdx

fix:  proper variable naming conventions for storage

fix: proper variable naming conventions for storage

---

src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx

Removed the probably incorrect extension `.js`.

remove explicit file extension from gen2 imports

---

src/pages/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/index.mdx

Adds docs on configuring `defineFunction` access to the `defineData` schema. The experience of configuring the data client in the lambda is still a work in progress, but this adds documentation on the currently supported experience.
Gen 2 function and data
NA

add docs on granting defineFunction access to defineData

---

src/fragments/lib-v1/geo/js/geofences.mdx
src/fragments/lib-v1/geo/js/google-migration.mdx
src/fragments/lib-v1/geo/js/maps.mdx
src/fragments/lib-v1/geo/js/search.mdx
src/fragments/lib/geo/js/geofences.mdx
src/fragments/lib/geo/js/google-migration.mdx
src/fragments/lib/geo/js/maps.mdx
src/fragments/lib/geo/js/search.mdx

- Update maplibre links to the new docs url: https://maplibre.org/maplibre-gl-js/docs/

Update maplibre links

---

yarn.lock

Updates yarn.lock for @docsearch/react 3.6 update which includes the accessibility updates we made in their repo. 🎉
https://updatealgoliasearch.d2bfwhpcsj9awv.amplifyapp.com/

chore: upgrade docsearch/react to 3.6

---

package.json
yarn.lock

- Update resolution for `follow-redirects`
Staging site: https://update-follow-redirects.d1ywzrxfkb9wgg.amplifyapp.com/

Update resolution for follow-redirects

---

src/pages/[platform]/build-a-backend/graphqlapi/custom-business-logic/index.mdx

- Amends the Gen 1 CLI docs with JavaScript resolver sample code 
- Addresses some issues of https://github.com/aws-amplify/amplify-category-api/issues/1015

Add JavaScript resolver code sample to Gen 1

---

src/styles/modal.scss

Fixes some missing mobile styles for displaying the Modal
**Before**
**After**

fix(next-release/main): mobile Modal styles

---

src/fragments/lib-v1/analytics/js/getting-started/20_installLib.mdx
src/fragments/lib-v1/auth/js/getting-started-rn.mdx
src/fragments/lib-v1/datastore/js/setup-env-js.mdx
src/fragments/lib-v1/datastore/react-native/getting-started/30_platformIntegration.mdx
src/fragments/lib-v1/geo/js/geofences.mdx
src/fragments/lib-v1/geo/js/getting-started.mdx
src/fragments/lib-v1/graphqlapi/js/js-configure.mdx
src/fragments/lib-v1/graphqlapi/js/react-native-configure.mdx
src/fragments/lib-v1/in-app-messaging/integrate-your-application/js/install-dependencies.mdx
src/fragments/lib-v1/push-notifications/react-native/getting_started/40_install_lib.mdx
src/fragments/lib-v1/react-native-polyfills.mdx
src/fragments/lib-v1/storage/js/getting-started.mdx
src/fragments/lib-v1/utilities/cache.mdx
src/fragments/start/getting-started/reactnative/getting-started-steps-ui.mdx
src/pages/[platform]/prev/build-a-backend/auth/set-up-auth/index.mdx
src/pages/[platform]/prev/build-a-backend/graphqlapi/connect-to-api/index.mdx

Update v5 libraries installation guides.
https://github.com/aws-amplify/docs/issues/6971
- smoked tested docs app - reviewed v5 and v6 pages
- ran the following commands with a clean build:
- npm install aws-amplify@^5.0
- npm install aws-amplify@^5.0 @aws-amplify/ui-react@^5.0 @aws-amplify/ui-react-geo@^1.0 maplibre-gl-js-amplify@^2.0 maplibre-gl
- npm install aws-amplify@^5.0 @react-native-async-storage/async-storage @react-native-community/netinfo
- npm install aws-amplify@^5.0 @aws-amplify/ui-react@^5.0 @aws-amplify/ui-react-notifications@^1.0
- npm install aws-amplify@^5.0 @aws-amplify/ui-react@^5.0
- npm install aws-amplify@^5.0 @aws-amplify/ui-vue@^3.0
- npm install aws-amplify@^5.0 @aws-amplify/ui-components@^0
- npm install aws-amplify@^5.0 @aws-amplify/ui-angular@^4.0
**If this …

fix(JS): Update v5 JS libraries installation guides.

---

src/pages/gen2/build-a-backend/functions/index.mdx

Update import path for generated function `env` symbol from
```ts
import { env } from '@env/<function-name>';
```
to
```ts
import { env } from '$amplify/env/<function-name>';
```
Add section with more information on the `env` symbol and how to manually configure your Amplify project to use it.
Gen 2 Function
N/A …

Change generated function env package name

---

src/pages/[platform]/build-a-backend/troubleshooting/library-not-configured/index.mdx

- Link in page was pointing to `localhost`. Updated it to point to the relative platform url

Update typo in url for localhost

---

next.config.mjs

Switch next config to use a static build id

update next config to use a static build Id

---

src/pages/gen1/index.tsx

On the /gen1 page it should now only show "Amplify Documentation" instead of "Amplify Documentation for React".
/gen1/react will continue to say "Amplify Documentation for React"

fix(next-release/main): remove the platform name from the h1 title for /gen1 page

---

src/pages/[platform]/build-a-backend/more-features/analytics/record-events/index.mdx

Adds a callout to the JS Analytics docs explaining that events will not be persisted between application sessions.

chore: Add callout on Analytics buffer persistence in Amplify JS

---

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
src/pages/[platform]/deploy-and-host/fullstack-branching/branch-deployments/index.mdx
src/pages/[platform]/deploy-and-host/fullstack-branching/custom-pipelines/index.mdx
src/pages/[platform]/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx
src/pages/[platform]/how-amplify-works/concepts/index.mdx
src/pages/[platform]/index.tsx
src/pages/[platform]/reference/iam-policy/index.mdx
src/pages/[platform]/start/mobile-support/index.mdx
src/pages/gen1/[platform]/build-a-backend/existing-resources/cdk/index.mdx
src/pages/gen1/[platform]/build-a-backend/existing-resources/cli/index.mdx
src/pages/gen1/[platform]/build-ui/formbuilder/call-to-action/index.mdx
src/pages/gen1/[platform]/build-ui/formbuilder/customize/index.mdx
src/pages/gen1/[platform]/build-ui/formbuilder/special-inputs/index.mdx
src/pages/gen1/[platform]/build-ui/formbuilder/validations/index.mdx
src/pages/index.tsx

Fixes videos that should play inline on iOS but were instead expanding to fullscreen. Interim fix until we make a `<Video />` component.

fix(next-release/main): add playsinline to video elements

---

src/styles/code.scss
src/styles/home.scss

https://fixfontsizes.d2bfwhpcsj9awv.amplifyapp.com/
Reins in the font sizes on the home page h1 (and other platform overview pages h1) and the font size used in code blocks.
The h1 font size is restricted to <1000px (the breakpoint that we flip to "mobile" views). The code block font size change affects all viewport sizes. The code block one is a little less notice-able, but in the screenshots you can see you get about one more line of code showing on that particular view of the page.
**Before**
**After**
_ref: MDX: …

fix(next-release/main): update home page h1 and code block font size

---

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx
src/pages/[platform]/build-a-backend/existing-resources/cli/index.mdx
src/pages/[platform]/build-ui/formbuilder/call-to-action/index.mdx
src/pages/[platform]/build-ui/formbuilder/customize/index.mdx
src/pages/[platform]/build-ui/formbuilder/special-inputs/index.mdx
src/pages/[platform]/build-ui/formbuilder/validations/index.mdx
src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/branch-deployments/index.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/custom-pipelines/index.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx
src/pages/gen2/how-amplify-works/concepts/index.mdx
src/pages/gen2/index.tsx
src/pages/gen2/reference/iam-policy/index.mdx
src/pages/gen2/start/mobile-support/index.mdx

Fixes videos on iOS popping out to fullscreen.

fix(main): Add playsInline to videos that should be played inline

---

src/pages/gen2/build-a-backend/add-aws-services/in-app-messaging/index.mdx
src/pages/gen2/build-a-backend/add-aws-services/rest-api/index.mdx
src/pages/gen2/build-a-backend/auth/grant-access-to-auth-resources/index.mdx
src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx
src/pages/gen2/build-a-backend/data/connect-to-API/index.mdx
src/pages/gen2/build-a-backend/functions/index.mdx
src/pages/gen2/build-a-backend/storage/index.mdx

removes parenthesis from references to "Amplify (Gen 2)" -> "Amplify Gen 2"

remove parenthesis from "Amplify (Gen 2)"

---

src/pages/gen2/build-a-backend/auth/enable-sign-up/index.mdx
src/pages/gen2/build-a-backend/auth/manage-mfa/index.mdx
src/pages/gen2/build-a-backend/auth/override-cognito/index.mdx
src/pages/gen2/build-a-backend/data/override-resources/index.mdx
src/pages/gen2/how-amplify-works/concepts/index.mdx
src/pages/gen2/index.tsx
src/pages/gen2/reference/project-structure/index.mdx
src/pages/gen2/start/manual-installation/index.mdx

remove explicit ".js" extension from gen2 resource imports

---

src/pages/gen2/build-a-backend/functions/index.mdx
src/pages/gen2/build-a-backend/storage/index.mdx

Removes the leading slash from storage access path definitions to conform to the latest validation updates.
https://github.com/aws-amplify/amplify-backend/pull/1202
Gen 2 storage
NA

remove leading slash from storage access paths

---

src/fragments/gen2/quickstart/deploy-and-host.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/branch-deployments/index.mdx

Fixed Amplify Console link to direct to the Amplify console and not the AWS Console.

Gen 2 Quickstart: Fix amplify console link

---

src/pages/[platform]/build-a-backend/push-notifications/push-notifications-migration-guide/index.mdx

This addresses a mislabeling of a snippet included in the v5 to v6 migration guide. The v5 snippet was labeled as v6 and the v6 was labeled as v5.

docs(migration): fixes mislabeling notification enable snippet

---

src/components/MDXComponents/MDXCode.tsx
src/components/MDXComponents/MDXCopyCodeButton.tsx
src/components/MDXComponents/__tests__/MDXCode.test.tsx
src/components/MDXComponents/__tests__/MDXCopyCodeButton.test.tsx

Currently, if you use the copy code button it will include the markdown comments for adding line highlighting like `//highlight-start`. This PR strips those comments from the copied code string. Additionally, moves the copy code button to it's own component and sets up some basic tests.
**To verify:**
On [this preview site page](https://fixcopycode.d2bfwhpcsj9awv.amplifyapp.com/gen2/build-a-backend/auth/manage-mfa/#configure-multi-factor-authentication-backend), click the copy code button for the code block in this section (titled "Configure multi-factor authentication backend"). Paste the code elsewhere and note that it doesn't contain the `// highlight-start` or `// highlight-end` comments in the pasted text.
Compare to [the same page on …

fix: copied code no longer includes markdown comments

---

src/pages/[platform]/build-a-backend/storage/configure-access/index.mdx
src/pages/[platform]/build-a-backend/storage/storage-v5-to-v6-migration-guide/index.mdx
src/pages/[platform]/build-a-backend/storage/transfer-acceleration/index.mdx

- Update migration docs to use path

[JS] Update migration docs to use path

---

src/fragments/lib-v1/geo/android/maps/20_display_map.mdx
src/fragments/lib/geo/android/maps/20_display_map.mdx

- Update the link to the `attrs.xml` file since it leads to a 404 now. Based off the commit history, the link to this github file was renamed: https://github.com/maplibre/maplibre-native/commits/main/platform/android/MapLibreAndroid/src/main/res/values/attrs.xml

Update github link to maplibre repo

---

src/pages/[platform]/build-a-backend/more-features/predictions/sdk/index.mdx
src/pages/[platform]/prev/build-a-backend/more-features/predictions/sdk/index.mdx

The documentation pages for `Use AWS SDK` with [Swift](https://docs.amplify.aws/swift/build-a-backend/more-features/predictions/sdk/) and [Android](https://docs.amplify.aws/android/build-a-backend/more-features/predictions/sdk/) are incorrectly referencing the analytics sections instead of the appropriate sections for predictions.
_By submitting this pull request, I confirm that my contribution is made under the terms …

fix(predictions): fix wrong reference of swfit/android predictions use aws sdk page

---

src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx

The correct DynamoDB syntax requires semicolon in both expression and expressionValues
Added a semiconlon to the code snippet for amplify/data/increment-like.js in readme file

Update amplify/data/increment-like.js syntax

---

src/fragments/gen2/quickstart/create-amplify.mdx
src/pages/gen2/build-a-backend/data/set-up-data/index.mdx
src/pages/gen2/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx
src/pages/gen2/reference/project-structure/index.mdx
src/pages/gen2/start/manual-installation/index.mdx
src/pages/gen2/start/mobile-support/index.mdx
src/pages/gen2/start/quickstart/vite-react-app/index.mdx

Gen2 backend came back to `latest` tag. Adjusting docs accordingly.
Companion PR https://github.com/aws-amplify/amplify-backend/pull/1340

use latest tag for Gen2 apps

---

src/fragments/gen2/quickstart/build-a-backend.mdx
src/pages/gen2/build-a-backend/data/connect-existing-data/index.mdx
src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx
src/pages/gen2/build-a-backend/data/custom-subscription/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/configure-custom-identity-and-group-claim/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/custom-data-access-patterns/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/multi-user-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/per-user-per-owner-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/public-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/signed-in-user-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/user-group-based-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/using-oidc-authorization-provider/index.mdx
src/pages/gen2/build-a-backend/data/data-modeling/identifiers/index.mdx
src/pages/gen2/build-a-backend/data/data-modeling/index.mdx
src/pages/gen2/build-a-backend/data/data-modeling/relationships/index.mdx
src/pages/gen2/build-a-backend/data/data-modeling/secondary-index/index.mdx
src/pages/gen2/build-a-backend/data/set-up-data/index.mdx
src/pages/gen2/start/mobile-support/index.mdx

Updated Data Gen 2 authorization rules to use the new syntax

---

src/pages/[platform]/start/getting-started/nextsteps/index.mdx

Modified link for "Serverless APIs" points to the correct URL.
The "Serverless APIs" under Next steps is redirecting to Storage category which is incorrect as the storage already has a link.
Doc Link : https://docs.amplify.aws/javascript/start/getting-started/nextsteps/
While searching on the issue, found an existing GitHub Issue : https://github.com/aws-amplify/docs/issues/6782
_By submitting this pull request, I …

Modified link for "Serverless APIs"  to point to the correct URL

---

src/components/Icons/IconTSBoxed.tsx

Cleans up some console warnings from these SVG attributes 

chore: clean up svg warnings

---

src/components/GetStartedPopover/GetStartedPopover.tsx
src/pages/[platform]/index.tsx
src/pages/gen1/[platform]/index.tsx
src/pages/gen1/index.tsx
src/pages/index.tsx

Swaps placement and color of homepage CTA buttons on `/`, `/[platform]`, `/gen1`, `gen1/platform` so that "Get Started" has primary placement and "How Amplify works" has secondary.
Staging links: 
- https://swap-cta.d1egzztxsxq9xz.amplifyapp.com/
- https://swap-cta.d1egzztxsxq9xz.amplifyapp.com/react
- https://swap-cta.d1egzztxsxq9xz.amplifyapp.com/gen1
- https://swap-cta.d1egzztxsxq9xz.amplifyapp.com/gen1/react
_By …

switch order of CTA buttons on homepage

---

src/components/GenSwitcher/GenSwitcher.tsx
src/components/GenSwitcher/__tests__/GenSwitcher.test.tsx

- Add `useCurrentPlatform` to gen switcher component so that it can use the current platform when creating the gen switcher links
https://gen-switcher-platform.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://gen-switcher-platform.d1ywzrxfkb9wgg.amplifyapp.com/
2. Change to a different platform
3. Use the gen switcher to switch to gen 1
4. Verify that the platform you selected is still selected
5. Switch back to gen 2 and verify that the same platform is still selected
_ref: MDX: …

Use current platform for gen switcher

---

src/components/FrameworkGrid/FrameworkGrid.tsx

- Update the order of the framework icons for the homepage
Staging site: https://update-homepage-icons-order.d1ywzrxfkb9wgg.amplifyapp.com/

Update order of framework icons for home pages

---

src/directory/directory.mjs
src/pages/[platform]/reference/flutter-api/index.mdx

Added the reference docs for each platform for API documentation

Add API reference docs

---

src/components/MDXComponents/MDXHeading.tsx
src/components/MDXComponents/__tests__/MDXHeading.test.tsx

Allows h2 and h3 headings to have `<code>` elements with working anchor links.
Currently, the anchor links are not being built correctly when the heading's child is a single `<code>` element; see the [h3 headings under "Additional configuration"](https://docs.amplify.aws/gen2/build-a-backend/functions/#additional-configuration). We do already have logic to loop through non-string children, but not when there is just one single child (where typeof results in `object`) They don't show up in the table of contents and don't have proper # urls.
This PR adds a check for object type when children is not a string, otherwise loops through the children (as we were before). Compare to [fixed version here](https://fixcodeheadings.d2bfwhpcsj9awv.amplifyapp.com/gen2/build-a-backend/functions/#runtime) …

fix(main): allow code elements to work in h2/h3 headings with anchor links

---

src/styles/block-switcher.scss

[Some BlockSwitcher's have really long tabs (example)](https://docs.amplify.aws/gen2/build-a-backend/data/connect-to-API/#set-authorization-mode-on-a-data-client). This makes the tablist element scrollable (it is already keyboard navigable, so keyboard users can use left/right arrow keys to navigate the list still)
[Preview fix](https://fixlongtabs.d2bfwhpcsj9awv.amplifyapp.com/gen2/build-a-backend/data/connect-to-API/#set-authorization-mode-on-a-data-client)
HTML: `<a …

fix(main): allow tablist in Blockswitcher to be scrollable

---

src/components/Layout/Layout.tsx

Adds "Gen 2" to the `<title>` element on Gen2 pages. Gen 1 already has "Gen 1" in it's title.

chore(next-release/main): add Gen 2 back to title element on Gen2 pages

---

src/components/Footer/Footer.tsx
src/components/Icons/IconXSocial.tsx
src/components/Icons/index.ts

I realize we have an IconX on next-release/main already (for a close icon) so renaming this one to avoid a conflict when we merge.

chore(main): update X icon name

---

mdx-components.tsx
src/components/MDXComponents/MDXTable.tsx
src/components/MDXComponents/__tests__/MDXTable.test.tsx
src/components/MDXComponents/index.ts
src/styles/table.scss

- Add custom component to use with MDX table so that we can wrap it in the `ScrollView` component to create a table that has the horizontal scrollbar focusable 
To test:
1. Go to https://scrollview-mdx-tables.d1ywzrxfkb9wgg.amplifyapp.com/angular/reference/cli-commands/#supported-graphql-client-code-combinations
2. Verify that you can use a keyboard `Tab` press to focus on the horizontal scrollbar for the table and use the left/right arrow keys to scroll it
HTML: `<a …

Add custom MDX table component that is wrapped in ScrollView

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/add-aws-services/pubsub/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/pubsub/publish/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/pubsub/set-up-pubsub/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/pubsub/subscribe/index.mdx

move pubsub to gen 2

---

src/pages/[platform]/build-a-backend/auth/remember-device/index.mdx

Remove extra line break for Flutter - Forget a device

Remove extra line break for Flutter - Forget a device

---

src/pages/[platform]/build-a-backend/auth/app-uninstall/index.mdx

Remove DataStore referenced in uninstall app for Swift and Android

Remove DataStore referenced in uninstall app for Swift and Android

---

src/components/PlatformNavigator/__tests__/PlatformNavigator.test.tsx
src/components/PlatformNavigator/index.tsx
src/pages/gen1/index.tsx

This PR updates the PlatformNavigator to link to the equivalent page for other platforms. That means:
- If you are on the [home page](https://maintainplatformpage.d2bfwhpcsj9awv.amplifyapp.com/) or [/gen1](https://maintainplatformpage.d2bfwhpcsj9awv.amplifyapp.com/gen1/), you'll be linked to the platform overview pages (/react or /gen1/react)
- If you are on a page that exists for all platforms, like [/[platform]/how-amplify-works](https://maintainplatformpage.d2bfwhpcsj9awv.amplifyapp.com/react/how-amplify-works/), you'll be linked to the platform specific versions of that page.
- If you are on [a page that only exists for some platforms](https://maintainplatformpage.d2bfwhpcsj9awv.amplifyapp.com/gen1/android/start/project-setup/upgrade-guide/), then those platforms will link to the …

feat: persist path on platform change when available

---

src/pages/gen2/reference/cli-commands/index.mdx

npx amplify generate config is throwing 
>>Unknown command: config
Checking the avl commands could see the following 
Generates post deployment artifacts
Commands:
amplify generate outputs               Generates amplify outputs
amplify generate forms                 Generates UI forms
amplify generate graphql-client-code   Generates graphql API code
amplify generate schema-from-database  Generates typescript data schema from a
SQL database
`npx amplify generate config` command no longer working
Was able to generate the client configuration file (such as amplifyconfiguration.json) using 
`npx amplify generate outputs`
Which platform(s) are …

Update npx amplify generate config -> outputs - Gen2 doc

---

src/pages/gen2/deploy-and-host/sandbox-environments/features/index.mdx
src/pages/gen2/deploy-and-host/sandbox-environments/setup/index.mdx

Updates the gen2 sandbox secret management docs to add more clarity on behavior. Also documents the new behavior of the `--name` argument applying to `sandbox secret` commands.
https://github.com/aws-amplify/amplify-backend/issues/1125
gen2 cli
NA

update sandbox secret management

---

src/pages/[platform]/start/getting-started/setup/index.mdx

add angular specific code snippet

---

src/pages/gen2/build-a-backend/data/connect-to-API/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/public-data-access/index.mdx
src/pages/gen2/build-a-backend/data/customize-authz/signed-in-user-data-access/index.mdx

For Gen2 JS data client, replaces references to `authMode: 'iam'` with `authMode: 'identityPool'`.
(The library changes has already been published to `@latest`)

chore(gen2): replace authMode 'iam' with 'identityPool'

---

src/components/NextPrevious/index.tsx

- Add paths to `NextPrevious` component to show next and previous buttons on gen 2 docs
- Next and previous buttons will only show on child pages that don't have children pages themselves
https://next-previous-gen2.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Visit these links:
- https://next-previous-gen2.d1ywzrxfkb9wgg.amplifyapp.com/react/build-a-backend/auth/set-up-auth/
- https://next-previous-gen2.d1ywzrxfkb9wgg.amplifyapp.com/react/build-a-backend/data/set-up-data/
- https://next-previous-gen2.d1ywzrxfkb9wgg.amplifyapp.com/react/build-a-backend/functions/define-function/
2. Verify that the next and previous buttons are working at the bottom of the page
Which product(s) are affected by this PR …

Add paths in NextPrevious component for gen2 links

---

src/fragments/lib-v1/graphqlapi/existing-resources.mdx

chore: added filter to fix broken link

---

src/pages/[platform]/reference/cli-commands/index.mdx

- updates `name` to `identifier`
- adds "Terminal" heading to code snippets
- removes line numbers from code snippets

name -> identifier for sandbox, tidy command snippet headings

---

package.json
yarn.lock

- Add resolution for `ejs`. This package is a dependency of `@aws-amplify/amplify-cli-core`, which I don't think is updated yet, https://github.com/aws-amplify/amplify-cli/blob/769211a99dd703f49e607b6e5da619204b920a4f/packages/amplify-cli-core/package.json#L45, but for now we'll manually update `ejs`

Add resolution for ejs

---

src/pages/[platform]/build-a-backend/add-aws-services/geo/configure-geofencing/index.mdx

Android and Swift libraries have support for geofences.
- Removes the **Configure a geofence collection** page for Android and Swift.

fix(geo): remove android and swift platforms from geofence page

---

src/pages/[platform]/build-a-backend/auth/customize-auth-lifecycle/custom-auth-flows/index.mdx

[Gen 2] Add the feedback for custom sign in.

---

tasks/__tests__/generate-sitemap.test.ts
tasks/generate-sitemap.mjs

- Simplifying the `lastmod` date to be an ISO string so that there aren't any invalid date errors

Fix Date for lastmod

---

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx

H3 heading on this page should be an H2

Fix a heading order on build-a-backend/auth/set-up-auth

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-bedrock/index.mdx

Adds a callout to mention region in policy statement must be one supported by Amazon Bedrock and foundation model

amazon-bedrock-region-support

---

src/fragments/lib-v1/auth/flutter/user_attributes/40_resend_code.mdx
src/fragments/lib-v1/auth/native_common/user_attributes/common.mdx
src/fragments/lib/auth/flutter/user_attributes/40_resend_code.mdx
src/fragments/lib/auth/native_common/user_attributes/common.mdx

fix: correct the sendUserAttributeConfirmationCode API name
https://github.com/aws-amplify/amplify-flutter/issues/3756

fix: correct the sendUserAttributeConfirmationCode API name

---

src/directory/directory.mjs
src/utils/globalnav.ts

- Update nav to remove link to Learn
- Add Learn to sidebar, underneath `Reference` for gen 1 site
https://update-nav.d2fsdx6say17x2.amplifyapp.com/
To test:
1. Go to https://update-nav.d2fsdx6say17x2.amplifyapp.com/gen1
2. Verify that the link to the learn site is in the sidebar underneath `Reference` for only the gen 1 site
_By submitting this pull request, I confirm that my contribution is made under the terms of …

Move Learn to sidebar for gen 1

---

src/components/MDXComponents/MDXCode.tsx
src/components/MDXComponents/__tests__/MDXCode.test.tsx

The current default is to show line numbers, this PR will update that so that `bash` code blocks will hide line numbers by default while all other languages will show them by default.

Default to hide line numbers for bash codeblocks

---

src/pages/[platform]/build-a-backend/add-aws-services/analytics/record-events/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/set-up-analytics/index.mdx

This PR addresses the following issues within the Swift Gen2 documentation for Analytics:
**Set up Amplify Analytics**
- Adding explicit mention on how to generate the `amplify_outputs.json` file and to add it to the Xcode project, otherwise Amplify will fail to configure.
- Updated instructions when selecting targets to reflect the current Xcode experience
**Record events**
- Adding code snippet to configure the `autoFlushEventsInterval` value, as we no longer support editing the old configuration file.
- Removing section about automatic submission of authentication events, as it's no longer supported and has to be done manually.
Which …

fix(Swift): Addressing some Analytics Gen2 issues

---

src/pages/[platform]/build-a-backend/add-aws-services/geo/configure-location-search/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/location-search/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/maps/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/set-up-geo/index.mdx

This PR addresses the following issues within the Swift Gen2 documentation for Geo:
- Removed unnecessary block for installation instructions, and rewrote them to be consistent with other platforms
- Added explicit instruction to generate and add the `amplify_outputs.json` file to the project.
- Fixed some outdated signatures being used
- Added missing import statement to the initialization code 
- Removed outdated UIKit code mentioning both "Stable release" (i.e. v1) and "Developer Preview" (i.e. v2) 
- Added missing `aws_region` to the backend code snippet.
- Fixed indentation in a code snippet
Which platform(s) are affected by this PR (if …

fix(Swift): Addressing some gaps in Geo Gen2 doc pages

---

src/pages/gen1/[platform]/build-a-backend/auth/admin-actions/index.mdx

Two changes are done in this PR.
1. Correctly passing access token :-
Previous :- Authorization: `${(await fetchAuthSession()).tokens.accessToken.payload}`
This is not working as expected and giving CORS error in the browser.
Updated to :- Authorization: `${(await fetchAuthSession()).tokens.accessToken}`
Working fine.
2. Correctly passing query string parameters :-
Previous :- queryStringParameters
It is not giving any error but parameters are neither visible in the request URL nor in the Lambda function.
updated to :- queryParams
Working as expected.
- [ Y] amplify-libraries
- [ Y] …

[Amplify JS Admin Actions] Correctly passing Auth header and query string parameters

---

src/pages/[platform]/build-a-backend/data/data-modeling/index.mdx

Although this example is just showing an overview of the features, I found it could be more useful if it could deploy without errors.

fix(data): customize your data model example fix

---

src/pages/[platform]/build-a-backend/functions/grant-access-to-other-resources/index.mdx

I believe I found a small typo in the docs around granting access to other resources and the environmental variables automatically created by the access property of the `define*` functions. 
In the code example it is correct, but in the narrative it is wrong referencing `myProjectFiles_BUCKET_NAME` rather then `myReports_BUCKET_NAME` as indicated in the code snippet below. 
_By submitting this pull request, I confirm …

fix: small docs typo around env var naming when granting access to other resources

---

src/pages/[platform]/start/quickstart/index.mdx

This callout is not needed as we get the user to download the outputs in the previous step: https://docs.amplify.aws/android/start/quickstart/#4-set-up-local-environment without installing any tooling.

Removed callout

---

src/components/Feedback/index.tsx

Removes some aria-labels that aren't needed.

fix: redundant aria labels

---

src/styles/algolia.scss
src/styles/base.scss
src/styles/code.scss
src/styles/feedback.scss
src/styles/gen-switcher.scss
src/styles/overview.scss
src/themes/baseTheme.ts
src/themes/gen1Theme.ts

There are some cases where our focus indicator might be a little more difficult to discern when it is used on our buttons that have a solid colored background (like the "Get started" button on the home page). This updates the focus indicator to be an outline offset by 2px across our button styles so the indicator is easier to differentiate (or fixes some instances where it just looks a little weird). In most cases it's just moving the indicator to :focus-visible and adding a 2px offset and removing the box-shadow (in favor of outline).
Updates are mostly visible for:
- Skip to main link
- Get started buttons/popover triggers
- Copy code button at the top of code blocks
- the Feedback yes/no buttons
- Anywhere an Amplify UI button style is used …

chore: minor improvements to focus state

---

src/fragments/lib-v1/auth/android/signin/20_confirmSignUp.mdx
src/fragments/lib-v1/auth/android/signin/30_signIn.mdx
src/fragments/lib-v1/auth/common/mfa/flows.mdx
src/fragments/lib-v1/auth/flutter/access_credentials/10_fetchAuthSession.mdx
src/fragments/lib-v1/auth/flutter/managing_credentials/10_managing_credentials.mdx
src/fragments/lib-v1/auth/ios/signin/20_confirmSignUp.mdx
src/fragments/lib-v1/auth/ios/signin/30_signIn.mdx
src/fragments/lib-v1/auth/native_common/access_credentials/common.mdx
src/fragments/lib-v1/auth/native_common/signin/common.mdx
src/fragments/lib-v1/auth/native_common/signout/common.mdx
src/fragments/lib/auth/flutter/signin_web_ui/10_cli_setup.mdx

chore(flutter) v2 auth fixes

---

src/fragments/lib-v1/datastore/native_common/getting-started.mdx
src/fragments/lib-v1/storage/flutter/copy.mdx
src/fragments/lib-v1/storage/flutter/get-properties.mdx
src/pages/gen1/[platform]/prev/build-a-backend/storage/copy/index.mdx
src/pages/gen1/[platform]/prev/build-a-backend/storage/get-properties/index.mdx

chore: flutter v2 storage fixes

---

src/pages/[platform]/build-a-backend/troubleshooting/index.mdx

Added flutter, android, and swift to platforms list on `[platform]/build-a-backend/troubleshooting/index.mdx` as the addition of [this page](https://docs.amplify.aws/swift/build-a-backend/troubleshooting/stack-cdktoolkit-already-exists/) for all platforms introduced a broken breadcrumb link for flutter, android, and swift.
_By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: add platforms to [platform]/build-a-backend/troubleshooting

---

src/pages/[platform]/build-a-backend/data/customize-authz/index.mdx
src/pages/[platform]/build-a-backend/data/customize-authz/multi-user-data-access/index.mdx
src/pages/[platform]/build-a-backend/data/customize-authz/per-user-per-owner-data-access/index.mdx
src/pages/[platform]/build-a-backend/data/customize-authz/public-data-access/index.mdx
src/pages/[platform]/build-a-backend/data/customize-authz/signed-in-user-data-access/index.mdx
src/pages/[platform]/build-a-backend/data/customize-authz/user-group-based-data-access/index.mdx

A few more Swift code snippets under Data sections

fix(data): swift code snippets for customize auth

---

src/pages/[platform]/build-a-backend/functions/grant-access-to-other-resources/index.mdx

Fix sample code of [Grant access to other resources](https://docs.amplify.aws/react/build-a-backend/functions/grant-access-to-other-resources/). `'/reports/*'` -> `'reports/*'` 
Current sample code returns error when grant storage access to functions.
When adding authorization rule, s3 path must not start with "/".
https://docs.amplify.aws/react/build-a-backend/storage/authorization/
N/A
_By submitting this pull …

function: delete unnecessary "/" when authorize for storage access

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/server-side-rendering/nuxt/index.mdx

Ported the Nuxt 3 doc from the Gen1 section with:
1. Replaced `amplifyconfiguration.json` with `amplify_outputs.json`
2. Replaced Gen1 GraphQL client with Gen2 Typebeast Data client
3. Updated Storage example to use the new `path` parameters instead of `accessLevel`
4. Some minor cleanups 
5. Removed the accordion wrappers from code examples (feedback from @josefaidt) …

chore: add Gen2 specific doc for using SSR adapter with Nuxt 3

---

.github/CODEOWNERS

chore: updated codeowners file for new structure

---

src/pages/[platform]/build-a-backend/auth/modify-resources-with-cdk/index.mdx

closes: https://github.com/aws-amplify/amplify-backend/issues/1511

update custom attribute and password policy example

---

src/fragments/lib/auth/ios/signout/10_local_signout.mdx
src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-out/index.mdx

Print statement has syntax error in `signOutLocally()`
https://docs.amplify.aws/gen1/swift/build-a-backend/auth/sign-out/
https://github.com/aws-amplify/amplify-swift/issues/3711

fix(swift): update signout code snippet

---

src/components/Layout/LayoutHeader.tsx

Add a transform function to remove pageMain anchor tags from search results
The result can be seen in https://next-docs.amplify.aws/

remove pageMain anchor from search results

---

src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx
src/pages/[platform]/build-a-backend/storage/data-usage/index.mdx
src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/[platform]/build-a-backend/storage/extend-s3-resources/index.mdx
src/pages/[platform]/build-a-backend/storage/index.mdx
src/pages/[platform]/build-a-backend/storage/lambda-triggers/index.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx
src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
src/pages/[platform]/build-a-backend/storage/use-aws-sdk/index.mdx

chore: remove "gen 2 not available" banners for flutter storage

---

src/pages/[platform]/build-a-backend/functions/set-up-function/index.mdx

Affected URL is https://docs.amplify.aws/angular/build-a-backend/functions/set-up-function/
The hander definition previously didn't include a type so the "npx ampx sandbox" compilation would fail and say: amplify/functions/say-hello/handler.ts(1,31): error TS7006: Parameter 'event' implicitly has an 'any' type. TypeScript validation check failed.
Resolution: Fix the syntax and type errors in your backend definition.
- [ X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE. …

Documentation - Resolve Typescript validation check failed

---

.github/workflows/check_for_console_errors.yml

Update console error check workflow to use environment variable instead of repo var.  This is to address the issue of PRs from forked repos not being able to access `vars`

use Environment variable for BUILD_DIR in error check

---

src/pages/[platform]/start/account-setup/index.mdx

Clarify that bootstrapping in the console must be performed by an account admin. I left a comment on the only line that has content changes. Everything else is automatic linting changes.
fixes: https://github.com/aws-amplify/docs/issues/7520
Gen 2 console bootstrap

fix: clarify root user signin for bootstrap

---

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
src/pages/[platform]/start/quickstart/index.mdx

1. Updated the documentation to add the required flag ` --outputs-version 0` by default to the command snippet for the Flutter docs. 
2. Updated the documentaion to include the explanation in closer proximity to the command.
3. Correct a typo in the command which from `--config-format dart` to `--outputs-format dart`
Preview of changes:
<details>
```bash title="Terminal" showLineNumbers={false}
npx ampx sandbox --outputs-format dart --outputs-out-dir lib --outputs-version 0
```
</details>
_ref: MDX: …

fix(Flutter): Added required flags to sandbox command when using Flutter

---

src/pages/[platform]/build-a-backend/data/customize-authz/index.mdx

rename `userPools` to `userPool`

---

src/pages/[platform]/build-a-backend/functions/examples/dynamo-db-stream/index.mdx

typo: wrong file name description from `amplify/functions/dynamoDB-function/resource.ts` to `amplify/functions/dynamoDB-function/handler.ts`

typo: wrong file name description in dynamoDB-function's docs

---

src/pages/[platform]/build-a-backend/data/customize-authz/index.mdx

Add a note that Amplify `@auth` directive is not fully supported on custom types.
NA
NA

docs(api): add auth directive limitation on custom types

---

src/pages/[platform]/build-a-backend/data/connect-from-server-runtime/nuxtjs-server-runtime/index.mdx

The Nuxt server run time shows `Amplify.configure(config...` this should be the outputs file that is imported in.
- [] amplify-cli
- [] amplify-ui
- [] amplify-studio

fix: Nuxt Server Run Time has wrong outputs file

---

package.json
tasks/count-gen2pages.mjs

Adds a small script to make counting canonical Gen2 pages easier.
Run `yarn countGen2` after running `yarn build`

chore: add utility to count gen2 pages in sitemap

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/index.mdx
src/pages/[platform]/start/platform-setup/index.mdx
src/pages/[platform]/start/quickstart/index.mdx

(fix) quickstart: Fix Flutter Quickstart Guide

---

src/components/MDXComponents/MDXCode.tsx
src/components/MDXComponents/__tests__/MDXCode.test.tsx

Update codeblock to throw if the codestring is an empty string.

throw error on empty code block

---

src/pages/[platform]/build-a-backend/functions/configure-functions/index.mdx

Changes the h3 headings to h2 headings.

fix: heading order on Configure Functions page

---

package.json
yarn.lock

re: https://github.com/aws-amplify/docs/security/dependabot/69
`ip` does not seem to be a dependency for any of the packages the docs site uses. I'm not seeing any issues in the staging site having removed it.
staging: https://dependabot-69.d1egzztxsxq9xz.amplifyapp.com/react/

remove ip package to resolve dependabot issue

---

src/components/GlobalNav/components/icons/ExternalLink.tsx

Cleans up the following warning during build about unexpected any type.

fix: unexpected any in GlobalNav component

---

src/fragments/lib-v1/push-notifications/react-native/getting_started/40_install_lib.mdx
src/fragments/lib-v1/push-notifications/react-native/migrate-from-previous-version.mdx

fix(js): Add 1.1.x version for js React Native v5 push notification

---

src/components/BlockSwitcher/BlockSwitcher.tsx
src/components/BlockSwitcher/__tests__/BlockSwitcher.test.tsx
src/fragments/lib/geo/ios/getting_started/30_install_lib.mdx
src/fragments/lib/graphqlapi/ios/optimistic-ui.mdx
src/fragments/lib/graphqlapi/ios/working-with-files.mdx
src/fragments/lib/logging/common/setup_logging/setup_logging.mdx
src/pages/[platform]/build-a-backend/add-aws-services/logging/set-up-logging/index.mdx
src/pages/gen1/[platform]/tools/cli/migration/lazy-load-custom-selection-set/index.mdx
src/pages/gen1/[platform]/tools/cli/migration/list-nullability/index.mdx

Throw error when BlockSwitcher only has a single block
staging site: https://blockswitcher.dmhjrabi3pkql.amplifyapp.com

Throw error when BlockSwitcher only has a single block

---

src/pages/[platform]/start/account-setup/index.mdx

Added additional information for local setup instructions. After talking to a few customers they get confused and think they must login with their email, which is wrong. They should log in with `amplify-admin` instead. I added a clarification to the setup instructions.

Added additional updates to setup instructions

---

src/pages/[platform]/build-a-backend/data/connect-from-server-runtime/nuxtjs-server-runtime/index.mdx

A customer noticed that `getCurrentUser` was only defined on the server in the Nuxt server guide and not in the client file. This fixes that.

Add getCurrentUser to client Nuxt Server Guide

---

src/pages/[platform]/build-a-backend/auth/use-aws-sdk/index.mdx

add auth escape hatch docs for android

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/troubleshooting/build-env-module/index.mdx
src/pages/[platform]/build-a-backend/troubleshooting/cannot-find-module-amplify-env/index.mdx

adds troubleshooting page on frontend build error 
closes:https://github.com/aws-amplify/docs/issues/7657

adds `Cannot find module $amplify/env/<function-name>` troubleshooting doc

---

src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-http-api/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx

updates api example and permissions

updates REST API examples and scopes permissions

---

Readme.md

Updated the README file to set the Node.js version requirement to >=18.17.0 and <22.0.0. This change ensures compatibility with the "next": "^14.2.3" specified in package.json. Node.js version 18.17.0 or later is required to support the features used in this project, and versions below 22.0.0 are recommended due to the deprecation of import assertions in Node.js 22 and later. The deprecation of import assertions is documented in the following commit: [nodejs/node@25c79f3331](https://github.com/nodejs/node/commit/25c79f3331).
**Please add the product(s)/platform(s) affected to the PR …

Update README to reflect new Node.js version requirements

---

src/pages/gen1/[platform]/build-a-backend/functions/secrets/index.mdx

Updated Amplify doc to add sdk v3 code

---

src/directory/directory.mjs
src/pages/[platform]/start/connect-existing-aws-resources/index.mdx
src/pages/[platform]/start/libraries-standalone/index.mdx

add page for using libraries without Amplify backend

---

src/pages/[platform]/build-a-backend/data/subscribe-data/index.mdx

Fixes the accessibility violations on this page related to heading order. Noticed they were failing in this run: https://github.com/aws-amplify/docs/actions/runs/9504729443/job/26198027563?pr=7738

fix: heading order on subscribe-data page

---

src/pages/[platform]/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx
src/pages/[platform]/deploy-and-host/fullstack-branching/monorepos/index.mdx

Adds instructions for sharing `Schema` type between frontend and backend apps

feat: add instructions for sharing schema type between apps

---

src/components/MDXComponents/MDXTable.tsx

Adds missing region role to the scrollable table.

chore(a11y audit): add region to scrollable table

---

src/fragments/lib/project-setup/native_common/prereq/common_header.mdx

Gen1 docs suggests an older version of node. This change updates our [Set Up Amplify Prerequisites ](https://docs.amplify.aws/javascript/start/project-setup/prerequisites/)sections to display the proper version of node (as seen in the [v5 to v6 migration guides](https://docs.amplify.aws/nextjs/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/#step-1-upgrade-your-dev-environment)).
- https://github.com/aws-amplify/docs/issues/7156
- https://github.com/aws-amplify/amplify-js/issues/13155
_ref: MDX: …

fix: update node and npm versions for gen 1 docs

---

src/fragments/lib-v1/android-maintenance.mdx
src/fragments/lib-v1/ios-maintenance.mdx

update maintenance mode messaging to deprecated for swift and android

---

package.json
yarn.lock

Address dependabot for braces package

chore: add resolution for braces

---

package.json
yarn.lock

Addresses https://github.com/aws-amplify/docs/security/dependabot/72

chore: add resolution for ws

---

src/utils/track.ts

Recently we made a change to only load analytics scripts in production and staging environments. However, we didn't add a check for that in our track utility so in local/development environments, actions which called this utility would throw an error:
Production should have been unaffected since we are loading the script there (or any environments set to staging)
This adds a check for AWSMA before calling the track functionality. Additionally, I removed some of the old search tracking events that were copied over from the old docs version since we no longer use them.
**Verification**
To test, open any of the Accordion elements ([like this one](https://fixtracklocalerror.d2bfwhpcsj9awv.amplifyapp.com/nextjs/start/quickstart/nextjs-pages-router/#3-view-deployed-app)), or click the Copy …

fix: check if AWSMA exists before tracking metric

---

src/components/GenSwitcher/GenSwitcher.tsx
src/components/GetStartedPopover/GetStartedPopover.tsx
src/components/GetStartedPopover/__tests__/GetStartedPopover.test.tsx
src/components/PlatformNavigator/__tests__/PlatformNavigator.test.tsx
src/components/PlatformNavigator/index.tsx
src/components/Popover/PopoverList.tsx
src/components/Popover/__tests__/Popover.test.tsx

Recommendation was that we can remove the unneeded nav role from the Popover component and the corresponding aria-label.
Also updates tests. I added the ability to pass a testId down to GetStarted dropdown and PlatformNavigator since we can no longer query that element by role.

chore(a11yaudit): remove unneeded nav/aria-label from Popover

---

src/fragments/lib-v1/push-notifications/android/getting_started/fcm-cli-resources.mdx
src/fragments/lib-v1/push-notifications/android/setup_push_service/setup-fcm.mdx
src/fragments/lib-v1/push-notifications/common/getting_started/getting-started.mdx
src/fragments/lib/push-notifications/android/getting_started/fcm-cli-resources.mdx
src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx
src/fragments/lib/push-notifications/common/getting_started/getting-started.mdx
src/fragments/sdk/push-notifications/android/getting-started.mdx
src/fragments/sdk/push-notifications/android/setup-fcm.mdx

chore(push): Update fcm setup instructions

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

removes callout for `domainPrefix` in auth docs. this has since been removed in favor of generating it automatically
#7546

rm stale auth domainPrefix callout

---

src/components/BlockSwitcher/BlockSwitcher.tsx

…eck for aria-controls
This PR adds a utility function to convert tab "names" to valid values for underlying `aria-controls` attributes that are added with the UI primitives.
```
Fix all of the following:
Invalid ARIA attribute value: aria-controls="Facebook Login-panel"
```
https://github.com/aws-amplify/docs/actions/runs/9589449155/job/26443227531?pr=7747
Instead of 
```
Facebook Login-panel
```
it will be
```
facebook-login-panel
```
this also updates the ID value in the panel element
```
<div role="tabpanel" id="Facebook Login-panel" aria-labelledby="Facebook Login-tab" class="amplify-tabs__panel amplify-tabs__panel--active">
```
Which …

add a utility to convert tab names with spaces to dashes, fix a11y check for aria-controls

---

cspell.json
src/fragments/lib/datastore/flutter/getting-started/20_installLib.mdx
src/fragments/lib/project-setup/flutter/platform-setup/android.mdx
src/fragments/lib/project-setup/flutter/platform-setup/ios.mdx
src/fragments/lib/project-setup/flutter/platform-setup/macos.mdx
src/pages/[platform]/start/platform-setup/index.mdx

- Update the android section of the getting started guide to reflect the correct versions of gradle, AGP, Java, xcode
- Update the Gen 2 guide
Updated Docs for Android

chore(flutter): update android section of Amplify Flutter getting started guide

---

src/pages/[platform]/start/quickstart/index.mdx

- updates prose with segue to guide
- updates link to guide for mobile quickstarts
#7741

update mobile quickstarts with link to fullstack branch deployment guide #7741

---

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
src/pages/gen1/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx

Add a callout regarding the next build error:
```
./node_modules/@aws-amplify/core/node_modules/@aws-crypto/sha256-js/build/module/index.js + 12 modules
Cannot get final name for export 'fromUtf8' of ./node_modules/@smithy/util-utf8/dist-es/index.js
```
and the recommended solution to resolve this error.
https://github.com/aws-amplify/amplify-js/issues/12856 …

chore: add serverComponentsExternalPackages callout for Next.js

---

src/pages/gen1/[platform]/tools/cli/reference/files/index.mdx

add warning callout to gen1 backend-config

---

src/fragments/lib-v1/graphqlapi/flutter/subscribe-data.mdx
src/fragments/lib-v1/graphqlapi/ios/subscribe-data.mdx
src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
src/fragments/lib/graphqlapi/ios/subscribe-data.mdx

Tested these pages manually since the headings are in fragments (which means they won't show in this PRs a11y run). The other platforms for these pages did not have violations.
http://localhost:3000/gen1/swift/build-a-backend/graphqlapi/subscribe-data/
http://localhost:3000/gen1/flutter/build-a-backend/graphqlapi/subscribe-data/
http://localhost:3000/gen1/swift/prev/build-a-backend/graphqlapi/subscribe-data/
http://localhost:3000/gen1/flutter/prev/build-a-backend/graphqlapi/subscribe-data/
_ref: MDX: …

fix: heading order on gen1/prev subscribe-data page

---

src/components/FeatureFlags/feature-flags.json

Set correct default value for `subscriptionsInheritPrimaryAuth`
N/A

fix subscriptionsInheritPrimaryAuth default value

---

src/components/Overview/Overview.tsx

Changed Overview card titles from `<Text>` tags to `<Heading>` tags. Overview card headings still do not show up in the table of contents because they are not included [here](https://github.com/aws-amplify/docs/blob/0cee76eeebd43a311055cef61ce03d95ebc69da0/src/components/Layout/Layout.tsx#L133C1-L134C1) because they are nested within the Overview component.
staging: https://a11y-overviewheadings.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/auth/concepts/
HTML: `<a …

a11y - use headings for Overview cards

---

src/components/MDXComponents/MDXCopyCodeButton.tsx

Removed conditional in `MDXCopyCodeButton.tsx` >> `aria-describedby={codeId}`

a11y - always use aria-describedby for Copy code button

---

src/pages/[platform]/build-a-backend/functions/set-up-function/index.mdx

updates "set up a Function" guide with examples for using Functions as handlers for custom queries and mutations with the data client and schema builder experience

update set up function guide with data example

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx
src/pages/[platform]/build-a-backend/auth/connect-your-frontend/switching-authentication-flows/index.mdx

This commit restores the following missing docs from Gen 1 to Gen 2
- `autoSignIn` section from `SignIn` page
- `Switching Authentication Flows` page

chore(js): restore missing gen1 documents

---

src/pages/[platform]/build-a-backend/storage/list-files/index.mdx

Add documentation for the `subpathStrategy` option in amplify-js.

feat(js): list api subpathStrategy parameter

---

src/pages/gen1/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx
src/styles/base.scss

Fixes a broken in-page anchor link. Adds scroll-margin to h4 headings 
Fixes: https://github.com/aws-amplify/docs/issues/6675

Fix: anchor link on data-modeling, add some scroll margin to h4 headings

---

src/pages/[platform]/build-a-backend/data/data-modeling/index.mdx
src/pages/[platform]/start/migrate-to-gen2/index.mdx

Document usage of string GraphQL SDL schema in Gen 2.
N/A

Add Gen 2 SDL docs

---

src/pages/[platform]/build-a-backend/auth/grant-access-to-auth-resources/index.mdx

add auth permissions from https://github.com/aws-amplify/amplify-backend/pull/1557

add auth permissions

---

cspell.json
src/pages/[platform]/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx

Clarified that environment variables need to be manually loaded using a library such as dotenv in both local and sandbox environments. Updated the documentation to reflect that the .env.local file is not automatically loaded in a sandbox environment.
- https://github.com/aws-amplify/amplify-backend/issues/1460#issuecomment-2101591095
- #7556
_By submitting this pull request, I confirm that my contribution is made under …

Clarify Manual Loading of Environment Variables in Sandbox Environments

---

src/pages/[platform]/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/index.mdx

changes callout for default env name to SCREAMING_SNAKE_CASE
`amplifyData_GRAPHQL_ENDPOINT` -> `AMPLIFY_DATA_GRAPHQL_ENDPOINT`
fixes #7825 

fix data env name in function example, ref #7825

---

src/pages/[platform]/reference/cli-commands/index.mdx

This PR updates the app id reference for the `pipeline-deploy` and `generate forms` commands. If customers use these existing commands as it is, the deployment on hosting will fail with an error because it is undefined. Amplify Hosting has [certain env vars](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables) accessible by default and `$AWS_APP_ID` is to access the app id for the current build.
N/A
- [ x ] Does this PR conform to [the …

Update app id reference for CI/CD deployments

---

src/fragments/lib/storage/ios/list.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx

This PR updates the Swift documentation for `Storage.list` with the new `SubpathStrategy` option parameter, as well as clarifying how the path is meant to be used.
Both Gen1 and Gen2 pages are updated, since the feature is supported on either backend. 

feat(Swift): Adding SubpathStrategy documentation for Storage.List

---

src/components/Callout/Callout.tsx
src/components/Callout/__tests__/Callout.test.tsx
src/components/Gen1Banner/Gen1Banner.tsx
src/components/Gen1Banner/index.ts
src/components/Layout/Layout.tsx

Adding a banner to gen1 getting started pages directing users to gen2
staging site: https://gen1banner.dmhjrabi3pkql.amplifyapp.com/gen1/react/start/getting-started/introduction/

Add Gen1 banner to getting started pages

---

src/components/Accordion/Accordion.tsx
src/components/Accordion/__tests__/Accordion.test.tsx

[Issue] When the user activates the "Close accordion" control to close  the accordion, which is located at the end of the opened accordion, the focus is shifted to the top of the page inappropriately.
[Fix] Re-focus on summary element when the "Close accordion" control is clicked.
To see current behavior: 
- Go to live docs: https://docs.amplify.aws/react/start/quickstart/#3-view-deployed-app
- Open accordion
- Scroll to bottom of accordion
- Click the close button at the bottom of the accordion
- In console, check focus after click (`document.activeElement`)
To test manually: 
- Go to staging: https://a11y-accordion-focus.d1egzztxsxq9xz.amplifyapp.com/react/start/quickstart/#3-view-deployed-app
- Open accordion
- Scroll to bottom of accordion
- Click the close button at the bottom of the …

a11y-when closing accordion from bottom, focus back on summary element

---

src/components/Feedback/index.tsx

[Issue]  When the user activates "Yes/No" in the "Was this  helpful?" section, the content that gets updated is not conveyed to the  screen reader user.  
[User Impact]  Screen reader users will be unaware of important updates to this content  when they occur.  
[Fix] Make feedback responses part of an aria-live area
To test manually: 
- Turn on screen reader (for Mac, System Settings > Accessibility > VoiceOver)
- Go to staging site: https://a11y-feedback-component.d1egzztxsxq9xz.amplifyapp.com/
- Keyboard navigate to the Feedback Component in the left nav
- Select "Yes" or "No" and make sure the response text ("Thank you for your feedback" or "Can you provide more details") is audibly read by the screenreader. 
**If this PR should not be merged upon approval for any reason, please …

a11y-feedback component should announce updates

---

src/components/MDXComponents/MDXHeading.tsx
src/components/MDXComponents/__tests__/MDXHeading.test.tsx
src/styles/base.scss

[Issue] After activating bookmark links present below the heading text "On this page" screen reader focus shifts to the top of the page.
[Fix] Added tabindex and :focus-visible to in-content headings.
To see current behavior: 
- Go to https://docs.amplify.aws/react/how-amplify-works/concepts/
- Click on a heading in the table of contents (i.e. Faster local development)
- In console, check element in focus (`document.activeElement`) and note that focus is on `body`
To test manually: 
- Go to https://a11y-heading-focus.d1egzztxsxq9xz.amplifyapp.com/react/how-amplify-works/concepts/
- Click on a heading in the table of contents (i.e. Faster local development)
- In console, check element in focus (`document.activeElement`) and confirm that focus is on the corresponding heading in the docs …

a11y-when clicking on toc entry, focus on respective heading in content

---

src/pages/[platform]/build-ui/formbuilder/customize/index.mdx
src/pages/[platform]/build-ui/formbuilder/validations/index.mdx

remove studio references in Gen 2 docs and updates the heading to be unique 
closes: https://github.com/aws-amplify/docs/issues/7852

remove studio reference in Amplify Gen 2 docs

---

package.json
yarn.lock

Updated resolution field for `fast-xml-parser`
https://github.com/aws-amplify/docs/security/dependabot/73

chore(dependabot): Add resolution for fast-xml-parser

---

src/fragments/lib/push-notifications/common/getting_started/cross-platform-prereq.mdx

Adding a snippet to flutter push notifications set up so users use the correct version of gms:google-services.
https://github.com/aws-amplify/amplify-flutter/issues/5119

chore(flutter): added push notifications snippet for updated settings.gradle file

---

src/pages/[platform]/build-ui/figma-to-code/index.mdx

add non-dev mode info to figma to react docs

---

src/components/PlatformNavigator/index.tsx

Add an id to Popover.Trigger and update the aria-describedby to use that id, in addition to platformNavigatorLabel 
Staging: https://a11y-platform-nav.d1egzztxsxq9xz.amplifyapp.com/

a11y- In PlatformNavigator, update aria-describedby to aria-labelledby  

---

cspell.json
src/pages/[platform]/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/index.mdx

removed hyphen from the logGroupName

fix: removed hyphen from the logGroupName

---

package.json
yarn.lock

* Axios is updated to use at least version 1.7.4
* This is needed because versions 1.3.2 through 1.7.3 contained safety vulnerabilities, which version 1.7.4 patches
[Server-Side Request Forgery in axios](https://github.com/aws-amplify/docs/security/dependabot/74)

chore(dependabot): Update Axios dependency to use new safe version

---

src/pages/[platform]/reference/permissions-boundary/index.mdx

The previous commend is not accurate as the [cdk docs](https://docs.aws.amazon.com/cdk/v2/guide/customize-permissions-boundaries.html#customize-permissions-boundaries-how-apply). Customer suggested to change.

update cdk bootstrap cmd

---

src/fragments/lib/auth/common/device_features/common.mdx
src/pages/[platform]/build-a-backend/auth/concepts/multi-factor-authentication/index.mdx
src/pages/gen1/[platform]/build-a-backend/auth/manage-mfa/index.mdx

We're getting reports that customers are confused about device tracking in MFA context.
It has been proven via two independent experiments that device tracking and MFA suppression work fine if login mechanism is `email`. Additionally none of cognito docs state such limitation.
Therefore we remove confusing and untrue statement from docs.
_By submitting this pull request, I confirm that my contribution is made under the …

Remove untrue claim about device tracking

---

src/pages/[platform]/build-a-backend/auth/manage-users/manage-devices/index.mdx

adding docs for fetchCurrentDevice API

Feat (Auth): added docs for fetchCurrentDevice API

---

src/pages/[platform]/build-a-backend/functions/grant-access-to-other-resources/index.mdx

Update documentation to clarify the usage of environment variable names in Amplify Gen 2. Specifically, update the environment variable references to use all caps with underscores. Creating a Next.JS Amplify Gen 2 application I noticed the automatically generated environment variable in the documentation **env.myReports_BUCKET_NAME** is not what is actually generated. What is actually generated is **env.MY_REPORTS_BUCKET_NAME** . Here is a failed Amplify Gen 2 branch deployment that shows this exact issue (with a different bucket name, but same concept).
`
2024-06-19T02:00:06.866Z [INFO]: amplify/functions/dynamodb-perform-search/handler.ts(20,17): error TS2551: Property 'mySearchResults_BUCKET_NAME' does not exist on type 'LambdaProvidedEnvVars & AmplifyBackendEnvVars'. Did you mean …

fix: update handler to use correct environment variable format

---

src/fragments/lib/auth/common/mfa/add_mfa.mdx
src/fragments/lib/auth/common/mfa/update_mfa.mdx
src/pages/gen1/[platform]/build-a-backend/auth/manage-mfa/index.mdx

Fixed heading order accessibility error

fix heading levels

---

src/pages/[platform]/build-a-backend/functions/set-up-function/index.mdx

`.default` is not working as expected for custom query/mutation arguments. There is an issue filed to track https://github.com/aws-amplify/amplify-category-api/issues/2802
In the meantime, this removes the reference to use `.default()` in the arguments block for setting up a function behind data

rm .default() in argument for set up function guide

---

customHttp.yml
src/pages/_document.tsx

This reverts commit a11a9e0af4962c81fdc5fb81d171dd868c1d1c69.
Revert csp changes that resulted in blocked scripts

Revert "Update headers and CSP value (#7904)"

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx

adds snippet for confirming sign in
closes #7782

add confirm sign in snippet #7782

---

src/fragments/lib-v1/geo/js/search.mdx
src/fragments/lib/geo/js/search.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/location-search/index.mdx

updating links to point to the new api docs for maplibre

update maplibre options links

---

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx

Add documentation for specifying custom SSL CA certificate bundle for SQL Lambda data sources.
- https://github.com/aws-amplify/amplify-backend/pull/1696
This should not be submitted until https://github.com/aws-amplify/amplify-backend/pull/1696 is released.

feat: custom SSL CA support for SQL data sources

---

src/fragments/lib-v1/analytics/android/existing-resources.mdx
src/fragments/lib-v1/analytics/flutter/existing-resources.mdx
src/fragments/lib-v1/analytics/ios/existing-resources.mdx
src/fragments/lib/analytics/android/existing-resources.mdx
src/fragments/lib/analytics/flutter/existing-resources.mdx
src/fragments/lib/analytics/ios/existing-resources.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/existing-resources/index.mdx

- update the anlaytics' use existing aws resources page to add a section for updating iam policy for flutter and natives. this section has already existed for js but was missing for flutter and natives.
https://github.com/aws-amplify/amplify-flutter/issues/5356

fix(analytics): add update iam policy section to existing resources page for flutter and natives

---

yarn.lock

- https://github.com/aws-amplify/docs/security/dependabot/75

fix(dependabot): update yarn.lock for micromatch version to 4.0.8

---

src/fragments/lib-v1/push-notifications/react-native/getting_started/expo-callout.mdx
src/fragments/lib/push-notifications/react-native/getting_started/expo-callout.mdx

Update the callout to specify not supporting EXPO GO only

Update callout warning for RN Push Notification

---

src/pages/[platform]/build-a-backend/functions/scheduling-functions/index.mdx

Fixed a missing parameter error in the EventBridgeHandler example code on the Scheduled Functions documentation page
fixes #7939 

Fixed a missing parameter error in the EventBridgeHandler example code on the Scheduled Functions documentation page

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

fix typo in backend auth sample. See the actual prop name https://github.com/aws-amplify/amplify-backend/blob/b2464ab051a1e4b8380fda8ebd911a610d64ac6e/packages/auth-construct/API.md?plain=1#L123

fix typo in backend auth sample

---

src/components/Callout/Callout.tsx
src/components/Callout/__tests__/Callout.test.tsx
src/components/Icons/IconWarning.tsx
src/components/Icons/index.ts
src/protected/ProtectedRedactionMessage/__tests__/__snapshots__/ProtectedRedactionMessage.test.tsx.snap

[Issue] There are meaningful "Info" icons but they are marked as decorative.
[Fix] Since the icon is part of Amplify UI component we cannot remove the aria-hidden without updating that component. We could move those icons inline to the content (and use hasIcon={false} on the component)
Staging: https://a11y-callout-icons.d1egzztxsxq9xz.amplifyapp.com/gen1/react/start/getting-started/
Example of page with protected callout: https://a11y-callout-icons.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/data/data-modeling/relationships/
**Please add the product(s)/platform(s) affected to …

a11y- Callouts should use descriptive text for icons

---

src/pages/[platform]/build-a-backend/functions/examples/dynamo-db-stream/index.mdx

fix dynamodb lambda stream setup 
* https://github.com/aws-amplify/amplify-backend/issues/1552
* https://github.com/aws-amplify/amplify-backend/issues/1594

fix dynamodb lambda stream setup

---

src/components/ApiDocs/display/TypeLink.tsx
src/styles/reference.scss

- Updates TypeLink to use a button (links with no href are not keyboard navigable), some styling updates for hover/focus
- Prettier'ed the css file

chore(api-docs-template): update TypeLink to use a button

---

src/components/ApiDocs/display/ApiModal.tsx
src/components/ApiDocs/display/ApiModalBreadcrumbs.tsx
src/components/ApiDocs/display/TypeLink.tsx
src/styles/reference.scss

- Adds some initial typing to ApiModal
- Moves breadcrumb related markup to its own component file
- Update styling
https://github.com/user-attachments/assets/5d62f11b-5539-4d55-996d-e0f369afc056

chore(api-docs-template): Update ApiModal styling/markup. Move breadcrumbs to ApiModalBreadcrumbs

---

src/pages/[platform]/build-a-backend/data/subscribe-data/index.mdx

Adds a troubleshooting accordion under the real-time data (observeQuery) section, explaining why data might appear to be "missing" from real-time updates with tips to resolve.
https://github.com/aws-amplify/amplify-js/issues/13267

Add troubleshooting for missing real-time event data

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx
src/pages/gen1/[platform]/build-a-backend/auth/add-social-provider/index.mdx

Adds two similar sections on using the new parameter on `signOut` API to both React Native and Web filters to the "Add social provider sign-in" section of the documentation. This change is to support the [feature release](https://github.com/aws-amplify/amplify-js/pull/13512) in Amplify JS.
-

chore: add information about the new signOut redirect url option

---

src/directory/generateDirectory.mjs

updating genereateDirectory script to also add in the api reference pages

update to generateDirectory to add api reference pages

---

src/utils/getApiStaticPath.ts

add getApiStaticPath util function

add getApiStaticPath util function

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/auth/connect-your-frontend/switching-authentication-flows/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/custom-auth-flows/index.mdx

Added an example page for setting up custom-auth-flows

---

src/pages/[platform]/build-a-backend/functions/environment-variables-and-secrets/index.mdx

adds an explainer for how the function env files are generated

add explainer for function env file generation

---

package.json
yarn.lock

* Removed dev dependency `serve`
* `serve` is not being used in repository
* Resolves a security vulnerability reported by dependabot for `path-to-regexp`
* Has been included via `serve` -> `serve-handler` -> `path-to-regexp`
https://github.com/aws-amplify/docs/security/dependabot/77

fix(security): Remove serve dev dependency

---

src/pages/[platform]/build-a-backend/ai/concepts/tools/index.mdx

Adds initial structure and content for `ai/concepts/tools` page.

docs(ai): add ai/concepts/tools page

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/index.mdx

Adds documentation for async function handlers.

docs(data): add async function handlers section to custom queries and mutations page

---

src/styles/code.scss

Long words like "AmplifyBackendDeployFullAccess" can get cut off on 320px viewport sizes.
example: https://docs.amplify.aws/react/start/account-setup
staging: https://a11y-long-words.d1egzztxsxq9xz.amplifyapp.com
page: /react/start/account-setup

a11y- fix cutoff words in viewports under 320px

---

src/pages/[platform]/start/account-setup/index.mdx

I added a YouTube video on the AWS for local development page

feat(local setup): Added a video to configure AWS for local development page

---

src/pages/[platform]/build-a-backend/auth/concepts/index.mdx

minor grammar fix in [Authentication-Concepts](https://docs.amplify.aws/android/build-a-backend/auth/concepts/)

fix(grammar): a to an in Authentication-Concepts

---

src/pages/[platform]/build-a-backend/storage/authorization/index.mdx

improve callout for group access in storage

---

src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx
src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx

Adding multi-bucket support documentation for Android and Swift Storage category.

storage: update android and swift storage category with multiple buckets support

---

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx

staging: https://broken-video.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/#step-5---configuring-database-connection-for-production

fix broken video on /react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database

---

src/pages/[platform]/build-a-backend/storage/list-files/index.mdx

The code snippets for Swift's list instructions from a specific bucket were incorrect.

fix(Storage): Fixing Swift list's code examples for multiple buckets

---

src/pages/[platform]/build-a-backend/add-aws-services/overriding-resources/index.mdx

follow-up to #7987
updates remaining override examples with updated ergonomics

follow-up to #7987, update remaining override examples with updated ergonomics

---

src/fragments/lib/analytics/ios/escapehatch.mdx
src/fragments/lib/auth/ios/escapehatch/10_awsmobileclient_escape.mdx
src/fragments/lib/geo/ios/escapehatch.mdx
src/fragments/lib/logging/ios/escapehatch/escapehatch.mdx
src/fragments/lib/project-setup/ios/upgrade-guide/upgrade-guide.mdx
src/fragments/lib/storage/ios/escapehatch.mdx
src/fragments/sdk/pubsub/ios/aws-iot-and-amplify.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/sdk/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/logging/sdk/index.mdx
src/pages/[platform]/build-a-backend/auth/use-aws-sdk/index.mdx
src/pages/[platform]/build-a-backend/storage/use-aws-sdk/index.mdx

With the AWS SDK for Swift going GA on September 17, 2024, the callout we had in each Escape Hatch section about the SDK being in Developer Preview is no longer necessary.

chore(Swift): Removing callouts regarding the Swift SDK being in Developer Preview

---

package.json
src/pages/[platform]/start/manual-installation/index.mdx

While looking for gaps in test coverage, discovered that the sample schema in the "Manual installation" guide is empty, which is not supported.
This PR adds a model to the schema ~and adds a note stating that a schema cannot be empty~.

fix empty schema on getting started manual installation page

---

src/components/ApiDocs/ApiComment.tsx
src/utils/parseMdxLinks.tsx

Adding formatting to api docs comments

add formatting to api comments

---

src/fragments/lib-v1/storage/js/download.mdx

Scope: Amplify JS v5 docuement.
Apply inline filter to hide the Storage blob Web specific example from react-native page.

chore(js): remove storage Web blob example from react-native doc

---

src/pages/[platform]/build-a-backend/data/data-modeling/add-fields/index.mdx
src/pages/[platform]/build-a-backend/data/data-modeling/relationships/index.mdx

Adds auth rules to sample snippets on `/data-modeling/*` pages to ensure snippets can be copy/pasted and run without error.

add missing auth rules to model snippets on data modeling pages

---

src/fragments/lib-v1/datastore/android/data-access/query-predicate-multiple-snippet.mdx
src/fragments/lib-v1/datastore/android/data-access/query-predicate-or-snippet.mdx
src/fragments/lib/datastore/android/data-access/query-predicate-multiple-snippet.mdx
src/fragments/lib/datastore/android/data-access/query-predicate-or-snippet.mdx

fix a typo in datastore query with multiple predicates code example (kotlin-callbacks)

fix(datastore): typo in datastore query with multiple predicates code example

---

src/pages/[platform]/build-a-backend/storage/lambda-triggers/index.mdx

Related to https://github.com/aws-amplify/docs/pull/8006 - Josef asked that I figure out how to just get the single mdx change file updated. The packageManager kept trying to get into package.json but I eventually figured that out.
Single mdx file change.

Updating the lambda-trigger mdx with an example

---

src/pages/[platform]/build-a-backend/data/data-modeling/add-fields/index.mdx

The docs say that default can be applied to _scalars_ and _arrays_ (and _not enums_), but I believe it should say that it can be applied to _scalars_ and _enums_ (and _not arrays_).
e.g. this schema will not work `npx ampx sandbox`:
```
const schema = a.schema({
Todo: a
.model({
content: a.integer().array().default([1, 2, 3]), // same as "[1, 2, 3]"
})
.authorization((allow) => [allow.publicApiKey()]),
});
// Failed to instantiate data construct
// Caused By: The @default directive may only be added to scalar or enum field types.
```
The actual check in `@default` is `if (isList() || !isScalarOrEnum()) throw;`
**Please add the product(s)/platform(s) affected to the PR …

fix: default() applies to scalars and enums, not arrays

---

src/pages/[platform]/start/quickstart/index.mdx

There is an issue with the current quickstart where due to the placement of the Authenticator component, a second user could sign in to the application and view the first user's todo list.
This PR updates react quickstart to place the Authenticator higher in the tree, rerendering the App component and starting from empty state.
_By submitting this pull request, I confirm that my contribution is made under the terms of …

update react quickstart to revise todo state, authenticator placement

---

src/pages/[platform]/start/quickstart/index.mdx

The Authenticator UI component has been moved higher up the tree to the `src/main.tsx` file . Thus, update the `App.tsx` file to remove the component reference and instead use the `user` property from the `useAuthenticator` hook.

update react quickstart to remove Authenticator reference from App.tsx

---

src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx

There is an issue with the current quickstart where due to the placement of the Authenticator component, a second user could sign in to the application and view the first user's todo list.
This PR updates next pages quickstart to place the Authenticator higher in the tree, re-rendering the App component and starting from empty state.
_By submitting this pull request, I confirm that my contribution is made under the …

update next pages quickstart to revise todo state and authenticator placement

---

src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx

There is an issue with the current quickstart where due to the placement of the Authenticator component, a second user could sign in to the application and view the first user's todo list.
This PR updates next app router quickstart to place the Authenticator higher in the tree, re-rendering the root component and starting from empty state.
_By submitting this pull request, I confirm that my contribution is made under …

update next app router quickstart to revise todo state and authenticator placement

---

src/styles/color-switcher.scss
src/styles/layout.scss

Fixes overlapping text when menu is open and overlapping colorswitcher.
Fixes https://github.com/aws-amplify/docs/issues/8012
**Before**
**After**

fix: z-index of open nav

---

src/pages/[platform]/build-a-backend/auth/moving-to-production/index.mdx

updates production email configuration to use new `senders` block in `defineAuth` instead of overrides with CDK

update auth example for "moving to production" email with `senders`

---

src/pages/[platform]/build-a-backend/auth/manage-users/manage-passwords/index.mdx

update password policy override

---

src/pages/[platform]/start/quickstart/index.mdx

Rename `my-app` -> `my_amplify_app` for consistency across examples 
Fixes https://github.com/aws-amplify/docs/issues/8038

fix: Rename example app for consistency in quickstart guide

---

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-external-ddb-table/index.mdx
src/pages/[platform]/build-a-backend/data/mutate-data/index.mdx
src/pages/[platform]/build-a-backend/data/override-resources/index.mdx

taking a pass at consolidating snippet code styles and headings for js/ts snippets, namely:
- running snippets through prettier for spacing
- adding snippet titles as necessary
- reworking override snippet ergonomics to align with others

run data snippets through prettier, naming updates

---

src/pages/gen1/[platform]/build-a-backend/graphqlapi/troubleshooting/index.mdx
src/pages/gen1/[platform]/tools/cli-legacy/searchable-directive/index.mdx

corrected OpenSearch ddb script path

Corrected OpenSearch ddb script path

---

src/pages/[platform]/build-a-backend/functions/add-lambda-layers/index.mdx

update layers page

---

src/pages/[platform]/build-a-backend/auth/concepts/tokens-and-credentials/index.mdx

adds a callout at the end of the auth tokens concept page for providing custom tokens

add a next step for providing custom tokens

---

src/pages/[platform]/build-a-backend/add-aws-services/custom-resources/index.mdx

Publisher Lambda function code is accessing incorrect env variable name. In the backend.ts it is defined as SNS_TOPIC_ARN whereas in function code it is being accessed as TOPIC_ARN.

Update index.mdx - Incorrect Env Name accessing in Lambda function

---

src/fragments/start/getting-started/next/setup.mdx
src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx
src/pages/gen1/[platform]/build-a-backend/restapi/gen-ai/index.mdx
src/pages/gen1/[platform]/start/getting-started/setup/index.mdx
src/pages/gen1/[platform]/start/project-setup/create-application/index.mdx

Specify next js versions more explicitly

fix(js): specify next js versions more explicitly

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/index.mdx

Added a callout for Removal Policy

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/connect-event-api/index.mdx

Adds AppSync Events client docs

feat: appsync events

---

src/pages/[platform]/build-a-backend/functions/grant-access-to-other-resources/index.mdx
src/pages/[platform]/build-ui/figma-to-code/index.mdx

removes unused import and updates heading

---

src/pages/[platform]/build-a-backend/data/customize-authz/index.mdx

Adds discussions on IAM authorization and authorization on custom operations
**IAM Authorization**
**Custom operations**
Prompted by https://github.com/aws-amplify/amplify-category-api/issues/2929

feat: add discussions on IAM authz; authz on custom operations

---

src/pages/[platform]/start/quickstart/index.mdx

add callout for rn web

---

redirects.json
src/pages/[platform]/ai/set-up-ai/index.mdx

Adds the initial set up AI page

set up ai page

---

src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx

JS library has a known issue that it does not URI encode the copy source path. We have to fix it only in next major version because users may already encoded the copy source, adding URI encode for them will cause the value to be double-encoded.

fix(js): add storage callout to encode copy source URI

---

src/fragments/lib-v1/graphqlapi/flutter/subscribe-data.mdx
src/fragments/lib-v1/project-setup/flutter/escape-hatch/escape-hatch.mdx
src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
src/pages/[platform]/build-a-backend/data/subscribe-data/index.mdx

Fixes dead links that were pointed to Dart API docs.
Verify links are valid destinations. 

fix(dart): corrected url path for dart docs

---

cspell.json
src/pages/[platform]/ai/concepts/architecture/index.mdx
src/pages/[platform]/ai/concepts/index.mdx
src/pages/[platform]/ai/concepts/inference-configuration/index.mdx
src/pages/[platform]/ai/concepts/models/index.mdx
src/pages/[platform]/ai/concepts/prompting/index.mdx
src/pages/[platform]/ai/concepts/streaming/index.mdx
src/pages/[platform]/ai/concepts/tools/index.mdx

Adds AI 'concepts' section and pages

add ai concepts section

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/aws-appsync-apollo-extensions/index.mdx

feat(data): appsync apollo extensions

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/index.mdx

reduce opensearch domain capacity to free tier-eligible

---

src/directory/directory.mjs
src/pages/gen1/[platform]/build-a-backend/troubleshooting/apikey-not-found/index.mdx

API key troubleshoot guide

---

src/pages/[platform]/ai/set-up-ai/index.mdx

Updates to set up ai page

---

cspell.json
src/pages/[platform]/ai/conversation/context/index.mdx
src/pages/[platform]/ai/conversation/history/index.mdx
src/pages/[platform]/ai/conversation/index.mdx
src/pages/[platform]/ai/conversation/knowledge-base/index.mdx
src/pages/[platform]/ai/conversation/response-components/index.mdx
src/pages/[platform]/ai/conversation/tools/index.mdx

Adding AI conversation section

---

src/pages/[platform]/build-a-backend/add-aws-services/deletion-backup-resources/index.mdx

Add callout that retaining resources on stack deletion is not supported for sandbox.

add info that retaining resources is not supported in sandbox

---

src/directory/directory.mjs
src/pages/[platform]/ai/generation/data-extraction/index.mdx

- Adds `Data Extraction` example in AI kit > generation > data-extraction page.

Add AI kit > generation > data-extraction example

---

src/pages/[platform]/ai/concepts/inference-configuration/index.mdx
src/pages/[platform]/ai/concepts/models/index.mdx
src/pages/[platform]/ai/concepts/prompting/index.mdx
src/pages/[platform]/ai/conversation/knowledge-base/index.mdx
src/pages/[platform]/ai/conversation/tools/index.mdx
src/pages/[platform]/ai/generation/data-extraction/index.mdx
src/pages/[platform]/ai/generation/index.mdx
src/pages/[platform]/ai/set-up-ai/index.mdx

Update docs to use Claude 3.5 Haiku

---

src/directory/directory.mjs
src/pages/[platform]/ai/conversation/connect-your-frontend/index.mdx

add conversations > connect your frontend page with client examples

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-up/index.mdx

Add passwordless sign up/ auto sign in changes for Swift
None

chore(auth): add swift passwordless sign up/auto sign in changes

---

Readme.md
src/fragments/lib-v1/ssr/js/next-js-callout.mdx

Updates broken Next.js pages links to latest version. Next.js removed their redirect from their older pages docs URL (`https://nextjs.org/docs/basic-features/pages`) to their [current pages docs](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts), so the older URL simply breaks now. …

fix: update Next.js pages link to latest ver

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx

The purpose of this pull request is to expand existing passwordless sign in examples to better illustrate the available options.

docs(js): more passwordless sign in examples

---

src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx
src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx
src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx

Add the following options to JS library:
* `expectedBucketOwner` option to all Storage APIs
* `eTag` option to the Storage copy API source.
* `notModifiedSince` option to the Storage copy API source.

docs(js): add durability options

---

src/pages/[platform]/ai/concepts/models/index.mdx

- Adds Amazon Nova Pro, Lite, and Micro to supported models page.
- Specifies conversation and generation route support per model.
- Adds model region support callout.
- Changes supported models overview from markdown list to Amplify UI Table component

ai kit: add table for supported models and add nova

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/multi-step-sign-in/index.mdx
src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-up/index.mdx
src/pages/[platform]/build-a-backend/auth/connect-your-frontend/switching-authentication-flows/index.mdx

The purpose of this pull request is to add additional passwordless JS examples.
- Update Multi Step Sign In page to include new passwordless sign in steps
- Expand autoSignIn example on sign up page to show full sequence of steps
- Expand USER_AUTH examples on switching authentication flows page

docs(js): expand passwordless examples for multistep sign in, autosign in, and switching flows

---

src/pages/[platform]/build-a-backend/functions/configure-functions/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/add-user-to-group/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/custom-auth-flows/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/custom-message/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/dynamo-db-stream/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/google-recaptcha-challenge/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/override-token/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/s3-upload-confirmation/index.mdx
src/pages/[platform]/build-a-backend/functions/examples/user-attribute-validation/index.mdx

adds resourceGroupName to function docs

---

src/pages/[platform]/build-a-backend/data/connect-event-api/index.mdx

feat: add instructions for adding event api to backend

---

src/pages/[platform]/build-a-backend/troubleshooting/cannot-find-module-amplify-env/index.mdx

updates the troubleshooting page to add information specific to vue config
https://github.com/aws-amplify/docs/issues/8114

update module troubleshooting page with vue config

---

src/pages/[platform]/build-a-backend/data/customize-authz/public-data-access/index.mdx

Add guide to:
1. Extends API key expiration date
2. Rotate API key

add guide to extend api key expiration and rotate api key

---

src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx

docs(js): support uploadData checksumAlgorithm option

---

src/pages/gen1/[platform]/build-a-backend/graphqlapi/connect-machine-learning-services/index.mdx

The dependent services for the `@predictions` directive don't support all regions that AppSync supports. 
Adds callout to the gen1 `@predictions` directive page.

add region callout for gen1 predictions directive

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx

The purpose of this pull request is to add a call out to mention the unique properties of `autoSignIn` api when used with the `USER_AUTH` flow.

docs(js): adding USER_AUTH autosignin callout

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/troubleshooting/circular-dependency/index.mdx

Add troubleshooting for circular dependency errors in Gen2 backend.

chore: add troubleshooting for circular dependency errors in backend

---

src/pages/gen1/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx
src/pages/gen1/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx

Adds a discussion about authorizing `@manyToMany` relationships in Gen 1, and a link to that discussion from the data modeling section.
**Discussion: `/gen1/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/#authorizing-manytomany-relationships`**
**Callout: `/gen1/[platform]/build-a-backend/graphqlapi/data-modeling/#many-to-many-relationship`** …

[amplify-data] feat: add gen1 manyToMany auth discussion

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx

- This PR adds short introduction to a new feature for signInAPI in AmplifyJS, resumable signin

feat(auth): Introduce resumable signin guide for the AmplifyJS

---

cspell.json
src/directory/directory.mjs
src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx

… Gen 2 @aws-amplify/amplify-backend/1602
Add custom runtime documents, it's required for [#1602](https://github.com/aws-amplify/amplify-backend/pull/1602)
[#1543](https://github.com/aws-amplify/amplify-backend/issues/1543), [#1486](https://github.com/aws-amplify/amplify-backend/issues/1486)
amplify-backend

feature(function): add custom functions documentation for AWS Amplify-backend

---

.github/CODEOWNERS

- removes requirement for docs team approval on all files. this was a temporary measure https://github.com/aws-amplify/docs/pull/5051
- adds josefaidt to deploy-and-host while mauerbac is out

update codeowners, remove docs team req

---

src/pages/[platform]/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx

adds a callout for branch env variables

add callout for branch env variables

---

src/fragments/lib-v1/start/getting-started/next/setup.mdx
src/fragments/lib/ssr/nextjs/version-range-callout.mdx
src/fragments/start/getting-started/next/setup.mdx
src/pages/gen1/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx
src/pages/gen1/[platform]/start/getting-started/setup/index.mdx
src/pages/gen1/[platform]/start/project-setup/create-application/index.mdx

Updated support Next.js version range throughout the doc.

chore: update supported Next.js version range

---

src/fragments/lib/troubleshooting/common/upgrading.mdx
src/fragments/start/getting-started/next/setup.mdx
src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx

chore: remove/update callout regarding supported next version range

---

src/pages/[platform]/build-a-backend/functions/add-lambda-layers/index.mdx

updates the layers doc with following
```
layers: {
"module": "myLayer:1"
},
```

update layer doc to add short version

---

src/pages/[platform]/build-a-backend/auth/concepts/passwordless/index.mdx

Add link on Passwordless page overview to the backend resources override docs.
https://github.com/aws-amplify/amplify-backend/issues/2276

Passwordless: link to UserPool overrides page

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/custom-business-logic/batch-ddb-operations/index.mdx

Add page for batch ddb operations.

add batch ddb operations page

---

cspell.json
src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/enable-logging/index.mdx

- Added documentation page for the new logging API for defineData.
- Added "Enable Logging" section under "Data" directory.

feat: new doc page for enable logging for `defineData`

---

src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx

fix: cleanup custom functions docs

---

src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx

Changed documentation example for Python Lambda function to use cp instead of rsync, as rsync not installed.
- [ yes] JS

Replaced rsync with cp - Affects JS

---

src/pages/[platform]/build-a-backend/auth/connect-your-frontend/sign-in/index.mdx

Add callout with link to setting up external IdP configuration from `signInWithRedirect` docs

chore: add callout with link to external IdP configuration in signInWithRedirect

---

cspell.json
src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx

Related to:
- https://github.com/aws-amplify/amplify-backend/issues/1543
- https://github.com/aws-amplify/amplify-backend/pull/1602
- https://github.com/aws-amplify/amplify-backend/issues/2386
This update describes how Amplify Backend's can be built if they require Docker.

Describe docker support state

---

src/pages/[platform]/build-a-backend/auth/modify-resources-with-cdk/index.mdx
src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx
src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx
src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx

Amplify Flutter is adding multibucket support, so this PR updates the relevant API documentation to show how to use it
N/A

amplify-libraries Flutter multibucket support documentation update

---

src/pages/[platform]/ai/conversation/knowledge-base/index.mdx

Added the missing import `import * as cdk from 'aws-cdk-lib';` to the page.
Import `import * as cdk from 'aws-cdk-lib';` was missing from the last code block resulting in the code failing.

Documentation update, JS, Update index.mdx with missing import

---

src/pages/[platform]/build-a-backend/functions/add-lambda-layers/index.mdx
src/pages/[platform]/build-a-backend/functions/configure-functions/index.mdx
src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx
src/pages/[platform]/build-a-backend/functions/environment-variables-and-secrets/index.mdx
src/pages/[platform]/build-a-backend/functions/scheduling-functions/index.mdx

Custom functions were recently supported by https://github.com/aws-amplify/amplify-backend/pull/1602. This documentation update makes it clear that most of the function configuration is only applicable for "native" functions and not custom functions.

Add callouts for backend-function configuration not supported in custom functions

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

update signIn with amazon example with as scope as profile, add link to AWS doc providing more info on social providers setup

update example with supported scope and adds link

---

src/pages/[platform]/build-a-backend/functions/custom-functions/index.mdx

updates callout to add resourceGroupName property and minor message enhancement. 
updates example to show property as optional.

update custom function on resourceGroupName property

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

separates backend auth resource snippets to show two separate examples:
1. web
2. mobile
mobile examples use the `myapp://...` redirect URI

separate web and mobile examples for redirect uri's

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/index.mdx

Created a hint for the correct syntax to use for an existing lambda function, instead of creating a new function via defineFunction. 
- [ X] Ready to merge

added advice how to reference existing lambda functions

---

src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx

This PR improves the `uploadData` code snippets for React to account for nullish file content in state at time of button click.
https://github.com/aws-amplify/amplify-js/issues/13628

chore: Improve uploadData snippets for React

---

src/pages/[platform]/deploy-and-host/sandbox-environments/setup/index.mdx

The sandbox termination behavior was recently updated with:
- https://github.com/aws-amplify/amplify-backend/pull/2160
`ctrl + c` no longer prompts asking about resource deletion.
The docs are out of date.
Updates **Terminating a sandbox environment** section of docs.

update terminate sandbox environment docs

---

src/pages/gen1/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx

Builds on https://github.com/aws-amplify/docs/pull/8221 and enhances the discussion of split schema files, especially with respect to directive support on fields of extended types.
- Added file title to schema code snippets
- Added field and directive examples to schema code snippets
- Consolidated info callouts about file order and duplicate names
- Added detail to unsupported use cases of the `extend` keyword
- Removed link to issue
- https://github.com/aws-amplify/amplify-category-api/issues/2371
- https://github.com/aws-amplify/amplify-category-api/issues/3036 …

feat(amplify-data): enhance discussion of split schema files

---

cspell.json
src/pages/[platform]/build-a-backend/auth/use-existing-cognito-resources/index.mdx

adds example on adding `groups` with referenceAuth

update reference auth with groups

---

src/pages/[platform]/ai/conversation/knowledge-base/index.mdx

retriveURL is not bedrock-runtime but bedrock-agent-runtime

docs: fix KnowledgeBaseDataSource URL to use bedrock-agent-runtime

---

.github/workflows/check_for_broken_links.yml

This PR pins the the Ubuntu image used by the `check_for_broken_links` workflow to 22.04.
Currently, the workflow is failing due to using `ubuntu-latest` which has [tightened its access to the user namespaces kernel feature](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces). Chromium is no longer able to run with this new security feature in place as it currently requires it. (See: https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md) As it relates to this repo, we use Puppeteer with headless Chromium to drive link checking and, as of a few weeks ago, this workflow has been failing since GH Actions have been slowly rolling out version 24 as the new `ubuntu-latest` over 22.
Per the recommendations in this [GitHub …

fix: Pin Ubuntu image to allow link checker action to run

---

src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/[platform]/build-a-backend/storage/list-files/index.mdx
src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx

closes: https://github.com/aws-amplify/docs/issues/8236

update storage identityId path

---

src/pages/[platform]/build-a-backend/add-aws-services/analytics/existing-resources/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/personalize-recommendations/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/set-up-analytics/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/storing-data/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/analytics/streaming-data/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/existing-resources/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/interactions/set-up-interactions/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/existing-resources/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-http-api/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx
src/pages/[platform]/reference/amplify_outputs/index.mdx

Recommend using `parseAmplifyConfig` instead of calling configure twice
[#12849](https://github.com/aws-amplify/amplify-js/issues/12849) : Unable to successfully override oauth config when calling `Amplify.configure` twice to override a config

fix(js): recommend parseAmplifyConfig instead of calling configure twice

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

fix broken markdown link format
https://docs.amplify.aws/react/build-a-backend/auth/concepts/external-identity-providers/#configure-external-sign-in-backend
> Learn more about using social identity providers with user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html)
before
```
Learn more about using social identity providers with user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html)
```
after
```
[Learn more about using social identity providers with user pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html)
```
Which product(s) are affected by this PR …

fix(docs): fix link formatting in external identity providers doc

---

src/pages/[platform]/deploy-and-host/sandbox-environments/setup/index.mdx

Add additional callouts about resource provisioning and disposition in sandbox mode
#8211 

Add additional callouts about resource provisioning and disposition in sandbox mode

---

package.json

adds `packageManager` key for [corepack](https://nodejs.org/api/corepack.html). Corepack auto detects and uses the package manager declared by this key in `package.json`, and with Node 22 it'll auto-add this key if you install deps, run scripts, etc.
Typically I discard the changes made by corepack, though this can be helpful to ensure all team members are using the same version of the package manager.
_By submitting …

add packageManager key for corepack

---

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
src/pages/gen1/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx

fix: wrong export function syntax

---

src/pages/[platform]/ai/conversation/index.mdx
src/pages/[platform]/ai/generation/index.mdx
src/pages/[platform]/ai/set-up-ai/index.mdx

Adds callout with link to support models list on conversation, generation, and setup pages.
- https://github.com/aws-amplify/docs/issues/8253

add supported models callout w link to relevant pages

---

src/pages/[platform]/reference/cli-commands/index.mdx

update generate outputs command reference

---

src/pages/[platform]/build-a-backend/auth/use-existing-cognito-resources/index.mdx

closes: https://github.com/aws-amplify/amplify-backend/issues/2488

adds callout on reference auth

---

src/pages/[platform]/build-a-backend/auth/concepts/external-identity-providers/index.mdx

The purpose of this change is to clarify the requirements surrounding attribute mapping when using external providers with Amplify Auth.
Also, fixes some errors in a few examples. 
https://github.com/aws-amplify/amplify-js/issues/14208

fix(auth): update attribute mapping section for defineAuth

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/index.mdx

Updated the custom operations documentation to include examples of supported argument types. This update aligns with the recent feature addition in [PR #497](https://github.com/aws-amplify/amplify-data/pull/497).

Update custom operations documentation with supported argument examples

---

cspell.json
src/pages/[platform]/build-a-backend/auth/concepts/user-attributes/index.mdx

adds list of required attributes on auth 

add auth required attributes mapping

---

src/pages/[platform]/build-a-backend/functions/streaming-logs/index.mdx

add callout on function streaming and fix minor nits

---

src/pages/[platform]/reference/cli-commands/index.mdx

command reference for `npx ampx generate schema-from-database`
https://docs.amplify.aws/react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/#step-2---generate-typescript-representation-of-your-database-schema

command reference for `generate schema-from-database`

---

src/fragments/lib-v1/push-notifications/react-native/getting_started/50_integrate_native_modules.mdx
src/fragments/lib/push-notifications/react-native/getting_started/50_integrate_native_modules.mdx

https://github.com/aws-amplify/amplify-js/issues/14248

chore: add AppDelegate updates example in Swift (react-native >= 0.77)

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/data-modeling/disable-operations/index.mdx

Disable operations usage
#8249 

Disable operations

---

src/fragments/lib/storage/android/download.mdx
src/fragments/lib/storage/ios/download.mdx
src/pages/[platform]/build-a-backend/storage/download-files/index.mdx
src/pages/gen1/[platform]/build-a-backend/storage/download/index.mdx

https://github.com/aws-amplify/amplify-js/issues/14249

chore: remove inaccuarte information about downloadData

---

src/fragments/lib/auth/flutter/social_signin_web_ui/10_cli_setup.mdx

Added http://localhost:3000/ to social provider redirect URI configuration
[#6021](https://github.com/aws-amplify/amplify-flutter/issues/6021)

Flutter: Add localhost to social provider redirect URI configuration

---

src/components/GetStartedPopover/GetStartedPopover.tsx
src/components/GetStartedPopover/__tests__/GetStartedPopover.test.tsx
src/pages/[platform]/index.tsx
src/pages/index.tsx

add deploy app option in getting started only for web developers

---

src/pages/[platform]/build-a-backend/server-side-rendering/nuxt/index.mdx

The Nuxt SSR example refers to the internal-only package `@aws-amplify/core`, which should not be used directly in customer apps. Updating the example to fix this issue.
This change also fixed the incorrect import of `amplify_outputs.json`.

fix(ssr): remove mentioning of internal packages

---

src/pages/[platform]/build-a-backend/data/connect-event-api/index.mdx

Add examples of publishing events over WebSocket to the docs, this change aligns with the feature addition in [this PR](https://github.com/aws-amplify/amplify-js/pull/14242)

feat:Add publish events over websocket docs

---

src/pages/[platform]/start/migrate-to-gen2/index.mdx

* Set instructions to use latest data snapshot.
* Changes names of props for table mappings
```
migratedAmplifyGen1DynamoDbTableMap -> migratedAmplifyGen1DynamoDbTableMappings
modelTableNameMap -> modelNameToTableNameMapping
```

Update data migrations

---

src/directory/directory.mjs
src/pages/[platform]/build-a-backend/data/field-level-validation/index.mdx

Added docs for field level validation. 

feat: add field level validation docs

---

src/pages/[platform]/how-amplify-works/concepts/index.mdx

Adds missing auth rule to a sample schema. (Schemas containing models without auth rules cannot be deployed.)

adds missing auth rules on sample schema

---

src/pages/[platform]/reference/cli-commands/index.mdx

This PR updates the documentation for the `npx ampx sandbox` CLI command. The changes includes:
- Split the flags amongst `Logs streaming` and `Options`
- Added the `debug` and `once` flag
N/A

chore: update npx ampx sandbox cli command

---

src/pages/[platform]/deploy-and-host/sandbox-environments/features/index.mdx
src/pages/[platform]/reference/cli-commands/index.mdx

adds command reference for `npx ampx sandbox secret remove --all`
https://github.com/aws-amplify/amplify-backend/pull/2423

secrets remove all option

---

src/pages/[platform]/build-a-backend/functions/set-up-function/index.mdx

When setting up the Lambda function by referring to the “Set up a Function” page, the following error occurred while executing the npx ampx sandbox command.
```bash
[Sandbox] Detected file changes while previous deployment was in progress. Invoking 'sandbox' again
File written: amplify_outputs.json
Custom operation sayHello requires both an authorization rule and a handler reference
Caused By: Custom operation sayHello requires both an authorization rule and a handler reference
Resolution: Check your data schema definition for syntax and type errors.
[Sandbox] Watching for file changes...
```
Page URL: https://docs.amplify.aws/nextjs/build-a-backend/functions/set-up-function/
By adding`.authorization(allow => [allow.guest()])` to data/resource.ts, the error was resolved.
```typescript …
```

chore(function): fix code snippet at set-up-function page

---

src/pages/gen1/[platform]/build-a-backend/server-side-rendering/index.mdx

Add a callout about the needs of decoding cookie value strings.

chore: add decode cookie value strings note to SSR example

---

src/fragments/lib-v1/geo/android/maps/20_display_map.mdx
src/fragments/lib/geo/android/maps/20_display_map.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/maps/index.mdx

Maptiler removed many pages related to the Android SDK reference and Maplibre GL for Android in general. The underlying Mapbox SDK has also been archived and moved to https://github.com/mapbox/mapbox-gl-native-android. Attempted to find and match as closely to the original docs intent as possible.
- Android Get Started with Maplibre: moved to https://docs.maptiler.com/maplibre-gl-native-android/
- [Camera Position SDK reference](https://web.archive.org/web/20230603184411/https://docs.maptiler.com/maplibre-gl-native-android/com.mapbox.mapboxsdk.camera/): page removed, underlying Mapbox SDK docs now point [here](https://docs.mapbox.com/android/maps/guides/camera-and-animation/camera/) as their latest reference docs.
- [Android Annotation …

chore: fix broken Android Maplibre SDK links

---

src/fragments/start/getting-started/reactnative/setup.mdx
src/pages/[platform]/reference/amplify_outputs/index.mdx
src/pages/gen1/[platform]/start/getting-started/setup/index.mdx
src/pages/gen1/[platform]/start/project-setup/create-application/index.mdx

chore: add callout about committing amplify config files for expo eas build

---

src/pages/[platform]/build-a-backend/add-aws-services/rest-api/delete-data/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/fetch-data/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/post-data/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-http-api/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx
src/pages/[platform]/build-a-backend/add-aws-services/rest-api/update-data/index.mdx

Add docs for retryStrategy in api-rest category
Document the changes made in this PR: https://github.com/aws-amplify/amplify-js/pull/14303

feat: add retry strategy for api-rest category

---

src/pages/[platform]/build-a-backend/data/data-modeling/add-fields/index.mdx

The docs currently describe the ability to define defaults for enums, which isn't supported in the types or the SchemaProcessor. This is a feature we should consider, but until its supported we should say that it works in the docs.
https://github.com/aws-amplify/amplify-data/issues/452
Good to merge if approved.

fix: Remove reference to using default with enum

---

src/fragments/lib/project-setup/native_common/prereq/common_header.mdx
src/fragments/lib/troubleshooting/common/upgrading.mdx

https://github.com/aws-amplify/docs/issues/7156

chore: update lowest supported node versions

---

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
src/pages/gen1/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx

https://github.com/aws-amplify/amplify-js/issues/14316

chore: add the docuemtnation about using lang query param

---

src/pages/[platform]/build-a-backend/data/customize-authz/grant-lambda-function-access-to-api/index.mdx

Update data lambda authz guide

---

src/pages/[platform]/build-a-backend/data/connect-event-api/index.mdx

The purpose of this PR is to update the React code example for the Events API to use a React pattern that won't result in dangling subscriptions due to the 2x render of `useEffect` hooks when `React.StrictMode` is enabled. Also, updated JSX to use index for key as `data.id` is not unique across subsequent events as it references the subscription id not the event id.
https://github.com/aws-amplify/amplify-data/issues/531
HTML: `<a …

fix(events): update events react example code

---

src/pages/[platform]/build-a-backend/functions/examples/user-attribute-validation/index.mdx

the comparison was the wrong way around so only let people under 13 sign up
n/a
issue with sign up when using documentation-provided lambda handler

fix issue with date comparison logic in sign up handler lambda

---

src/pages/[platform]/ai/conversation/connect-your-frontend/index.mdx
src/pages/[platform]/ai/conversation/context/index.mdx

Clarify usage of `aiContext` vs `metadata` with AI Kit
https://github.com/aws-amplify/amplify-data/issues/584

chore: clarify aiContext vs metadata`

---

src/pages/[platform]/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/index.mdx

Added missing code highlighting to the code block in the [Connect to Amazon OpenSearch for search and aggregate queries](https://docs.amplify.aws/react/build-a-backend/data/custom-business-logic/search-and-aggregate-queries/#step-2-setting-up-the-opensearch-instance) under `Step 2: Setting Up the OpenSearch Instance`.
The updated code block is as follows:
```typescript
// Create the OpenSearch domain
const openSearchDomain = new opensearch.Domain(
backend.data.stack,
'OpenSearchDomain',
{
version: opensearch.EngineVersion.OPENSEARCH_2_11,
nodeToNodeEncryption: true,
// set removalPolicy to DESTROY to make sure the open search domain is deleted on stack deletion.
removalPolicy: RemovalPolicy.DESTROY,
encryptionAtRest: {
enabled: true
}
}
);
```
Adding this highlight improves readability, …

Add missing code highlight to OpenSearch page

---

src/fragments/lib/project-setup/flutter/platform-setup/android.mdx
src/pages/[platform]/start/platform-setup/index.mdx

The latest Dart SDK produces build errors when using the Gradle and plugin version specified in our docs. This change updates our recommended versions to 8.3 (Plugin) and 8.4 (Gradle) as per this [compatibility matrix](https://developer.android.com/build/releases/gradle-plugin#updating-gradle).
[6138](https://github.com/aws-amplify/amplify-flutter/issues/6138) …

chore: update Flutter Gradle and Plugin version

---

src/fragments/lib-v1/analytics/flutter/record.mdx
src/fragments/lib-v1/analytics/ios/record.mdx
src/fragments/lib/analytics/flutter/record.mdx
src/fragments/lib/analytics/ios/record.mdx

Added callout that Analytic Data is unencrypted and stored locally for Flutter and Swift. Mobile platforms are sandboxed (other apps can't access this data normally), so we did not include this notice for Android.

chore: Flutter/Swift unencrypted analytics

---

src/pages/[platform]/build-a-backend/storage/download-files/index.mdx

This is a docs change that goes out in parallel with Amplify Android change https://github.com/aws-amplify/amplify-android/pull/3056. Amplify Android is adding a new StorageException scenario when it attempts to download a file when the following conditions are met:
- A file in the given path already exists
- The app does *not* have write permission to that file
- e.g. if that file was authored by a different app and the app that is attempting to overwrite the file has someting called "[scoped storage](https://developer.android.com/training/data-storage#scoped-storage)" enabled
Essentially, since the app doesn't have write permissions, Amplify can't overwrite the file so throw an exception for the developer to react to. Since scoped storage is a relatively new (and honestly very difficult …

chore: Add callout for Android storage permissions

---

src/pages/[platform]/start/migrate-to-gen2/index.mdx

Add links in Gen1 vs Gen2 feature matrix to known pages that documment how to achieve things with raw CDK.

Add links in feature matrix

---

src/fragments/lib-v1/geo/js/google-migration.mdx
src/fragments/lib/geo/js/google-migration.mdx
src/pages/[platform]/build-a-backend/add-aws-services/geo/google-migration/index.mdx

Update links that no longer work

fix(geo): update stale links

---

src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx

When using Authenticator component directly in Next.js App Router's layout.tsx, a build error occurs:
`Attempted import error: 'useForm' is not exported from 'react-hook-form'` This is because Next.js App Router renders components on the server by default (Server-Side Rendering) Authenticator component requires browser-only APIs and client-side functionality Incompatibility between server-side rendering and client-side dependencies causes the import error. While "use client" is written in the doc example but it is not compatible with [meta data](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#the-metadata-object) that is usually part of `Layout.tsx`. The Solution is to Create a separate client component wrapper around the Authenticator:
Create …

fix(next-app-router) starter tutorial authenticator build issue

---

src/fragments/lib-v1/android-sdk.mdx
src/fragments/lib-v1/ios-sdk.mdx
src/fragments/lib/android-sdk.mdx
src/fragments/lib/ios-sdk.mdx
src/fragments/sdk/library-callout.mdx
src/fragments/sdk/sdk-api-ref/ios.mdx

chore: Maintenance notice for AWS SDK for Android and iOS

---

package.json
yarn.lock

Bumoing the tmp package version to ^0.2.4 in order to resolve a dependabot alert: https://github.com/aws-amplify/docs/security/dependabot/103
- [N/A] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.
- [N/A] Are any files being deleted with this PR? If so, have the needed redirects been created?
- [N/A] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
HTML: `<a …

chore(deps): bump tmp to 0.2.4

---

tasks/generate-sitemap.mjs

Build started failing since Amplify Hosting now uses Node 22.18.0 due to:
```
import flatDirectory from '../src/directory/flatDirectory.json' assert { type: 'json' };
SyntaxError: Unexpected identifier 'assert'
```

fix: wrong syntax for assert in import
