aws-amplify/docs

src/fragments/lib/graphqlapi/js/working-with-files.mdx
feat(data): add API record id to Storage file prefix for API + Storage docs; update comments; update callout
=> feat(data): add API record id to Storage file prefix for API + Storage docs; update comments; update callout

src/pages/cli/usage/containers.mdx
created this PR as the original branch for #4941 was accidentally deleted.
- https://github.com/aws-amplify/amplify-adminui/issues/662
- https://github.com/aws-amplify/amplify-cli/issues/11567
=> chore: callout need for additional permissions for containers

src/fragments/lib/auth/ios/signin/30_signIn.mdx
Fix typo in signIn v2 Swift combine flavor
=> fix(auth): fix typo in signIn v2 combine flavor

src/fragments/lib/push-notifications/flutter/getting_started/40_install_lib.mdx
Updates versions for Push Notifications in Flutter
=> chore(flutter): Update versions

src/fragments/lib/auth/js/set-up-auth.mdx
=> Add JTBD auth staging page

.github/workflows/add_redirects_label.yml, .github/workflows/check_for_redirects.yml, .github/workflows/scripts/check_for_redirects.js, .github/workflows/scripts/utilities.js, .mergify.yml
- Update redirects workflow to use Github API. This helps with finding deleted files within a PR instead of trying to find deleted files by comparing commits
- The updated workflow:
1. Makes a request to get all files from the PR using the GH API, then it filters for deleted files under `src/pages` and `src/fragments`.
2. If there are deleted files, then it saves the count of this inside an artifact, `redirectsArtifact.txt` attached to the workflow
3. A new workflow, `add_redirects_label.yml` was added and runs when `check_for_redirects.yml` is finished, using the `workflows_run` trigger.
- This workflow reads the artifact an if the count of deleted files is greater than 0, then it adds the `redirects-label`. 
- Added `workflow/scripts/utilities.js` as a home for workflow utility scripts …
=> Update redirects workflow to use Github API

src/pages/ChooseFilterPage.tsx
Changed a title prop in the `ChooseFilterPage.tsx` file to `${chapterTitle} - ${title} - Choose a platform` to make it more descriptive and consistent with other sub tabs titles. Updated title is within recommended 60-70 characters length for SEO's purposes.
=> page title updated

src/pages/cli/auth/overview.mdx
When modifying the `breakCircularDependency` flag, users will need to use the update auth flow or force push to mitigate the missing arn error.
The PR adds this info as troubleshooting section in the auth overview page.
https://github.com/aws-amplify/amplify-cli/issues/12690
=> feat: add troubleshooting info for breakCircularDependency flag

src/fragments/lib/auth/flutter/user_attributes/50_custom_attributes.mdx, src/fragments/lib/auth/native_common/user_attributes/common.mdx
Adds documentation for custom attributes in Amplify Flutter.
https://github.com/aws-amplify/amplify-flutter/issues/1180
=> feat(flutter): add custom attribute documentation

src/pages/_app.tsx
- Reorder how the AA scripts were loaded so custom events work normally
=> Reorder AA scripts

src/fragments/lib/auth/ios/getting_started/15_preReq_web_ui.mdx, src/fragments/lib/auth/native_common/signin_web_ui/common.mdx, src/fragments/lib/auth/native_common/social_signin_web_ui/common.mdx, src/fragments/lib/ios-prereq-category.mdx, src/fragments/lib/push-notifications/ios/getting_started/20_set_entitlements.mdx, src/fragments/lib/push-notifications/ios/getting_started/30_create_app_delegate.mdx, src/fragments/lib/push-notifications/ios/record_notifications/10_notification_received.mdx, src/fragments/lib/push-notifications/ios/record_notifications/20_notification_opened.mdx, src/fragments/lib/push-notifications/ios/register_device/20_register_with_apns.mdx, src/fragments/lib/push-notifications/ios/register_device/30_register_with_pinpoint.mdx, src/fragments/lib/push-notifications/ios/remote_media/10_remote_media.mdx
- Adding mention to **tvOS** and **watchOS** being supported, and their requirements.
- Adding/Updating code snippets for those platforms when necessary.
- Adding callout of unsupported features.
=> feat: Adding mention for tvOS and watchOS support in the Swift docs.

src/components/contribute/AmplifyBadges.tsx
=> Updating the badge section title

src/pages/start/q/integration/[integration].mdx
Update getting started first paragraph wording
- [X ] amplify-cli
- [X ] amplify-ui
- [ X] amplify-hosting
- [X ] amplify-libraries
- [ X] JS
- [ X] iOS
- [X ] Android
- [X ] Flutter
- [ X] React Native
- [X ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?
=> Update getting started first paragraph wording

src/pages/cli-legacy/graphql-transformer/storage.mdx
=> Updated transformer v1 docs on Storage

src/pages/cli-legacy/graphql-transformer/relational.mdx
=> Addresses #5604

src/components/SearchBar/index.tsx
Added `aria-label` to the search box to improve accessibility
=> added aria-label to the search box

src/fragments/lib/auth/js/set-up-auth.mdx, src/pages/lib/auth/set_up_auth/q/platform/[platform].mdx
Updating the `JTBD-Auth` branch with changes for "Set up Amplify Auth"
N/A
=> Updates for JTBD-Auth: Set up Amplify Auth

src/components/contribute/QuickstartResources.tsx
=> Updating text in Quickstart section

src/components/contribute/AmplifyBadges.tsx
=> Updating description of Amplify Badge program

src/components/contribute/HowItWorks.tsx
=> Updating wording in How it Works section

src/fragments/lib/storage/ios/escapehatch.mdx
https://github.com/aws-amplify/amplify-swift/issues/3001
=> update swift storage escape hatch SDK documentation links

src/fragments/lib/storage/ios/upload.mdx
https://github.com/aws-amplify/amplify-swift/issues/3000
=> update swift storage category upload

src/fragments/lib/push-notifications/flutter/identify_user/10_get_auth_user.mdx
update userID code snippet for Push Notifications and Flutter
- [X ] amplify-libraries
- [X ] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?
=> update userID code snippet for Push Notifications and Flutter

src/pages/console/adminui/start.mdx
Adds recommendation for account management when enabling Amplify Studio.
=> Provides recommendation to isolate Amplify workloads by account

.github/workflows/check_for_broken_links.yml
Update spacing on workflow yml file
=> update workflow formatting

.github/workflows/check_for_broken_links.yml
Add cron schedule to link checker workflow
=> add cron schedule to link checker workflow

.github/workflows/check_for_broken_links.yml, tasks/link-checker.js
Update link checker script to filter out the github new issues links
=> Slack webhook

cspell.json, src/directory/directory.mjs, src/fragments/lib/logging/android/change_local_storage/10_local_storage_size.mdx, src/fragments/lib/logging/android/change_log_levels/10_default_log_level.mdx, src/fragments/lib/logging/android/change_log_levels/20_category_log_level.mdx, src/fragments/lib/logging/android/common/10_category_list.mdx, src/fragments/lib/logging/android/configure_user/auth_current_user.mdx, src/fragments/lib/logging/android/configure_user/configure_user.mdx, src/fragments/lib/logging/android/enable_disable/enable_disable.mdx, src/fragments/lib/logging/android/escapehatch/escapehatch.mdx, src/fragments/lib/logging/android/flush_logs/flush_interval.mdx, src/fragments/lib/logging/android/flush_logs/flush_logs.mdx, src/fragments/lib/logging/android/hub_events/hub_events.mdx, src/fragments/lib/logging/android/remote_configuration/10_remote_config_provider.mdx, src/fragments/lib/logging/android/sending_logs/10_sending_logs.mdx, src/fragments/lib/logging/android/setup_logging/10_pre_req.mdx, src/fragments/lib/logging/android/setup_logging/20_initialize_with_config.mdx, src/fragments/lib/logging/android/setup_logging/30_initialize_without_config.mdx, src/fragments/lib/logging/common/access_logs/access_logs.mdx, src/fragments/lib/logging/common/remote_configuration/remote_configuration.mdx, src/fragments/lib/logging/common/setup_logging/setup_logging.mdx, src/pages/lib/logging/access-logs/q/platform/[platform].mdx
* Add android changes for central logging plugin.
=> feat: Add Android documentation for logging plugin

src/fragments/lib/logging/android/setup_logging/10_pre_req.mdx, src/fragments/lib/logging/ios/setup_logging/10_pre_req.mdx, src/fragments/start/getting-started/android/nextsteps.mdx, src/fragments/start/getting-started/ios/nextsteps.mdx
* Add link to logging in next-steps.
* Add pre-req for minimum Amplify version for logging.
=> chore(logging): Add pre-req for amplify version

src/pages/console/data/data-model.mdx, src/pages/console/formbuilder/data-binding.mdx, src/pages/console/formbuilder/overview.mdx, src/pages/console/formbuilder/special-inputs.mdx
The PR fixes broken studio links
=> fix: broken studio links

src/components/Menu/RepoActions/index.tsx
- For the repo actions, using `aria-label` to provide a more informative text for screen readers for the "feedback" and "edit" links
=> Use aria-label to give more descriptive text for screen reader

src/fragments/cli-config.mdx, src/fragments/lib/project-setup/ios/prereq/prereq.mdx, src/fragments/lib/project-setup/native_common/prereq/common_body.mdx, src/fragments/start/getting-started/common/prereq.mdx
Update the installation command in the library guide for all libraries
=> show the installation command for prereq

src/fragments/lib-v1/auth/native_common/signin_web_ui/common.mdx, src/fragments/lib/auth/native_common/signin_web_ui/common.mdx
updated auth flows code grant link
=> updated auth flows code grant link

src/fragments/lib-v1/debugging/android/dev-menu/usage.mdx, src/fragments/lib-v1/project-setup/android/create-application/10_createProject.mdx, src/fragments/lib-v1/project-setup/android/create-application/20_gradle.mdx, src/fragments/lib-v1/project-setup/android/use-existing-resources/use-existing-resources.mdx, src/fragments/lib/debugging/android/dev-menu/usage.mdx, src/fragments/lib/project-setup/android/create-application/10_createProject.mdx, src/fragments/lib/project-setup/android/create-application/20_gradle.mdx, src/fragments/lib/project-setup/android/use-existing-resources/use-existing-resources.mdx, src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx, src/fragments/sdk/analytics/android/getting-started.mdx, src/fragments/sdk/api/android/graphql.mdx, src/fragments/sdk/pubsub/android/getting-started.mdx, src/fragments/sdk/storage/android/transfer-utility.mdx, src/fragments/start/getting-started/android/add-api.mdx, src/fragments/start/getting-started/android/setup.mdx, src/fragments/start/sample-apps/android/todo-app.mdx
=> fix(misc): Fix for missing or incorrect accessibility text in some images in Android documentation

src/fragments/lib-v1/auth/native_common/signin_web_ui/common.mdx, src/fragments/lib/auth/native_common/signin_web_ui/common.mdx
updated link to remove text highlight
=> updated link to remove text highlight

src/fragments/lib/auth/js/set-up-auth.mdx
Setting up branch for review with PR comments
=> Added expanders and general format

src/pages/console/adminui/extend-cli.mdx
The PR adds info on limitations and adds info about troubleshooting override error that occurs on studio deploy
https://github.com/aws-amplify/amplify-studio/issues/1004
=> feat: add troubleshooting info and limitations for studio

src/directory/directory.mjs, src/fragments/lib/graphqlapi/js/setup/connect.mdx, src/pages/lib/graphqlapi/connect/q/platform/[platform].mdx
=> Updating changes to guide for review

src/directory/directory.mjs, src/fragments/lib/auth/js/enable-signin-signup-signout.mdx, src/fragments/lib/auth/js/set-up-auth.mdx, src/pages/lib/auth/enable_signup_signin_signout/q/platform/[platform].mdx
=> Auth-jtbd-update-abdallah

cspell.json, src/components/YoutubeEmbed/YoutubeEmbed.tsx, src/components/YoutubeEmbed/index.ts, src/components/contribute/QuickstartResources.tsx, src/fragments/cli-config.mdx, src/fragments/guides/hosting/custom-domains.mdx, src/fragments/guides/hosting/nextjs.mdx, src/fragments/guides/hosting/password-protected-deployments.mdx, src/fragments/guides/hosting/pull-request-previews.mdx, src/fragments/lib-v1/datastore/native_common/how-it-works.mdx, src/fragments/lib/datastore/js/getting-started/30_platformIntegration.mdx, src/fragments/lib/datastore/native_common/how-it-works.mdx, src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx, src/pages/console/uibuilder/bestpractices.mdx, src/plugins/import.tsx
- Added a `YoutubeEmbed` component to help streamline setting up an iframe for youtube embeds
- Replaced existing youtube iframes with the `YoutubeEmbed` component
- Updated `cspell.json` to have a regex ignore list so that it ignores the string for the youtube embed Ids
Some testing URLs:
- https://youtube-embed-component.d3kzzkiugubm89.amplifyapp.com/contribute/
-  videos at the bottom of the page
- https://youtube-embed-component.d3kzzkiugubm89.amplifyapp.com/cli/start/install/#configure-the-amplify-cli-version--1080
- https://youtube-embed-component.d3kzzkiugubm89.amplifyapp.com/lib/datastore/getting-started/q/platform/js/#option-1-platform-integration
Which product(s) are affected by this PR …
=> Youtube embed component

src/pages/cli/auth/admin.mdx
update the admin queries example that uses withAuthenticator to `@aws-amplify/ui-react`.
https://ui.docs.amplify.aws/react/connected-components/authenticator
=> fix:update the import in admin auth example

src/fragments/lib/auth/js/getting_started/10_setUpBackendResources.mdx
Update the switcher for Auth resources set up
- [ X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?
- [X ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
=> Update the switcher for Auth resources set up

src/fragments/cli-config.mdx, src/fragments/lib-v1/datastore/native_common/how-it-works.mdx, src/fragments/lib/auth/common/device_features/common.mdx, src/fragments/lib/auth/common/sms/flows.mdx, src/fragments/lib/auth/common/social_signin_web_ui/configure_auth_category.mdx, src/fragments/lib/auth/common/social_signin_web_ui/setup_auth_provider.mdx, src/fragments/lib/auth/flutter/signin_web_ui/20_platform_specific_setup.mdx, src/fragments/lib/datastore/native_common/how-it-works.mdx, src/fragments/lib/project-setup/flutter/platform-setup/ios.mdx, src/fragments/lib/project-setup/flutter/platform-setup/macos.mdx, src/fragments/lib/push-notifications/android/setup_push_service/setup-fcm.mdx, src/fragments/lib/push-notifications/common/enable-rich-notifications.mdx, src/fragments/lib/push-notifications/common/interact_with_notifications/notification-lifecycle.mdx, src/fragments/lib/push-notifications/ios/getting_started/ios-set-entitlements.mdx, src/fragments/lib/storage/flutter/upload.mdx
Alt text was added/improved for the images in the flutter library docs.
Fixes #5714 
=> chore: added alt text for the images in the flutter library docs

Readme.md
=> Accordion readme

src/constants/versions.ts
Version Update for Amplify Android Release v2.12.0
=> Amplify Android Release 2.12.0

src/directory/directory.mjs, src/fragments/common/guide-header.mdx, src/fragments/lib/auth/js/enable-signin-signup-signout.mdx, src/fragments/lib/auth/js/set-up-auth.mdx, src/pages/lib/auth/emailpassword/q/platform/[platform].mdx, src/pages/lib/auth/getting-started/q/platform/[platform].mdx
=> Updated code and small edits

src/fragments/lib/auth/flutter/managing_credentials/10_managing_credentials.mdx
=> chore: add callout to flutter credentials page

src/fragments/lib/auth/js/enable-signin-signup-signout.mdx, src/pages/lib/auth/emailpassword/q/platform/[platform].mdx
=> Update the user attributes

tasks/link-checker.js
Reset the browser and page objects on error
=> reset browser and page on error

src/pages/console/adminui/start.mdx
=> improved banner message

src/pages/cli/graphql/troubleshooting.mdx
Add troubleshooting step for disabling iterative deployment gsi limit check.
This aligns with proposed CLI update https://github.com/aws-amplify/amplify-cli/pull/13172
https://github.com/aws-amplify/amplify-category-api/issues/1812
=> chore: add troubleshooting callout for disabling gsi limit check [amplify-cli]

src/fragments/lib-v1/analytics/js/getting-started/30_initAnalytics.mdx, src/fragments/lib-v1/analytics/js/identifyuser.mdx, src/fragments/lib-v1/analytics/js/record.mdx, src/fragments/lib-v1/analytics/native_common/getting-started/common.mdx, src/fragments/lib-v1/v6/callout/analytics-providers.mdx
This change includes the final docs updates for the Analytics category in v6 Dev Preview.
=> feat: Final Analytics Dev Preview docs

src/fragments/lib-v1/v6/callout/auth-authenticator-support.mdx, src/pages/lib-v1/auth/getting-started/q/platform/[platform].mdx
This PR updates the "Set up Amplify Auth" page to reflect v6.
Changes:
- Removed references to authenticator & Studio
- Added call out about authenticator support
=> feat: Update "Set up Amplify Auth" page

src/components/Menu/index.tsx, src/directory/directory.mjs, src/fragments/lib-v1/utilities/js/hub.mdx, src/pages/lib-v1/utilities/hub/q/platform/[platform].mdx
A few chores:
- Remove RN from dev preview menu
- Add Hub documentation
- Fix a linking issue in Troubleshooting
=> chore: Remove RN from lib-v1, add Util > Hub, fix TS

src/fragments/lib-v1/v6/callout/auth-federation.mdx, src/pages/lib-v1/auth/switch-auth/q/platform/[platform].mdx
This change updates the documentation on the "Switching authentication flows" page. Removed all references to federation, which is not supported in dev preview.
It should be safe to modify the generic file for this page as no other platforms have this page with a `lib-v1` route.
=> feat: Add "Switching authentication flows" Dev Preview documentation

src/directory/directory.mjs, src/fragments/lib-v1/auth/js/overview.mdx, src/pages/lib-v1/auth/overview/q/platform/[platform].mdx
Updates the Under the Hood Auth page for dev preview. 
This new file is a direct copy of the existing one with the following changes:
- Removed federation information & added call-out
- Updated inline API references
Also removed `react-native` from Auth Dev Preview pages in the directory.
=> feat: Update the Under the Hood Auth page

src/fragments/guides/hosting/git-based-deployments.mdx
Fixed a few typos.
- [x ] amplify-hosting
=> Hosting: Minor editorial fixes for git-based-deployments.mdx

src/fragments/lib-v1/storage/js/copy.mdx, src/fragments/lib-v1/storage/js/getting-started.mdx, src/fragments/lib-v1/storage/js/list.mdx, src/fragments/lib-v1/storage/js/remove.mdx
Update Storage list, copy, remove API docs
=> chore(storage): cleanup

src/pages/lib-v1/auth/social/q/platform/[platform].mdx
This PR adds documentation for the `signInWithRedirect` API.
=> feat: Added social signin docs

src/pages/lib-v1/auth/emailpassword/q/platform/[platform].mdx
Adds documentation for the sign-in, sign-up, and sign-out APIs.
=> feat: Added sign in, sign up, and sign out API documentation

src/fragments/lib-v1/start/getting-started/vue/setup.mdx, src/pages/lib-v1/q/platform/[platform].mdx
Cleans up the intro sections for Dev Preview docs.
=> chore: Clean up intro sections.

src/directory/directory.mjs, src/fragments/lib-v1/storage/js/download.mdx, src/fragments/lib-v1/storage/js/transfer-acceleration.mdx, src/fragments/lib-v1/storage/js/upload.mdx, src/pages/lib-v1/storage/transfer-acceleration/q/platform/[platform].mdx, src/pages/lib-v1/storage/upload/q/platform/[platform].mdx
Add the following changes to Js lib-v1 : Storage
- Add transfer acceleration page to storage
- Fix upload data page
- Remove `targetIdentityId` option from uploadData API 
=> feat(storage): add transfer-acceleration to js v6

Readme.md
Updating the README to include content about using `<InlineFilter>`s from @heatheramz 
=> Adding InlineFragment content

src/fragments/lib-v1/ssr/nextjs/version-range-callout.mdx, src/pages/lib-v1/q/platform/[platform].mdx
Tweaks some wording on the Amplify Libraries page based on feedback.
=> chore: Tweak Amplify Libraries wording

src/fragments/lib-v1/auth/js/advanced.mdx, src/fragments/lib-v1/auth/js/common_prereq.mdx, src/pages/lib-v1/auth/getting-started/q/platform/[platform].mdx, src/pages/lib-v1/auth/social/q/platform/[platform].mdx
Tweaks to various Auth pages based on docs feedback.
=> chore: Updated Auth pages

src/pages/lib-v1/auth/emailpassword/q/platform/[platform].mdx
=> chore: Add return values for signUp, signIn, and confirmSignUp APIs

src/pages/guides/functions/graphql-server-in-lambda/q/platform/[platform].mdx
=> updated Apollo Server Lambda link

src/fragments/lib/auth/js/react-native-social.mdx, src/fragments/lib/utilities/serviceworker.mdx
**broken link** - https://aws-amplify.github.io/amplify-js/docs/api/classes/serviceworkerclass.html
**parentUrl** - https://docs.amplify.aws/lib/utilities/serviceworker/q/platform/js/
**linkText** - API Reference
**fixed url** - https://aws-amplify.github.io/amplify-js/api/classes/serviceworkerclass.html
**Page with updated link:**
**Links to:**
**broken link** - https://docs.expo.io/versions/latest/workflow/linking/#linking-to-your-app
**parentUrl** - https://docs.amplify.aws/lib/auth/social/q/platform/react-native/
**linkText** - in the Expo client
**fixed url** - https://docs.expo.dev/guides/linking/#linking-to-your-app
**Page with updated link:**
**Links to:** 
Which product(s) are affected by …
=> fix: broken external links

src/pages/lib/auth/mfa/q/platform/[platform].mdx
=> fix: JTBD Auth MFA changes

src/pages/lib/auth/manage-session/q/platform/[platform].mdx
=> fix: JTBD Auth ManageUserSession

src/pages/lib/graphqlapi/mutate-data/q/platform/[platform].mdx
=> JTBD Guide Review for Create, update, and delete application data

src/pages/lib/graphqlapi/query-data/q/platform/[platform].mdx
=> JTBD Guide Review for Read application data

src/pages/lib/graphqlapi/subscribe-data/q/platform/[platform].mdx
=> JTBD Guide Review for Subscribe to real-time events

package.json, yarn.lock
- Add resolution for `zod: 3.22.3`
=> Add resolution for zod 3.22.3

src/pages/cli/graphql/authorization-rules.mdx
=> added iam fix reference

src/pages/cli/graphql/authorization-rules.mdx
=> Updated `group` key name and fixed links

src/pages/lib/auth/social/q/platform/[platform].mdx
=> fix: JTBD Auth Social SignIn

src/pages/lib/auth/manageusers/q/platform/[platform].mdx
=> fix: JTBD Auth ManageUsersProfile

src/pages/lib/auth/password_management/q/platform/[platform].mdx
=> fix: JTBD Auth Password

src/pages/lib/auth/delete_user/q/platform/[platform].mdx
=> fix: JTBD Auth Delete User

.github/CODEOWNERS, .github/workflows/build.yml, amplify.yml, package.json, src/fragments/lib/auth/js/advanced.mdx, src/pages/cli/graphql/authorization-rules.mdx, src/pages/console/adminui/extend-cli.mdx, src/utils/track.ts, yarn.lock
Merge the latest from main into next-release/main
=> chore(next-release/main): merge latest from main

src/pages/cli/graphql/overview.mdx
=> Correcting CDK sample schema

.github/workflows/check_bundle_size.yml, .github/workflows/check_for_new_fragments.yml, .github/workflows/scripts/check_bundle_size.js, next.config.mjs, package.json, yarn.lock
GitHub action to check bundle size of below selected pages on PR branch vs on main branch. PR to fail if bundle size increases by +5% on any of the selected pages.
- `/cli`
- `/cli/start/install`
- `/lib/auth/getting-started/q/platform/[platform]`
- `/start`
- `/cli`
Example failure from testing on my local fork (with console logs):
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> GH action to check bundlesize of PR

src/pages/lib/auth/social/q/platform/[platform].mdx
=> fix: JTBD Auth Social SignIn - final RN changes

src/components/FeaturesGrid/index.tsx, src/components/Hero/styles.tsx, src/components/WhatsNewBanner/index.tsx, src/components/WhatsNewBanner/styles.tsx, src/pages/index.tsx
- Added new "what's new banner" to share latest features
- Hides on mobile to not disrupt small screen real estate
N/A
Desktop
Mobile:
=> Added What's New Banner

src/pages/cli/graphql/data-modeling.mdx
=> Be more explicit on 1:1 belongsTo relationship requirements

src/pages/lib/auth/ssr/q/platform/[platform].mdx
=> chore: JTBD Auth SSR

src/data/platforms.ts
Adds all of the other platforms.
=> chore(next-release/main): add all platforms

package.json, yarn.lock
Staging site: https://dependabot-60.d1egzztxsxq9xz.amplifyapp.com/
https://github.com/aws-amplify/docs/security/dependabot/60
=> fix: updating @babel/traverse

src/pages/lib/auth/auth-events/q/platform/[platform].mdx
=> chore: JTBD Auth Events

src/pages/gen2/README.mdx
=> Update readme and simplify menu structure

src/fragments/lib/auth/js/react-native-social.mdx, src/pages/lib/graphqlapi/connect/q/platform/[platform].mdx
=> JTBD Guide Review for Connect your app code to the API

.github/workflows/check_pr_for_broken_links.yml, mdx-components.tsx, src/components/Banner/Banner.tsx, src/styles/banner.scss, src/styles/layout.scss, tasks/generate-sitemap.mjs
=> Banner updates

src/styles/banner.scss
Fixes the gen2 banner button stretching weird on large viewports.
**Before**
**After**
=> fix(next-release/main): update banner button layout for large viewports

amplify.yml
=> add debugging line to ampliy.yml

src/components/FeatureLists/FeatureList.tsx, src/components/FeatureLists/FeatureLists.tsx, src/components/FeatureLists/PlatformFeatureList.tsx, src/styles/feature-links.scss
=> chore: update feature-lists, remove unneeded css, allow title to be customized

src/components/Overview/Overview.tsx, src/pages/_app.tsx
- Fix bugs with overview component
- Bug where the overview component was showing child pages that did not exist for the specific platform
- Clicking on the child card navigates to the page but doesn't display the content
Staging: https://overview-fixes.d1egzztxsxq9xz.amplifyapp.com/
To test:
1. Go to https://overview-fixes.d1egzztxsxq9xz.amplifyapp.com/javascript/get-started/tutorials/
2. Click on any of the child cards and verify that the page is routed to the correct one and that it shows the respective content
3. Click on "Home" in the breadcrumbs and verify that it takes you back to home and shows the content
4. Go to: https://overview-fixes.d1egzztxsxq9xz.amplifyapp.com/javascript/build-a-backend/
- Verify that for `javascript` there is only the "API (Rest)" page since the api …
=> Overview fixes

src/styles/link-card.scss
Staging site: https://fix-link-card.d3dchdtz73jhjz.amplifyapp.com 
fix: link-card style
=> fix: fix link card component style

src/styles/popover.scss, src/styles/split-button.scss, src/themes/baseTheme.ts
https://buttonsizingradii.d2bfwhpcsj9awv.amplifyapp.com/
=> Button sizing radii

src/styles/base.scss, src/styles/feature-links.scss, src/styles/footer.scss, src/styles/framework-grid.scss, src/styles/link-card.scss
Just consolidating some of our link styles and a little clean up here and there.
https://linkstylecleanup.d2bfwhpcsj9awv.amplifyapp.com/
=> chore(next-release/main): clean up some of the duplicate link styles

src/components/CliCommands/Command.tsx, src/components/CliCommands/CommandHeading.tsx, src/components/CliCommands/index.ts, src/components/Layout/Layout.tsx, src/components/MDXComponents/MDXCode.tsx, src/directory/directory.mjs, src/pages/[platform]/tools/cli/commands.tsx, src/pages/[platform]/tools/cli/index.mdx, src/pages/[platform]/tools/index.mdx, src/styles/commands.scss, src/styles/styles.scss
- Add components to build CLI commands page
- Set up IA for CLI commands page
Staging site: https://cli-commands-page.d1ywzrxfkb9wgg.amplifyapp.com/javascript/tools/cli/commands/
=> Add components to build CLI commands page

src/pages/[platform]/build-a-backend/api-rest/index.mdx, src/pages/[platform]/build-a-backend/index.mdx, src/pages/[platform]/build-a-ui/index.mdx, src/pages/[platform]/get-started/index.mdx, src/pages/[platform]/get-started/project-setup/index.mdx, src/pages/[platform]/get-started/sample-apps/index.mdx, src/pages/[platform]/get-started/tutorials/connect-api-and-database.mdx, src/pages/[platform]/get-started/tutorials/deploy-and-host-app.mdx, src/pages/[platform]/get-started/tutorials/index.mdx, src/pages/[platform]/get-started/tutorials/next-steps.mdx, src/pages/[platform]/get-started/tutorials/setup-amplify.mdx, src/pages/[platform]/get-started/tutorials/setup-fullstack-project.mdx
- Add the other platforms to the existing sample pages so that the Menu builds them out
Staging site: https://sample-ia-platforms.d1ywzrxfkb9wgg.amplifyapp.com/
=> chore: Add other platforms to the existing sample pages

src/directory/directory.mjs, src/fragments/lib-v1/interactions/js/chatbot.mdx, src/fragments/lib-v1/interactions/js/frontend.mdx, src/fragments/lib-v1/interactions/js/getting-started.mdx, src/fragments/lib/interactions/js/chatbot.mdx, src/fragments/lib/interactions/js/frontend.mdx, src/fragments/lib/interactions/js/getting-started.mdx, src/pages/lib-v1/interactions/chatbot/index.mdx, src/pages/lib-v1/interactions/chatbot/q/platform/[platform].mdx, src/pages/lib-v1/interactions/getting-started/index.mdx, src/pages/lib-v1/interactions/getting-started/q/platform/[platform].mdx
- update documention of interactions for amplify-js v6
=> update interactions doc for amplify-js v6

.github/CODEOWNERS, Readme.md
=> Revert "Chore: Update codeowners file to exclude documentation team for approvals on cspell json file changes"

src/directory/directory.mjs, src/fragments/lib-v1/pubsub/js/getting-started.mdx, src/fragments/lib-v1/pubsub/js/publish.mdx, src/fragments/lib-v1/pubsub/js/subunsub.mdx, src/fragments/lib/pubsub/js/getting-started.mdx, src/fragments/lib/pubsub/js/publish.mdx, src/pages/lib-v1/pubsub/getting-started/index.mdx, src/pages/lib-v1/pubsub/getting-started/q/platform/[platform].mdx, src/pages/lib-v1/pubsub/publish/index.mdx, src/pages/lib-v1/pubsub/publish/q/platform/[platform].mdx, src/pages/lib-v1/pubsub/subunsub/index.mdx, src/pages/lib-v1/pubsub/subunsub/q/platform/[platform].mdx
- Adding PubSub v6 documentation
- Porting old V5 documentation for PubSub to the V5 tab
=> chore(pubsub): Update v6 docs and port V5 content to lib-v1

src/components/Banner/Banner.tsx
=> chore(next-release/main): update gen2 banner text

src/themes/baseTheme.ts
=> chore(next-release/main): shrink font ramp

src/fragments/lib/predictions/js/getting-started.mdx, src/fragments/lib/predictions/js/sample.mdx
Fixes code samples for importing amplifyconfig.
=> fix(predictions): add .json to amplifyconfiguration imports

src/components/GlobalNav/GlobalNav.tsx, src/components/GlobalNav/components/AmplifyNavLink.tsx
- Update gen2 banner title
- Remove unused imports in GlobalNav component
=> chore(next-release/main): update gen2 header, remove unused imports

src/pages/[platform]/build-a-backend/auth/index.mdx, src/pages/[platform]/build-a-backend/datastore/index.mdx, src/pages/[platform]/build-a-backend/functions/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/index.mdx, src/pages/[platform]/build-a-backend/index.mdx, src/pages/[platform]/build-a-backend/more-features/logging/index.mdx, src/pages/[platform]/build-a-backend/push-notifications/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx, src/pages/[platform]/build-a-backend/storage/index.mdx, src/pages/[platform]/build-a-backend/troubleshooting/index.mdx, src/pages/[platform]/build-ui/index.mdx, src/pages/[platform]/start/getting-started/index.mdx, src/pages/[platform]/start/index.mdx, src/pages/[platform]/start/project-setup/index.mdx, src/pages/[platform]/start/sample-apps/index.mdx, src/pages/[platform]/tools/cli/start/index.mdx, src/pages/[platform]/tools/index.mdx
staging site: https://summarypages.dmhjrabi3pkql.amplifyapp.com/
=> update summary pages

src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx
=> fix(flutter/analytics): temporarily remove broken url

src/pages/[platform]/build-a-backend/test-notifications/index.mdx, src/pages/[platform]/prev/build-a-backend/datastore/how-it-works/index.mdx
- Saw the spellcheck workflow was failing for this PR so made the fixes to it
=> Fix spellcheck for pagemigrationupdates branch

src/fragments/lib/interactions/js/frontend.mdx, src/fragments/lib/predictions/js/getting-started.mdx, src/fragments/lib/pubsub/js/getting-started.mdx
=> updated callouts for matching scopes package to umbrella package

src/directory/directory.mjs, src/fragments/lib-v1/analytics/js/autotrack/autotrack.mdx, src/fragments/lib-v1/analytics/js/getting-started/30_initAnalytics.mdx, src/fragments/lib-v1/analytics/js/personalize.mdx, src/fragments/lib/analytics/js/autotrack/autotrack.mdx, src/fragments/lib/analytics/js/autotrack/page-tracking.mdx, src/fragments/lib/analytics/js/enable-disable/disable.mdx, src/fragments/lib/analytics/js/enable-disable/enable.mdx, src/fragments/lib/analytics/js/getting-started/12_amplifyConfig.mdx, src/fragments/lib/analytics/js/personalize.mdx, src/fragments/lib/analytics/js/storing.mdx, src/fragments/lib/analytics/js/streaming.mdx, src/pages/lib-v1/analytics/personalize/index.mdx, src/pages/lib-v1/analytics/storing/index.mdx, src/pages/lib/analytics/autotrack/q/platform/[platform].mdx, src/pages/lib/analytics/enable-disable/q/platform/[platform].mdx, src/pages/lib/analytics/personalize/index.mdx, src/pages/lib/analytics/personalize/q/platform/[platform].mdx, src/pages/lib/analytics/record/q/platform/[platform].mdx, src/pages/lib/analytics/storing/index.mdx, src/pages/lib/analytics/storing/q/platform/[platform].mdx, src/pages/lib/analytics/streaming/index.mdx, src/pages/lib/analytics/streaming/q/platform/[platform].mdx
- update analytics doc for amplify-js V6
=> update analytics doc for amplify-js v6

src/fragments/lib-v1/storage/js/existing-resources.mdx, src/pages/lib/storage/existing-resources/q/platform/[platform].mdx
- fix wrong V5 links in storage "existing resources" page
- update V6 "existing resources" page
=> fix(storage): Use existing AWS resources

src/fragments/lib/auth/common/device_features/common.mdx, src/fragments/lib/auth/js/device_features/10_rememberDevice.mdx, src/fragments/lib/auth/js/device_features/20_forgetDevice.mdx, src/fragments/lib/auth/js/device_features/30_fetchDevice.mdx, src/fragments/lib/auth/js/getting-started-rn.mdx, src/fragments/lib/auth/js/overview.mdx, src/fragments/lib/auth/js/switch-auth.mdx, src/pages/lib/auth/auth-events/q/platform/[platform].mdx, src/pages/lib/auth/delete_user/q/platform/[platform].mdx, src/pages/lib/auth/emailpassword/q/platform/[platform].mdx, src/pages/lib/auth/getting-started/q/platform/[platform].mdx, src/pages/lib/auth/manage-session/q/platform/[platform].mdx, src/pages/lib/auth/manageusers/q/platform/[platform].mdx, src/pages/lib/auth/mfa/q/platform/[platform].mdx, src/pages/lib/auth/password_management/q/platform/[platform].mdx, src/pages/lib/auth/social/q/platform/[platform].mdx
Pages added:
- Set up Amplify Auth
- Manage user profiles
- Set up user password change and recovery
- Switching authentication flows
- Listen to auth events
- Remember a device
- Delete user account
- Under the hood
=> feat(auth): add final auth docs batch

src/fragments/lib/predictions/js/getting-started.mdx, src/fragments/lib/predictions/js/identify-text.mdx, src/fragments/lib/predictions/js/label-image.mdx
=> fix: amplify/.backend should be amplify/backend, conform to styleguide

src/fragments/lib/auth/js/advanced.mdx
Updates the V6 content for advanced workflows for JS and RN
=> feat(auth): Auth advanced workflows for JS and RN

src/pages/[platform]/index.tsx
- Reuse `home-cta` class, originally for the home page to make the CTA buttons have flex column when on smaller screens
Staging site: https://fix-cta-buttons.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://fix-cta-buttons.d1ywzrxfkb9wgg.amplifyapp.com/javascript
2. Make the browser width small and verify that the CTA buttons switch to a flex column layout
_By submitting this pull request, I confirm that my contribution is made …
=> Make cta buttons on platform "overview" page have flex column layout on smaller screens

src/styles/algolia.scss, src/styles/base.scss
=> css tweaks for search

.github/workflows/check_for_console_errors.yml, package.json, tasks/console-errors.js, tasks/get-sitemap-links.js, yarn.lock
=> Console errors

src/components/GetStartedPopover/GetStartedPopover.tsx, src/pages/[platform]/start/getting-started/introduction/index.mdx
Staging site: https://update-getting-started-links.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to the staging site and test out the getting started button and the dropdown menu
2. It should take you to the introduction page
=> Add updated geting started links

src/fragments/lib/datastore/js/getting-started/10_preReq.mdx, src/fragments/lib/geo/js/search.mdx
=> fix: update recommended cli version in datastore and geo

src/components/Accordion/icons.tsx
We are doing these changes to fix the `console errors` https://github.com/aws-amplify/docs/actions/runs/6580015445/job/17877101477?pr=5966
`Staging site` : https://svg-fix.d3r4kml651kqcm.amplifyapp.com/
=> fix: <svg> attribute height: Expected length, unset.

src/fragments/lib/predictions/js/sample.mdx
=> fix(Predictions): fix issue with pollyfills incompatible with vite & mjs

src/pages/console/authz/permissions.mdx
Added alternate property for the image
Fix: Failed to load resource: the server responded with a status of 404 (Not Found) found on http://localhost:3000/console/authz/permissions/
We are doing these changes to fix the console errors https://github.com/aws-amplify/docs/actions/runs/6580015445/job/17877101477?pr=5966
=> fix: add alternate property for images to fix the server responded width a status of 404

src/pages/lib/auth/getting-started/q/platform/[platform].mdx
=> fix(Auth): update required versions

Readme.md, src/pages/[platform]/start/getting-started/data-model/index.mdx
=> fix fragments

src/styles/menu.scss
- Update font size for "page" class
- Make subcategories have bold text
Staging site: https://fix-menu-font-size.d1ywzrxfkb9wgg.amplifyapp.com/
=> Update font sizes and weight for menu

src/pages/[platform]/build-a-backend/auth/manage-user-session/index.mdx
=> Fixes for https://github.com/aws-amplify/amplify-js/pull/12533/files

src/styles/callout.scss
- Add a `min-width: 0` to the callout content
Staging site: https://callout-content-fix.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/more-features/predictions/example-app/
=> Fix content in callout overflowing

src/styles/block-switcher.scss
- Added a border to the block switcher component (as well as some padding)
Staging links to look at the block switcher:
- https://update-blockswitcher-border.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/auth/enable-sign-up/
- This one has code blocks in the block switchers 
- https://update-blockswitcher-border.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/auth/add-social-provider/
- This one has some block switchers with a numbered list in them and pictures  …
=> Add border to block-switcher and some padding

src/components/PlatformNavigator/index.tsx, src/styles/platform-navigator.scss
=> small css tweaks

src/styles/version-switcher.scss
Before:
https://github.com/aws-amplify/docs/assets/376920/5a851605-4729-4fc5-b565-1b7df82e4096
After:
https://github.com/aws-amplify/docs/assets/376920/da062875-37e9-46aa-afef-9c01d9987ade
=> fix(next-release/main): fix focus overlap on version switcher

src/pages/contribute/getting-started.tsx
=> chore: fix typo on the contribute getting-started page

src/styles/home.scss
Increases the max width of the home page intro text paragraph
**before**
**after**
=> fix(next-release/main): increase home content paragraph text width

src/components/Layout/Layout.tsx, src/pages/[platform]/index.tsx, src/pages/index.tsx
- Update `Amplify Docs` to `Amplify Documentation`
Staging site: https://update-docs-to-documentation.d1ywzrxfkb9wgg.amplifyapp.com/
=> Update Amplify Docs to Amplify Documentation

src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx
Fixes and additional examples to Gen2 Custom Resources Docs
[● JTBD Guides and Samsara Docs KANBAN - vNext Guides - Add any AWS Svc - Custom Resources - Asana](https://app.asana.com/0/1205212189033571/1205381356323141)
=> Fixes and additional examples to Gen2 Custom Resources Docs

src/directory/generateDirectory.mjs
- The script still wasn't generating the correct routes on windows and this was because the relative path being created was still using paths with `\\`. With this change, we convert this relative path into a POSIX path with forward slashes `/` so that it can be used for our `route` property to help next.js link everything
Staging site: https://update-generate-directory-script.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Pull down the branch and run `yarn dev`
2. Verify everything still works normally and that the `directory.json` gets generated correctly …
=> Update generate directory script to handle windows paths

src/directory/directory.mjs, src/pages/[platform]/tools/cli-legacy/graphql-transformer/auth-directive/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/connection-directive/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/directives/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/key-directive/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/overview/index.mdx, src/pages/[platform]/tools/cli-legacy/graphql-transformer/versioned-directive/index.mdx
=> fixed legacy CLI links + nav

src/pages/[platform]/build-a-backend/restapi/index.mdx, src/pages/[platform]/cli/tools/auth/admin-actions/index.mdx
Updated some files to get overview component to work
Staging site: https://reesscot-patch-overview-pages.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/restapi/
=> chore: add missing overview card links to pages

src/pages/[platform]/build-ui/formbuilder/special-inputs/index.mdx, src/pages/[platform]/build-ui/uibuilder/bestpractices/index.mdx, src/pages/[platform]/build-ui/uibuilder/collections/index.mdx, src/pages/[platform]/build-ui/uibuilder/override/index.mdx, src/pages/[platform]/build-ui/uibuilder/responsive/index.mdx, src/pages/[platform]/build-ui/uibuilder/slots/index.mdx, src/pages/[platform]/build-ui/uibuilder/theming/index.mdx
=> Minor content/layout updates to pages in Build UI

src/components/NextPrevious/index.tsx
Adding next/prev to project-setup, figma-to-code, and form-builder sections
staging site: https://next-release-next-prev-sections.dmhjrabi3pkql.amplifyapp.com/
=> add next/prev to more sections

src/components/Layout/Layout.tsx
update search to send gen2 as platform for gen2 pages
staging site: https://update-gen2-search.dmhjrabi3pkql.amplifyapp.com/
=> send gen2 as platform for gen2 pages

src/directory/directory.mjs
=> fix legacy nav

src/styles/code.scss
Removes the glow-ey shadow thing from gen2 code examples, it's a little over the top.
**before**
**after**
=> fix(next-release/main): remove gen2 specific code example styles

src/directory/directory.mjs, src/fragments/guides/hosting/custom-domains.mdx, src/fragments/guides/hosting/git-based-deployments.mdx, src/fragments/guides/hosting/local-deployments.mdx, src/fragments/guides/hosting/password-protected-deployments.mdx, src/fragments/guides/hosting/pull-request-previews.mdx, src/pages/[platform]/deploy-and-host/custom-configuration/index.mdx, src/pages/[platform]/deploy-and-host/deployment/index.mdx
=> Updates to Deploy and host

mdx-components.tsx, src/pages/[platform]/build-ui/uibuilder/override/index.mdx
This will replace `HTML table` with Grid component to make it responsive in `UI builder `section.
We have lot of prettier changes in this pr!
Staging site: [https://table-width-issue...amplifyapp.com](https://table-width-issue.d1ywzrxfkb9wgg.amplifyapp.com/)
Testing URL: https://table-width-issue.d1ywzrxfkb9wgg.amplifyapp.com/react-native/build-ui/uibuilder/override/#extend-generated-components-via-overrides-prop
_By submitting this …
=> fix: make table responsive in ui builder section

src/styles/code.scss
=> fix(next-release/main) fix code in headers

src/components/NextPrevious/index.tsx
Adding Next/Prev to build a backend and tools sections
Staging site: https://addition-next-prev.dmhjrabi3pkql.amplifyapp.com/
=> Addition next prev

src/components/MDXComponents/MDXLink.tsx, src/pages/[platform]/tools/console/adminui/start/index.mdx, src/pages/[platform]/tools/console/index.mdx
Fixed parsing issue in links with hashes and `("https` instances
staging: https://broken-link-patch.d1egzztxsxq9xz.amplifyapp.com/
- `("http` example: https://broken-link-patch.d1egzztxsxq9xz.amplifyapp.com/javascript/tools/console/adminui/start/ - see link at "AWS Free Tier"
- `/#` example: https://broken-link-patch.d1egzztxsxq9xz.amplifyapp.com/javascript/build-a-backend/auth/configure-auth/ - see link at "more documentation on adding each social provider in the Libraries section"
_ref: MDX: …
=> fix: patch for broken link fix

src/constants/versions.ts
=> chore: Update Android Version (next)

src/components/Banner/ClassicBanner.tsx
Need to fix the typo in `Classic Banner` text
Staging site: https://fix-banner.d1ywzrxfkb9wgg.amplifyapp.com 
=> fix: change description of docs2 banner

src/components/FeatureLists/PlatformFeatureList.tsx, src/constants/feature-lists-data.ts
This will add the content URLS for `featurelist` components
We can successfully verify the links since they are added as relative thanks to @reesscot 
Staging Site: https://featurte-list-urls.d1ywzrxfkb9wgg.amplifyapp.com/
Some test cases 
- React native is using the same as the other JS pages (enable-sign-up). Only swift, android, and flutter use the enable-sign-in page
- Cloud-connected UI components of Storage available only for  `React/Javascript`.
HTML: `<a …
=> feat: added required urls for feature lists

src/pages/[platform]/build-a-backend/graphqlapi/connect-from-server-runtime/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
=> fix(js-ssr): in page links and add missing imports

src/pages/[platform]/build-a-backend/more-features/analytics/index.mdx, src/pages/[platform]/build-a-backend/more-features/datastore/index.mdx, src/pages/[platform]/build-a-backend/more-features/geo/index.mdx, src/pages/[platform]/build-a-backend/more-features/interactions/index.mdx, src/pages/[platform]/build-a-backend/push-notifications/index.mdx, src/pages/[platform]/prev/build-a-backend/more-features/analytics/index.mdx, src/pages/[platform]/prev/build-a-backend/more-features/datastore/index.mdx, src/pages/[platform]/prev/build-a-backend/more-features/geo/index.mdx, src/pages/[platform]/prev/build-a-backend/more-features/interactions/index.mdx, src/pages/[platform]/prev/build-a-backend/push-notifications/index.mdx, src/pages/[platform]/sdk/analytics/index.mdx, src/pages/[platform]/sdk/push-notifications/index.mdx
=> Cards for more-features

src/fragments/lib/troubleshooting/common/upgrading.mdx, src/pages/[platform]/build-a-backend/troubleshooting/upgrade-amplify-packages/index.mdx
* Reformatted the source code using the repo recommended extension and prettier rules
* Fixed example code snippet formatting
* Updated v5 vs v6 examples to match their use case for the purpose of migration guide
* Removed the "upgrade to v6 developer preview" section
=> chore(js-v6): fixing minor issues in the migration guide

src/fragments/lib/auth/js/advanced.mdx
=> Adds token provider instructions

src/fragments/lib-v1/analytics/ios/identifyuser.mdx, src/fragments/lib-v1/geo/js/geofences.mdx, src/fragments/lib-v1/geo/js/search.mdx, src/fragments/lib-v1/utilities/serviceworker.mdx, src/fragments/lib/datastore/native_common/real-time.mdx, src/fragments/lib/graphqlapi/js/query-data.mdx, src/pages/[platform]/tools/cli/usage/containers/index.mdx
=> chore: fix more broken links

src/components/Menu/MenuItem.tsx, src/directory/directory.mjs, src/pages/[platform]/reference/flutter-api/index.mdx
staging: https://next-release-references.d1egzztxsxq9xz.amplifyapp.com/
=> adding platform specific reference link to menu

src/fragments/lib-v1/geo/android/maps/20_display_map.mdx, src/fragments/lib-v1/geo/android/search/30_location_search_map.mdx, src/fragments/lib-v1/geo/ios/maps/10_install_adapter.mdx, src/fragments/lib-v1/geo/js/geofences.mdx, src/fragments/lib-v1/geo/js/maps.mdx, src/fragments/lib-v1/geo/js/search.mdx, src/fragments/lib-v1/geo/native_common/search/common.mdx, src/fragments/lib/geo/android/maps/20_display_map.mdx, src/fragments/lib/geo/android/search/30_location_search_map.mdx, src/fragments/lib/geo/ios/maps/10_install_adapter.mdx, src/fragments/lib/geo/js/geofences.mdx, src/fragments/lib/geo/js/maps.mdx, src/fragments/lib/geo/js/search.mdx, src/fragments/lib/geo/native_common/maps/common.mdx, src/fragments/lib/geo/native_common/search/common.mdx, src/fragments/lib/graphqlapi/graphql-from-node.mdx, src/fragments/lib/graphqlapi/ios/upgrade-guide.mdx, src/fragments/lib/graphqlapi/js/upgrade-guide.mdx, src/fragments/lib/troubleshooting/common/upgrading.mdx, src/pages/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/troubleshooting/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/upgrade-guide/index.mdx, src/pages/[platform]/build-a-backend/more-features/geo/configure-location-search/index.mdx, src/pages/[platform]/build-a-backend/more-features/geo/configure-maps/index.mdx, src/pages/[platform]/tools/cli-legacy/auth-directive/index.mdx, src/pages/[platform]/tools/cli-legacy/storage/index.mdx
=> fix most remaining links

src/fragments/lib/troubleshooting/common/upgrading.mdx
=> fix: fix utils examples in upgrade guide

src/components/Layout/Layout.tsx, src/constants/algolia.ts
=> turn on search and point to prod

src/pages/[platform]/start/getting-started/index.mdx, src/pages/[platform]/start/project-setup/index.mdx
=> Updated description text for Getting started and Project setup

src/pages/[platform]/build-a-backend/graphqlapi/connect-to-api/index.mdx, src/pages/[platform]/prev/build-a-backend/graphqlapi/connect-to-api/index.mdx
=> Fix inline filters and project setup links

src/pages/[platform]/start/getting-started/setup/index.mdx
=> fix(nextjs): configure Amplify misses App Router specifics

src/pages/[platform]/build-a-backend/more-features/predictions/example-app/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/identify-entity/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/identify-text/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/interpret-sentiment/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/label-image/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/set-up-predictions/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/text-to-speech/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/transcribe-audio/index.mdx, src/pages/[platform]/build-a-backend/more-features/predictions/translate/index.mdx
=> fix(predictions): remove rn docs

src/pages/gen2/build-a-backend/auth/delete-user-account/index.mdx
Updating and ensuring Gen2 backlinks
=> Update Gen2 Delete User

src/pages/gen2/how-amplify-works/concepts/index.mdx
=> Change up code, make less marketing-y

src/pages/[platform]/tools/cli/graphqlapi/index.mdx
Adding route so that overview component will render
=> add route to cli/graphqlapi overview page

src/pages/gen2/build-a-backend/auth/delete-user-account/index.mdx, src/pages/gen2/build-a-backend/index.mdx, src/pages/gen2/build-a-backend/storage/index.mdx, src/pages/gen2/deploy-and-host/hosting/index.mdx, src/pages/gen2/deploy-and-host/index.mdx, src/pages/gen2/deploy-and-host/sandbox-environments/features/index.mdx, src/pages/gen2/deploy-and-host/sandbox-environments/setup/index.mdx, src/pages/gen2/start/manual-installation/index.mdx
=> Edits initial review auth fs branch storage

src/pages/gen2/deploy-and-host/fullstack-branching/pr-previews/index.mdx, src/pages/gen2/reference/cdk-constructs/index.mdx, src/pages/gen2/reference/cli-commands/index.mdx
=> Edits p rpreviews

src/pages/[platform]/build-a-backend/graphqlapi/best-practice/index.mdx
Parent page has a single child. Parent specifics extra platforms which child does not resulting in blank page for those platforms
=> fix(graphqlapi best-practice): remove blank page for flutter, rn

src/pages/gen2/build-a-backend/storage/index.mdx
Fix during technical review.
https://app.asana.com/0/1205212189033571/1205381356323139/f
=> fix: Storage page to update getStack -> createStack since the API was recently updated

src/pages/[platform]/build-a-backend/storage/list/index.mdx
fix storage `list` method code snippet
=> fix storage list code snippet

src/pages/gen2/build-a-backend/storage/index.mdx
=> gen2-storage-edits

src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx
=> Update set up auth

src/pages/gen2/build-a-backend/auth/override-cognito/index.mdx
=> Update override page

src/pages/gen2/how-amplify-works/faq/index.mdx, src/pages/gen2/start/manual-installation/index.mdx
=> manual install

src/pages/gen2/build-a-backend/data/override-resources/index.mdx
https://app.asana.com/0/1205212189033571/1205212939610124/f
=> feat: Migrate Modify Amplify-generated resources to Gen2

src/pages/gen2/build-a-backend/data/set-up-data/index.mdx
=> Edits to Set up Data guide

src/pages/gen2/build-a-backend/data/data-modeling/identifiers/index.mdx
=> fix: minor identifier updates

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
=> fix(ssr): add explanation re: setting ssr: true

src/pages/gen2/build-a-backend/data/subscribe-data/index.mdx
=> Edits to real-time events guide

src/pages/gen2/build-a-backend/auth/auth-events/index.mdx
=> fix: Update Auth Events

src/pages/gen2/how-amplify-works/faq/index.mdx
=> Fix link notation

src/pages/gen2/build-a-backend/auth/auth-events/index.mdx
=> Edits for auth events guide

src/pages/gen2/build-a-backend/add-aws-services/overriding-resources/index.mdx
https://app.asana.com/0/1205212189033571/1205381356323145/f
=> feat: Add content for Gen2 Overriding Resources page

src/pages/gen2/build-a-backend/auth/add-social-provider/index.mdx
Add social provider to Gen2 docs
=> Update Social Provider Section

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
=> fix: missing config import in setup auth

src/pages/gen2/build-a-backend/data/subscribe-data/index.mdx
Fix useEffect sample in gen2 docs so it doesn't repeatedly trigger.
=> fix use effect

src/pages/gen2/build-a-backend/data/mutate-data/index.mdx
=> Edits to mutate-data guide

src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx
Revising the custom resources page. Tweaked some wording here and there, added an example on using existing CDK Constructs and removed an example on creating a custom stack that had some technical problems and was also too long / unnecessary.
=> review custom resources page

src/directory/directory.mjs
=> Remove Auth SSR from directory

src/pages/gen2/reference/cli-commands/index.mdx
=> Updated CLI menu

src/pages/gen2/how-amplify-works/faq/index.mdx, src/pages/gen2/start/quickstart/index.mdx
=> getting started and faq

src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx
Added callout for React Native Authenticator to Social Signin docs.
=> chore: add react native authenticator callout

src/pages/[platform]/deploy-and-host/custom-configuration/index.mdx, src/pages/[platform]/deploy-and-host/deployment/index.mdx
=> Update filters for deployment indexes

src/pages/gen2/reference/telemetry/index.mdx
=> Telemetry edits

src/pages/gen2/index.tsx
- [x ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
=> Edits to Gen2 homepage

src/pages/gen2/reference/cli-commands/index.mdx
- [x ] Are all links in MDX files using the MDX link syntax rather than HTML link syntax? <br /> 
=> Edits to CLI commands reference page

src/pages/gen2/deploy-and-host/hosting/index.mdx, src/pages/gen2/reference/cdk-constructs/index.mdx, src/pages/gen2/reference/cli-commands/index.mdx, src/pages/gen2/reference/telemetry/index.mdx, src/pages/gen2/start/mobile-support/index.mdx
=> Edits to CDK constructs page and cleanup of some left nav items

src/pages/[platform]/build-a-backend/storage/existing-resources/index.mdx
=> Updated import docs

src/pages/[platform]/deploy-and-host/index.mdx, src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx, src/pages/gen2/deploy-and-host/index.mdx
=> Edits to data custom business logic and some left nav updates

src/pages/gen2/build-a-backend/functions/index.mdx
=> Edits to Functions page

src/directory/directory.mjs, src/fragments/lib/troubleshooting/common/upgrading.mdx, src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx, src/pages/[platform]/build-a-backend/auth/v6-change-log/index.mdx
=> feat(auth): add change log

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
Adds description to auth migration guide based on the descriptions on other category migration guides.
=> chore: add description to auth migration guide

src/fragments/start/getting-started/reactnative/setup.mdx
=> add react-native-get-random-values on getting started setup

src/pages/_app.tsx
- Update the meta viewport to be more mobile friendly
Staging site: https://mobile-meta-viewport.d1ywzrxfkb9wgg.amplifyapp.com/
=> Add mobile meta viewport

src/pages/gen2/start/quickstart/index.mdx
=> Addressing customer feedback for clarification

src/pages/[platform]/build-a-backend/auth/auth-events/index.mdx
small documentation fix in auth-events
=> auth-events: small documentation fix

.github/CODEOWNERS, .github/workflows/check_pr_for_broken_links.yml, cspell.json, src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx, src/pages/[platform]/build-a-backend/auth/auth-events/index.mdx, src/pages/[platform]/build-a-backend/storage/download/index.mdx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx, src/pages/gen2/build-a-backend/add-aws-services/overriding-resources/index.mdx, src/pages/gen2/start/quickstart/index.mdx, src/styles/banner.scss
=> Catching up to main

src/fragments/lib/troubleshooting/common/upgrading.mdx
Updates structure of migration guide to allow for easier access to category sections as well as better highlighting of category-specific migration guides.
=> chore: update structure of migration guide

src/constants/versions.ts
=> chore: Update Android Version

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
Collapses Input/Output changes into an Accordion to lighten the Auth Migration Guide for an initial pass. More changes to follow.
=> chore (auth migration guide): collapse Input/Output into Accordion

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx
=> remove introspection and schema gen steps

cspell.json, src/directory/directory.mjs, src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nuxt/index.mdx
=> feat(js-ssr): add instructions of using the generic adapter with Nuxt 3

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx
=> fix: Remove DYNAMODB from list of supported SQL databases

src/fragments/lib/troubleshooting/common/upgrading.mdx
=> chore(js-react-native): add packages should be removed in migration guide

src/pages/[platform]/how-amplify-works/index.mdx
=> Inserting inline filter to address 404 issue

cspell.json, src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
Incorporates feedback to add more text around what has changed and why for each API. Fixes a few errors in the original doc.
=> Auth migration guide v4

src/pages/[platform]/build-a-backend/existing-resources/cli/index.mdx
=> Existing aws resources

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
=> fix: update link to identity-pools setup

src/pages/[platform]/prev/tools/index.mdx, src/pages/[platform]/prev/tools/libraries/configure-categories/index.mdx, src/pages/[platform]/prev/tools/libraries/index.mdx, src/pages/[platform]/tools/index.mdx, src/pages/[platform]/tools/libraries/configure-categories/index.mdx
Address library versions in the Tools menu for the new IA - includes:
1- Create link to previous version for JS family users - https://tools-library-config-version.d9kfkg9g23gld.amplifyapp.com/react/tools/libraries/configure-categories/
2 - Update tools, library, and configure-categories for prev/tools section with navigation options since cannot use left menu - this included brining in the lib-v1 library page and adding an index page for tools so it is not empty.
- Examples:
-- https://tools-library-config-version.d9kfkg9g23gld.amplifyapp.com/react/prev/tools/
-- https://tools-library-config-version.d9kfkg9g23gld.amplifyapp.com/react/prev/tools/libraries/
-- https://tools-library-config-version.d9kfkg9g23gld.amplifyapp.com/react/prev/tools/libraries/configure-categories/
**If this PR …
=> Tools library config version

src/pages/gen2/build-a-backend/add-aws-services/custom-resources/index.mdx, src/pages/gen2/build-a-backend/add-aws-services/overriding-resources/index.mdx
=> Edits to 'Add any AWS service' section

src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx
updates the angular auth example, config import statement for consistency with other examples
=> update angular auth example

src/pages/[platform]/build-a-backend/utilities/cache/index.mdx
=> chore: use default values with Cache.createInstance() (aws-amplify/amplify-js#12705)

src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx, src/pages/gen2/build-a-backend/data/customize-authz/custom-data-access-patterns/index.mdx, src/pages/gen2/build-a-backend/functions/index.mdx
Adds docs around the `defineFunction` DX that has replaced the `Func.fromDir` DX. Includes an overhaul of the functions page as well as updates to mentions of functions in the data docs.
Also includes several lint updates that happened automatically.
Gen2 function DX
NA
=> `defineFunction` docs

src/fragments/lib/datastore/native_common/real-time.mdx
=> Add note for AppSync service limit and increase (DataStore)

src/pages/[platform]/tools/cli/project/troubleshooting/index.mdx
adds troubleshooting notes for using SSO with Amplify CLI
=> add sso credentials troubleshooting notes

src/fragments/cli-config.mdx, src/pages/[platform]/tools/cli/start/set-up-cli/index.mdx
brings over the changes from #6752 into the CLI config fragment
=> port gen1 changes from #6752 to cli config fragment

src/pages/[platform]/build-a-backend/server-side-rendering/nuxt/index.mdx
https://github.com/aws-amplify/docs/issues/6744
=> chore(js-ssr): update doc to fit refactored Nuxt useCookie interface

src/pages/[platform]/build-a-backend/auth/manage-mfa/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx
- `src/pages/[platform]/build-a-backend/auth/manage-mfa/index.mdx`
- Moved closing `InlineFilter` to wrap JS code snippets and text
- Urls to test:
- https://update-inline-filters.d1ywzrxfkb9wgg.amplifyapp.com/swift/build-a-backend/auth/manage-mfa/
- https://update-inline-filters.d1ywzrxfkb9wgg.amplifyapp.com/android/build-a-backend/auth/manage-mfa/ 
- https://update-inline-filters.d1ywzrxfkb9wgg.amplifyapp.com/flutter/build-a-backend/auth/manage-mfa/
- https://update-inline-filters.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/auth/manage-mfa/
-  `src/pages/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx`
- Removed native platforms
- Urls to test:
- https://update-inline-filters.d1ywzrxfkb9wgg.amplifyapp.com/javascript/build-a-backend/graphqlapi/data-modeling/
- …
=> Update inline filters for certain native pages

src/pages/[platform]/build-a-backend/graphqlapi/connect-api-to-existing-database/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx
=> Hide JS snippets to native customers

src/pages/[platform]/build-a-backend/auth/manage-user-session/index.mdx
Added the `refresh session` and `refresh session with social providers` sub sections to the [Manage user session](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/) page
=> chore(auth): add refresh session sections

src/pages/[platform]/build-a-backend/graphqlapi/connect-from-server-runtime/index.mdx
=> Removes SSR content from non-js platforms

src/pages/[platform]/tools/console/adminui/start/index.mdx
=> revert improved banner message

src/fragments/lib-v1/datastore/react-native/getting-started/30_platformIntegration.mdx, src/fragments/lib-v1/datastore/react-native/getting-started/polyfills.mdx, src/fragments/lib/datastore/react-native/getting-started/30_platformIntegration.mdx, src/fragments/lib/datastore/react-native/getting-started/polyfills.mdx, src/fragments/start/getting-started/reactnative/getting-started-steps-ui.mdx
=> add core-js to datastore getting started dependencies

src/pages/[platform]/build-a-backend/graphqlapi/connect-from-server-runtime/index.mdx
- Removing swift and android, based on this PR: https://github.com/aws-amplify/docs/pull/6777/files
=> Remove swift and android from page

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx
=> New guide for connecting existing CDK backend to apps

.github/CODEOWNERS, src/pages/[platform]/tools/console/adminui/start/index.mdx, src/protected/ProtectedAccountMessage/index.tsx, tsconfig.json
This component is a wrapper to lock the components message so that it can't be updated without approval
Staging Site: https://protected-folder.dmhjrabi3pkql.amplifyapp.com/react/tools/console/adminui/start/
=> Add ProtectedAccountMessage component

src/fragments/gen2/quickstart/build-a-backend.mdx
Make accordion code reference consistent with Todo code sample.
=> fix: Fix accordion code reference

src/pages/[platform]/build-a-backend/more-features/analytics/identify-user/index.mdx
The example code and surrounding text did not match the actual types in v6. Updated the code snippet and description with the correct property names and types.
=> fix: update example code and text to match v6 type definitions

src/pages/[platform]/build-a-backend/storage/storage-v5-to-v6-migration-guide/index.mdx
This PR adds an event tracking section to the Storage migration guide
=> chore: Add instructions for migrating storage event tracking

src/utils/__tests__/usePathWithoutHash.test.ts
- Add test for `usePathWithoutHash`
Coverage results:
```
$ jest src/utils/__tests__/usePathWithoutHash.test.ts --coverage
PASS  src/utils/__tests__/usePathWithoutHash.test.ts
usePathWithoutHash
✓ should remove the hashmark and everything after it from the url (7 ms)
✓ should not modify url if there are no hashmarks (1 ms)
-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------|---------|----------|---------|---------|-------------------
All files              |     100 |      100 |     100 |     100 |                   
usePathWithoutHash.ts |     100 |      100 |     100 |     100 | …
```
=> Add tests for usePathWithoutHash

src/fragments/lib-v1/push-notifications/react-native/interact_with_notifications/on-foreground-notification.mdx, src/fragments/lib/push-notifications/react-native/interact_with_notifications/on-background-notification.mdx, src/pages/[platform]/build-a-backend/push-notifications/push-notifications-migration-guide/index.mdx
This PR adds additional migration details on the v5 -> v6 migration guide for In-App Messaging.
* Adds input/output parameter and type changes where applicable
* Adds descriptions of what has changed
* Fixes some existing documentation errors
=> feat: add details to Push Notifications migration guide

src/pages/gen2/reference/cli-commands/index.mdx
=> changed the docs to use npx prefix

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
=> Clarified "Legacy" designation in Auth.signUp/Auth.signIn

src/utils/__tests__/useTabKeyDetection.test.tsx, src/utils/useTabKeyDetection.ts
- Add tests for `useTabKeyDetection`
Coverage results:
```
$ jest src/utils/__tests__/useTabKeyDetection.test.tsx --coverage
PASS  src/utils/__tests__/useTabKeyDetection.test.tsx
useTabKeyDetection
✓ should initially set isTabKeyPressed to false (12 ms)
✓ should set isTabKeyPressed to true when Tab key is pressed (3 ms)
✓ should set isTabKeyPressed to false when Tab key is released (3 ms)
✓ should not set isTabKeyPressed to true when another key is pressed (1 ms)
✓ should clean up event listeners on unmount (2 ms)
✓ should not add event listeners if there is no ref.current (1 ms)
-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```
=> Add tests for useTabKeyDetection

src/fragments/lib/troubleshooting/common/upgrading.mdx
Added migration details pertinent to React Native
=> feat: add React Native migration details

src/utils/__tests__/useClickOutside.test.tsx
- Add tests for `useClickOutside`
Coverage results:
```
$ jest src/utils/__tests__/useClickOutside.test.ts --coverage
PASS  src/utils/__tests__/useClickOutside.test.tsx
useClickOutside
✓ should call callback when clicked outside (10 ms)
✓ should not call callback when clicked inside (7 ms)
✓ should clean up event listener on unmount (1 ms)
--------------------|---------|----------|---------|---------|-------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------|---------|----------|---------|---------|-------------------
All files           |     100 |      100 |     100 |     100 |                   
useClickOutside.ts |     100 |      100 |     100 |     100 | …
```
=> Add tests for useClickOutside

src/pages/gen2/start/quickstart/nextjs-app-router-server-components/index.mdx
=> Fix: add create amplify fragment to RSC Quickstart

src/pages/gen2/reference/project-structure/index.mdx
=> Edits to Gen 2 project structure page

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx, src/pages/[platform]/build-a-backend/existing-resources/cli/index.mdx
=> Updates to CLI and CDK guides in G1 Build & Connect Backend section 

src/pages/gen2/reference/project-structure/index.mdx
=> Adding link to create-amplify package name

src/pages/gen2/start/account-setup/index.mdx
=> Edits to set up AWS account guide

src/pages/gen2/build-a-backend/data/subscribe-data/index.mdx
=> fix(js-graphql): code example doesn't update component

src/pages/[platform]/start/getting-started/setup/index.mdx
=> chore: Angular build path fix

src/pages/[platform]/build-a-backend/graphqlapi/customize-authorization-rules/index.mdx
remove Dynamic Group Auth for Native platforms: https://docs.amplify.aws/android/build-a-backend/graphqlapi/customize-authorization-rules/#user-group-based-data-access
=> Remove Dynamic Group Auth for Native platforms

src/fragments/lib/troubleshooting/common/upgrading.mdx
- The "react native" tab included a link specific to react native but was using the `platform` slug to build the link. This caused the other platform pages to create a link to a 404 page
- Refactored the content inside the block switcher to be inline using inline filters. This makes it so that platform specific content is shown directly on the page, meaning the react native link should only show on the react native page now
Staging site:
- For the "web" tab:
- https://fix-404-push-notification-links.d1ywzrxfkb9wgg.amplifyapp.com/angular/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/
- https://fix-404-push-notification-links.d1ywzrxfkb9wgg.amplifyapp.com/react/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/
- …
=> Refactor blockswitcher into inline filters

src/pages/[platform]/build-a-backend/graphqlapi/custom-business-logic/index.mdx
Fixes discrepancy in function name in CDK code sample
=> fix: Make CDK functionName match example function name

src/pages/[platform]/build-ui/uibuilder/theming/index.mdx
removes references to studio github repository
=> removes reference to studio repository

src/pages/gen2/reference/cli-commands/index.mdx
adds amplify info and pipeline-deploy commands to the commands reference page
=> update Gen 2 commands

src/pages/[platform]/build-a-backend/graphqlapi/data-modeling/index.mdx
=> Updated the description for default values for clarity

src/pages/[platform]/build-a-backend/storage/upload/index.mdx
=> fix storage upload

src/directory/directory.mjs, src/pages/gen2/start/quickstart/vite-react-app/index.mdx
=> Add vite react app quickstart

.github/CODEOWNERS
Adds some new paths from the site relaunch, such as data, themes, etc. 
Removes no longer relevant path like ChooseFilterPage.tsx
=> chore(CODEOWNERS): update files owned by engineering team

package.json, src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx, yarn.lock
Before resolution: 
After resolution: 
=> chore: add resolution for ip package with vulnerability

src/pages/[platform]/build-a-backend/graphqlapi/subscribe-data/index.mdx
=> Elevate custom subscription into its own heading

package.json, yarn.lock
=> pin version of sharp

src/components/BlockSwitcher/__tests__/BlockSwitcher.test.tsx
Unit tests for BlockSwitcher component
=> chore: add unit tests for BlockSwitcher

src/components/Banner/__tests__/Banner.test.tsx, src/components/Banner/__tests__/ClassicBanner.test.tsx
Unit tests for Banner and ClassicBanner components
=> chore: add unit tests for Banner and ClassicBanner components

src/fragments/gen2/quickstart/build-a-backend.mdx, src/pages/gen2/start/quickstart/vite-react-app/index.mdx
=> Minor edits to Vite + React quickstart

src/constants/versions.ts
=> Version update for Amplify Android Release 2.14.11

src/components/Breadcrumbs/index.tsx, src/components/Layout/Layout.tsx, src/components/Layout/LayoutHeader.tsx, src/components/Layout/index.ts, src/constants/versions.ts, src/fragments/gen2/quickstart/build-a-backend.mdx, src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx, src/pages/gen2/start/quickstart/vite-react-app/index.mdx
Merge the latest from main to **next-release/main**
=> chore(next-release/main) - merge from main

.github/CODEOWNERS
=> Update CODEOWNERS with correct PM alignment

src/fragments/gen2/quickstart/create-amplify.mdx, src/pages/gen2/build-a-backend/data/set-up-data/index.mdx, src/pages/gen2/deploy-and-host/fullstack-branching/mono-and-multi-repos/index.mdx, src/pages/gen2/reference/project-structure/index.mdx, src/pages/gen2/start/mobile-support/index.mdx, src/pages/gen2/start/quickstart/vite-react-app/index.mdx
=> fixed gen 2 getting started guide

redirects.json
Update redirects to include hidden pages that were picked up by search engines before they were deleted. 
Related PR that shows deleted pages - https://github.com/aws-amplify/docs/pull/6895/files
=> Add redirects for deleted hidden pages

src/pages/gen2/start/manual-installation/index.mdx
=> Update manual installation to point to @beta tag

package.json, src/components/Accordion/Accordion.tsx, src/components/Accordion/__tests__/Accordion.test.tsx
=> chore: add unit tests for Accordion component

.github/CODEOWNERS
=> add gen2 codeowners

src/pages/gen2/build-a-backend/data/data-modeling/add-fields/index.mdx
=> Support for enum value listing

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx
=> Updates to CDK guide for React and Flutter

src/components/Layout/Layout.tsx, src/components/Layout/LayoutHeader.tsx, src/components/Menu/Menu.tsx, src/components/PlatformNavigator/index.tsx, src/components/VersionSwitcher/index.tsx, src/data/routes.ts, src/pages/gen1/index.tsx, src/styles/layout.scss
- Update menu to work with gen1 routes
- Update version switcher to work only for gen1 routes
Staging site: https://menu-gen2-update.d1ywzrxfkb9wgg.amplifyapp.com/
To test on base version:
1. Go to https://menu-gen2-update.d1ywzrxfkb9wgg.amplifyapp.com/
2. Verify that only the platform navigator is available in the base version of the docs
To test on gen1:
1. Go to https://menu-gen2-update.d1ywzrxfkb9wgg.amplifyapp.com/gen1/
2. Test the menu and make sure it's linking to the gen1 pages
3. Test navigating to different platforms
4. Test the version switcher for the build a backend section
5. Test the sdk site: https://menu-gen2-update.d1ywzrxfkb9wgg.amplifyapp.com/gen1/swift/sdk/
- I think it should only work on android and swift
6. Test the cli legacy site: …
=> Update menu and version switcher

src/directory/directory.mjs, src/pages/gen2/build-a-backend/data/customize-authz/index.mdx, src/pages/gen2/build-a-backend/data/data-modeling/index.mdx, src/pages/gen2/build-a-backend/data/data-modeling/secondary-index/index.mdx, src/pages/gen2/build-a-backend/data/query-data/index.mdx, src/pages/gen2/build-a-backend/data/set-up-data/index.mdx, src/pages/gen2/build-a-backend/data/subscribe-data/index.mdx
=> Adding secondary index to Gen 2

src/pages/gen2/reference/amplifyconfiguration/index.mdx
extending `amplifconfiguration.json` outputs
created post discussion: https://github.com/aws-amplify/docs/pull/6901
=> extend config to show addOuput

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/connect-to-api/index.mdx
=> Add additional instructions for allowGuestMode on JS

src/components/NextPrevious/__tests__/NextPrevious.test.tsx
=> chore: add unit tests for NextPrevious component

src/components/LinkCard/__tests__/LinkCard.test.tsx, src/components/LinkCards/__tests__/LinkCards.test.tsx
=> chore: add unit tests for LinkCards and LinkCard components

src/components/GetStartedPopover/__tests__/GetStartedPopover.test.tsx
=> chore: add unit tests for GetStartedPopover component

src/pages/[platform]/build-a-backend/storage/configure-access/index.mdx
The page here references the incorrect Auth method that is unique to V5 and older but not available in V6. Updating to the correct method
N/A
=> fix: [Storage] Configure Access

src/directory/directory.mjs, src/fragments/lib/analytics/native_common/getting-started/30_initAnalytics.mdx, src/fragments/lib/geo/js/getting-started.mdx, src/fragments/lib/in-app-messaging/integrate-your-application/integrate-your-application.mdx, src/fragments/lib/interactions/js/getting-started.mdx, src/fragments/lib/predictions/js/getting-started.mdx, src/fragments/lib/restapi/js/getting-started/30_initapi.mdx, src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx, src/pages/[platform]/build-a-backend/graphqlapi/connect-to-api/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nuxt/index.mdx, src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/build-a-backend/troubleshooting/library-not-configured/index.mdx, src/pages/[platform]/start/getting-started/setup/index.mdx
Adds callouts and a troubleshooting to address the Library Not Configured error message.
=> chore: add callouts and troubleshooting guide for configuration

src/fragments/lib-v1/graphqlapi/js/upgrade-guide.mdx, src/fragments/sdk/api/android/graphql.mdx, src/fragments/sdk/api/ios/graphql.mdx, src/fragments/sdk/storage/android/getting-started.mdx, src/fragments/sdk/storage/ios/getting-started.mdx, src/pages/[platform]/build-ui/formbuilder/call-to-action/index.mdx, src/pages/[platform]/build-ui/formbuilder/customize/index.mdx, src/pages/[platform]/build-ui/formbuilder/data-binding/index.mdx, src/pages/[platform]/build-ui/formbuilder/index.mdx, src/pages/[platform]/build-ui/formbuilder/lifecycle/index.mdx, src/pages/[platform]/build-ui/formbuilder/overrides/index.mdx, src/pages/[platform]/build-ui/formbuilder/special-inputs/index.mdx, src/pages/[platform]/build-ui/formbuilder/validations/index.mdx, src/pages/[platform]/build-ui/uibuilder/bestpractices/index.mdx, src/pages/[platform]/build-ui/uibuilder/collections/index.mdx, src/pages/[platform]/build-ui/uibuilder/databinding/index.mdx, src/pages/[platform]/build-ui/uibuilder/eventhandling/index.mdx, src/pages/[platform]/build-ui/uibuilder/index.mdx, src/pages/[platform]/build-ui/uibuilder/override/index.mdx, src/pages/[platform]/build-ui/uibuilder/responsive/index.mdx, src/pages/[platform]/build-ui/uibuilder/slots/index.mdx, src/pages/[platform]/build-ui/uibuilder/theming/index.mdx, src/pages/[platform]/tools/console/adminui/start/index.mdx, src/pages/[platform]/tools/console/data/data-model/index.mdx, src/pages/[platform]/tools/console/tutorial/bindui/index.mdx, src/pages/[platform]/tools/console/tutorial/buildui/index.mdx, src/pages/[platform]/tools/console/tutorial/code/index.mdx, src/pages/[platform]/tools/console/tutorial/collections/index.mdx, src/pages/[platform]/tools/console/tutorial/data/index.mdx, src/pages/[platform]/tools/console/tutorial/index.mdx
- adjusted page platform lists:
- added `nextjs` to platform list of all `/[platform]/build-ui` pages
- [prod](https://docs.amplify.aws/nextjs/build-ui/formbuilder/)
- [staging](https://correct-content-filtering.d1egzztxsxq9xz.amplifyapp.com/nextjs/build-ui/formbuilder/)
- removed all but `react`, `javascript`, `nextjs` from `/[platform]/tools/console/tutorial/` pages
- <img width="334" alt="Screenshot 2024-03-06 at 11 50 21 AM" src="https://github.com/aws-amplify/docs/assets/30757403/a019062a-7060-4b92-955e-b552a4c59ef8">
- filtered out broken content links for platforms where links were not applicable
- `/pages/[platform]/tools/console/adminui/start/index.mdx`
- [prod](https://docs.amplify.aws/swift/tools/console/adminui/start/#:~:text=new%20browser%20tab-,Next%20steps,-You%20are%20ready …
=> fix: resolve in-content broken links

src/pages/gen2/build-a-backend/functions/index.mdx, src/pages/gen2/build-a-backend/storage/index.mdx
Overhaul of the gen 2 function and storage pages to document new behavior that has been added since reInvent.
The biggest additions are function environment variables and secrets and storage access patterns.
fixes https://github.com/aws-amplify/amplify-backend/issues/1052
Gen2 storage and functions
NA
=> update gen2 storage and function docs

src/pages/gen2/reference/cli-commands/index.mdx
Update `sandbox --dir-to-watch` description to match current behavior.
Gen2 sandbox
N/A
=> Update sandbox --dir-to-watch description

src/components/Layout/LayoutHeader.tsx
- Apply facet filter for gen1 or gen2
=> Add facet filters for gen2

src/pages/gen2/build-a-backend/auth/enable-sign-up/index.mdx, src/pages/gen2/build-a-backend/auth/manage-mfa/index.mdx, src/pages/gen2/build-a-backend/auth/manage-user-profile/index.mdx, src/pages/gen2/build-a-backend/auth/password-management/index.mdx
=> fix: Update diff code blocks to TypeScript with code highlights

package.json, src/components/PlatformNavigator/__tests__/PlatformNavigator.test.tsx
=> chore: add unit tests for PlatformNavigator

src/pages/[platform]/prev/build-a-backend/auth/add-social-provider/index.mdx
=> Update links to expo docs

src/components/InternalLinkButton/__tests__/InternalLinkButton.test.tsx
=> chore: add unit tests for InternalLinkButton

package.json, src/components/TableOfContents/__tests__/TableOfContents.test.tsx
=> chore: add unit tests for TOC

src/components/ExternalLink/__tests__/ExternalLink.test.tsx
Unit tests for ExternalLink component
=> chore: add unit tests for ExternalLink

src/components/ExternalLinkButton/__tests__/ExternalLinkButton.test.tsx
Unit tests for ExternalLinkButton component
=> chore: add unit tests for ExternalLinkButton

src/components/MigrationAlert/__tests__/MigrationAlert.test.tsx
=> chore: add unit tests for MigrationAlert component

src/components/Overview/__tests__/Overview.test.tsx
=> chore: add unit test for Overview component

src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx
=> Added new `a.handler.function` documentation for Gen 2 and utility type docs

src/components/PageLastUpdated/__tests__/PageLastUpdated.test.tsx
=> chore: add unit tests for PageLastUpdated

src/pages/[platform]/build-a-backend/existing-resources/cdk/index.mdx, src/pages/[platform]/build-a-backend/existing-resources/cli/index.mdx, src/pages/[platform]/build-a-backend/restapi/gen-ai/index.mdx, src/pages/[platform]/tools/cli-legacy/directives/index.mdx, src/pages/[platform]/tools/cli-legacy/overview/index.mdx, src/pages/gen2/build-a-backend/auth/grant-access-to-auth-resources/index.mdx, src/pages/gen2/build-a-backend/functions/index.mdx, src/pages/gen2/build-a-backend/storage/index.mdx
- Updated urls using the relative paths
- Added trailing slash to urls if it didn't have one
- Updated urls that were pointing to the old docs (which would get redirected to the new docs url paths)
=> Update relative urls

tasks/link-checker.js
- Update the link checker to account for duplicate urls from different pages and link text. This helps notify us where to fix the links.
- Previously the link checker was indexing broken urls based on the url and would only notify of the first broken link found. If the same url was used somewhere else, then it wouldn't have caught it
_By submitting this pull request, I confirm that my contribution is made under the …
=> Updating link checker

src/fragments/gen2/quickstart/build-a-backend.mdx, src/fragments/gen2/quickstart/create-amplify.mdx
=> Update gen2 links for gen2 fragments

src/pages/[platform]/build-a-backend/storage/download/index.mdx
DownloadData doc updates for Gen2 storage work.
=> [Gen2 Storage JS] DownloadData doc updates

src/components/Layout/Layout.tsx, src/components/SpaceShip/SpaceShip.tsx, src/styles/layout.scss, src/styles/spaceship.scss
Tidies up some of the styles used for the spaceship and also makes it purple in darkmode for Gen2 (it's using teal styles in darkmode currently).
**After changes**
=> fix(next-release/main): tidy spaceship styles, fix darkmode colors

src/pages/gen2/build-a-backend/auth/set-up-auth/index.mdx
updates 
```
function App({ Component, pageProps, signOut, user }: WithAuthenticatorProps)
```
with
```
{ signOut, user, Component, pageProps }: WithAuthenticatorProps & AppProps
```
closes:https://github.com/aws-amplify/docs/issues/7105
=> update setup auth client example with correct props

src/directory/directory.mjs, src/pages/gen2/build-a-backend/data/custom-subscription/index.mdx
- Gen 2 docs for custom subscriptions
=> Custom subscription docs to Gen 2

src/pages/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
`autoSignIn` key is the `options` object child, not it's sibling
Source: https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/#auto-sign-in
=> autoSignIn position correction in v6 migration docs

src/fragments/cli-install-block.mdx, src/fragments/guides/hosting/gatsby.mdx, src/fragments/guides/hosting/gridsome.mdx, src/fragments/guides/hosting/nuxt.mdx, src/fragments/guides/hosting/vite.mdx, src/fragments/lib-v1/datastore/js/getting-started/40_codegen.mdx, src/fragments/lib-v1/start/getting-started/vue/setup.mdx, src/fragments/lib-v1/troubleshooting/js/upgrading.mdx, src/fragments/lib/datastore/js/getting-started/40_codegen.mdx, src/fragments/start/getting-started/vue/setup.mdx, src/pages/[platform]/build-a-backend/troubleshooting/upgrade-amplify-packages/index.mdx, src/pages/[platform]/start/getting-started/installation/index.mdx, src/pages/[platform]/tools/cli/custom/cdk/index.mdx, src/pages/[platform]/tools/cli/plugins/authoring/index.mdx, src/pages/[platform]/tools/cli/start/key-workflows/index.mdx, src/pages/[platform]/tools/cli/start/set-up-cli/index.mdx, src/pages/gen2/build-a-backend/functions/index.mdx, src/pages/gen2/build-a-backend/storage/index.mdx, src/pages/gen2/reference/cli-commands/index.mdx
Changes all references of "NPM" to "npm"
https://github.com/npm/cli#faq-on-branding
=> change "NPM" to "npm"

src/components/Layout/Layout.tsx, src/components/NextPrevious/__tests__/NextPrevious.test.tsx, src/components/NextPrevious/index.tsx, src/pages/gen1/index.tsx
- Update the Next/Previous component to support gen 1 routes
- Added platforms to gen1 index page so that the component could search within the node
- Added logic in Next/Previous component to handle gen 1 routes
Staging site: https://update-next-previous-gen1.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://update-next-previous-gen1.d1ywzrxfkb9wgg.amplifyapp.com/gen1/react/build-a-backend/auth/set-up-auth/
2. Verify that there is a Next link at the bottom of the page
3. Go to https://update-next-previous-gen1.d1ywzrxfkb9wgg.amplifyapp.com/gen1/flutter/build-a-backend/auth/set-up-auth/ 
4. Verify that there is a Next link at the bottom of the page and that it is different from the link in step 1. This is because the different platforms have different next pages
**If this PR should …
=> Update next previous component to work with gen1 links

src/pages/[platform]/start/getting-started/auth/index.mdx
Removed 'Angular' from the app description. It is not necessarily an angular app.
- [] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?
=> remove unnecessary "Angular" mention in auth getting started

src/pages/gen2/build-a-backend/data/custom-business-logic/index.mdx
Edits to custom business logic page. Edits inlude small code and filename corrections, formatting, etc.
=> edits to gen 2 custom business logic page

src/pages/[platform]/start/quickstart/vite-react-app/index.mdx
=> fixed placement of code

src/directory/directory.mjs, src/pages/[platform]/start/quickstart/vite-react-app-option-2/index.mdx
=> created new option

src/pages/gen2/build-a-backend/data/override-resources/index.mdx
=> Update amplifyDynamoDbTables override to reflect the correct placement in the API

src/directory/directory.mjs, src/pages/[platform]/build-ui/figma-to-code/index.mdx, src/pages/[platform]/build-ui/forms/index.mdx, src/pages/[platform]/build-ui/index.mdx, src/pages/[platform]/start/quickstart/vite-react-app-option-2/index.mdx, src/pages/[platform]/start/quickstart/vite-react-app/index.mdx
Catching `next-release/main` up with the changes made in `next-release/dev`.
=> chore: weekly merge of `next-release/dev` into `next-release/main`

src/pages/[platform]/build-a-backend/add-aws-services/analytics/record-events/index.mdx
=> minor update on analytics android example

src/fragments/lib/predictions/js/getting-started.mdx
=> Fixed typo in amplifyconfiguration.json for predictions

src/pages/[platform]/build-a-backend/graphqlapi/mutate-data/index.mdx
=> fix swift docs to use the `.update` call

src/fragments/lib/auth/android/social_signin_web_ui/20_signin.mdx, src/fragments/lib/storage/android/upload.mdx
=> Added Metadata section in Storage

src/pages/gen2/build-a-backend/data/data-modeling/relationships/index.mdx
=> Updated Gen 2 relationship behavior

src/pages/[platform]/build-a-backend/add-aws-services/predictions/identify-entity/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/identify-text/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/interpret-sentiment/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/label-image/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/text-to-speech/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/transcribe-audio/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/translate/index.mdx
=> [Gen 2][Mobile] Predictions 

src/pages/[platform]/build-a-backend/functions/examples/kinesis-stream/index.mdx
Kinesis Data Streams - Technical and Content review edits
=> Kinesis Data Streams - Technical and Content review edits

src/pages/[platform]/build-a-backend/functions/examples/dynamo-db-stream/index.mdx
DynamoDB Streams - Technical and Content review edits
=> DynamoDB Streams - Technical and Content review edits

src/components/Icons/IconTSBoxed.tsx, src/components/Icons/index.ts, src/components/Modal/Modal.tsx, src/components/Modal/__tests__/Modal.test.tsx, src/styles/modal.scss
- Update copy for popup for gen2
https://update-modal.d1ywzrxfkb9wgg.amplifyapp.com/
=> Update gen 2 info modal copy

src/pages/[platform]/build-a-backend/auth/delete-user-account/index.mdx
=> [Gen 2][Mobile] Add missing code snippets on Android, Flutter and Swift for delete user account.

src/pages/[platform]/build-a-backend/auth/auth-events/index.mdx
=> [Gen 2][Mobile] Add listen to auth events docs for mobile.

src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/create-campaign/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/display-messages/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/identify-user/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/integrate-application/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/set-up-in-app-messaging/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/sync-messages/index.mdx
=> edits to in app messaging

src/pages/[platform]/start/quickstart/vite-react-app/index.mdx
=> add feedback to quickstart

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/functions/examples/s3-upload-confirmation/index.mdx
=> Gen2 Functions | S3 trigger example 

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/enable-sign-out/index.mdx
=> [GEN 2][Mobile] Add enable sign-out for Android, Flutter and iOS

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-external-ddb-table/index.mdx, src/pages/[platform]/build-a-backend/data/optimistic-ui/index.mdx, src/pages/[platform]/build-a-backend/q-developer/index.mdx, src/pages/[platform]/start/quickstart/vite-react-app/index.mdx
=> added optimistic UI docs for swift + web on Gen 2

src/components/GlobalNav/components/AmplifyNavLink.tsx
- Use the `useCurrentPlatform` hook to append the current platform to the home page link if it exists
https://update-home-link.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://update-home-link.d1ywzrxfkb9wgg.amplifyapp.com/
2. Click on "Amplify Docs" in the navbar
3. Verify that it takes you to the same page (home page) and shows the default platform
4. Navigate to a doc page
5. Repeat step 2
6. Verify that it takes you to the current platform's root page
7. Switch to a different platform
8. Repeat steps 4-6 …
=> Check for current platform when creating home link

src/components/GetStartedPopover/generateGetStartedLinks.tsx, src/components/PlatformNavigator/__tests__/PlatformNavigator.test.tsx, src/constants/frameworks.tsx, src/data/platforms.ts
- Updated order of platforms in platform navigator and the get started dropdown
https://set-nextjs-default-platform.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://set-nextjs-default-platform.d1ywzrxfkb9wgg.amplifyapp.com/
3. Open the platform navigator, and verify the order of the platform list
4. Open the get started dropdown and verify the order of the platform list
_By submitting this pull request, I …
=> Rearrange order of platforms

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/functions/examples/create_user_profile_record/index.mdx
=> Functions - Example use cases for functions - Create a user profile model/record

src/pages/[platform]/build-a-backend/functions/examples/add-user-to-group/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/dynamo-db-stream/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/email-domain-filtering/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/kinesis-stream/index.mdx
=> minor edits on function examples

src/directory/directory.mjs, src/pages/[platform]/reference/permissions-boundary/index.mdx
=> Reference - Permission boundaries

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/app-uninstall/index.mdx
=> [Gen 2][iOS, Android] Add App Uninstall page to auth for iOS and Androi.

src/directory/directory.mjs, src/pages/[platform]/build-ui/figma-to-code/index.mdx, src/pages/[platform]/build-ui/index.mdx
- Update directory to correctly link to Amplify UI Docs for the respective platform
https://update-ui-links.d1ywzrxfkb9wgg.amplifyapp.com/
To test:
1. Go to https://update-ui-links.d1ywzrxfkb9wgg.amplifyapp.com/
2. Verify that the external links in the `Build UI` section of the menu correctly go to their respective platform pages on the Amplify UI Docs site. …
=> Update UI links

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-external-ddb-table/index.mdx
edits and corrections to external dynamodb data source page
=> Connect to external DynamoDB table edits

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-external-ddb-table/index.mdx
=> remove sentence

src/pages/gen2/build-a-backend/storage/index.mdx
=> Fix gen-1 storage code

src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx
=> GEN2 | Predictions | guardian feedback

src/pages/[platform]/build-a-backend/add-aws-services/geo/location-search/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/test-api/index.mdx
Fixing typos that make broken links
=> Broken link fixes

src/pages/[platform]/build-a-backend/functions/examples/create-user-profile-record/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/kinesis-stream/index.mdx
=> minor edit: add import and install on function

src/pages/[platform]/reference/cli-commands/index.mdx
=> nits to cli-commands

src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx
=> chore: update flutter v2 migration guide

src/pages/[platform]/deploy-and-host/fullstack-branching/pr-previews/index.mdx
=> update pr previews file

src/fragments/lib/analytics/flutter/record.mdx, src/fragments/lib/datastore/flutter/conflict.mdx, src/fragments/lib/datastore/flutter/sync/50-selectiveSync.mdx, src/fragments/lib/graphqlapi/flutter/advanced-workflows/50_interceptor.mdx, src/fragments/lib/graphqlapi/flutter/authz/10_userpool.mdx, src/fragments/lib/graphqlapi/flutter/authz/2X_add_plugin.mdx, src/fragments/lib/graphqlapi/flutter/getting-started/30_initapi.mdx, src/fragments/lib/graphqlapi/flutter/subscribe-data.mdx
=> chore: update flutter v2 docs to use plugin options

src/pages/[platform]/build-a-backend/auth/password-management/index.mdx
=> [GEN 2][Mobile] Update password management page with iOS, Android and Flutter snippets.

src/pages/gen2/build-a-backend/auth/manage-mfa/index.mdx
Update the casing of MFA mode which is all caps.
=> [Gen2][Backend] Update casing of MFA mode.

src/fragments/lib-v1/auth/native_common/signin_next_steps/common.mdx
- added missing multi auth snippets back into the v2 branch
=> chore: add multi auth back to v1 previous

src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx
=> [Gen 2][Mobile] Update social sign-in to support iOS, Android, Flutter and React Native.

src/styles/base.scss
Fixes the overflow background color in dark mode. 
The background color of the html element is what needs the background-color, however, I think because our dark mode css variables are scoped to the `[data-amplify-color-mode='dark']` data attribute which is on a nested div inside of body. That means we can't just set the background color to `var(--amplify-colors-background-primary)` because that value will not be updated at the `:root` level when flipped to dark mode. So in this case, we use :has() to check for the existence of that data attribute then set the background color of the html element there.
https://fixoverflowbackground.d2bfwhpcsj9awv.amplifyapp.com/
To test: Scroll to the bottom of the page in Chrome and try to scroll more so it does the bouncy thing.
**If this PR should not …
=> fix(main): update overflow background color in dark mode

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/under-the-hood/index.mdx
=> [Gen 2] Add under the hood docs

src/pages/[platform]/build-a-backend/auth/accessing-credentials/index.mdx, src/pages/[platform]/build-a-backend/auth/manage-user-session/index.mdx
Updates to Accessing credentials pages for mobile - Swift, Android, Flutter, React Native
=> Updates to Accessing credentials pages for mobile

src/fragments/lib/project-setup/flutter/platform-setup/android.mdx
Update Flutter docs:
- change kotlin version after creating a Flutter app
- adjust for formatting changes for Flutter's new Gradle plugins
=> chore: add kotlin update to docs and formatting changes for flutter

src/pages/[platform]/build-a-backend/functions/examples/add-user-to-group/index.mdx
There was an issue with this example where we were missing the group definition and access.
- adds note for creating "EVERYONE" group
- adds note for defining access
- shuffles content to prevent bouncing back and forth to the auth resource file
=> fix gen2 add user to group functions example

src/pages/[platform]/build-a-backend/data/connect-to-API/index.mdx
=> Review Connect data to API

src/pages/[platform]/reference/permissions-boundary/index.mdx
=> Reference - Permission boundaries - feedback

src/pages/[platform]/start/quickstart/index.mdx
Update the Swift getting started guide with some fixes.
- configure with `with: .amplifyOutputs)` for Gen2 config file
- add empty `createTodo` and `listTodos` in anticipation of the method implementations
- update codegen command to specific swift model generation
- Update `authorization` rule on the Todo model to use `allow => [rules]` closure
_By submitting this pull request, I confirm that my contribution is made …
=> fix(swift): getting started

src/pages/[platform]/build-a-backend/data/connect-to-API/index.mdx
Merge after library changes https://github.com/aws-amplify/amplify-swift/pull/3631 and https://github.com/aws-amplify/amplify-android/pull/2791
=> fix(data): update to use default graphql api constant

src/constants/feature-lists-data.ts, src/fragments/lib-v1/graphqlapi/native_common/getting-started/common.mdx, src/fragments/lib/graphqlapi/native_common/getting-started/common.mdx, src/pages/[platform]/build-a-backend/storage/import/index.mdx, src/pages/[platform]/prev/build-a-backend/storage/import/index.mdx
=> chore: fix broken links by adding inline filters

src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
changed the configuration from amplifyconfiguration to amplify_outputs.
=> updated the configuration

cspell.json, src/pages/[platform]/build-a-backend/auth/enable-sign-in/index.mdx
Enable signin review - Flutter, Android, Swift
=> Enable signin review

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-translate/index.mdx
edits to connect to translate page
=> edits to connect to translate pge

src/pages/[platform]/build-a-backend/data/connect-to-API/index.mdx
- Saw other pages with bullet points capitalize the first word of the sentences and so I updated these bullet points to be capitalized as well
=> Capitlize sentences for connect-to-api page

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/modify-resources-with-cdk/index.mdx
split off from https://github.com/aws-amplify/docs/pull/7312 for ease of review
=> update gen2 auth cdk override

src/pages/[platform]/build-a-backend/add-aws-services/analytics/set-up-analytics/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/amazon-location-sdk/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/geofences/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/location-search/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/maps/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/set-up-geo/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/integrate-application/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/in-app-messaging/set-up-in-app-messaging/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/interactions/set-up-interactions/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx, src/pages/[platform]/build-a-backend/auth/add-social-provider/index.mdx, src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx, src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-polly/index.mdx, src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-rekognition/index.mdx, src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-translate/index.mdx, src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/s3-upload-confirmation/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nextjs-app-router-server-components/index.mdx, src/pages/[platform]/build-a-backend/storage/download-files/index.mdx, src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx, src/pages/[platform]/build-ui/formbuilder/index.mdx, src/pages/[platform]/start/quickstart/index.mdx, src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx, src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx
=> change all occurrences of "npm install" to "npm add"

src/pages/[platform]/build-a-backend/auth/enable-sign-in/index.mdx, src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx, src/pages/[platform]/deploy-and-host/fullstack-branching/branch-deployments/index.mdx, src/pages/[platform]/start/quickstart/index.mdx
=> remove equals sign from cli options

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/moving-to-production/index.mdx
split off from https://github.com/aws-amplify/docs/pull/7312 for ease of review
=> add gen2 auth "moving to production"

src/pages/[platform]/build-a-backend/functions/examples/s3-upload-confirmation/index.mdx
content review & edits to upload confirmation page
=> content review & edits to upload confirmation page

src/pages/[platform]/reference/amplifyconfiguration/index.mdx, src/pages/[platform]/reference/cli-commands/index.mdx, src/pages/[platform]/reference/project-structure/index.mdx
=> Gen2 Update a link to use an example for function

src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/test-api/index.mdx
=> RestAPI add comments and modify test example

src/pages/[platform]/start/quickstart/index.mdx
=> Quickstart updates

src/pages/[platform]/build-a-backend/functions/examples/google-recaptcha-challenge/index.mdx
adds a recaptcha example for gen2
=> add recaptcha functions example

src/pages/[platform]/build-a-backend/storage/download-files/index.mdx, src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
- fix StorageManager example to use correct prop
- update StorageImage to show custom path
- hide unsupported frameworks 
=> Update Storage UI examples 

src/pages/gen1/[platform]/prev/index.mdx, src/pages/gen1/[platform]/tools/console/data/index.mdx
Examples:
- https://next-docs.amplify.aws/gen1/angular/tools/console/data/
- https://next-docs.amplify.aws/gen1/vue/prev/
=> fix: adding missing platforms to overview index.mdx pages that are causing broken breadcrumb links

src/pages/[platform]/start/quickstart/index.mdx
* Fixed Amplify configure command
* Properly added .kts extension to build.gradle files
* Fix generate command
=> Android Quickstart updates

src/pages/[platform]/how-amplify-works/faq/index.mdx
=> content review & edits to FAQ page

src/pages/[platform]/build-a-backend/add-aws-services/analytics/streaming-data/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/geo/set-up-geo/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/logging/set-up-logging/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx, src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/build-a-backend/functions/examples/kinesis-stream/index.mdx
=> add inline filter for sometimes broken link

src/pages/[platform]/build-a-backend/storage/configure-access/index.mdx, src/pages/[platform]/build-a-backend/storage/list/index.mdx, src/pages/[platform]/build-a-backend/storage/path/index.mdx
- Adding more clarity on list API doc on specific use case
=> Chore: JS List API doc

src/pages/[platform]/build-a-backend/storage/authorization/index.mdx, src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx, src/pages/[platform]/build-a-backend/storage/download-files/index.mdx, src/pages/[platform]/build-a-backend/storage/list-files/index.mdx, src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx, src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx, src/pages/[platform]/start/gen1-gen2/index.mdx
=> address storage feedback

src/pages/[platform]/build-a-backend/data/optimistic-ui/index.mdx, src/pages/[platform]/build-a-backend/data/query-data/index.mdx, src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/start/quickstart/index.mdx
=> replace Schema["MODEL_NAME"] with Schema["MODEL_NAME"]["type"]

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx
=> Set up auth review for mobile

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-polly/index.mdx
Edits to connect to polly page
=> edits to connect to polly page

src/pages/[platform]/build-a-backend/auth/grant-access-to-auth-resources/index.mdx
split off from https://github.com/aws-amplify/docs/pull/7312 for ease of review
=> update example for gen2 auth "grant access..."

src/pages/[platform]/start/quickstart/index.mdx
=> Android Quickstart code example updates

src/pages/[platform]/start/gen1-gen2/index.mdx
=> Gen 1 -> Gen 2 guide formatting and edits

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/functions/set-up-function/index.mdx, src/pages/[platform]/how-amplify-works/concepts/index.mdx, src/pages/[platform]/how-amplify-works/index.mdx
=> few nits for the docs

src/pages/[platform]/index.tsx
=> change copy on OTHER homepage

src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
=> update swift set up code sample

src/pages/[platform]/reference/cli-commands/index.mdx
=> disable line numbers, add title for "console" snippet

src/pages/[platform]/index.tsx
=> Update the mobile main pages.

src/pages/[platform]/build-a-backend/auth/set-up-auth/index.mdx, src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/start/quickstart/index.mdx
=> Gen2 Android corrections

src/pages/[platform]/start/quickstart/index.mdx
- Update schema to use required `isDone` for the Todo model. This greatly simplifies the code for binding the toggle to the value.
- Move view into ContentView
- Move logic into TodoViewModel
- Move contents of List view into TodoRow
=> fix(swift): refactor swift getting started

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/auth/advanced-workflows/index.mdx, src/pages/[platform]/build-ui/formbuilder/lifecycle/index.mdx, src/pages/[platform]/build-ui/formbuilder/special-inputs/index.mdx
=> Gen2 Fix broken \Gen 1 links

src/pages/[platform]/start/quickstart/index.mdx
=> Remove XCode reference from JavaScript Quickstart

src/components/Layout/LayoutHeader.tsx, yarn.lock
=> Hide search

redirects.json
=> prettify redirects.json

src/pages/[platform]/build-a-backend/add-aws-services/logging/sdk/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/logging/set-up-logging/index.mdx
=> Fix Android Logging Set Up Guide 

src/pages/[platform]/start/quickstart/index.mdx
=> Fix Success message showing twice for Next.js

src/fragments/lib/analytics/android/getting-started/10_preReq.mdx
=> Fixed min version support for gen1 AndroidV2 Analytics

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx
=> added specific VPC language for `npx ampx generate schema-from-database`

src/directory/directory.mjs, src/pages/[platform]/start/kotlin-coroutines/index.mdx
=> Android Coroutines support

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-http-api/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx
closes: https://github.com/aws-amplify/docs/issues/7487
closes: https://github.com/aws-amplify/docs/issues/7486
=> rest api: separate example to individual pages and change config

src/pages/[platform]/how-amplify-works/faq/index.mdx
=> update faq text

src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx
=> Android | Missing TodoList

src/pages/[platform]/start/quickstart/index.mdx
=> Fix: correct typo

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
update example code for utils/amplifyServerUtils.ts
=> Update code snippet @NextJS server Side rendering 

src/pages/gen1/[platform]/prev/build-a-backend/restapi/set-up-rest-api/index.mdx, tasks/console-errors.js
Fixed a typo that was causing hydration errors
update to puppeteer pagewait condition to catch hydration errors
=> Fix Typo and update to puppeteer script

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-polly/index.mdx, src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-eventbridge-datasource/index.mdx, src/pages/[platform]/how-amplify-works/concepts/index.mdx, src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx, src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx
=> fixed some missed spots of new authZ and relationship pattern

src/pages/[platform]/build-a-backend/data/connect-from-server-runtime/nuxtjs-server-runtime/index.mdx, src/pages/[platform]/build-a-backend/data/query-data/index.mdx, src/pages/[platform]/build-a-backend/data/subscribe-data/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx, src/pages/[platform]/build-a-backend/server-side-rendering/nextjs-app-router-server-components/index.mdx
=> fixed out of date schema types

src/pages/[platform]/build-a-backend/storage/storagepath/index.mdx, src/pages/gen1/[platform]/build-a-backend/storage/storagepath/index.mdx
=> chore: add storage path for flutter

src/constants/versions.ts
=> Update Android version

src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx
=> fix storage typo

src/pages/[platform]/build-a-backend/storage/authorization/index.mdx
=> add callout for group access precedence

src/fragments/lib/analytics/flutter/getting-started/10_preReq.mdx, src/fragments/lib/auth/flutter/getting_started/10_preReq.mdx, src/fragments/lib/datastore/flutter/getting-started/10_preReq.mdx, src/fragments/lib/graphqlapi/flutter/getting-started/10_preReq.mdx, src/fragments/lib/project-setup/flutter/prereq/prereq.mdx, src/fragments/lib/project-setup/flutter/upgrade-guide/upgrade-guide.mdx, src/fragments/lib/restapi/flutter/getting-started/10_preReq.mdx, src/fragments/lib/storage/flutter/getting-started/10_preReq.mdx, src/fragments/start/getting-started/flutter/prereq.mdx, src/pages/[platform]/build-a-backend/add-aws-services/analytics/set-up-analytics/index.mdx, src/pages/[platform]/build-a-backend/auth/customize-auth-lifecycle/custom-auth-flows/index.mdx, src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/start/quickstart/index.mdx, src/pages/gen1/[platform]/start/getting-started/installation/index.mdx, src/pages/gen2/start/mobile-support/index.mdx
=> chore: flutter v2 cleanup

src/pages/[platform]/reference/cli-commands/index.mdx
Included an options section for the Generate form command.
=> Included an options section for the Generate form command.

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/troubleshooting/stack-cdktoolkit-already-exists/index.mdx
=> add troubleshooting guide for "Stack CDKToolkit already exists"

src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx
Updating Amplify Swift Storage category getting started code snippet so that images selected from photo picker are displayed correctly in simulators and real devices at runtime.
=> chore(swift): update storage get started code snippet

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx
=> addToSchema

src/components/MDXComponents/MDXCode.tsx, src/components/MDXComponents/TokenList.tsx, src/components/MDXComponents/__tests__/MDXCode.test.tsx, src/styles/code.scss
Updating code blocks to use CSS line numbers.
Staging site: https://terminalnumbers.dmhjrabi3pkql.amplifyapp.com/react/
=> Terminal numbers

src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/start/quickstart/index.mdx
=> change view to visit

.github/workflows/codeql.yml
=> Fix indentation

src/pages/[platform]/build-a-backend/data/connect-to-API/index.mdx, src/pages/[platform]/build-a-backend/data/set-up-data/index.mdx, src/pages/[platform]/start/quickstart/index.mdx
This PR updates the Swift / Data / "Set up Amplify Data" page and "Connect your app code" to API page
=> fix(swift): Data - Set up Amplify Data code improvements

src/pages/[platform]/start/quickstart/index.mdx
=> Tweak language in Android QS

src/components/Layout/LayoutHeader.tsx
enabling search on next-release/main branch and testing removing mainPage anchor tags from results
=> enable search and remove pageMain anchor from search results

src/pages/[platform]/start/quickstart/index.mdx, src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx, src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx
=> update quickstart text for data manager

src/pages/[platform]/build-a-backend/functions/examples/create-user-profile-record/index.mdx
=> Functions | Example | adding a callout

src/pages/[platform]/start/quickstart/index.mdx
Some file names were incorrect, and one change described an incorrect location to insert a function
- [X ] documentation
- [ X] Does this PR conform to [the styleguide](https://github.com/aws-amplify/docs/blob/main/STYLEGUIDE.md)?
- [X ] Does this PR include filetypes other than markdown or images? Please add or update unit tests accordingly.
- [ X] Are any files being deleted with this PR? If so, have the needed redirects been created?
- [ X] Are all links in MDX files using the MDX link syntax rather than HTML link …
=> Documentation/Angular Quickstart - Fix minor react->angular conversion mistakes

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx, src/pages/gen1/[platform]/build-a-backend/server-side-rendering/nextjs/index.mdx
Updated nextjs middleware to check for access token and id token from fetchAuthSession response 
=> fix: nextjs middleware check for access and id token

src/pages/[platform]/deploy-and-host/sandbox-environments/features/index.mdx
=> fix sandbox typo

src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-http-api/index.mdx, src/pages/[platform]/build-a-backend/add-aws-services/rest-api/set-up-rest-api/index.mdx
=> spread existingConfig.API

src/components/Layout/LayoutHeader.tsx
Updating search comment to better describe the purpose and need for transformItems
=> update search comment

src/pages/[platform]/build-a-backend/data/customize-authz/index.mdx
Add details about the sequence the auth rules are evaluated for auth directive's user pools and oidc auth modes.
NA
=> docs(api): add userpools and oidc rules evaluation sequence

.github/workflows/codeql.yml
=> pin codeql actions to latest v2

src/pages/[platform]/start/account-setup/index.mdx
=> fix idc reference

src/pages/[platform]/reference/amplify_outputs/index.mdx
=> fix: a typo

src/pages/[platform]/reference/cli-commands/index.mdx
Fixed to appropriate code at ampx.
=> fix: change amplify to ampx

src/pages/[platform]/build-a-backend/auth/moving-to-production/index.mdx
=> fix: typo requesting -> request

src/fragments/gen2/quickstart/create-amplify.mdx
sandbox command was out of date, so it was newly modified.
**from**
```
npx amplify sandbox
```
**to**
```
npx ampx sandbox
```
=> fix: sandbox command

Readme.md
=> update readme with note on when new fragments are allowed

src/pages/[platform]/build-a-backend/data/custom-business-logic/index.mdx
Code sample for creating a custom JS resolver using gen2 Data is missing required `import`, which causes error during deployment. 
=> fix: data custom resolver example - missing import

src/components/MDXComponents/MDXTable.tsx
=> Revert "chore(a11y audit): add region to scrollable table"

src/pages/[platform]/start/quickstart/index.mdx
Removed mention of create-vite-app
=> Update index.mdx to fix typo

src/pages/[platform]/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/index.mdx, src/pages/[platform]/start/migrate-to-gen2/index.mdx
Removes checkboxes: https://docs.amplify.aws/react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/
removes circle for consistency: https://docs.amplify.aws/react/start/migrate-to-gen2/#functions
=> fix: removed checkboxes and circles from pages

src/pages/[platform]/build-a-backend/auth/grant-access-to-auth-resources/index.mdx
=> fix: heading order

src/pages/gen1/[platform]/build-a-backend/graphqlapi/client-code-generation/index.mdx
Tiny typo to clear out an issue
Fixes: https://github.com/aws-amplify/docs/issues/6212
=> fix: typo on client code generation page

src/components/MDXComponents/MDXCopyCodeButton.tsx
[Issue] Whenever the user activates the copy button, the focus is incorrectly shifted to the top of the page.
[Fix] The copy button was disabled temporarily on click. To fix the focus issue, we've left the button enabled at all times
To see current behavior: 
- Go to [a code block](https://docs.amplify.aws/react/build-a-backend/auth/set-up-auth/)
- Click copy and keep mouse hovered over "Copy" to note the temporary disabling
- In console, check current focus (`document.activeElement`) to see that the focus jumps to the main-content
To test manually: 
- Go to [a code block on the staging link](https://a11y-copy-button-focus.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/auth/set-up-auth/)
- Click copy and keep mouse hovered over "Copy" to note that the button is no longer disabled …
=> a11y-remove temporary disabling of copy-code button

src/directory/directory.mjs, src/pages/[platform]/build-a-backend/functions/streaming-logs/index.mdx, src/pages/[platform]/deploy-and-host/sandbox-environments/features/index.mdx, src/pages/[platform]/reference/cli-commands/index.mdx
- adds docs for streaming function logs
- updates sandbox features
- updates cli command reference
=> add streaming function logs docs

src/pages/[platform]/build-a-backend/storage/use-with-custom-s3/index.mdx, src/pages/[platform]/start/account-setup/index.mdx, src/pages/[platform]/start/quickstart/index.mdx, src/pages/[platform]/start/quickstart/nextjs-app-router-client-components/index.mdx, src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx
[Issue] There are decorative images which are found under steps explained with textual equivalents.
[Fix] Remove alt text to mark these images as decorative
on page: https://docs.amplify.aws/react/start/quickstart/#4-set-up-local-environment
`<img alt="outputs" />`
on page: https://docs.amplify.aws/react/start/account-setup/#1-create-user-with-amplify-permissions
- `<img alt="AWS IAM Identity Center page indicating the "enable" button." />`
- `<img alt="AWS IAM Identity Center enable dialog with AWS Organizations, indicating to "continue".">`
- `<img alt="AWS IAM Identity Center password reset." />`
- `<img alt="Create new app page in Amplify console with the Initialize setup now button." />`
To see current behavior: 
- Go to [live …
=> a11y-remove alt text for decorative image

src/pages/[platform]/build-a-backend/auth/concepts/user-attributes/index.mdx, src/pages/[platform]/build-a-backend/auth/connect-your-frontend/manage-user-attributes/index.mdx, src/pages/[platform]/build-a-backend/auth/modify-resources-with-cdk/index.mdx
- adds docs for configuring user attributes
- adds "next step" link to direct towards understanding how attributes are added to tokens
- removed custom attribute override example
- updates links for custom attributes to point to this new section
add docs for https://github.com/aws-amplify/amplify-backend/pull/1732 …
=> add docs for auth custom attribute support

src/components/Modal/Modal.tsx
=> a11y- add more descriptive text to learn more in gen2 modal

src/pages/[platform]/build-a-backend/auth/customize-auth-lifecycle/email-customization/index.mdx
Adds documentation explaining how to customize the user invitation email. Updates the language and headings on the same docs page to reflect the addition of the new section.
n/a, I came across this in my own work 😄 
=> Add Docs for Email Invitation Customization

src/pages/[platform]/build-a-backend/storage/copy-files/index.mdx, src/pages/[platform]/build-a-backend/storage/download-files/index.mdx, src/pages/[platform]/build-a-backend/storage/list-files/index.mdx, src/pages/[platform]/build-a-backend/storage/remove-files/index.mdx, src/pages/[platform]/build-a-backend/storage/set-up-storage/index.mdx, src/pages/[platform]/build-a-backend/storage/upload-files/index.mdx, src/pages/[platform]/build-a-backend/storage/use-with-custom-s3/index.mdx
The purpose of this pull request is to update documentation to include multi bucket setup and usage examples.
=> [Multi-bucket] Storage - add multi bucket setup and usage examples

customHttp.yml, src/pages/_document.tsx
Updating headers and CSP values to follow the latest guidance.
staging site: https://updateheaders.dmhjrabi3pkql.amplifyapp.com/
=> Update headers and CSP value

src/pages/[platform]/build-a-backend/functions/scheduling-functions/index.mdx
=> fix cron format

src/pages/[platform]/build-a-backend/ai/generation/index.mdx, src/pages/[platform]/build-a-backend/ai/set-up-ai/index.mdx
- Adds initial content for generation route page.
=> docs(ai): add initial generation route page

src/components/ApiDocs/display/ApiModal.tsx
staging (still building): https://apidocs-modal-tabbing.d1egzztxsxq9xz.amplifyapp.com/react/build-a-backend/storage/reference/
=> focus modal on open

src/components/ApiDocs/FunctionReturn.tsx
=> format "Returns" as code

src/pages/[platform]/build-a-backend/server-side-rendering/index.mdx
=> chore(js): add js sdk recommendation for server use cases

src/pages/[platform]/start/quickstart/nextjs-pages-router/index.mdx
=> Fix on AppRouter mention in Pages Router Page - Update index.mdx

redirects.json
=> fix(docs): fix infinite redirects

src/pages/[platform]/build-a-backend/data/connect-event-api/index.mdx
=> fix events api snippet, remove dupe "events" variable

.github/workflows/update_references.yml
update api references workflow permissions to allow PR creation
=> update api docs workflow permissions

src/fragments/lib-v1/auth/android/user_attributes/10_fetch_attributes.mdx, src/fragments/lib/auth/android/user_attributes/10_fetch_attributes.mdx, src/pages/[platform]/build-a-backend/auth/connect-your-frontend/manage-user-attributes/index.mdx
Fixed a typo in fetchUserAttributes API code example (kotlin-callbacks)
=> fix(auth): typo in fetchUserAttributes API code example

src/pages/[platform]/ai/concepts/index.mdx
=> fix ai concepts page

src/pages/[platform]/start/quickstart/index.mdx
=> Fix typo in description of the use of amplify_outputs.json (Angular)

src/pages/[platform]/build-ui/formbuilder/index.mdx
Updated numbered list in UI "Connected forms" docs. 
=> chore: update numbered list in UI "Connected forms" docs

src/pages/[platform]/deploy-and-host/fullstack-branching/secrets-and-vars/index.mdx
=> add dotenvx with sandbox usage

src/pages/[platform]/build-a-backend/add-aws-services/predictions/set-up-predictions/index.mdx
update the predictions Amplify config setup to use the custom outputs
report: https://discord.com/channels/705853757799399426/1341335224897769493/1341335224897769493
=> update predictions config

src/pages/[platform]/build-a-backend/auth/examples/microsoft-entra-id-saml/index.mdx
=> fix azure portal url, fixes #8247

src/pages/[platform]/start/migrate-to-gen2/index.mdx
=> testing info

src/pages/[platform]/start/migrate-to-gen2/index.mdx
=> update data info

package.json, yarn.lock
=> chore: bump next version

src/pages/gen1/[platform]/build-a-backend/auth/auth-migration-guide/index.mdx
https://github.com/aws-amplify/docs/issues/8310
=> fix: incorrect arrow function expression

package.json, yarn.lock
=> chore: bump @actions/core for bump undici

package.json, yarn.lock
=> chore: bump prismjs version

src/pages/[platform]/ai/conversation/connect-your-frontend/index.mdx
Update the sample code for `aiContext`
https://github.com/aws-amplify/amplify-data/issues/584
=> fix: update `aiContext` sample

package.json, yarn.lock
=> chore: remove prismjs resolution

src/pages/[platform]/build-a-backend/storage/use-with-custom-s3/index.mdx
=> [Chore]: fix custom bucket stack usage

.github/CODEOWNERS
- After discussion with product team, decided to have a respresentive from other team in addition to docs admin for respective content is decided and updated in docs repo
=> Chore: Update Codeowners

src/pages/[platform]/build-a-backend/data/custom-business-logic/connect-amazon-rekognition/index.mdx
=> update identifyText.js to identifyText.ts

src/directory/directory.mjs, src/pages/[platform]/deploy-and-host/sandbox-environments/seed/index.mdx, src/pages/[platform]/reference/cli-commands/index.mdx
Seeding auth, data, and storage resources is now supported in Amplify Gen2 CLI. These docs describe how to use the new feature as well as best practices for using the seed feature. 
This PR can be merged upon approval. The release related to the seed feature went out on April 24
=> Add seed docs

src/pages/[platform]/start/migrate-to-gen2/index.mdx
=> add migration updates

src/pages/[platform]/deploy-and-host/sandbox-environments/seed/index.mdx
Add mention about installing `@aws-amplify/seed` package to the instruction.
https://github.com/aws-amplify/amplify-backend/issues/2810
=> mention seed package installation
